// Presentation-offer data only. No DNS, message, checkout or commission execution.
export const SELLER_THEME_CONTRACT='novastore-seller-theme-offers/1';
export const MAX_OFFERS=100;
export const STATES=Object.freeze({draft:'Taslak',validated:'Doğrulandı',ready:'Sunuma hazır',withdrawn:'Geri çekildi'});
export const sameScope=(a,b)=>a?.tenantId===b?.tenantId&&a?.storeId===b?.storeId;
export const sameRecipient=(a,b)=>sameScope(a,b)&&a?.sellerId===b?.sellerId;
export const fail=(code,message)=>{throw Object.assign(new Error(message),{code});};
export const clone=value=>structuredClone(value);
export function isRecord(value){if(!value||typeof value!=='object')return false;const proto=Object.getPrototypeOf(value);return proto===null||(Object.getPrototypeOf(proto)===null&&Object.getOwnPropertyDescriptor(proto,'constructor')?.value?.name==='Object');}
function obj(value,name){if(!isRecord(value))fail('SCHEMA',`${name} geçersiz.`);return value;}
function keys(value,allowed,name){obj(value,name);if(Object.keys(value).some(k=>!allowed.includes(k)))fail('SCHEMA',`${name} desteklenmeyen alan içeriyor.`);}
export function text(value,name,max=100,min=1){if(typeof value!=='string'||value.trim()!==value||value.length<min||value.length>max||/[\u0000-\u001f\u007f]/.test(value))fail('SCHEMA',`${name} geçersiz.`);return value;}
export function id(value,name='Kimlik'){text(value,name,100);if(!/^[a-zA-Z0-9][a-zA-Z0-9_.:-]*$/.test(value))fail('SCHEMA',`${name} geçersiz.`);return value;}
export function integer(value,name,max=Number.MAX_SAFE_INTEGER){if(!Number.isSafeInteger(value)||value<0||value>max)fail('AMOUNT',`${name} geçersiz.`);return value;}
export function normalizeScope(value){keys(value,['tenantId','storeId'],'Mağaza kapsamı');return{tenantId:id(value.tenantId),storeId:id(value.storeId)};}
export function normalizeRecipient(value,owner){keys(value,['tenantId','sellerId','storeId','name'],'Satıcı');const result={...normalizeScope({tenantId:value.tenantId,storeId:value.storeId}),sellerId:id(value.sellerId),name:text(value.name,'Mağaza adı',100)};if(result.tenantId!==owner.tenantId)fail('SCOPE','Satıcı başka bir kuruluşa ait.');return result;}
export function normalizeTheme(value){keys(value,['id','name','source','version','channels'],'Tema');if(!['studio','sector'].includes(value.source))fail('THEME','Tema kaynağı geçersiz.');if(!Array.isArray(value.channels)||!value.channels.length||value.channels.some(c=>!['web','android'].includes(c))||new Set(value.channels).size!==value.channels.length)fail('THEME','Tema kanalları geçersiz.');return{id:id(value.id),name:text(value.name,'Tema adı',100),source:value.source,version:text(value.version,'Tema sürümü',200),channels:[...value.channels]};}
export function decimalToMinor(value){if(typeof value!=='string'||!/^\d{1,11}([.,]\d{1,2})?$/.test(value))fail('AMOUNT','Tutarı en fazla iki ondalıkla yaz; binlik ayırıcı kullanma.');const [whole,fraction='']=value.replace(',','.').split('.');const n=BigInt(whole)*100n+BigInt(fraction.padEnd(2,'0'));if(n>9999999999999n)fail('AMOUNT','Tutar çok büyük.');return Number(n);}
export function percentToBps(value){const n=decimalToMinor(value);if(n>10000)fail('COMMISSION','Komisyon %0–100 arasında olmalı.');return n;}
export function minorToDecimal(value){integer(value,'Tutar',9999999999999);return `${Math.floor(value/100)}.${String(value%100).padStart(2,'0')}`;}
export function commissionExample(amountMinor,bps){integer(amountMinor,'Tutar',9999999999999);integer(bps,'Komisyon',10000);const fee=Number((BigInt(amountMinor)*BigInt(bps)+5000n)/10000n);return{amountMinor,commissionMinor:fee,sellerMinor:amountMinor-fee,currency:'TRY',simulation:true};}
export function normalizeDomain(value,{allowEmpty=false}={}){text(value,'Alan adı',253,allowEmpty?0:1);if(!value&&allowEmpty)return '';if(/[\s/:@?#%\\]/.test(value)||value.endsWith('.'))fail('DOMAIN','Yalnız alan adını yaz; protokol, yol veya port ekleme.');let domain;try{domain=new URL('https://'+value).hostname.toLowerCase();}catch{fail('DOMAIN','Alan adı geçersiz.');}if(domain.length>253||!domain.includes('.')||/^[\d.]+$/.test(domain)||/\.(localhost|local|test|invalid|example|internal)$/.test(domain)||domain==='localhost'||domain.endsWith('.localdomain'))fail('DOMAIN','Genel bir alan adı kullan.');const labels=domain.split('.');if(labels.some(label=>label.length>63||! /^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/.test(label))||!/[a-z]/.test(labels.at(-1)))fail('DOMAIN','Alan adı etiketleri geçersiz.');return domain;}
export function normalizeSite(value){keys(value,['mode','subdomain','domain','locale','currency'],'Site planı');if(!['subdomain','custom-domain'].includes(value.mode)||value.locale!=='tr-TR'||value.currency!=='TRY')fail('PLAN','Site planı desteklenmiyor.');const subdomain=text(value.subdomain,'Alt alan adı',48,0);if(['www','api','admin','auth','checkout','cdn','assets','mail','status','studio'].includes(subdomain))fail('DOMAIN','Bu alt alan adı platform için ayrılmış.');if(subdomain&&!/^[a-z0-9](?:[a-z0-9-]*[a-z0-9])?$/.test(subdomain))fail('DOMAIN','Alt alan adında küçük harf, rakam ve tire kullan.');return{mode:value.mode,subdomain,domain:normalizeDomain(value.domain,{allowEmpty:true}),locale:'tr-TR',currency:'TRY'};}
export function normalizeCommercial(value){keys(value,['commissionBps','setupFeeMinor','monthlyFeeMinor','currency','basis','termsVersion'],'Ticari taslak');if(value.currency!=='TRY'||value.basis!=='net-products-after-discounts')fail('AMOUNT','Ticari hesap temeli geçersiz.');return{commissionBps:integer(value.commissionBps,'Komisyon',10000),setupFeeMinor:integer(value.setupFeeMinor,'Kurulum bedeli',9999999999999),monthlyFeeMinor:integer(value.monthlyFeeMinor,'Aylık bedel',9999999999999),currency:'TRY',basis:'net-products-after-discounts',termsVersion:text(value.termsVersion,'Koşul taslağı sürümü',100)};}
export function normalizeOffer(value,owner){keys(value,['schemaVersion','id','revision','scope','recipient','theme','channels','site','commercial','productIds','status','createdAt','updatedAt','history'],'Teklif');if(!Number.isSafeInteger(value.revision)||value.revision<1)fail('VERSION','Teklif sürümü geçersiz.');if(value.schemaVersion!==1||!sameScope(value.scope,owner))fail('SCOPE','Teklif başka bir yönetim kapsamına ait.');const recipient=normalizeRecipient(value.recipient,owner),theme=normalizeTheme(value.theme);if(!Array.isArray(value.channels)||!value.channels.length||new Set(value.channels).size!==value.channels.length||value.channels.some(c=>!theme.channels.includes(c)))fail('CHANNEL','Teklif kanalları geçersiz.');if(!Array.isArray(value.productIds)||value.productIds.length>300||new Set(value.productIds).size!==value.productIds.length)fail('CATALOG','Ürün seçimi geçersiz.');if(!Object.hasOwn(STATES,value.status))fail('STATE','Teklif durumu geçersiz.');if(!Array.isArray(value.history)||value.history.length>40)fail('HISTORY','Teklif geçmişi geçersiz.');const history=value.history.map(h=>{keys(h,['at','action','revision'],'Geçmiş');if(!['created','edited','validated','ready','withdrawn','reopened'].includes(h.action))fail('HISTORY','Geçmiş işlemi geçersiz.');text(h.at,'Geçmiş tarihi',30);if(!Number.isFinite(Date.parse(h.at)))fail('HISTORY','Geçmiş tarihi geçersiz.');return{at:h.at,action:h.action,revision:integer(h.revision,'Geçmiş sürümü',1000000)};});for(const date of ['createdAt','updatedAt'])if(!Number.isFinite(Date.parse(text(value[date],date,30))))fail('SCHEMA','Teklif tarihi geçersiz.');return{schemaVersion:1,id:id(value.id),revision:integer(value.revision,'Teklif sürümü',1000000),scope:normalizeScope(value.scope),recipient,theme,channels:[...value.channels],site:normalizeSite(value.site),commercial:normalizeCommercial(value.commercial),productIds:value.productIds.map(v=>id(v,'Ürün kimliği')),status:value.status,createdAt:value.createdAt,updatedAt:value.updatedAt,history};}
export function validateCatalog(products,recipient){if(!Array.isArray(products)||products.length>2000)fail('CATALOG','Yetkili ürün listesi geçersiz.');const occupied=new Set();return products.map(p=>{keys(p,['id','name','scope','priceMinor','currency','stock','imageUrl'],'Ürün');if(!sameRecipient(p.scope,recipient))fail('SCOPE','Ürün başka bir satıcıya veya mağazaya ait.');const productId=id(p.id,'Ürün kimliği');if(occupied.has(productId))fail('CATALOG','Ürün kimliği tekrarlanıyor.');occupied.add(productId);return{id:productId,name:text(p.name,'Ürün adı',200),scope:clone(recipient),priceMinor:integer(p.priceMinor,'Ürün tutarı',9999999999999),currency:p.currency==='TRY'?'TRY':fail('CATALOG','Para birimi desteklenmiyor.'),stock:integer(p.stock,'Stok',1000000),imageUrl:typeof p.imageUrl==='string'&&/^\/(?!\/)[\w./-]+$/.test(p.imageUrl)?p.imageUrl:''};});}
export function readiness(offer,{themes,recipients,products,offers=[]}){const checks=[];const add=(id,label,ok)=>checks.push({id,label,ok});const recipient=recipients.find(r=>sameRecipient(r,offer.recipient));const theme=themes.find(t=>t.id===offer.theme.id&&t.source===offer.theme.source&&t.version===offer.theme.version);const ids=new Set(products.map(p=>p.id));add('recipient','Mağaza yetkili listede',!!recipient);add('theme-version','Tema ve sürümü koleksiyonda',!!theme);add('channels','Seçilen kanallar destekleniyor',!!theme&&offer.channels.every(c=>theme.channels.includes(c)));add('catalog','Yalnız bu mağazanın seçili ürünleri',offer.productIds.length>0&&offer.productIds.every(p=>ids.has(p))&&products.every(p=>sameRecipient(p.scope,offer.recipient)));const destination=offer.site.mode==='custom-domain'?offer.site.domain:offer.site.subdomain;add('site','Site adres planı tamam',destination.length>=2);add('destination','Adres başka bir aktif hazırlığa ayrılmamış',!offers.some(x=>x.id!==offer.id&&x.status==='ready'&&x.site.mode===offer.site.mode&&(x.site.mode==='custom-domain'?x.site.domain:x.site.subdomain)===destination&&!sameRecipient(x.recipient,offer.recipient)));return{ready:checks.every(x=>x.ok),checks,productionReady:false,gates:['Sunucuda satıcı / mağaza yetkisi ve ürün sahipliği','Alan adı sahipliği, DNS ve TLS','Komisyon koşullarının kabulü, sipariş muhasebesi ve iade dağıtımı','Gerçek katalog / oturum / sepet / ödeme adaptörü','Satıcı kabulü, yayın sürümü ve geri dönüş planı']};}
