import React,{useEffect,useMemo,useState,useRef} from 'react';
import {Check,ChevronRight,Eye,FileCheck,Globe,Plus,RotateCcw,ShieldCheck,Store,X} from 'lucide-react';
import {getStudioHost} from '../../studio-integration/context.js';
import {createSellerThemeOffers} from './session.js';
import {resolveOfferThemeCatalog,selectOfferThemeId} from './themeCatalog.js';
import {LOCAL_OFFER_SCOPE,localRecipients,localCatalog} from './localAdapter.js';
import {STATES,decimalToMinor,percentToBps,minorToDecimal,commissionExample,sameScope} from './model.js';
import './seller-themes.css';
const money=v=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(v/100);
const formFor=o=>({themeId:o.theme.id,channels:[...o.channels],site:{...o.site},commission:minorToDecimal(o.commercial.commissionBps),setup:minorToDecimal(o.commercial.setupFeeMinor),monthly:minorToDecimal(o.commercial.monthlyFeeMinor),productIds:[...o.productIds]});
const recipientKey=r=>`${r.sellerId}/${r.storeId}`;
export default function SellerThemeOffers({themes:localThemes,initialThemeId,onClose,configuration,onPreview}){
 const catalog=useMemo(()=>{try{return{themes:resolveOfferThemeCatalog(localThemes,configuration)};}catch(cause){return{themes:[],error:cause.message};}},[localThemes,configuration]);
 const themes=catalog.themes;
 const [view,setView]=useState(null),[error,setError]=useState(''),[message,setMessage]=useState(''),[selectedId,setSelectedId]=useState(''),[recipientId,setRecipientId]=useState(''),[newTheme,setNewTheme]=useState(()=>selectOfferThemeId(themes,initialThemeId)),[form,setForm]=useState(null),[products,setProducts]=useState([]),[checks,setChecks]=useState(null),[preview,setPreview]=useState(null),[busy,setBusy]=useState(false),[productQuery,setProductQuery]=useState('');
 const signature=JSON.stringify([configuration?.mode,configuration?.scope,configuration?.actor,themes]);
 const session=useMemo(()=>{try{if(catalog.error)throw new Error(catalog.error);const mounted=getStudioHost();if(mounted&&(!configuration||configuration.mode!=='host'||!sameScope(mounted.scope,configuration.scope)||mounted.actor.id!==configuration.actor?.id))throw new Error('Bu admin oturumunda satıcı teklif bağlantısı henüz bağlı değil. Yerel satıcılar kullanılmadı.');let persistence=null;if(!configuration){try{persistence=localStorage;}catch{}}return createSellerThemeOffers(configuration?{...configuration,themes,baseURL:location.href}:{mode:'local',scope:LOCAL_OFFER_SCOPE,actor:{id:'local-admin'},themes,storage:persistence,localRecipients,localCatalog,baseURL:location.href});}catch(cause){return{configurationError:cause.message};}},[configuration,signature,catalog.error]);
 useEffect(()=>{setView(null);setSelectedId('');setForm(null);setChecks(null);setPreview(null);setError('');if(session.configurationError){setError(session.configurationError);return;}let active=true;const unsub=session.subscribe(()=>{if(active)setView(session.snapshot());});session.initialize().then(s=>{if(active){setView(s);setRecipientId(s.recipients[0]?recipientKey(s.recipients[0]):'');}}).catch(cause=>{if(active)setError(cause.message);});return()=>{active=false;unsub();session.dispose();};},[session]);
 useEffect(()=>{setNewTheme(current=>selectOfferThemeId(themes,initialThemeId||current));},[initialThemeId,themes]);
 const selected=view?.offers.find(o=>o.id===selectedId),pending=busy||view?.pending;
 useEffect(()=>{if(!selected){setForm(null);setProducts([]);setChecks(null);return;}let active=true;setForm(formFor(selected));setChecks(null);setProductQuery('');session.catalogFor(selected.recipient).then(p=>{if(active)setProducts(p);}).catch(e=>{if(active){setProducts([]);setError(e.message);}});return()=>{active=false;};},[session,selected?.id,selected?.revision]);
 async function perform(fn){if(pending)return;setBusy(true);setError('');setMessage('');try{await fn();}catch(cause){setError(cause.message||'İşlem tamamlanamadı.');}finally{setBusy(false);}}
 async function create(){if(dirty&&!confirm('Kaydedilmemiş değişiklikleri bırakıp yeni hazırlık aç?'))return;await perform(async()=>{const recipient=view.recipients.find(r=>recipientKey(r)===recipientId);if(!recipient)throw Error('Bir mağaza seç.');const offer=await session.create({recipient,themeId:newTheme});setSelectedId(offer.id);setMessage('Hazırlık taslağı kaydedildi.');});}
 async function save(){await perform(async()=>{const theme=themes.find(t=>t.id===form.themeId);await session.update(selected.id,{theme,channels:form.channels,site:form.site,commercial:{...selected.commercial,commissionBps:percentToBps(form.commission),setupFeeMinor:decimalToMinor(form.setup),monthlyFeeMinor:decimalToMinor(form.monthly)},productIds:form.productIds},selected.revision);setMessage('Teklif taslağı kaydedildi; yeniden kontrol edebilirsin.');});}
 async function transition(status){await perform(async()=>{if(status==='validated'){const report=await session.inspect(selected.id);setChecks(report);if(!report.ready)return;}const offer=await session.transition(selected.id,status,selected.revision);setChecks(['validated','ready'].includes(status)?await session.inspect(offer.id):null);setMessage(status==='ready'?'Sunum hazırlığı kaydedildi. Satıcıya mesaj gönderilmedi.':status==='withdrawn'?'Hazırlık geri çekildi.':status==='draft'?'Yeni düzenleme için taslağa alındı.':'Teklifin yerel yapısı doğrulandı.');});}
 async function openPreview(channel){await perform(async()=>{const result=await session.preview(selected.id,channel);if(result.mode==='local'&&onPreview){const handled=await onPreview(result);if(handled?.handled===true)return;if(handled?.url){const url=new URL(handled.url,location.href);if(url.origin!==location.origin||!['http:','https:'].includes(url.protocol)||url.username||url.password)throw Error('Önizleme yalnız bu denemenin adresinde açılabilir.');result.url=url.href;}}setPreview(result);});}
 const dirty=!!selected&&!!form&&JSON.stringify(form)!==JSON.stringify(formFor(selected));
 let quote=null;try{quote=commissionExample(100000,percentToBps(form?.commission||'0'));}catch{}
 const canPrepare=view?.mode==='local'||configuration?.capabilities?.prepare===true;
 const editable=selected?.status!=='withdrawn'&&(view?.mode==='local'||configuration?.capabilities?.edit===true);
 const visibleProducts=products.filter(p=>p.name.toLocaleLowerCase('tr-TR').includes(productQuery.toLocaleLowerCase('tr-TR')));
 return <section className="st-offers" aria-label="Satıcıya tema sunma hazırlığı">
  <header className="st-offers-head"><div><span><Store size={15}/>SATICI SİTELERİ</span><h2>Satıcıya sun.</h2><p>Bir mağazaya tasarım, ürün seçkisi ve site planı hazırla.</p></div>{onClose&&<button type="button" onClick={onClose} aria-label="Satıcı tekliflerini kapat"><X size={20}/></button>}</header>
  <div className="st-offers-mode"><ShieldCheck size={20}/><div><strong>{configuration?'Admin bağlantısında hazırlık':'Bu tarayıcıdaki yerel hazırlık'}</strong><p>“Sunuma hazır” teklif hazırlığını ifade eder. Satıcı kabulü, alan adı bağlantısı ve canlı yayın ayrı adımlardır.</p></div></div>
  {(error||view?.error)&&<p role="alert" className="st-offers-error">{error||view.error}</p>}{message&&<p role="status" className="st-offers-success">{message}</p>}
  {view?.phase==='ready'?<>
   <button type="button" disabled={pending} onClick={()=>{if(dirty&&!confirm('Kaydedilmemiş değişiklikleri bırakıp kayıtları yenile?'))return;perform(async()=>{const result=await session.initialize();setView(result);setSelectedId('');setChecks(null);setMessage('Teklif kayıtları yenilendi.');});}}><RotateCcw size={16}/>Kayıtları yenile</button><div className="st-offers-create"><label>Mağaza<select aria-label="Mağaza" value={recipientId} onChange={e=>setRecipientId(e.target.value)} disabled={pending}>{view.recipients.map(r=><option key={recipientKey(r)} value={recipientKey(r)}>{r.name}</option>)}</select></label><label>Hazır tasarım<select aria-label="Hazır tasarım" value={newTheme} onChange={e=>setNewTheme(e.target.value)} disabled={pending}>{themes.map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><button type="button" className="st-offers-primary" disabled={pending||!recipientId||(configuration?.mode==='host'&&configuration?.capabilities?.edit!==true)} onClick={create}><Plus size={16}/>Yeni hazırlık</button></div>
   <div className="st-offers-layout"><aside className="st-offers-list"><h3>Hazırlıklar <span>{view.offers.length}</span></h3>{!view.offers.length&&<p>İlk mağazanı ve tasarımını seçerek başlayabilirsin.</p>}{[...view.offers].sort((a,b)=>b.updatedAt.localeCompare(a.updatedAt)).map(o=><button type="button" key={o.id} onClick={()=>{if(dirty&&!confirm('Kaydedilmemiş form değişikliklerini bırakıp başka teklifi aç?'))return;setSelectedId(o.id);setError('');}} aria-pressed={o.id===selectedId}><strong>{o.recipient.name}</strong><span>{o.theme.name}</span><small>{STATES[o.status]} · v{o.revision}</small><ChevronRight size={16}/></button>)}</aside>
   {!selected||!form?<div className="st-offers-empty"><FileCheck size={40}/><h3>Mağazaya uygun bir teklif hazırla.</h3><p>Hazır bir tasarım seç, sadece o mağazanın ürünlerini ekle ve ticari koşul taslağını kaydet.</p></div>:<div className="st-offers-detail">
    <div className="st-offers-detail-head"><div><span>{STATES[selected.status]} · v{selected.revision}</span><h3>{selected.recipient.name}</h3><p>{selected.theme.name} · kaynak sürümü {selected.theme.version}</p></div><span>{dirty?'Kaydedilmemiş değişiklikler':'Kayıtlı taslak'}</span></div>
    <form onSubmit={e=>{e.preventDefault();save();}}><fieldset disabled={pending||!editable}>
     <div className="st-offers-fields"><label>Tasarım<select aria-label="Tasarım" value={form.themeId} onChange={e=>{const t=themes.find(t=>t.id===e.target.value);setForm(f=>({...f,themeId:t.id,channels:[...t.channels]}));}}>{themes.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select></label><div className="st-offers-channel"><span>Sunum kanalları</span>{(themes.find(t=>t.id===form.themeId)?.channels||[]).map(c=><label key={c}><input type="checkbox" checked={form.channels.includes(c)} onChange={e=>setForm(f=>({...f,channels:e.target.checked?[...f.channels,c]:f.channels.filter(v=>v!==c)}))}/>{c==='web'?'Web sitesi':'Uygulama görünümü'}</label>)}</div></div>
     <h4><Globe size={16}/>Site adres planı</h4><div className="st-offers-fields"><label>Adres türü<select aria-label="Adres türü" value={form.site.mode} onChange={e=>setForm(f=>({...f,site:{...f.site,mode:e.target.value}}))}><option value="subdomain">Platform alt alan adı</option><option value="custom-domain">Satıcının kendi alan adı</option></select></label>{form.site.mode==='custom-domain'?<label>Alan adı<input value={form.site.domain} onChange={e=>setForm(f=>({...f,site:{...f.site,domain:e.target.value}}))} placeholder="magazan.com" maxLength={253}/></label>:<label>Alt alan adı<input value={form.site.subdomain} onChange={e=>setForm(f=>({...f,site:{...f.site,subdomain:e.target.value}}))} placeholder="magaza-kisa-adi" maxLength={48}/></label>}</div><p className="st-offers-help">Adresin biçimi ve bu hazırlıklardaki çakışması kontrol edilir. Alan adı sahipliği, DNS ve TLS henüz doğrulanmaz.</p>
     <h4>Ticari koşul taslağı</h4><div className="st-offers-fields st-offers-three"><label>Komisyon · %<input inputMode="decimal" value={form.commission} onChange={e=>setForm(f=>({...f,commission:e.target.value}))}/></label><label>Kurulum bedeli · ₺<input inputMode="decimal" value={form.setup} onChange={e=>setForm(f=>({...f,setup:e.target.value}))}/></label><label>Aylık bedel · ₺<input inputMode="decimal" value={form.monthly} onChange={e=>setForm(f=>({...f,monthly:e.target.value}))}/></label></div>{quote&&<p className="st-offers-calculation">Örnek {money(quote.amountMinor)} net ürün tutarı: {money(quote.commissionMinor)} komisyon, {money(quote.sellerMinor)} satıcı payı. Tahsilat yapılmaz.</p>}<p className="st-offers-help">Taslak matrah: indirim sonrası ürün tutarı; vergi ve kargo hariç. Gerçek sözleşme, iade ve ödeme dağıtımı sunucuda onaylanmalıdır.</p>
     <div className="st-offers-product-head"><h4>{view.mode==='local'?'Mağazanın örnek ürün seçkisi':'Mağazanın yetkili ürünleri'}</h4><span>{form.productIds.length} seçili</span></div><input aria-label="Teklif ürünlerinde ara" placeholder="Ürün ara" value={productQuery} onChange={e=>setProductQuery(e.target.value)}/><div className="st-offers-product-actions"><button type="button" onClick={()=>setForm(f=>({...f,productIds:products.map(p=>p.id)}))}>Tümünü seç</button><button type="button" onClick={()=>setForm(f=>({...f,productIds:[]}))}>Seçimi temizle</button></div>
     <div className="st-offers-products">{visibleProducts.map(p=><label key={p.id}><input type="checkbox" checked={form.productIds.includes(p.id)} onChange={e=>setForm(f=>({...f,productIds:e.target.checked?[...f.productIds,p.id]:f.productIds.filter(x=>x!==p.id)}))}/>{p.imageUrl&&<img src={p.imageUrl} alt=""/>}<span><strong>{p.name}</strong><small>{money(p.priceMinor)} · stok {p.stock}</small></span></label>)}</div>{!products.length&&<p className="st-offers-help">Bu mağazaya ait ürün listesi henüz alınamadı. Başka mağazanın ürünleri kullanılmaz.</p>}
     <button type="submit" className="st-offers-primary" disabled={!dirty}><Check size={16}/>Taslağı kaydet</button>
    </fieldset></form>
    <div className="st-offers-actions">{selected.status==='draft'&&<button type="button" disabled={pending||dirty||!editable||!canPrepare} onClick={()=>transition('validated')}><FileCheck size={16}/>Kontrol et</button>}{selected.status==='validated'&&<button type="button" className="st-offers-primary" disabled={pending||dirty||!editable||!canPrepare} onClick={()=>transition('ready')}><Check size={16}/>Sunuma hazırla</button>}{selected.status!=='withdrawn'?<button type="button" disabled={pending||dirty||!editable} onClick={()=>transition('withdrawn')}>Geri çek</button>:<button type="button" disabled={pending||(configuration?.mode==='host'&&configuration?.capabilities?.edit!==true)} onClick={()=>transition('draft')}><RotateCcw size={16}/>Yeniden taslak</button>}{selected.channels.map(c=><button type="button" key={c} disabled={pending||dirty||selected.status==='withdrawn'} onClick={()=>openPreview(c)}><Eye size={16}/>{c==='web'?'Web önizle':'Uygulama önizle'}</button>)}</div>
    {checks&&<div className="st-offers-checks"><h4>Sunum hazırlığı kontrolleri</h4>{checks.checks.map(c=><p key={c.id} data-ok={c.ok}>{c.ok?'✓':'○'} {c.label}</p>)}<h4>Canlı kurulumda tamamlanacaklar</h4><ul>{checks.gates.map(g=><li key={g}>{g}</li>)}</ul></div>}
    <details className="st-offers-history"><summary>Hazırlık geçmişi · {selected.history.length}</summary><ol>{selected.history.map((h,i)=><li key={i}>v{h.revision} · {({created:'Taslak oluşturuldu',edited:'Taslak düzenlendi',validated:'Kontrol edildi',ready:'Sunuma hazırlandı',withdrawn:'Geri çekildi',reopened:'Yeniden taslağa alındı'})[h.action]} <time>{new Date(h.at).toLocaleString('tr-TR')}</time></li>)}</ol></details>
   </div>}</div>
  </>:!error&&<p role="status">Satıcı hazırlıkları yükleniyor…</p>}
  {preview&&<OfferPreview onClose={()=>setPreview(null)}><div><header><h3>{preview.offer.recipient.name} · teklif önizlemesi</h3><button type="button" autoFocus onClick={()=>setPreview(null)} aria-label="Teklif önizlemesini kapat"><X size={20}/></button></header><p>{preview.offer.theme.name} · {preview.channel==='web'?'Web sitesi':'Uygulama görünümü'} · Sunum taslağı</p>{preview.url?<iframe title="Satıcı temasının doğrulanmış önizlemesi" src={preview.url}/>:<><p>Seçilen tema ve mağaza ürünlerinin teklif özeti. Tam site önizlemesi admin bağlayıcısıyla açılır.</p><div className="st-offers-preview-products">{preview.products.map(p=><article key={p.id}>{p.imageUrl&&<img alt="" src={p.imageUrl}/>}<strong>{p.name}</strong><span>{money(p.priceMinor)}</span></article>)}</div></>}</div></OfferPreview>}
 </section>;
}

function OfferPreview({children,onClose}){const ref=useRef(null),previous=useRef(document.activeElement);useEffect(()=>{const dialog=ref.current;if(!dialog.open)dialog.showModal();return()=>{if(dialog.open)dialog.close();if(previous.current?.isConnected)previous.current.focus();};},[]);function containTab(e){if(e.key!=='Tab')return;const elements=[...ref.current.querySelectorAll('button:not(:disabled),a[href],input:not(:disabled),select:not(:disabled),iframe')];const first=elements[0],last=elements.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last?.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first?.focus();}}return <dialog ref={ref} onKeyDown={containTab} className="st-offers-preview" aria-label="Teklif önizlemesi" onCancel={e=>{e.preventDefault();onClose();}}>{children}</dialog>;}
