import {SELLER_THEME_CONTRACT,MAX_OFFERS,normalizeScope,normalizeRecipient,normalizeTheme,normalizeOffer,validateCatalog,readiness,sameScope,sameRecipient,id,clone,fail,isRecord} from './model.js';
const PATCH_KEYS=['theme','channels','site','commercial','productIds'];
export function createSellerThemeOffers(configuration){
 const {mode,scope:rawScope,actor:rawActor,themes:rawThemes,ports={},capabilities={},storage,localRecipients,localCatalog,now=()=>new Date().toISOString(),uuid=()=>crypto.randomUUID(),baseURL='http://localhost/'}=configuration||{};
 if(!['local','host'].includes(mode))fail('CONFIG','Yerel veya host çalışma modu açıkça seçilmeli.');
 const scope=normalizeScope(rawScope),actor={id:id(rawActor?.id,'Yönetici kimliği')};
 if(mode==='local'&&scope.tenantId!=='local-demo')fail('SCOPE','Yerel çalışma yalnız deneme kuruluşunda kullanılabilir.');
 if(!Array.isArray(rawThemes)||!rawThemes.length||rawThemes.length>200)fail('THEME','Tema koleksiyonu gerekli.');const themes=rawThemes.map(normalizeTheme);if(new Set(themes.map(t=>t.id)).size!==themes.length)fail('THEME','Tema kimliği tekrarlanıyor.');
 const key=`novastore-seller-theme-offers:v1:${scope.tenantId}:${scope.storeId}`,listeners=new Set(),catalogs=new Map(),pendingCreates=new Map(),pendingWrites=new Map();let state={phase:'loading',mode,scope,offers:[],recipients:[],themes,error:'',pending:false},disposed=false;
 const emit=()=>listeners.forEach(f=>f());const request=extra=>({contractVersion:SELLER_THEME_CONTRACT,scope:clone(scope),actor:clone(actor),...extra});
 const access=(ability,port)=>{if(disposed)fail('CLOSED','Teklif çalışma alanı kapatıldı.');if(mode==='host'&&(capabilities[ability]!==true||typeof ports[port]!=='function'))fail('UNAVAILABLE','Satıcı tema bağlantısı veya işlem yetkisi hazır değil.');};
 const envelope=(r)=>{if(!sameScope(r?.scope,scope))fail('SCOPE','Sunucu yanıtı başka bir yönetim kapsamına ait.');return r;};
 const list=(items)=>{if(!Array.isArray(items)||items.length>MAX_OFFERS)fail('STORAGE','Teklif listesi geçersiz.');const out=items.map(o=>normalizeOffer(o,scope));if(new Set(out.map(o=>o.id)).size!==out.length)fail('STORAGE','Teklif kimliği tekrarlanıyor.');return out;};
 function readLocal(){if(!storage?.getItem||!storage?.setItem)fail('STORAGE','Tarayıcı depolaması kullanılamıyor.');const raw=storage.getItem(key);if(!raw)return[];if(raw.length>2000000)fail('STORAGE','Teklif kaydı sınırı aşıyor.');let parsed;try{parsed=JSON.parse(raw);}catch{fail('STORAGE','Teklif kaydı okunamadı; önceki kayıtlar korunuyor.');}if(parsed.version!==1||!sameScope(parsed.scope,scope)||Object.keys(parsed).some(k=>!['version','scope','offers'].includes(k)))fail('STORAGE','Teklif kayıt biçimi geçersiz.');return list(parsed.offers);}
 function roster(items){if(!Array.isArray(items)||items.length>500)fail('SCOPE','Yetkili satıcı listesi geçersiz.');const next=items.map(r=>normalizeRecipient(r,scope));if(new Set(next.map(r=>`${r.sellerId}:${r.storeId}`)).size!==next.length)fail('SCOPE','Satıcı kapsamı tekrarlanıyor.');return next;}
 async function initialize(){if(state.pending)fail('BUSY','Önce mevcut işlemin bitmesini bekle.');try{access('read','readOffers');let recipients,offers;if(mode==='host'){access('read','readRecipients');recipients=roster(envelope(await ports.readRecipients(request({}))).recipients);offers=list(envelope(await ports.readOffers(request({}))).offers);}else{if(typeof localRecipients!=='function'||typeof localCatalog!=='function')fail('CONFIG','Yerel satıcı kaynağı gerekli.');recipients=roster(await localRecipients());offers=readLocal();}if(offers.some(o=>!recipients.some(r=>sameRecipient(r,o.recipient))))fail('SCOPE','Teklif listesinde yetkili olmayan mağaza var.');if(disposed)return;catalogs.clear();pendingCreates.clear();pendingWrites.clear();state={...state,phase:'ready',recipients,offers,error:''};emit();return snapshot();}catch(error){if(!disposed){state={...state,phase:'error',error:['SCOPE','STORAGE','CONFIG'].includes(error.code)?error.message:'Satıcı tema bağlantısı kurulamadı.'};emit();}throw error;}}
 const snapshot=()=>clone(state);const recipientFor=r=>state.recipients.find(x=>sameRecipient(x,r))||fail('SCOPE','Mağaza yetkili listede bulunamadı.');
 async function catalogFor(r,{refresh=false}={}){const recipient=recipientFor(r),k=JSON.stringify([recipient.tenantId,recipient.sellerId,recipient.storeId]);if(!refresh&&catalogs.has(k))return clone(catalogs.get(k));access('read','readCatalog');let data;if(mode==='host'){const e=envelope(await ports.readCatalog(request({recipient:clone(recipient)})));if(!sameRecipient(e.recipient,recipient))fail('SCOPE','Katalog başka bir satıcıya ait.');data=e.products;}else data=await localCatalog(recipient);const products=validateCatalog(data,recipient);if(disposed)fail('CLOSED','Çalışma alanı kapatıldı.');catalogs.set(k,products);return clone(products);}
 function current(offerId,expectedRevision){const o=state.offers.find(x=>x.id===offerId);if(!o)fail('NOT_FOUND','Teklif bulunamadı.');if(o.revision!==expectedRevision)fail('CONFLICT','Teklif başka bir işlemde değişti. Listeyi yeniden aç.');return o;}
 async function run(fn){if(state.phase!=='ready')fail('UNAVAILABLE','Teklif çalışma alanı hazır değil.');if(state.pending)fail('BUSY','Önce mevcut işlemin bitmesini bekle.');state={...state,pending:true,error:''};emit();try{return await fn();}catch(error){state={...state,error:['SCOPE','CONFLICT','CATALOG','STATE','DOMAIN','STORAGE','THEME','NOT_READY'].includes(error.code)?error.message:'İşlem tamamlanamadı; son kayıt korunuyor.'};throw error;}finally{state={...state,pending:false};emit();}}
 async function persist(next,expectedRevision){access('edit','saveOffer');normalizeOffer(next,scope);let saved;
  if(mode==='host'){const operation=`${next.id}:${expectedRevision}`,prior=pendingWrites.get(operation),stable=o=>JSON.stringify({...o,updatedAt:'',history:o.history.map(h=>({...h,at:''}))});if(prior&&stable(prior.offer)!==stable(next))fail('UNCERTAIN','Önceki sunucu kaydının sonucu belirsiz. Listeyi yeniden açmadan farklı bir kayıt gönderilemez.');const attempt=prior||{offer:clone(next),idempotencyKey:uuid()};pendingWrites.set(operation,attempt);next=attempt.offer;const response=envelope(await ports.saveOffer(request({offer:clone(next),expectedRevision,idempotencyKey:attempt.idempotencyKey})));saved=normalizeOffer(response.offer,scope);if(saved.id!==next.id||saved.revision!==next.revision||!sameRecipient(saved.recipient,next.recipient)||JSON.stringify({...saved,updatedAt:next.updatedAt})!==JSON.stringify(next))fail('RESPONSE','Sunucu farklı bir teklif döndürdü. Listeyi yeniden aç.');pendingWrites.delete(operation);}
  else{const save=()=>{const data=readLocal(),old=data.find(x=>x.id===next.id);if((old?.revision??0)!==expectedRevision)fail('CONFLICT','Teklif başka bir sekmede değişti. Listeyi yeniden aç.');if(next.status==='ready'&&!readiness(next,{themes,recipients:state.recipients,products:catalogs.get(JSON.stringify([next.recipient.tenantId,next.recipient.sellerId,next.recipient.storeId]))||[],offers:data}).ready)fail('NOT_READY','Adres veya ürün hazırlığı başka bir işlemde değişti.');const result=[...data.filter(x=>x.id!==next.id),next];if(result.length>MAX_OFFERS)fail('STORAGE','En fazla 100 teklif hazırlanabilir.');const raw=JSON.stringify({version:1,scope,offers:result});if(raw.length>2000000)fail('STORAGE','Teklif kayıt alanı dolu.');try{storage.setItem(key,raw);}catch{fail('STORAGE','Teklif kaydedilemedi. Depolama alanını kontrol et.');}return next;};saved=globalThis.navigator?.locks?.request?await navigator.locks.request(key,save):save();}
  if(disposed)fail('CLOSED','Çalışma alanı kapatıldı.');state={...state,offers:[...state.offers.filter(o=>o.id!==saved.id),clone(saved)]};return clone(saved);
 }
 function event(offer,action){const at=now();return{...clone(offer),revision:offer.revision+1,updatedAt:at,history:[...offer.history,{at,action,revision:offer.revision+1}].slice(-40)};}
 const create=({recipient,themeId})=>run(async()=>{const selected=recipientFor(recipient),theme=themes.find(t=>t.id===themeId)||fail('THEME','Tema bulunamadı.'),creationKey=JSON.stringify([selected.sellerId,selected.storeId,themeId]),at=pendingCreates.get(creationKey)?.createdAt||now(),offer=pendingCreates.get(creationKey)||{schemaVersion:1,id:uuid(),revision:1,scope,recipient:clone(selected),theme:clone(theme),channels:[...theme.channels],site:{mode:'subdomain',subdomain:'',domain:'',locale:'tr-TR',currency:'TRY'},commercial:{commissionBps:0,setupFeeMinor:0,monthlyFeeMinor:0,currency:'TRY',basis:'net-products-after-discounts',termsVersion:'proposal-1'},productIds:[],status:'draft',createdAt:at,updatedAt:at,history:[{at,action:'created',revision:1}]};pendingCreates.set(creationKey,offer);const saved=await persist(offer,0);pendingCreates.delete(creationKey);return saved;});
 const update=(offerId,patch,revision)=>run(async()=>{const old=current(offerId,revision);recipientFor(old.recipient);if(old.status==='withdrawn')fail('STATE','Geri çekilen teklifi önce yeniden taslağa al.');if(!isRecord(patch)||Object.keys(patch).some(k=>!PATCH_KEYS.includes(k)))fail('SCHEMA','Teklif düzenleme alanı geçersiz.');const next=normalizeOffer({...event(old,'edited'),...clone(patch),status:'draft'},scope);const theme=themes.find(t=>t.id===next.theme.id&&t.source===next.theme.source&&t.version===next.theme.version);if(!theme)fail('THEME','Tema sürümü artık koleksiyonda değil.');const products=await catalogFor(next.recipient,{refresh:true});if(next.productIds.some(pid=>!products.some(p=>p.id===pid)))fail('CATALOG','Seçimde bu mağazaya ait olmayan ürün var.');return persist(next,revision);});
 async function inspect(offerId){const old=state.offers.find(o=>o.id===offerId)||fail('NOT_FOUND','Teklif bulunamadı.');const products=await catalogFor(old.recipient,{refresh:true});return readiness(old,{themes,recipients:state.recipients,products,offers:mode==='local'?readLocal():state.offers});}
 const transition=(offerId,action,revision)=>run(async()=>{const old=current(offerId,revision);recipientFor(old.recipient);const allowed={validated:['draft'],ready:['validated'],withdrawn:['draft','validated','ready'],draft:['withdrawn']};if(!allowed[action]?.includes(old.status))fail('STATE','Bu durum geçişi kullanılamıyor.');if(action==='validated'||action==='ready'){const report=await inspect(offerId);if(!report.ready)fail('NOT_READY','Tema, ürün seçimi ve site planındaki eksikleri tamamla.');if(mode==='host'){access('prepare','validateOffer');const r=envelope(await ports.validateOffer(request({offer:clone(old),expectedRevision:revision})));if(r.offerId!==old.id||r.revision!==revision||r.readyForPresentation!==true||!sameRecipient(r.recipient,old.recipient))fail('NOT_READY','Sunucu teklifi sunuma hazır doğrulamadı.');}}return persist({...event(old,action==='draft'?'reopened':action),status:action},revision);});
 async function preview(offerId,channel){const offer=state.offers.find(x=>x.id===offerId)||fail('NOT_FOUND','Teklif bulunamadı.');recipientFor(offer.recipient);if(!themes.some(t=>t.id===offer.theme.id&&t.source===offer.theme.source&&t.version===offer.theme.version))fail('THEME','Tema sürümü artık koleksiyonda değil.');if(!offer.channels.includes(channel)||offer.status==='withdrawn')fail('STATE','Bu teklif için önizleme kullanılamıyor.');const products=await catalogFor(offer.recipient,{refresh:true});if(offer.productIds.some(x=>!products.some(p=>p.id===x)))fail('CATALOG','Teklifte artık yetkili olmayan ürün var.');if(mode==='local')return{mode,offer:clone(offer),channel,products:products.filter(p=>offer.productIds.includes(p.id)),productionReady:false};access('preview','createPreview');const r=envelope(await ports.createPreview(request({offerId,expectedRevision:offer.revision,recipient:clone(offer.recipient),channel})));if(!sameRecipient(r.recipient,offer.recipient)||r.offerId!==offerId||r.revision!==offer.revision||r.channel!==channel)fail('SCOPE','Önizleme kapsamı uyuşmuyor.');if(typeof r.url!=='string'||!r.url.trim())fail('URL','Önizleme bağlantısı eksik.');const url=new URL(r.url,baseURL);if(!['http:','https:'].includes(url.protocol)||url.origin!==new URL(baseURL).origin||url.username||url.password)fail('URL','Önizleme bağlantısı onaylı aynı kök adreste olmalı.');return{mode,offer:clone(offer),channel,url:url.href,productionReady:false};}
 return{initialize,snapshot,subscribe:fn=>{listeners.add(fn);return()=>listeners.delete(fn);},create,update,inspect,transition,preview,catalogFor,storageKey:key,dispose(){disposed=true;listeners.clear();catalogs.clear();pendingCreates.clear();pendingWrites.clear();}};
}
