'use strict';
// Actual disposable PostgreSQL, canonical auth/router/policy and signed HTTP.
// Upstream Stocky session truth is an explicit local signed protocol test double;
// this suite does not claim a real Stocky browser login or publication acceptance.
const assert=require('node:assert/strict'),crypto=require('node:crypto'),express=require('express');
const startDisposable=require('./helpers/themePlatformDisposableDb');
let db,server,upstream;const gates=[];
async function gate(name,work){await work();gates.push({name,status:'PASS'});db.originalConsole.log('PASS '+name);}
(async()=>{
 db=await startDisposable();const pool=db.pool,fixture=await require('./helpers/themePlatformWave2Fixtures').seedWave2(pool,db.sensitive);
 const {admin,a,b,viewer,unbound,support,storeA,storeB}=fixture,platform=require('../services/themePlatformService'),bridge=require('../services/themeSellerBridgeService'),connector=require('../services/stockySystemConnectorService');
 const actor={kind:'admin',userId:admin.userId,sessionId:admin.sessionId},serviceApi=platform.createThemePlatformService(pool),experience=require('../services/themePlatformExperienceService').createThemeExperienceService(pool);
 const execute=(api,action,params,body)=>api.execute(actor,action,params,{...body,reason:'Owned no-assignment Admin scope acceptance'},{idempotencyKey:crypto.randomUUID()}).then(row=>row.result);
 const serviceA=await execute(serviceApi,'createService',{}, {storeId:storeA.id,plan:'pro',status:'ACTIVE',startsAt:'2026-01-01T00:00:00Z',expiresAt:null});
 const serviceB=await execute(serviceApi,'createService',{}, {storeId:storeB.id,plan:'pro',status:'ACTIVE',startsAt:'2026-01-01T00:00:00Z',expiresAt:null});
 await execute(experience,'configureExperience',{serviceId:serviceA.id},{expectedRevision:Number(serviceA.policy_revision),profileCode:'BASIC',overrides:{'theme.colors':{effect:'DENY'}}});
 const secret=crypto.randomBytes(48).toString('base64url');db.sensitive.add(secret);
 Object.assign(process.env,{NOVASTORE_STOCKY_THEME_DELIVERY_ENABLED:'true',NOVASTORE_STOCKY_THEME_DELIVERY_ACTIVATION_MODE:'local',NOVASTORE_STOCKY_THEME_DELIVERY_LOCAL_TRANSPORT_ENABLED:'true',NOVASTORE_STOCKY_THEME_DELIVERY_ALLOWED_HOSTS:'127.0.0.1',NOVASTORE_STOCKY_SYSTEM_COMMERCE_SECRETS_JSON:JSON.stringify({fixture:secret})});
 db.sensitive.add(process.env.NOVASTORE_STOCKY_SYSTEM_COMMERCE_SECRETS_JSON);
 const runtime=require('../services/themeStockyDeliveryService').resolveThemeDeliveryRuntime({environment:process.env,startupSafety:require('../config/startupSafety').resolveStartupSafety(process.env)});
 let remoteActive=true,wrongIdentity=false,corruptSignature=false,disconnect=false,introspectionCalls=0,connection;
 const remote=express();remote.use(express.text({type:'application/json'}));remote.post(bridge.INTROSPECT_PATH,(request,response)=>{
  introspectionCalls++;const body=JSON.parse(request.body),timestamp=Number(request.get('X-NovaStore-Timestamp')),nonce=request.get('X-NovaStore-Nonce');
  const signed=connector.signStockyThemeSellerRequest({connection,runtime,method:'POST',path:bridge.INTROSPECT_PATH,body:request.body,timestamp,nonce});
  assert.equal(request.get('X-NovaStore-Signature'),signed.headers['X-NovaStore-Signature']);
  if(disconnect){request.socket.destroy();return;}
  const reply=JSON.stringify({active:remoteActive,tenantId:body.tenantId,humanUserId:wrongIdentity?body.humanUserId+1:body.humanUserId,sessionHash:body.sessionHash});
  const canonical=['v1-response','200',bridge.INTROSPECT_PATH,'127.0.0.1',connection.id,connection.key_id,String(timestamp),nonce,bridge.digest(reply)].join('\n');
  const signature=corruptSignature?'0'.repeat(64):crypto.createHmac('sha256',secret).update(canonical).digest('hex');
  response.set({'X-NovaStore-Connection':connection.id,'X-NovaStore-Key-Id':connection.key_id,'X-NovaStore-Request-Timestamp':String(timestamp),'X-NovaStore-Request-Nonce':nonce,'X-NovaStore-Response-Signature':'sha256='+signature}).type('json').send(reply);
 });
 upstream=await new Promise(resolve=>{const listener=remote.listen(0,'127.0.0.1',()=>resolve(listener));});
 const app=express();app.use(express.json());app.locals.sellerDatabase=pool;const routers=require('../routes/themePlatformRoutes');
 app.use('/api/admin/theme-platform',routers.createAdminThemeRouter({database:pool,enabled:true}));
 app.use('/api/seller/v1/theme-platform',routers.createSellerThemeRouter({database:pool,enabled:true,auth:require('../middlewares/sellerAuthMiddleware').createSellerAuthMiddleware({verifyAccessToken:fixture.tokenService.verify}),tenant:require('../middlewares/sellerTenantContext').createSellerTenantContextMiddleware()}));
 server=await new Promise(resolve=>{const listener=app.listen(0,'127.0.0.1',()=>resolve(listener));});
 const request=async(path,who=admin)=>{const result=await fetch(`http://127.0.0.1:${server.address().port}${path}`,{headers:who?{authorization:`Bearer ${who.token}`}:{}});return {status:result.status,body:await result.json()};};
 const details=id=>request(`/api/admin/theme-platform/services/${id}/experience-details`),preview=id=>request(`/api/admin/theme-platform/services/${id}/seller-preview`);
 const unavailable=row=>{assert.equal(row.status,200);assert.equal(row.body.experience.mode,'configured-only');assert.equal(row.body.experience.sellerAccess.status,'UNAVAILABLE');assert(Object.values(row.body.experience.capabilities).every(item=>item.state==='HIDDEN'));};
 await gate('A01 native live Seller policy is intersected with configured service permissions',async()=>{const row=await details(serviceA.id);assert.equal(row.status,200);assert.equal(row.body.experience.sellerAccess.status,'VERIFIED');assert.equal(row.body.experience.capabilities['theme.colors'].state,'HIDDEN');assert.equal(row.body.experience.capabilities['theme.banner'].state,'EDITABLE');});
 await pool.query("UPDATE seller_sessions SET status='revoked' WHERE organization_id=$1",[storeA.org]);
 await gate('A02 no Seller session and zero assignments still exposes Admin configuration with no effective grants',async()=>{const row=await details(serviceA.id);unavailable(row);assert.equal(row.body.service.id,serviceA.id);assert.deepEqual(row.body.assignments,[]);assert.equal(row.body.experience.configuredCapabilities['theme.banner'].state,'EDITABLE');assert.deepEqual(row.body.experience.overrides,{'theme.colors':{effect:'DENY'}});assert.equal(Number((await pool.query('SELECT count(*) n FROM theme_assignments')).rows[0].n),0);});
 await gate('A03 unauthenticated, unbound and support actors cannot read protected details',async()=>{for(const[who,status]of[[null,401],[unbound,403],[support,403],[b,401]])assert.equal((await request(`/api/admin/theme-platform/services/${serviceA.id}/experience-details`,who)).status,status);});
 await gate('A04 foreign Seller cannot use another service experience and no-session preview remains closed',async()=>{assert.equal((await request(`/api/seller/v1/theme-platform/services/${serviceA.id}/experience`,b)).status,404);assert.equal((await preview(serviceA.id)).status,409);});
 const cid=crypto.randomUUID(),tid=crypto.randomUUID(),mapping=crypto.randomUUID();
 await pool.query(`INSERT INTO stocky_connector_connections(id,organization_id,store_id,remote_store_id,endpoint_origin,key_id,secret_ref) VALUES($1,$2,$3,'human-mapping-fixture',$4,'scope-test','fixture')`,[cid,storeA.org,storeA.id,`http://127.0.0.1:${upstream.address().port}`]);
 connection=(await pool.query('SELECT * FROM stocky_connector_connections WHERE id=$1',[cid])).rows[0];
 await pool.query(`INSERT INTO theme_seller_bridge_mappings(id,connection_id,tenant_id,stocky_user_id,organization_id,store_id,membership_id,user_id,approved_by_user_id,approval_reason) VALUES($1,$2,$3,901,$4,$5,$6,$7,$8,'Explicit human fixture mapping only')`,[mapping,cid,tid,storeA.org,storeA.id,a.membershipId,a.userId,admin.userId]);
 const authBridge=bridge.createThemeSellerBridge({database:pool,runtime});
 const authenticate=async()=>{const request={method:'GET',path:'/assignments'},now=Math.floor(Date.now()/1000),assertion={version:1,audience:'novastore-theme-seller',purpose:'theme-action',connectionId:cid,keyId:'scope-test',tenantId:tid,humanUserId:901,sessionHash:crypto.randomBytes(32).toString('hex'),issuedAt:now,expiresAt:now+15,nonce:crypto.randomBytes(16).toString('hex'),requestHash:bridge.digest(bridge.canonical(request))};return authBridge.authenticate({request,assertion,signature:crypto.createHmac('sha256',secret).update(`theme-seller-assertion-v1\n${bridge.canonical(assertion)}`).digest('hex')});};
 await gate('A05 membership mapping without an authenticated lease grants no projected Seller access',async()=>unavailable(await details(serviceA.id)));
 let bridged;
 await gate('A06 real bridge lease and signed live callback enable exact scoped role projection',async()=>{bridged=await authenticate();const count=introspectionCalls,row=await details(serviceA.id);assert.equal(row.status,200);assert.equal(row.body.experience.sellerAccess.status,'VERIFIED');assert.equal(row.body.experience.capabilities['theme.banner'].state,'EDITABLE');assert(introspectionCalls>count);const read=await preview(serviceA.id);assert.equal(read.status,200);assert.deepEqual(read.body.availableChannels,[]);});
 await gate('A07 projection brand cannot mutate or survive serialization',async()=>{await platform.transaction(pool,async client=>{const projection=await bridge.resolveAdminThemeSellerProjection(client,actor,serviceA);const auth=require('../services/themePlatformAuthService').authorize;assert.equal((await auth(client,projection,'draft.read',serviceA)).userId,a.userId);await assert.rejects(auth(client,projection,'draft.edit',serviceA),{code:'THEME_PERMISSION_DENIED'});await assert.rejects(auth(client,JSON.parse(JSON.stringify(projection)),'draft.read',serviceA),{code:'THEME_AUTH_REQUIRED'});});});
 await gate('A08 remote logout hides effective access despite an unexpired local lease',async()=>{remoteActive=false;unavailable(await details(serviceA.id));assert.equal((await preview(serviceA.id)).status,401);assert((await pool.query('SELECT expires_at>now() live FROM theme_seller_bridge_sessions WHERE id=$1',[bridged.bridgeSessionId])).rows[0].live);remoteActive=true;});
 await gate('A09 signed wrong human identity and corrupt response signature never enable projection',async()=>{wrongIdentity=true;unavailable(await details(serviceA.id));wrongIdentity=false;corruptSignature=true;unavailable(await details(serviceA.id));corruptSignature=false;});
 await gate('A15 an unavailable upstream preserves Admin metadata but never grants Seller preview',async()=>{disconnect=true;unavailable(await details(serviceA.id));assert.equal((await preview(serviceA.id)).status,503);disconnect=false;});
 await gate('A10 local lease revocation prevents projection before remote lookup',async()=>{await pool.query('UPDATE theme_seller_bridge_sessions SET revoked_at=clock_timestamp() WHERE id=$1',[bridged.bridgeSessionId]);const count=introspectionCalls;unavailable(await details(serviceA.id));assert.equal(introspectionCalls,count);});
 await gate('A11 new authenticated lease restores actual access; a foreign store cannot borrow it',async()=>{bridged=await authenticate();assert.equal((await details(serviceA.id)).body.experience.sellerAccess.status,'VERIFIED');await pool.query("UPDATE seller_sessions SET status='revoked' WHERE organization_id=$1",[storeB.org]);unavailable(await details(serviceB.id));});
 await gate('A12 current membership revocation blocks otherwise-live remote sessions',async()=>{await pool.query('UPDATE seller_memberships SET membership_revision=membership_revision+1 WHERE id=$1',[a.membershipId]);unavailable(await details(serviceA.id));});
 await gate('A13 immutable mapping revocation blocks projection and no lease is renewed by Admin reads',async()=>{const before=(await pool.query('SELECT count(*)::int n,max(expires_at) expiry FROM theme_seller_bridge_sessions')).rows[0];await pool.query('UPDATE theme_seller_bridge_mappings SET active=FALSE,revoked_at=clock_timestamp(),revision=revision+1 WHERE id=$1',[mapping]);unavailable(await details(serviceA.id));const after=(await pool.query('SELECT count(*)::int n,max(expires_at) expiry FROM theme_seller_bridge_sessions')).rows[0];assert.deepEqual(after,before);});
 await gate('A14 authorized Admin can update configured profile without a Seller session while effective access stays hidden',async()=>{const before=await details(serviceA.id),response=await fetch(`http://127.0.0.1:${server.address().port}/api/admin/theme-platform/services/${serviceA.id}/experience`,{method:'PUT',headers:{authorization:`Bearer ${admin.token}`,'content-type':'application/json','idempotency-key':crypto.randomUUID()},body:JSON.stringify({expectedRevision:before.body.experience.policyRevision,profileCode:'ADVANCED',overrides:{'theme.banner':{effect:'DENY'}},reason:'Configured policy update without pretending Seller authentication'})});assert.equal(response.status,200);const after=await details(serviceA.id);unavailable(after);assert.equal(after.body.experience.profileCode,'ADVANCED');assert.equal(after.body.experience.configuredCapabilities['theme.banner'].state,'HIDDEN');assert(after.body.experience.policyRevision>before.body.experience.policyRevision);});
 db.originalConsole.log(JSON.stringify({suite:'themeAdminExperienceScopePostgresSmoke',result:'PASS',pass:gates.length,fail:0,skip:0,migrations:db.migrations.length,gates,scope:'Real disposable PG, original Admin/native Seller HTTP auth and real signed bridge protocol. Upstream Stocky live-session truth is an explicit local protocol double. No real Stocky browser or publication claim.'}));
})().catch(error=>{(db?.originalConsole.error||console.error)(db?db.redact(error.stack):error.message);process.exitCode=1;}).finally(async()=>{if(server)await new Promise(resolve=>server.close(resolve));if(upstream)await new Promise(resolve=>upstream.close(resolve));if(db)try{console.log(JSON.stringify({cleanup:await db.cleanup()}));}catch(error){console.error(error.message);process.exitCode=1;}});
