'use strict';
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const registry=require('../theme-platform/presentations.json'),service=require('../services/themePlatformPresentationService');
const {buildRegistry}=require('../scripts/buildThemePlatformPresentationRegistry');
const {validatePresentationDocument}=require('../services/themePlatformPresentationEditGuard');
const {validateThemePackage}=require('../services/themePlatformPackageService');
const v=require('../services/themePlatformValidation');
const {loadBuildAcceptance}=require('../scripts/lib/themePresentationAcceptance');
const atelier=require('../theme-platform/packages/nova-atelier-studio-web-v1.json'),classic=require('../theme-platform/packages/nova-classic-studio-web-v1_1.json');
test('27 families and 54 exact channel entries preserve 52 source-only entries and two reviewed web channels',()=>{
 assert.deepEqual(buildRegistry(),registry);assert.equal(registry.inventory.length,54);assert.equal(new Set(registry.inventory.map(r=>r.themeId)).size,27);
 const proof=loadBuildAcceptance(path.resolve(__dirname,'..'),registry.presentations);assert.deepEqual(proof.rejected,[]);assert.equal(proof.accepted.size,2);
 assert.equal(registry.inventory.filter(row=>row.status==='READY').length,2);assert.equal(registry.inventory.filter(row=>row.status==='PARTIAL').length,52);
 for(const row of registry.inventory){const accepted=proof.accepted.get(`${row.rendererId}/${row.channel}`);assert.equal(row.status,accepted?'READY':'PARTIAL');assert.equal(row.runtimeReady,!!accepted);assert.equal(row.assignmentEligible,!!accepted);if(accepted){assert.equal(row.channel,'web');assert.equal(row.acceptance.proofSHA256,accepted.proofSHA256);assert.equal(row.acceptance.storeActivation,'NOT_ASSERTED');}assert.ok(row.sourceIdentity);assert.ok(row.previewAssets.sourceEntry);for(const source of row.sourceHashes){const bytes=fs.readFileSync(path.join(__dirname,'../studio-core/workshop-public/theme-library',source.path));assert.equal(bytes.length,source.bytes);assert.equal(v.digest(bytes),source.sha256);}}
});
test('Classic accepted immutable presentation digest remains unchanged',()=>{const entry=registry.presentations.find(p=>p.id==='nova-classic'),{digest,...identity}=entry;assert.equal(digest,'d8c72698fc9a4be3f6393dbe47b6ff5ed981d67ea24896e0fb8ef159daf91668');assert.equal(v.digest(identity),digest);assert.equal(service.presentationReadiness(classic.renderer.presentation,'web').presentationReady,true);});
test('Atelier is a separate exact original identity, not a Classic alias; no unknown fallback',()=>{assert.notEqual(atelier.renderer.presentation.digest,classic.renderer.presentation.digest);assert.equal(service.presentationMetadata(atelier,2).sourceThemeId,'02-atelier');for(const value of [{...atelier.renderer.presentation,id:'unknown'},{...atelier.renderer.presentation,digest:'0'.repeat(64)}])assert.throws(()=>service.resolvePresentation(value,{schemaVersion:2,channels:['web']}),{code:'THEME_PRESENTATION_UNSUPPORTED'});assert.throws(()=>service.resolvePresentation(atelier.renderer.presentation,{schemaVersion:2,channels:['app']}),{code:'THEME_PRESENTATION_UNSUPPORTED'});});
test('reviewed web compatibility allows assignment but never implies active publication or app acceptance',()=>{for(const input of [atelier,classic]){const ready=service.presentationReadiness(input.renderer.presentation);assert.equal(ready.localPreviewSupported,true);assert.equal(ready.runtimeReady,true);assert.equal(ready.assignmentEligible,true);assert.equal(ready.acceptance.storeActivation,'NOT_ASSERTED');assert.equal(ready.acceptance.phase,'COMPATIBILITY_ACCEPTED_PRE_PUBLICATION');assert.deepEqual(service.requireAssignablePresentation(input.renderer.presentation),ready);assert.throws(()=>service.requireAssignablePresentation(input.renderer.presentation,'app'),{code:'THEME_PRESENTATION_UNSUPPORTED'});}assert.equal(service.presentationReadiness(null).status,'UNSUPPORTED');assert.throws(()=>service.requireAssignablePresentation(null),{code:'THEME_PRESENTATION_NOT_READY',statusCode:409});});
test('renderer intersection only reduces authority and hides unsupported capability names',()=>{const input={policyRevision:7,capabilities:{'theme.banner':{state:'PUBLISH',supported:true},'theme.logo':{state:'HIDDEN',supported:true},'theme.version_history':{state:'MANAGE',supported:true},'theme.custom_js':{state:'PUBLISH',supported:true},'unknown':{state:'EDITABLE',supported:true}}};const out=service.intersectPresentationCapabilities(input,atelier.renderer.presentation);assert.equal(out.capabilities['theme.banner'].state,'EDITABLE');assert.equal(out.capabilities['theme.logo'].state,'HIDDEN');assert.equal(out.capabilities['theme.version_history'].state,'READ_ONLY');assert.equal(out.capabilities['theme.custom_js'].state,'HIDDEN');assert.equal(out.capabilities.unknown.state,'HIDDEN');assert.equal(out.policyRevision,7);assert.equal(input.capabilities['theme.banner'].state,'PUBLISH');for(const item of Object.values(service.intersectPresentationCapabilities(input,null).capabilities))assert.equal(item.state,'HIDDEN');});
test('Atelier package validates with original photographic bytes and immutable family schema',()=>{assert.ok(validateThemePackage(atelier,{capabilityCodes:Object.keys(require('../services/themePlatformExperiencePolicy').CATALOG)}));assert.equal(validatePresentationDocument(atelier.renderer.presentation,atelier.document),atelier.document);});
test('Atelier accepts rendered copy/hero/colors but refuses ineffective categories/story media and forged canonical data',()=>{
 const next=structuredClone(atelier.document);next.studio.blocks[0].title='Yeni hikÃ¢ye';next.studio.blocks[0].target='categories';next.studio.blocks[3].description='MaÄŸazanÄ±n Ã¶ykÃ¼sÃ¼';next.studio.theme.accent='#212121';assert.equal(validatePresentationDocument(atelier.renderer.presentation,atelier.document,next),next);
 for(const change of [s=>{s.blocks[1].title='Ignored';},s=>{s.blocks[3].image=s.blocks[0].image;},s=>s.blocks.reverse(),s=>{s.blocks[2].productLimit=2;},s=>{s.design.elements.push({id:'productTitle',content:{text:'Fake product'}});}]){const document=structuredClone(atelier.document);change(document.studio);assert.throws(()=>validatePresentationDocument(atelier.renderer.presentation,atelier.document,document),{code:'THEME_PRESENTATION_EDIT_UNSUPPORTED'});}
 assert.throws(()=>validatePresentationDocument(atelier.renderer.presentation,classic.document),{code:'THEME_PRESENTATION_EDIT_UNSUPPORTED'});
});
