import { ArrowLeft, Minus, Plus, Trash2 } from "lucide-react";
import { useCart } from "../state/CartContext";

export function CartPage() {
  const { items, loading, busy, setQuantity, removeProduct, checkout } = useCart();
  const total = items.filter((item) => item.selected).reduce((sum, item) => sum + item.price * item.quantity, 0);
  if (loading) return <section className="section"><p>Sepet yükleniyor…</p></section>;
  return <section className="section cart-page"><a className="back-link" href="/theme-preview"><ArrowLeft /> Alışverişe dön</a><div className="section-heading"><div><span className="eyebrow">Sepetim</span><h1>Seçtiklerin</h1></div></div>{items.length === 0 ? <div className="empty-cart"><h2>Sepetin henüz boş</h2><p>Beğendiğin ürünleri ekleyerek alışverişe başlayabilirsin.</p><a className="button primary" href="/theme-preview">Ürünleri Keşfet</a></div> : <div className="cart-layout"><div className="cart-list">{items.map((item) => <article className="cart-item" key={item.productId}>{item.image ? <img src={item.image} alt={item.name} /> : <div className="cart-placeholder">N</div>}<div><strong>{item.name}</strong><span>{item.price.toLocaleString("tr-TR", { minimumFractionDigits: 2 })} TL</span></div><div className="quantity compact"><button onClick={() => setQuantity(item.productId, Math.max(1, item.quantity - 1))}><Minus /></button><strong>{item.quantity}</strong><button onClick={() => setQuantity(item.productId, item.quantity + 1)}><Plus /></button></div><button className="remove" onClick={() => removeProduct(item.productId)} aria-label={`${item.name} ürününü sepetten kaldır`}><Trash2 /></button></article>)}</div><aside className="cart-summary"><span>Toplam</span><strong>{total.toLocaleString("tr-TR", { minimumFractionDigits: 2 })} TL</strong><button className="button primary" disabled={busy} onClick={async () => { await checkout(); window.location.href = "/checkout.html"; }}>Checkout’a Devam Et</button><small>Ödeme, mevcut NovaStore checkout akışında tamamlanır.</small></aside></div>}</section>;
}
