import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {createPlatformClient,mountPlatformStudio} from '../../studio-core/src/studio-integration/platform-bridge.js';
import './style.css';
import {createSessionBoundary} from './session-boundary.js';
import {createLatestRequest} from '../../studio-core/src/studio-integration/latest-request.js';
import {createStudioLeaveGuard,hasUnsavedStudioWork} from '../../studio-core/src/studio-integration/navigation-guard.js';

function App(){
  const historyGate=useRef(createLatestRequest()).current;
  const boundary=useRef(createSessionBoundary()).current,selectedService=useRef(''),studio=useRef(null);
  const credentials=useRef(null),refreshTimer=useRef(null),[session,setSession]=useState(null),[identifier,setIdentifier]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[assignments,setAssignments]=useState([]),[serviceId,setServiceId]=useState(''),[context,setContext]=useState(null),[history,setHistory]=useState(null),[assignmentsPhase,setAssignmentsPhase]=useState('idle'),[loadingStudio,setLoadingStudio]=useState(false),[notice,setNotice]=useState(''),[key,setKey]=useState(0),host=useRef(null);
  selectedService.current=serviceId;
  const readStudioState=()=>studio.current?.frame?.contentWindow?.NovaStoreStudio?.getState();
  const canLeaveStudio=()=>createStudioLeaveGuard({readState:readStudioState,confirm:message=>window.confirm(message),notify:setError})();
  function selectService(next){if(next===serviceId||!canLeaveStudio())return;historyGate.invalidate();setContext(null);setHistory(null);setNotice('');setLoadingStudio(false);setServiceId(next);}
  function reloadWorkspace(){if(canLeaveStudio()){historyGate.invalidate();setHistory(null);setKey(value=>value+1);}}
  const clearScoped=()=>{historyGate.invalidate();studio.current?.unmount();studio.current=null;setAssignments([]);setAssignmentsPhase('idle');setLoadingStudio(false);setServiceId('');selectedService.current='';setContext(null);setHistory(null);setNotice('');setError('');setPassword('');};
  const expire=()=>{boundary.advance();credentials.current=null;clearTimeout(refreshTimer.current);setSession(null);setBusy(false);clearScoped();};
  const client=useMemo(()=>createPlatformClient({kind:'seller',token:()=>credentials.current?.access_token||'',onUnauthorized:issuedToken=>{if(issuedToken&&issuedToken===credentials.current?.access_token)expire();}}),[]);
  async function auth(path,body,token){const response=await fetch('/api/seller/v1/auth/'+path,{method:'POST',credentials:'same-origin',cache:'no-store',headers:{'Content-Type':'application/json',...(token?{Authorization:'Bearer '+token}:{})},body:JSON.stringify(body)});const data=await response.json();if(!response.ok)throw Error(data.code||'Oturum açılamadı.');return data;}
  function remember(value,generation){if(!boundary.current(generation))return;credentials.current={...credentials.current,...value};setSession({...credentials.current,access_token:undefined,refresh_token:undefined});clearTimeout(refreshTimer.current);refreshTimer.current=setTimeout(async()=>{if(!boundary.current(generation)||!credentials.current)return;const refreshCredential=credentials.current.refresh_token;try{const updated=await auth('refresh',{refresh_token:refreshCredential});remember(updated,generation);}catch{if(boundary.current(generation)){expire();setError('Oturum yenilenemedi. Yeniden giriş yapın.');}}},Math.max(1000,(Number(value.expires_in)-60)*1000));}
  async function login(event){event.preventDefault();const generation=boundary.advance();setBusy(true);clearScoped();try{const response=await auth('login',{identifier,password});remember(response,generation);if(boundary.current(generation))setPassword('');}catch(e){boundary.apply(generation,()=>setError(e.message));}finally{boundary.apply(generation,()=>setBusy(false));}}
  async function logout(){if(!canLeaveStudio())return;const token=credentials.current?.access_token;expire();const generation=boundary.capture();setBusy(true);try{await auth('logout',{},token);}catch{boundary.apply(generation,()=>setError('Yerel oturum kapatıldı. Sunucudaki çıkış doğrulanamadı.'));}finally{boundary.apply(generation,()=>setBusy(false));}}
  async function refresh(){const generation=boundary.capture();setAssignmentsPhase('loading');setError('');try{const response=await client.get('/assignments');if(!boundary.current(generation))return;setAssignments(response);setAssignmentsPhase('ready');setNotice('');await studio.current?.refresh();}catch(e){boundary.apply(generation,()=>{setAssignmentsPhase('error');setError(e.message);});}}
  useEffect(()=>{if(session)refresh();},[session?.session_id]);
  useEffect(()=>()=>{boundary.advance();credentials.current=null;clearTimeout(refreshTimer.current);},[]);
  useEffect(()=>{const protect=event=>{try{if(!hasUnsavedStudioWork(readStudioState()))return;}catch{}event.preventDefault();event.returnValue='';};window.addEventListener('beforeunload',protect);return()=>window.removeEventListener('beforeunload',protect);},[]);
  useEffect(()=>{if(!serviceId||!session)return;let cancelled=false,mounted;const controller=new AbortController(),generation=boundary.capture(),target=serviceId;const active=()=>!cancelled&&boundary.current(generation)&&selectedService.current===target;historyGate.invalidate();setError('');setHistory(null);setLoadingStudio(true);setContext(null);(async()=>{try{const path='/services/'+target+'/editor-context',data=await client.get(path,{signal:controller.signal});if(!active())return;setContext(data);mounted=await mountPlatformStudio(host.current,{client,context:data,contextPath:path,signal:controller.signal,onContextUpdated:fresh=>{if(active())setContext(fresh);},onError:e=>{if(active()){historyGate.invalidate();setHistory(null);setError(e.message);setContext(null);}}});if(!active())mounted.unmount();else studio.current=mounted;}catch(e){if(active())setError(e.message);}finally{if(active())setLoadingStudio(false);}})();return()=>{cancelled=true;controller.abort();mounted?.unmount();if(studio.current===mounted)studio.current=null;};},[serviceId,session?.session_id,key]);
  async function accept(assignment){if(!canLeaveStudio())return;const generation=boundary.capture(),target=serviceId;const active=()=>boundary.current(generation)&&selectedService.current===target;setBusy(true);setError('');try{await client.write('/assignments/'+assignment.id+'/accept',{expectedRevision:Number(assignment.revision),reason:'Satıcı tema atamasını kabul etti'});if(!active())return;await refresh();if(active()){setNotice('Tema ataması kabul edildi. Bu işlem canlı yayın değildir.');setKey(value=>value+1);}}catch(e){if(active())setError(e.message);}finally{boundary.apply(generation,()=>setBusy(false));}}
  async function readHistory(){const generation=boundary.capture(),target=serviceId,request=historyGate.begin();const active=()=>boundary.current(generation)&&selectedService.current===target&&historyGate.current(request);setError('');try{const entries=await Promise.all(context.availableChannels.map(async channel=>({channel,items:await client.get('/services/'+target+'/drafts/'+context.channels[channel].draftId+'/history')})));if(active())setHistory(entries);}catch(e){if(active())setError(e.message);}}
  if(!session)return <main className="seller-login"><div className="seller-brand">N<span>NovaStore<small>MAĞAZA TASARIMI</small></span></div><form onSubmit={login}><small>SELLER STUDIO</small><h1>Mağazanızın deneyimini yönetin.</h1><p>NovaStore satıcı hesabınızla giriş yapın. Tasarım yetkileri mağazanızın güncel politikasından alınır.</p><label>E-posta veya telefon<input autoComplete="username" required value={identifier} onChange={e=>setIdentifier(e.target.value)}/></label><label>Şifre<input type="password" autoComplete="current-password" required value={password} onChange={e=>setPassword(e.target.value)}/></label>{error&&<p role="alert" className="seller-error">{error}</p>}<button className="primary" disabled={busy}>{busy?'Giriş yapılıyor…':'Giriş yap'}</button><p className="login-note">Stocky oturumu ayrı bir sistemdir. Bu ekran Stocky teslim bağlantısı değildir.</p></form></main>;
  const selected=assignments.filter(item=>item.service_id===serviceId),services=[...new Set(assignments.map(item=>item.service_id))];
  return <main className="seller-theme-shell"><header className="seller-topbar"><div className="seller-brand">N<span>NovaStore<small>MAĞAZA TASARIMI</small></span></div><span>{session.organization?.display_name}</span><button onClick={logout} disabled={busy}>Çıkış yap</button></header><section className="seller-intro"><div><small>SELLER STUDIO</small><h1>Markanıza ait bir deneyim.</h1><p>İzin verilen alanları düzenleyin, taslağı kaydedin ve önizleyin.</p></div><label>Mağaza tasarımı<select aria-label="Mağaza tasarımı" value={serviceId} disabled={busy||loadingStudio} onChange={e=>selectService(e.target.value)}><option value="">Atanmış bir hizmet seçin</option>{services.map(id=><option key={id} value={id}>Mağaza {assignments.find(item=>item.service_id===id).store_id} · {assignments.filter(item=>item.service_id===id).map(item=>item.channel==='app'?'Uygulama':'Web').join(' / ')}</option>)}</select></label><button onClick={refresh} disabled={busy||assignmentsPhase==='loading'}>{assignmentsPhase==='loading'?'Yükleniyor…':'Yenile'}</button></section>{error&&<p role="alert" className="seller-error">{error}</p>}{notice&&<p role="status" className="seller-notice">{notice}</p>}
    {assignmentsPhase==='loading'&&!assignments.length&&<p className="seller-notice" role="status">Tema atamaları yükleniyor…</p>}{assignmentsPhase==='ready'&&!assignments.length&&<section className="seller-empty"><h2>Henüz atanmış bir tema yok</h2><p>Bir atama hazırlandığında burada görüntülenecek. Yerel örnek veya taslak verisi yüklenmedi.</p></section>}
    {context&&<section className="seller-policy"><div><strong>{context.profile.name}</strong><small>Politika sürümü {context.policyRevision}</small></div><span>{Object.values(context.capabilities).filter(item=>['EDITABLE','MANAGE','PUBLISH'].includes(item.state)).length} düzenlenebilir yetenek</span>{selected.filter(item=>item.status==='ASSIGNED').map(item=><button key={item.id} disabled={busy||!['EDITABLE','MANAGE'].includes(context.capabilities['theme.save_draft']?.state)} onClick={()=>accept(item)}>{item.channel==='app'?'Uygulama':'Web'} atamasını kabul et</button>)}{context.capabilities['theme.version_history']&&context.capabilities['theme.version_history'].state!=='HIDDEN'&&<button onClick={readHistory}>Sürüm geçmişi</button>}<button onClick={reloadWorkspace} disabled={busy||loadingStudio}>Çalışma alanını yeniden aç</button></section>}
    {history&&<section className="seller-history"><button onClick={()=>setHistory(null)}>Geçmişi kapat</button>{history.map(entry=><div key={entry.channel}><h2>{entry.channel==='app'?'Uygulama':'Web'} taslak geçmişi</h2>{(Array.isArray(entry.items)?entry.items:entry.items.items||[]).map(revision=><p key={revision.revision}>Sürüm {revision.revision} · {new Date(revision.created_at).toLocaleString('tr-TR')}</p>)}</div>)}</section>}
    {loadingStudio&&<p className="seller-notice" role="status">Yetkili mağaza tasarımı yükleniyor…</p>}{serviceId&&!context&&!loadingStudio&&error&&<button className="seller-reopen" onClick={reloadWorkspace}>Çalışma alanını yeniden aç</button>}<div ref={host} className="seller-editor" aria-busy={loadingStudio}/><footer className="seller-footer">Yayın isteği, canlı yayın ve Stocky teslimi ayrı işlemlerdir. Uygulama görünümü tarayıcı önizlemesidir.</footer>
  </main>;
}
createRoot(document.getElementById('root')).render(<App/>);
