import React,{useEffect,useMemo,useRef,useState} from 'react';
import {createPortal} from 'react-dom';
import {ArrowDown,ArrowUp,Copy,ImagePlus,Plus,Redo2,Save,Shapes,Trash2,Type,Undo2,X} from 'lucide-react';
import {normalizeCampaignCanvas,renderCampaignCanvas,MAX_CANVAS_LAYERS,CANVAS_LAYOUTS,CANVAS_GEOMETRY,placeCampaignLayer,renderCampaignLayer,CAMPAIGN_TEXT_DEFAULTS,CAMPAIGN_TEXT_OPTIONAL,campaignFontFamily} from '../campaignCanvas.js';
import {CANVAS_MOTIF_SETS,campaignMotifAsset} from '../campaignCanvasPresets.js';
import {visualAssets} from '../visual/visualAssets.js';
import {applyCanvasMedia,moveCanvasLayer,shouldDeleteCanvasLayer} from './campaignCanvasActions.js';
import CampaignColorField from './CampaignColorField.jsx';
import CampaignTextControls from './CampaignTextControls.jsx';
import {CAMPAIGN_SHAPES,getCampaignShape} from '../campaignShapes.js';
import CampaignShapePicker from './CampaignShapePicker.jsx';
import CampaignMediaPicker from './CampaignMediaPicker.jsx';
import './campaign-canvas.css';
import {assetURL} from '../../studio-integration/context.js';
const copy=value=>JSON.parse(JSON.stringify(value)),uid=()=>crypto.randomUUID(),clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const name=layer=>layer.kind==='text'?layer.text.slice(0,35)||'Yazı':layer.kind==='icon'?(layer.asset?(layer.asset.viewBox==='0 0 24 40'?'Ramazan feneri':'Vektör süsleme'):visualAssets.builtinIcons.find(i=>i.id===layer.iconId)?.label||layer.iconId):layer.kind==='image'?'Görsel':layer.shapeId?getCampaignShape(layer.shapeId).label:'Şekil';
const field=(label,value,onChange,props={})=><label className="cc-field"><span>{label}</span><input value={value} onChange={e=>onChange(props.type==='number'?Number(e.target.value):e.target.value)} {...props}/></label>;
export default function CampaignCanvasEditor({value,theme={},onSave,onClose}){
 const properties=useRef(null);
 const [shapePicker,setShapePicker]=useState(null),[mediaPicker,setMediaPicker]=useState(null);
 const uploadMode=useRef('add');
 const initial=useRef(normalizeCampaignCanvas(value)),[history,setHistory]=useState({past:[],present:initial.current,future:[]}),[selected,setSelected]=useState(initial.current.layers.at(-1)?.id||''),[temporary,setTemporary]=useState(null),[error,setError]=useState(''),[notice,setNotice]=useState(''),[uploading,setUploading]=useState(false),[discardOpen,setDiscardOpen]=useState(false),[query,setQuery]=useState(''),[motif,setMotif]=useState('ramadan');
 const dialog=useRef(null),stage=useRef(null),drag=useRef(null),upload=useRef(null),latest=useRef(null),historyRef=useRef(history),uploadTarget=useRef(''),uploadSequence=useRef(0),active=useRef(true);historyRef.current=history;const doc=temporary||history.present,layer=doc.layers.find(l=>l.id===selected),dirty=JSON.stringify(history.present)!==JSON.stringify(initial.current);
 const icons=useMemo(()=>visualAssets.builtinIcons.map(i=>({...i,url:visualAssets.assetDataURL(visualAssets.icon(i.id))})),[]),matches=icons.filter(i=>`${i.id} ${i.label} ${(i.terms||[]).join(' ')}`.toLocaleLowerCase('tr-TR').includes(query.toLocaleLowerCase('tr-TR')));
 function replaceHistory(next){historyRef.current=next;setHistory(next);}
 function change(mutate,key=''){try{const current=historyRef.current,next=copy(current.present);mutate(next);const normal=normalizeCampaignCanvas(next);const now=Date.now(),merge=key&&latest.current?.key===key&&now-latest.current.time<650;latest.current={key,time:now};replaceHistory({past:merge?current.past:[...current.past,current.present].slice(-30),present:normal,future:[]});setError('');setNotice('');setDiscardOpen(false);return true;}catch(e){setError(e.message);return false;}}
 const patch=(key,value)=>change(next=>{const l=next.layers.find(l=>l.id===selected);if(l){l[key]=value;if(key==='color'&&l.kind==='icon')l.iconColorMode='single';}},`${selected}:${key}`);
 function undo(){latest.current=null;const h=historyRef.current;if(h.past.length){const previous=h.past.at(-1),restored=previous.layers.find(item=>!h.present.layers.some(current=>current.id===item.id));replaceHistory({past:h.past.slice(0,-1),present:previous,future:[h.present,...h.future]});if(restored)setSelected(restored.id);setNotice('Son tuval değişikliği geri alındı.');}setDiscardOpen(false);}
 function redo(){latest.current=null;const h=historyRef.current;if(h.future.length){const next=h.future[0],restored=next.layers.find(item=>!h.present.layers.some(current=>current.id===item.id));replaceHistory({past:[...h.past,h.present],present:next,future:h.future.slice(1)});if(restored)setSelected(restored.id);setNotice('Tuval değişikliği yeniden uygulandı.');}setDiscardOpen(false);}
 function add(kind,values={}){if(doc.layers.length>=MAX_CANVAS_LAYERS){setError('Tuvalde en fazla 24 öğe bulunabilir.');return;}const next={id:uid(),kind,x:30,y:35,width:kind==='text'?40:20,height:kind==='text'?20:30,color:'@accent',...values};change(d=>d.layers.push(next));setSelected(next.id);}
 function start(event,item,resizing=false){if(event.button!==0||uploading)return;event.preventDefault();event.stopPropagation();setSelected(item.id);event.currentTarget.setPointerCapture(event.pointerId);drag.current={id:item.id,x:event.clientX,y:event.clientY,before:copy(historyRef.current.present),resizing,rect:stage.current.getBoundingClientRect(),moved:false};}
 function move(event){const d=drag.current;if(!d)return;const next=copy(d.before),l=next.layers.find(l=>l.id===d.id),dx=(event.clientX-d.x)/d.rect.width*100,dy=(event.clientY-d.y)/d.rect.height*100;d.moved=Math.abs(dx)+Math.abs(dy)>.2;if(d.resizing){l.width=clamp(l.width+dx,1,CANVAS_GEOMETRY.maxSize);l.height=clamp(l.height+dy,1,CANVAS_GEOMETRY.maxSize);}else{l.x=clamp(l.x+dx,CANVAS_GEOMETRY.minPosition,CANVAS_GEOMETRY.maxPosition);l.y=clamp(l.y+dy,CANVAS_GEOMETRY.minPosition,CANVAS_GEOMETRY.maxPosition);}d.next=normalizeCampaignCanvas(next);setTemporary(d.next);}
 function cancel(){drag.current=null;setTemporary(null);}
 function finish(){const d=drag.current;if(!d)return;drag.current=null;if(d.moved&&d.next){const h=historyRef.current;latest.current=null;replaceHistory({past:[...h.past,h.present].slice(-30),present:d.next,future:[]});}setTemporary(null);}
 useEffect(()=>{active.current=true;const previous=document.activeElement,overflow=document.body.style.overflow;document.body.style.overflow='hidden';dialog.current?.focus();return()=>{active.current=false;uploadSequence.current++;document.body.style.overflow=overflow;if(previous?.isConnected)previous.focus();};},[]);
 useEffect(()=>{if(!doc.layers.some(l=>l.id===selected))setSelected(doc.layers.at(-1)?.id||'');},[doc.layers,selected]);
 function close(){if(drag.current)cancel();if(dirty||uploading)setDiscardOpen(true);else onClose();}
 function save(){if(uploading){setError('Görsel yüklemesinin bitmesini bekle.');return;}if(drag.current){setError('Önce sürüklediğin öğeyi bırak.');return;}onSave(normalizeCampaignCanvas(historyRef.current.present));}
 function chooseImage(targetId='',mode=targetId?'replace':'add'){if(drag.current){setError('Önce sürüklediğin öğeyi bırak.');return;}uploadTarget.current=targetId;uploadMode.current=mode;upload.current.click();}
 function selectShape(shape){
  const targetId=shapePicker?.targetId,id=targetId||uid();
  const applied=change(next=>{
   if(targetId){
    const index=next.layers.findIndex(item=>item.id===targetId);if(index<0)throw Error('Seçili öğe artık tuvalde bulunmuyor.');
    const item=next.layers[index];
    if(item.kind==='image'){
     const {src,alt,fit,imageKind,...geometry}=item;
     next.layers[index]={...geometry,kind:'shape',shape:'rect',shapeId:shape.id,fillMode:'image',imageSrc:src,imageAlt:alt,imageFit:fit,strokeWidth:2};
    }else if(item.kind==='shape'){item.shapeId=shape.id;item.shape='rect';item.fillMode=item.fillMode||'solid';}
    else throw Error('Şekil yalnız görsel veya şekil öğesine uygulanabilir.');
   }else{
    if(next.layers.length>=MAX_CANVAS_LAYERS)throw Error('Tuvalde en fazla 24 öğe bulunabilir.');
    next.layers.push({id,kind:'shape',shape:'rect',shapeId:shape.id,fillMode:'solid',x:35,y:30,width:25,height:40,color:'@accent',opacity:1,strokeWidth:2});
   }
  });
  if(applied){setSelected(id);setShapePicker(null);setNotice(targetId?'Şekil güncellendi; konumu ve boyutu korundu.':'Hazır şekil tuvale eklendi.');}
 }
 function selectMedia(item){
  const mode=mediaPicker?.mode||'add',targetId=mediaPicker?.targetId||'',id=targetId||uid();
  if(change(next=>Object.assign(next,applyCanvasMedia(next,{mode,targetId,id,src:item.src,alt:item.alt,imageKind:item.imageKind})))){
   setSelected(id);setMediaPicker(null);setNotice(mode==='shape'?'Görsel şeklin içine yerleştirildi.':mode==='replace'?'Seçili görsel değiştirildi.':'Hazır görsel yeni katman olarak eklendi.');
  }
 }
 function removeSelected(){if(uploading||drag.current)return;if(change(next=>{next.layers=next.layers.filter(item=>item.id!==selected);}))setNotice('Öğe silindi. Geri al ile yeniden getirebilirsin.');}
 function sendLayer(direction){change(next=>Object.assign(next,moveCanvasLayer(next,selected,direction)));}
 function keys(event){
  if(shapePicker||mediaPicker)return;
  event.stopPropagation();
  if(['Delete','Backspace'].includes(event.key)&&!discardOpen&&selected&&shouldDeleteCanvasLayer(event.target)){event.preventDefault();removeSelected();return;}
  if(event.key==='Escape'){event.preventDefault();if(drag.current)cancel();else if(discardOpen)setDiscardOpen(false);else close();return;}
  if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?redo():undo();}
  if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='s'){event.preventDefault();save();}
  if(event.key==='Tab'){
   const all=[...dialog.current.querySelectorAll('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),[tabindex="0"]')].filter(el=>el.getClientRects().length),first=all[0],last=all.at(-1),inside=all.includes(document.activeElement);
   if(event.shiftKey&&(!inside||document.activeElement===first)){event.preventDefault();last?.focus();}
   else if(!event.shiftKey&&(!inside||document.activeElement===last)){event.preventDefault();first?.focus();}
  }
 }
 useEffect(()=>{if(properties.current)properties.current.scrollTop=0;},[selected]);
 useEffect(()=>{if(!shapePicker&&!mediaPicker&&!dialog.current?.contains(document.activeElement))dialog.current?.focus();},[shapePicker,mediaPicker]);

 async function file(event){const f=event.target.files?.[0],targetId=uploadTarget.current,mode=uploadMode.current;event.target.value='';if(!f)return;const request=++uploadSequence.current;setUploading(true);setError('');setNotice('');try{if(!['image/png','image/jpeg','image/webp'].includes(f.type)||f.size>2_000_000)throw Error('PNG, JPG veya WebP seç; dosya en fazla 2 MB olabilir.');const src=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.onerror=()=>reject(Error('Görsel okunamadı.'));r.readAsDataURL(f);});const image=new Image();image.src=src;await image.decode();if(!image.naturalWidth||image.naturalWidth>8192||image.naturalHeight>8192||image.naturalWidth*image.naturalHeight>32_000_000)throw Error('Görsel en fazla 8192 px ve 32 milyon piksel olabilir.');if(!active.current||request!==uploadSequence.current)return;const id=targetId||uid();if(change(next=>Object.assign(next,applyCanvasMedia(next,{mode,targetId,id,src,alt:f.name.slice(0,200),imageKind:'object'})))){setSelected(id);setNotice(mode==='shape'?'Yüklenen görsel şeklin içine yerleştirildi.':targetId?'Seçili görsel değiştirildi; konumu ve boyutu korundu.':'Görsel yeni katman olarak eklendi.');}}catch(e){if(active.current&&request===uploadSequence.current)setError(e.message||'Görsel açılamadı.');}finally{if(active.current&&request===uploadSequence.current)setUploading(false);}}
 return createPortal(<div className="cc-backdrop"><section ref={dialog} className="cc-editor" role="dialog" aria-modal="true" aria-label="Kampanya tuvali" tabIndex={-1} onKeyDown={keys}>
  <header><div><small>NOVA STORE / SERBEST KAMPANYA TASARIMI</small><h2>Kendi kompozisyonunu oluştur.</h2><p>Öğeyi seç; rengini ve içeriğini sağda düzenle. Kenar süsü için tuvalin dışına taşıyabilirsin.</p></div><button aria-label="Kampanya tuvalini kapat" onClick={close}><X size={22}/></button></header>
  <div className="cc-toolbar"><button onClick={()=>add('text',{text:'Yeni kampanya yazısı',color:'@text'})}><Type size={16}/> Yazı ekle</button><button disabled={uploading||doc.layers.length>=MAX_CANVAS_LAYERS} onClick={()=>setShapePicker({})}><Shapes size={16}/> Hazır şekiller ({CAMPAIGN_SHAPES.length})</button><button disabled={uploading||doc.layers.length>=MAX_CANVAS_LAYERS} onClick={()=>setMediaPicker({mode:'add'})}><ImagePlus size={16}/> Hazır görseller (130)</button><button disabled={uploading||doc.layers.length>=MAX_CANVAS_LAYERS} onClick={()=>chooseImage()}><ImagePlus size={16}/> {uploading?'Görsel yükleniyor…':'Görsel yükle'}</button><input hidden ref={upload} type="file" accept="image/png,image/jpeg,image/webp" aria-label="Tuvale görsel yükle" onChange={file}/><span>{doc.layers.length}/24 öğe</span><button aria-label="Tuval değişikliğini geri al" onClick={undo} disabled={!history.past.length}><Undo2 size={16}/></button><button aria-label="Tuval değişikliğini yinele" onClick={redo} disabled={!history.future.length}><Redo2 size={16}/></button></div>
  <div className="cc-body"><aside className="cc-layers"><h3>Katmanlar</h3><p>En alttaki satır görselde en öndedir.</p>{doc.layers.map((l,index)=><div className={l.id===selected?'is-selected':''} key={l.id}><button aria-pressed={l.id===selected} onClick={()=>setSelected(l.id)}><small>{index+1}</small>{name(l)}</button><button aria-label={`${index+1}. tuval öğesini arkaya al`} disabled={!index} onClick={()=>change(d=>{[d.layers[index-1],d.layers[index]]=[d.layers[index],d.layers[index-1]];})}><ArrowUp size={13}/></button><button aria-label={`${index+1}. tuval öğesini öne al`} disabled={index===doc.layers.length-1} onClick={()=>change(d=>{[d.layers[index],d.layers[index+1]]=[d.layers[index+1],d.layers[index]];})}><ArrowDown size={13}/></button></div>)}</aside>
  <main className="cc-workspace"><div className="cc-stage" ref={stage} style={{aspectRatio:doc.aspectRatio}}><div dangerouslySetInnerHTML={{__html:renderCampaignCanvas(doc,{theme,motion:false})}}/>{doc.layers.map(l=><div key={l.id} role="button" tabIndex={0} aria-label={`${name(l)} tuval öğesini seç`} aria-pressed={selected===l.id} className={`cc-hit ${selected===l.id?'is-selected':''}`} data-canvas-hit={l.id} style={{left:`${l.x}%`,top:`${l.y}%`,width:`${l.width}%`,height:`${l.height}%`,transform:`rotate(${l.rotate}deg)`}} onPointerDown={e=>start(e,l)} onPointerMove={move} onPointerUp={finish} onPointerCancel={cancel} onLostPointerCapture={()=>{if(drag.current)cancel();}} onFocus={()=>setSelected(l.id)} onClick={()=>setSelected(l.id)} onDoubleClick={()=>{if(l.kind==='text')properties.current?.querySelector('[data-canvas-text-input]')?.focus();}} onKeyDown={e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();setSelected(l.id);}if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)){e.preventDefault();const step=e.shiftKey?5:1;change(d=>{const item=d.layers.find(v=>v.id===l.id);item.x=clamp(item.x+(e.key==='ArrowLeft'?-step:e.key==='ArrowRight'?step:0),CANVAS_GEOMETRY.minPosition,CANVAS_GEOMETRY.maxPosition);item.y=clamp(item.y+(e.key==='ArrowUp'?-step:e.key==='ArrowDown'?step:0),CANVAS_GEOMETRY.minPosition,CANVAS_GEOMETRY.maxPosition);});}}}>{selected===l.id&&<button className="cc-resize" aria-label="Seçili tuval öğesini boyutlandır" onPointerDown={e=>start(e,l,true)} onPointerMove={move} onPointerUp={finish} onPointerCancel={cancel}/>}</div>)}</div><p className="cc-stage-note">{CANVAS_LAYOUTS.find(l=>l.id===doc.layout)?.label} · Tuvalin dışındaki kısımlar kampanyada kırpılır.</p></main>
  <aside className="cc-properties" aria-label="Seçili öğe ayarları" ref={properties}><label className="cc-field"><span>Seçili tuval öğesi</span><select value={selected} onChange={e=>setSelected(e.target.value)}>{doc.layers.map((l,i)=><option key={l.id} value={l.id}>{i+1}. {name(l)}</option>)}</select></label>  {layer&&<><div className="cc-selected-preview"><div className="cc-selected-art" aria-label="Seçili öğenin görünümü">{layer.kind==='text'?<span className="cc-text-sample" style={{fontFamily:campaignFontFamily(layer.font),fontWeight:layer.fontWeight,fontStyle:layer.fontStyle||'normal',textDecoration:layer.textDecoration||'none'}}>Aa</span>:<div dangerouslySetInnerHTML={{__html:renderCampaignLayer({...layer,x:8,y:8,width:84,height:84,rotate:0,opacity:1},{theme})}}/>}</div><div><small>SEÇİLİ {layer.kind==='shape'?'ŞEKİL':layer.kind==='icon'?'SİMGE':layer.kind==='image'?'GÖRSEL':'YAZI'}</small><h3>{name(layer)}</h3><p>Görünüm ve içerik ayarları</p></div></div>
  {layer.kind==='text'&&<CampaignTextControls key={layer.id} layer={layer} theme={theme} onPatch={patch} onReset={()=>change(next=>{const item=next.layers.find(l=>l.id===selected);Object.assign(item,CAMPAIGN_TEXT_DEFAULTS);CAMPAIGN_TEXT_OPTIONAL.forEach(key=>delete item[key]);})}/>}
  {layer.kind==='icon'&&<><label className="cc-field"><span>Simge renk biçimi</span><select value={layer.iconColorMode||(layer.asset?'original':'single')} onChange={e=>patch('iconColorMode',e.target.value)}><option value="single">Seçtiğim tek renk</option><option value="original">Görselin özgün renkleri</option></select></label><p className="cc-help">Çizgili simgelerde renk çizgilere uygulanır. Dolu bir yıldız için şekil kütüphanesini kullanabilirsin.</p></>}
  {!['image','text'].includes(layer.kind)&&<CampaignColorField label={layer.kind==='icon'?'Simge rengi':layer.kind==='text'?'Yazı rengi':layer.fillMode==='outline'?'Çizgi rengi':'Dolgu rengi'} value={layer.kind==='shape'&&layer.fillMode==='outline'?(layer.strokeColor||layer.color):layer.color} theme={theme} transparent onChange={value=>patch(layer.kind==='shape'&&layer.fillMode==='outline'?'strokeColor':'color',value)}/>}
  {layer.kind==='icon'&&field('Simge çizgi kalınlığı',layer.iconStrokeWidth||1.8,v=>patch('iconStrokeWidth',v),{type:'number',min:.5,max:4,step:.1})}
  {field('Görünürlük (%)',Math.round(layer.opacity*100),v=>patch('opacity',v/100),{type:'range',min:0,max:100,step:1})}<p className="cc-help">{Math.round(layer.opacity*100)}% görünür · 0% seçilirse öğe görünmez.</p>
  {layer.kind==='image'&&<><button disabled={uploading} onClick={()=>chooseImage(layer.id)}><ImagePlus size={15}/> Seçili görseli değiştir</button><button disabled={uploading} onClick={()=>setMediaPicker({mode:'replace',targetId:layer.id})}><ImagePlus size={15}/> Kütüphaneden değiştir</button><button disabled={uploading} onClick={()=>setShapePicker({targetId:layer.id})}><Shapes size={15}/> Şeklin içine yerleştir</button><button onClick={()=>change(d=>{const item=d.layers.find(l=>l.id===selected);Object.assign(item,{x:0,y:0,width:100,height:100,rotate:0,fit:'cover',radius:0});Object.assign(d,moveCanvasLayer(d,selected,'back'));})}>Tuval arka planı yap</button>{field('Görsel alternatif metni',layer.alt,v=>patch('alt',v),{maxLength:200})}<label className="cc-field"><span>Görselin içeriği</span><select value={layer.imageKind} onChange={e=>{const kind=e.target.value;change(d=>{const l=d.layers.find(l=>l.id===selected);l.imageKind=kind;l.fit=kind==='scene'?'cover':'contain';});}}><option value="object">Tek nesne / şeffaf ürün</option><option value="scene">Oda / doğa / tam fotoğraf</option></select></label><label className="cc-field"><span>Görsel sığdırma</span><select value={layer.fit} onChange={e=>patch('fit',e.target.value)}><option value="contain">Tamamı görünsün</option><option value="cover">Kutuyu doldur</option></select></label>{field('Görsel köşesi',layer.radius,v=>patch('radius',v),{type:'number',min:0,max:50})}</>}
  {layer.kind==='shape'&&<fieldset className="cc-shape-settings" disabled={uploading}>
   <button disabled={uploading} onClick={()=>setShapePicker({targetId:layer.id})}><Shapes size={15}/> Şekli değiştir</button>
   <div className="cc-shape-shortcuts"><button disabled={uploading||layer.shape==='line'} onClick={()=>setMediaPicker({mode:'shape',targetId:layer.id})}><ImagePlus size={15}/> İçine hazır görsel koy</button><button disabled={uploading||layer.shape==='line'} onClick={()=>chooseImage(layer.id,'shape')}>İçine kendi görselimi yükle</button><button onClick={()=>change(d=>{const item=d.layers.find(l=>l.id===selected);delete item.shapeId;item.shape='circle';item.width=clamp(item.width,Math.max(1,1/d.aspectRatio),Math.min(CANVAS_GEOMETRY.maxSize,CANVAS_GEOMETRY.maxSize/d.aspectRatio));item.height=item.width*d.aspectRatio;})}>Tam daire yap</button></div>
   {layer.shapeId?<p>{getCampaignShape(layer.shapeId).label}</p>:<label className="cc-field"><span>Temel şekil</span><select value={layer.shape} onChange={e=>patch('shape',e.target.value)}><option value="rect">Dikdörtgen</option><option value="circle">Daire</option><option value="line">Çizgi</option></select></label>}
   {layer.shape!=='line'&&<><label className="cc-field"><span>Şekil dolgusu</span><select value={layer.fillMode||'solid'} onChange={e=>patch('fillMode',e.target.value)}><option value="solid">Renk ile doldur</option><option value="outline">Yalnız çerçeve</option><option value="image">İçine görsel yerleştir</option></select></label>
   {(layer.fillMode==='image')&&<><div className="cc-image-fill-preview">{layer.imageSrc?<img src={assetURL(layer.imageSrc)} alt={layer.imageAlt||'Şeklin içindeki görsel'}/>:<p>Şeklin içine yerleştirmek için bir görsel seç.</p>}</div><button disabled={uploading} onClick={()=>setMediaPicker({mode:'shape',targetId:layer.id})}>Hazır görsellerden seç</button><button disabled={uploading} onClick={()=>chooseImage(layer.id,'shape')}>Şekle görsel yükle</button>{layer.imageSrc&&<><button onClick={()=>change(d=>{const item=d.layers.find(l=>l.id===selected);delete item.imageSrc;delete item.imageAlt;item.fillMode='outline';})}>İçindeki görseli kaldır</button>{field('Şekil görseli açıklaması',layer.imageAlt||'',v=>patch('imageAlt',v),{maxLength:200})}</>}<label className="cc-field"><span>Şekil içinde sığdırma</span><select value={layer.imageFit||'cover'} onChange={e=>patch('imageFit',e.target.value)}><option value="cover">Şekli doldur</option><option value="contain">Görselin tamamını göster</option></select></label></>}
   {layer.fillMode!=='outline'&&<><label className="cc-toggle"><input type="checkbox" checked={!!layer.strokeColor&&layer.strokeColor!=='transparent'} onChange={e=>change(d=>{const item=d.layers.find(l=>l.id===selected);if(e.target.checked)item.strokeColor=item.color;else delete item.strokeColor;})}/> Şekle çerçeve ekle</label>{layer.strokeColor&&layer.strokeColor!=='transparent'&&<CampaignColorField label="Çerçeve rengi" value={layer.strokeColor} theme={theme} onChange={v=>patch('strokeColor',v)}/>}</>}</>}

   {field('Çizgi kalınlığı',layer.strokeWidth,v=>patch('strokeWidth',v),{type:'number',min:1,max:16,step:.5})}
  </fieldset>}
  <details className="cc-position" open><summary>Konum ve ölçü</summary><p className="cc-help">Şekli kenardan dışarı taşıyabilirsin. Dışarıda kalan bölüm kampanyada görünmez; katman silinmez.</p>
  <button className="cc-recenter" onClick={()=>change(d=>{const item=d.layers.find(l=>l.id===selected);Object.assign(item,placeCampaignLayer(item,'center'));})}>Seçili öğeyi ortaya getir</button>
  <div className="cc-align" role="group" aria-label="Kenara hizala">{[['left','Sola hizala'],['right','Sağa hizala'],['top','Üste hizala'],['bottom','Alta hizala']].map(([id,label])=><button key={id} onClick={()=>change(d=>{const item=d.layers.find(l=>l.id===selected);Object.assign(item,placeCampaignLayer(item,id));})}>{label}</button>)}</div>
  <div className="cc-align" role="group" aria-label="Köşe süsü yerleşimi">{[['corner-tl','Sol üst süs'],['corner-tr','Sağ üst süs'],['corner-bl','Sol alt süs'],['corner-br','Sağ alt süs']].map(([id,label])=><button key={id} onClick={()=>change(d=>{const item=d.layers.find(l=>l.id===selected);Object.assign(item,placeCampaignLayer(item,id));})}>{label}</button>)}</div>
  <div className="cc-grid">{[['x','Yatay konum (%)',-200,200],['y','Dikey konum (%)',-200,200],['width','Öğe genişliği (%)',1,200],['height','Öğe yüksekliği (%)',1,200],['rotate','Dönüş (°)',-180,180]].map(([key,label,min,max])=>field(label,layer[key],v=>patch(key,v),{key,type:'number',min,max,step:.5}))}</div></details>
  <div className="cc-row"><button disabled={doc.layers[0]?.id===selected} onClick={()=>sendLayer('back')}><ArrowUp size={14}/> En arkaya</button><button disabled={doc.layers.at(-1)?.id===selected} onClick={()=>sendLayer('front')}><ArrowDown size={14}/> En öne</button></div>
  <div className="cc-row"><button disabled={doc.layers.length>=24} onClick={()=>{const next={...layer,id:uid(),x:clamp(layer.x+2,CANVAS_GEOMETRY.minPosition,CANVAS_GEOMETRY.maxPosition),y:clamp(layer.y+2,CANVAS_GEOMETRY.minPosition,CANVAS_GEOMETRY.maxPosition)};change(d=>d.layers.push(next));setSelected(next.id);}}><Copy size={14}/> Çoğalt</button><button disabled={uploading} onClick={removeSelected}><Trash2 size={14}/> Öğeyi sil</button></div></>}
  <details className="cc-position"><summary>Tuvalin zemin ve boyut ayarları</summary>{field('Tuval en boy oranı',doc.aspectRatio,n=>change(d=>{d.aspectRatio=n;}),{type:'number',min:.5,max:4,step:.05})}<CampaignColorField label="Tuval zemini" value={doc.background} theme={theme} onChange={v=>change(d=>{d.background=v;d.themeMode=v.startsWith('@')?'inherit':'custom';})}/></details>
  <details className="cc-motifs" open><summary>Döneme uygun motifler</summary><label className="cc-field"><span>Motif grubu</span><select value={motif} onChange={e=>setMotif(e.target.value)}>{CANVAS_MOTIF_SETS.map(m=><option key={m.id} value={m.id}>{m.label}</option>)}</select></label><div className="cc-icon-grid">{CANVAS_MOTIF_SETS.find(m=>m.id===motif).icons.map(id=><button key={id} aria-label={`${id} motifini ekle`} onClick={()=>add('icon',id==='nova-ramadan-lantern'?{asset:campaignMotifAsset(id)}:{iconId:id})}><img src={visualAssets.assetDataURL(campaignMotifAsset(id))} alt=""/><span>{id==='nova-ramadan-lantern'?'Ramazan feneri':icons.find(i=>i.id===id)?.label||id}</span></button>)}</div></details>
  <details className="cc-motifs"><summary>Bütün simgeler ({icons.length})</summary>{field('Tuval simgesi ara',query,setQuery)}<div className="cc-icon-grid cc-all-icons">{matches.map(i=><button key={i.id} aria-label={`${i.label} tuval simgesini ekle`} onClick={()=>add('icon',{iconId:i.id})}><img src={i.url} alt=""/><span>{i.label}</span></button>)}</div></details>
  </aside></div><footer>{error&&<p role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}{uploading&&<p role="status">Görsel kontrol ediliyor; yükleme bitmeden tuval uygulanmaz.</p>}{discardOpen?<><span role="alert">{uploading?'Görsel yüklemesi sürüyor. Kapatırsan uygulanmayacak.':'Tuvalde uygulanmamış düzenlemelerin var.'}</span><button onClick={()=>setDiscardOpen(false)}>Düzenlemeye dön</button><button onClick={onClose}>Uygulamadan kapat</button></>:<><span>Tuval düzenlemeleri yalnız “Tuvali uygula” ile paketine aktarılır.</span><button onClick={close}>Vazgeç</button><button className="cc-save" disabled={uploading||!!temporary} onClick={save}><Save size={16}/> Tuvali uygula</button></>}</footer>
 </section>{shapePicker&&<CampaignShapePicker onSelect={selectShape} onClose={()=>setShapePicker(null)}/ >}{mediaPicker&&<CampaignMediaPicker onSelect={selectMedia} onClose={()=>setMediaPicker(null)}/ >}</div>,document.body);
}
