import React,{useId,useState} from 'react';
import {CalendarDays} from 'lucide-react';
import {Field,Select} from './Controls.jsx';
import {CAMPAIGN_SEASONS,CAMPAIGN_SECTORS,normalizeCampaign,suggestCampaignDates} from '../campaignModel.js';
import {SEASON_LABELS,SECTOR_LABELS} from '../campaignLibrary.js';
import {isStudioHost} from '../../studio-integration/context.js';
export default function CampaignSettings({value,onChange,pack,pages=[],blocks=[],channel,compact=false}) {
  const timeZonesId=useId(),[suggestionError,setSuggestionError]=useState('');const set=(key,next)=>{setSuggestionError('');onChange({...value,[key]:next});};let error='';try{normalizeCampaign(value);}catch(e){error=e.message;}
  const suggestion=()=>{setSuggestionError('');try{const dates=suggestCampaignDates(pack?.rule,Number(value.year));if(dates)onChange({...value,...dates,scheduleMode:'suggested'});else setSuggestionError('Bu kampanya için tarihleri elle seç.');}catch(error){setSuggestionError(error.message||'Tarih önerisi oluşturulamadı.');}};
  return <div className={`cl-settings ${compact?'is-compact':''}`}>
    <div className="cl-settings-heading"><CalendarDays size={16}/><strong>Kampanya planı</strong><small>İçerik ve görünürlük</small></div>
    <div className="cl-form-grid"><Select label="Paket sektörü" value={value.sector} options={CAMPAIGN_SECTORS.map(id=>({value:id,label:SECTOR_LABELS[id]}))} onChange={v=>set('sector',v)}/><Select label="Paket dönemi" value={value.season} options={CAMPAIGN_SEASONS.map(id=>({value:id,label:SEASON_LABELS[id]}))} onChange={v=>set('season',v)}/></div>
    <fieldset className="cl-channels"><legend>Paketin kullanılabileceği kanallar</legend>{[['web','Web'],['android','Android']].map(([id,label])=><label key={id}><input type="checkbox" checked={value.channels.includes(id)} onChange={e=>set('channels',e.target.checked?[...value.channels,id]:value.channels.filter(c=>c!==id))}/>{label}</label>)}</fieldset>
    <p className="sl-field-note">Şu an {channel==='android'?'Android':'Web'} taslağındasın. Paket diğer kanala kendiliğinden eklenmez.</p>
    <div className="cl-form-grid"><Field label="Plan yılı" type="number" min={2000} max={2100} value={value.year} onChange={v=>set('year',v===''?'':Number(v))}/><Field label="Saat dilimi" list={timeZonesId} value={value.timeZone} maxLength={80} onChange={v=>set('timeZone',v)} hint="IANA adı; tarayıcının saatiyle karışmaz."/></div><datalist id={timeZonesId}><option>Europe/Istanbul</option><option>Europe/Berlin</option><option>Europe/London</option><option>America/New_York</option><option>Asia/Dubai</option><option>UTC</option></datalist>
    <fieldset disabled={isStudioHost()} style={{border:0,padding:0,margin:0}}><Select label="Tarih planı" value={value.scheduleMode} options={[{value:'none',label:'Paket genelinde ek tarih sınırı yok'},{value:'manual',label:'Tarihleri kendim seçeceğim'},{value:'suggested',label:'Takvim önerisini düzenle'}]} onChange={v=>set('scheduleMode',v)}/><p className="sl-field-note">Paket aralığı seçildiğinde eklenen bütün bölümlere uygulanır. Ek sınır koymazsan bölümlerin kendi tarihleri korunur.</p>
    {pack&&<div className="cl-date-guide"><p>{pack.rule?.label}</p><button type="button" className="sp-button sp-button-outline" disabled={pack.rule?.kind==='manual'||!Number.isInteger(value.year)} onClick={suggestion}>Seçilen yıl için tarih öner</button></div>}
    {value.scheduleMode!=='none'&&<><div className="cl-form-grid"><Field label="Paket başlangıcı" type="datetime-local" value={value.startsLocal} onChange={v=>set('startsLocal',v)}/><Field label="Paket bitişi" type="datetime-local" value={value.endsLocal} onChange={v=>set('endsLocal',v)}/></div><p className="sl-field-note">Başlangıç anı dahil; bitiş anında görünüm kapanır. Boş alan sınır koymaz. Dini bayram, okul ve mağaza tarihlerini seçilen yıl için doğrula.</p></>}
    </fieldset>{isStudioHost()&&<p className="sl-field-note">Zamanlama bu bağlantıda kapalıdır. Paket tarihsiz taslak olarak hazırlanır.</p>}{!!pages.length&&<><Select label="Paket hedef sayfası" value={value.targetPage} options={[...(!pages.some(p=>p.id===value.targetPage)?[{value:value.targetPage,label:'Kayıtlı hedef bulunamadı — yeni sayfa seç',disabled:true}]:[]),...pages.map(p=>({value:p.id,label:p.label}))]} onChange={v=>onChange({...value,targetPage:v,afterBlockId:''})}/><Select label="Sayfadaki konumu" value={value.placement} options={[{value:'append',label:'Sayfanın sonuna'},{value:'prepend',label:'Sayfanın başına'},{value:'after',label:'Seçtiğim bölümün arkasına'}]} onChange={v=>set('placement',v)}/>{value.placement==='after'&&<Select label="Bu bölümün arkasına ekle" value={value.afterBlockId} options={[{value:'',label:'Bölüm seç'},...blocks.map((b,i)=>({value:b.id,label:`${i+1}. ${b.title||b.type}`}))]} onChange={v=>set('afterBlockId',v)}/>}</>}
    <Field label="İç plan notu" value={value.note} onChange={v=>set('note',v)} multiline maxLength={1200} hint="Müşteriye gösterilmez; stok, içerik ve onay notlarını kaydet."/>
    <p className="cl-commercial-note">Bu paket fiyat, kupon, stok veya kargo kuralı oluşturmaz. İndirim duyurusunu yalnız gerçek ticaret kuralın onaylandıktan sonra yaz.</p>
    {(error||suggestionError)&&<p role="alert" className="sl-field-error">{error||suggestionError}</p>}
  </div>;
}
