import React,{useEffect,useRef,useState} from 'react';
import {Hand,Layers3,SquarePlus,Maximize2,Minimize2,Monitor,MousePointer2,PanelRight,RotateCw,Smartphone,Tablet,ZoomIn,ZoomOut} from 'lucide-react';
import {validOrder} from './previewOrder.js';
import {isVisualElement} from '../visualDesign.js';
import {CanvasDimension,ResizeHandles,useCanvasViewport} from './CanvasViewport.jsx';
import './canvas-workspace.css';
import {useSandboxState} from '../useSandbox.js';
import {previewPageBlocks} from '../../studio-integration/preview-navigation.js';

export const DEVICES={desktop:{label:'Masaüstü',width:1440,icon:Monitor},tablet:{label:'Tablet',width:768,icon:Tablet},mobile:{label:'Mobil',width:390,icon:Smartphone}};
import {withMerchantScope} from '../merchantWorkspaces.js';
import {isStudioHost,getStudioHost,getStudioSession} from '../../studio-integration/context.js';
export function previewURL(channel,pageKey,hash,{draft=true,studio=false,embed=false}={}){if(isStudioHost()){const state=getStudioSession()?.getState();if(draft)return state?.host.workingPreview?.[channel]?.url||'';const preview=state?.host.preview[channel];return preview?.pageKey===pageKey&&!preview?.previewAt?preview.url:'';}const url=new URL(location.pathname,location.origin);url.searchParams.set('surface',channel==='android'?'android':'storefront');if(draft)url.searchParams.set('preview','draft');if(embed)url.searchParams.set('embed','1');if(studio)url.searchParams.set('studio','1');const workshop=new URLSearchParams(location.search).get('themeWorkshop');if(workshop)url.searchParams.set('themeWorkshop',workshop);url.searchParams.set('studioPage',pageKey);url.hash=hash||'#/';return withMerchantScope(url.href);}

export default function Canvas({orderPreview,channel,pageKey,pageLabel,hash,device,setDevice,previewLive,setPreviewLive,selectBlock,selectElement,blockIds,expanded,setExpanded,overlay,setOverlay,onEscape,onInsertIcon,onMoveIcon,onNavigatePage}){
  const container=useRef(null),frame=useRef(null),[bounds,setBounds]=useState({width:600,height:640}),[reload,setReload]=useState(0),[interactive,setInteractive]=useState(false),[loaded,setLoaded]=useState(false),[inserting,setInserting]=useState(false),normalDevice=useRef({channel,device}),previousExpanded=useRef(expanded);
  const [orderSupported,setOrderSupported]=useState(false);
  const state=useSandboxState(),draft=state.channels[channel].draft;
  const [previewError,setPreviewError]=useState('');
  useEffect(()=>{
    if(!isStudioHost()||previewLive)return;
    let current=true;
    getStudioSession().workingPreview(channel,{pageKey}).then(()=>{if(current)setPreviewError('');}).catch(error=>{if(current&&error.code!=='STALE')setPreviewError('Çalışma önizlemesi doğrulanamadı. Yetki ve taslak içeriğini kontrol et.');});
    return()=>{current=false;};
  },[draft,channel,pageKey,previewLive,state.host?.policyRevision]);
  const orderRef=useRef(null);
  orderRef.current={type:'novastore-studio-preview-order',channel,pageKey,order:!previewLive&&orderPreview&&validOrder(blockIds.map(id=>({id})),orderPreview.order)?orderPreview.order:null};
  useEffect(()=>{if(orderSupported)frame.current?.contentWindow?.postMessage(orderRef.current,location.origin);},[orderPreview,orderSupported,channel,pageKey,previewLive,loaded]);
  const viewport=useCanvasViewport({expanded,channel,device,presetWidth:DEVICES[device].width}),{size:{width,height},view:{zoom,pan}}=viewport;
  useEffect(()=>{if(expanded&&!previousExpanded.current)normalDevice.current={channel,device};else if(!expanded&&previousExpanded.current&&normalDevice.current.channel===channel)setDevice(normalDevice.current.device);previousExpanded.current=expanded;},[expanded,channel]);
  useEffect(()=>{const element=container.current;if(!element)return;const observer=new ResizeObserver(()=>setBounds({width:element.clientWidth,height:element.clientHeight}));observer.observe(element);setBounds({width:element.clientWidth,height:element.clientHeight});return()=>observer.disconnect();},[]);
  useEffect(()=>{function receive(event){if(event.origin!==location.origin||event.source!==frame.current?.contentWindow)return;const data=event.data;if(data?.type==='novastore-studio-route'&&data.channel===channel&&typeof data.pageKey==='string'&&previewPageBlocks(draft,data.pageKey)){onNavigatePage?.(data.pageKey);return;}if(data?.type==='novastore-studio-ready'){setOrderSupported(data.capabilities?.transientOrder===true);if(data.capabilities?.transientOrder===true)frame.current?.contentWindow?.postMessage(orderRef.current,location.origin);frame.current?.contentWindow?.postMessage({type:'novastore-studio-set-editing',enabled:!interactive&&!previewLive,insert:inserting},location.origin);return;}if(data?.type==='novastore-studio-escape'){onEscape?.();return;}if(['novastore-studio-place-icon','novastore-studio-move-icon'].includes(data?.type)&&isVisualElement(data.elementId)&&Number.isFinite(data.x)&&Number.isFinite(data.y)&&data.x>=0&&data.x<=100&&data.y>=0&&data.y<=100){if(data.type==='novastore-studio-place-icon'){setInserting(false);onInsertIcon?.(data);}else if(typeof data.decorationId==='string'&&/^[a-zA-Z0-9_-]{1,80}$/.test(data.decorationId))onMoveIcon?.(data);return;}if(data?.type==='novastore-studio-select-element'&&isVisualElement(data.elementId)){const blockId=data.elementId.startsWith('block:')?data.elementId.split(':')[1]:null;if(blockId&&!blockIds.includes(blockId))return;selectElement(data.elementId,blockId);}else if(data?.type==='novastore-studio-select'&&typeof data.blockId==='string'&&blockIds.includes(data.blockId))selectBlock(data.blockId);}window.addEventListener('message',receive);return()=>window.removeEventListener('message',receive);},[selectBlock,selectElement,blockIds,onEscape,interactive,previewLive,inserting,onInsertIcon,onMoveIcon,onNavigatePage,channel,draft]);
  const fit=Math.min(1,(bounds.width-56)/width),scale=zoom==='fit'?Math.max(.1,fit):Number(zoom);
  const url=previewURL(channel,pageKey,hash,{draft:!previewLive,studio:true,embed:true});
  const sendEditing=()=>frame.current?.contentWindow?.postMessage({type:'novastore-studio-set-editing',enabled:!interactive&&!previewLive,insert:inserting},location.origin);
  useEffect(()=>{sendEditing();},[interactive,previewLive,inserting,url,loaded]);
  useEffect(()=>{setLoaded(false);setOrderSupported(false);},[url,reload]);
  return <section className={`sp-canvas ${expanded?'is-expanded':''}`}>
    <header className="sp-canvas-toolbar">{expanded&&<button className="sp-overlay-toggle is-left" aria-expanded={overlay==='layers'} onClick={()=>setOverlay(overlay==='layers'?null:'layers')}><Layers3 size={17}/>Katmanlar</button>}<div className="sp-segment"><button className={!previewLive?'selected':''} onClick={()=>setPreviewLive(false)}>{isStudioHost()?'Çalışma taslağı':'Taslak'}</button><button className={previewLive?'selected':''} onClick={()=>setPreviewLive(true)}>{isStudioHost()?'Sunucu önizlemesi':new URLSearchParams(location.search).has('themeWorkshop')?'Son kayıt':'Yayımlanan'}</button></div><div className="sp-canvas-center-tools"><div className="sp-device-buttons">{Object.entries(DEVICES).map(([id,{label,icon:Icon}])=><button key={id} className={device===id?'selected':''} aria-label={`${label} önizleme`} onClick={()=>setDevice(id)} disabled={channel==='android'&&id!=='mobile'} title={`${label} · ${DEVICES[id].width}px`}><Icon size={16}/></button>)}</div><button className={`sp-icon-button ${interactive?'selected':''}`} aria-label={interactive?'Bölüm seçme moduna geç':'Önizlemeyi kullan'} title={interactive?'Gezinme açık':'Bölüm seçimi açık'} onClick={()=>{viewport.setPanning(false);setInserting(false);setInteractive(v=>!v);}}><MousePointer2 size={16}/></button><button className={`sp-icon-button ${inserting?'selected':''}`} aria-label="Simge ekle" aria-pressed={inserting} disabled={isStudioHost()&&getStudioHost().capabilities.edit!==true} title={inserting?'Simge için sayfada bir yere tıkla':'Seçtiğin yere simge ekle'} onClick={()=>{viewport.setPanning(false);setInteractive(false);setInserting(!inserting);}}><SquarePlus size={17}/></button><button className={`sp-icon-button ${viewport.panning?'selected':''}`} aria-label="Tuvali sürükle" aria-pressed={viewport.panning} title="Tuvali sürükle" onClick={()=>viewport.setPanning(!viewport.panning)}><Hand size={16}/></button><button className="sp-icon-button" aria-label={expanded?'Tam ekrandan çık':'Tam ekran çalışma alanı'} aria-pressed={expanded} onClick={()=>{setOverlay?.(null);setExpanded(!expanded);}}>{expanded?<Minimize2 size={17}/>:<Maximize2 size={17}/>}</button></div>{expanded&&<button className="sp-overlay-toggle is-right" aria-expanded={overlay==='inspector'} onClick={()=>setOverlay(overlay==='inspector'?null:'inspector')}>Seçili öğe<PanelRight size={17}/></button>}</header>
    <div className="sp-canvas-address"><span><i/><i/><i/></span><small>{channel==='android'?'NovaStore uygulaması':'novastore'} / {pageLabel}</small><button className="sp-icon-button" aria-label="Önizlemeyi yenile" onClick={()=>setReload(v=>v+1)}><RotateCw size={12}/></button></div>
    <div className={`sp-canvas-stage ${device} ${viewport.panning?'is-panning':''}`} ref={container}>
      <div className={`sp-device-frame ${device}`} hidden={isStudioHost()&&!url} style={{width:width*scale,height:height*scale,transform:`translate(${pan.x}px,${pan.y}px)`}}><iframe key={isStudioHost()?`${channel}-${url}-${reload}`:`${channel}-${pageKey}-${reload}`} ref={frame} title={`${pageLabel} ${previewLive?'sunucu':'taslak'} önizlemesi`} src={url||undefined} onLoad={async event=>{const target=event.currentTarget;try{if(isStudioHost()&&url)await getStudioHost().ports.mountPreviewFrame?.(target,url);if(frame.current===target)setLoaded(true);}catch{if(frame.current===target)setPreviewError('Önizleme bağlamı yüklenemedi.');}}} style={{width,height,transform:`scale(${scale})`,transformOrigin:'top left'}}/>{url&&<ResizeHandles viewport={viewport} scale={scale}/>}</div>
      {viewport.panning&&<div className="sp-pan-surface" aria-label="Tuvali sürükleme alanı" onPointerDown={event=>viewport.start(event,'pan',scale)} onPointerMove={viewport.move} onPointerUp={viewport.end} onPointerCancel={viewport.end} onLostPointerCapture={viewport.end}/>}
      {isStudioHost()&&!url?<div className="nsi-preview-gate"><h3>{previewLive?'Sunucu önizlemesi':'Çalışma taslağı'}</h3><p>{previewLive?'Kaydettiğin taslak sürümü sunucuda doğrulanarak hazırlanır.':'Taslak yalnız bu mağazanın doğrulanmış ürünleriyle çalışma alanında görüntülenir.'}</p><button className="sp-button sp-button-dark" disabled={getStudioHost().capabilities.preview!==true||typeof getStudioHost().ports.createPreview!=='function'||Boolean(getStudioSession().getState().host.pending[channel])||(previewLive&&state.host.dirty[channel])} onClick={async()=>{try{setPreviewError('');if(previewLive)await getStudioSession().preview(channel,{pageKey,published:false});else await getStudioSession().workingPreview(channel,{pageKey});}catch{setPreviewError('Önizleme hazırlanamadı. Admin bağlantısını kontrol et.');}}}>{previewLive&&state.host.dirty[channel]?'Önce taslağı kaydet':'Bu sayfanın önizlemesini hazırla'}</button>{previewError&&<p role="alert">{previewError}</p>}</div>:!loaded&&<span className="sp-canvas-loading">Önizleme hazırlanıyor…</span>}
    </div>
    {previewError&&url&&<p role="alert" className="theme-preview-notice">{previewError}</p>}{orderPreview&&!previewLive&&<div className="sp-order-preview-status" role="status">{orderSupported?"Sıra önizlemesi · Bırakınca kaydedilir · Escape ile iptal":"Bu önizleme geçici sıralamayı desteklemiyor. Bırakınca taslak sırası kaydedilir."}</div>}<footer className="sp-canvas-footer"><div className="sp-viewport-dimensions">{[['width','Genişlik',width],['height','Yükseklik',height]].map(([kind,label,value])=><CanvasDimension key={kind} kind={kind} label={label} value={value} onChange={next=>viewport.resize({[kind]:next})}/>)}</div><div className="sp-viewport-zoom"><button type="button" aria-label="Önizlemeyi uzaklaştır" onClick={()=>viewport.setZoom(Math.max(.25,Number((scale-.1).toFixed(2))))}><ZoomOut size={15}/></button><select aria-label="Önizleme yakınlaştırma" value={zoom} onChange={e=>viewport.setZoom(e.target.value==='fit'?'fit':Number(e.target.value))}><option value="fit">Sığdır · %{Math.round(fit*100)}</option>{[.25,.5,.75,1,1.25,1.5,2].map(value=><option key={value} value={value}>%{value*100}</option>)}{zoom!=='fit'&&![.25,.5,.75,1,1.25,1.5,2].includes(Number(zoom))&&<option value={zoom}>%{Math.round(Number(zoom)*100)}</option>}</select><button type="button" aria-label="Önizlemeyi yakınlaştır" onClick={()=>viewport.setZoom(Math.min(2,Number((scale+.1).toFixed(2))))}><ZoomIn size={15}/></button><button type="button" aria-label="Tuvali ortala ve sığdır" title="Ortala ve sığdır" onClick={viewport.reset}><Maximize2 size={14}/></button></div></footer>
  </section>
}
