import React,{useEffect,useRef,useState} from 'react';
export const PREVIEW_LIMITS={width:[320,2560],height:[240,2160]};
export const clampPreview=(value,kind)=>Math.round(Math.min(PREVIEW_LIMITS[kind][1],Math.max(PREVIEW_LIMITS[kind][0],value)));
export function CanvasDimension({kind,label,value,onChange}){const[draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value]);return <label><span>{label}</span><input type="number" aria-label={`Önizleme ${label.toLocaleLowerCase('tr')}`} min={PREVIEW_LIMITS[kind][0]} max={PREVIEW_LIMITS[kind][1]} value={draft} onChange={event=>{setDraft(event.target.value);const next=Number(event.target.value);if(event.target.value&&Number.isFinite(next)&&next>=PREVIEW_LIMITS[kind][0]&&next<=PREVIEW_LIMITS[kind][1])onChange(clampPreview(next,kind));}} onBlur={()=>setDraft(String(value))} onKeyDown={event=>{if(event.key==='Enter')event.currentTarget.blur();}}/><small>px</small></label>;}
export function useCanvasViewport({expanded,channel,device,presetWidth}){
  const [views,setViews]=useState({normal:{zoom:'fit',pan:{x:0,y:0},sizes:{}},full:{zoom:'fit',pan:{x:0,y:0},sizes:{}}}),[panning,setPanning]=useState(false),gesture=useRef(null);
  const mode=expanded?'full':'normal',view=views[mode],key=`${channel}-${device}`,size=view.sizes[key]||{width:presetWidth,height:device==='desktop'?900:device==='tablet'?1024:844};
  const update=patch=>setViews(all=>({...all,[mode]:{...all[mode],...patch}}));
  const resize=patch=>setViews(all=>({...all,[mode]:{...all[mode],sizes:{...all[mode].sizes,[key]:{...size,...patch}}}}));
  function start(event,kind,scale){if(event.button!==0)return;event.preventDefault();event.stopPropagation();event.currentTarget.setPointerCapture(event.pointerId);gesture.current={kind,x:event.clientX,y:event.clientY,width:size.width,height:size.height,pan:view.pan,scale};if(kind!=='pan')update({zoom:scale});}
  function move(event){const start=gesture.current;if(!start)return;const dx=event.clientX-start.x,dy=event.clientY-start.y;if(start.kind==='pan')update({pan:{x:Math.max(-4000,Math.min(4000,start.pan.x+dx)),y:Math.max(-4000,Math.min(4000,start.pan.y+dy))}});else resize({...(start.kind!=='height'?{width:clampPreview(start.width+dx/start.scale,'width')}:{ }),...(start.kind!=='width'?{height:clampPreview(start.height+dy/start.scale,'height')}:{ })});}
  function end(event){gesture.current=null;if(event.currentTarget.hasPointerCapture?.(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);}
  return {view,size,panning,setPanning,setZoom:zoom=>update({zoom}),reset:()=>update({zoom:'fit',pan:{x:0,y:0}}),resize,start,move,end};
}
export function ResizeHandles({viewport,scale}){
  return ['width','height','both'].map(kind=><button key={kind} type="button" className={`sp-resize-handle is-${kind}`} aria-label={kind==='width'?'Önizleme genişliğini boyutlandır':kind==='height'?'Önizleme yüksekliğini boyutlandır':'Önizleme genişlik ve yüksekliğini boyutlandır'} title="Sürükle · Ok tuşları: 10 px · Shift: 1 px" onPointerDown={event=>viewport.start(event,kind,scale)} onPointerMove={viewport.move} onPointerUp={viewport.end} onPointerCancel={viewport.end} onLostPointerCapture={viewport.end} onKeyDown={event=>{if(!['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(event.key))return;event.preventDefault();const delta=(event.shiftKey?1:10)*(['ArrowLeft','ArrowUp'].includes(event.key)?-1:1),axis=kind==='both'?(['ArrowLeft','ArrowRight'].includes(event.key)?'width':'height'):kind;viewport.resize({[axis]:clampPreview(viewport.size[axis]+delta,axis)});}}><i/></button>);
}
