import React,{useState,useSyncExternalStore} from 'react';
import {Pencil,Eye,Check,Layers3} from 'lucide-react';
import {getWorkshopLibrary,subscribeWorkshop,workshopURL} from '../themeWorkshopStore.js';
import {withMerchantScope} from '../merchantWorkspaces.js';

export default function EditedThemes({channel,update,notify,onBrowse}){
 const {items}=useSyncExternalStore(subscribeWorkshop,getWorkshopLibrary,getWorkshopLibrary),[query,setQuery]=useState('');
 return <div className="sp-settings-content tw-library"><div className="sp-info-note">Hazır tasarımların çalışma kopyaları ve kaydettiğin yeni temalar burada. Düzenlemek mevcut sitenin taslağını değiştirmez.</div><p><a href="/theme-library/#edited-collection" target="_blank" rel="noreferrer">Yeni sektör koleksiyonundaki düzenlenmiş temaları aç</a></p><label className="sp-search"><input aria-label="Düzenlenmiş temalarda ara" placeholder="Tema adı ara…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="tw-grid">{items.filter(i=>i.name.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))).map(item=><article className="tw-card" key={item.id}><div className="tw-card-art" style={{background:item.channels[channel].draft.theme.background}}><Layers3 size={34}/><strong>Nova Store</strong><span>{item.channels[channel].draft.blocks.length} bölüm · Web + Android</span></div><div className="tw-card-body"><small>{item.kind==='theme'?'KAYITLI TEMA':'ÇALIŞMA KOPYASI'}</small><h2>{item.name}</h2><p>{new Date(item.updatedAt).toLocaleString('tr-TR')}</p><div className="tw-actions"><a className="sp-button sp-button-dark" href={workshopURL(item.id)}><Pencil size={15}/>Tasarımı düzenle</a><a className="sp-button sp-button-outline" target="_blank" rel="noreferrer" href={withMerchantScope(`/?surface=${channel==='android'?'android':'storefront'}&preview=draft&themeWorkshop=${encodeURIComponent(item.id)}#/`)}><Eye size={15}/>Önizle</a>{item.kind==='theme'&&<button className="sp-button sp-button-outline" onClick={()=>{if(update(next=>Object.assign(next,structuredClone(item.channels[channel].published))))notify(`${item.name} ${channel==='web'?'web':'Android'} taslağına alındı. Henüz yayımlanmadı.`);}}><Check size={15}/>Kayıtlı temayı taslağa uygula</button>}</div></div></article>)}</div>{!items.length&&<div className="sd-empty"><h2>İlk tasarımını kişiselleştir.</h2><p>Hazır tasarımlardan birini seçip “Tasarımı düzenle” ile başlayabilirsin.</p><button className="sp-button sp-button-dark" onClick={onBrowse}>Hazır tasarımları aç</button></div>}{items.length>0&&!items.some(i=>i.name.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr')))&&<p>Bu adla bir tema bulunamadı.</p>}</div>;
}
