import React,{useEffect,useState} from 'react';
import {ArrowLeft,MousePointer2,RotateCcw,SlidersHorizontal} from 'lucide-react';
import {Color,Field,ImageField,Select,Toggle} from './Controls.jsx';
import {getVisualContent,normalizeVisualDesign,parseVisualElement,setVisualContent,setVisualStyle,setVisualEnhancement,STYLE_NUMBERS,visualContentKeys,visualLabel} from '../visualDesign.js';
import VisualAssetControls from './VisualAssetControls.jsx';
import {readVisualDefaults} from '../visual/visualTargets.js';
import {getDocumentCatalog} from '../store.js';
import {classicVisualContentKeys,classicVisualReplacementAllowed} from '../../studio-integration/classic-editor-policy.js';

const LABELS={width:'Genişlik (yüzde)',widthPx:'Genişlik (piksel)',maxWidth:'En fazla genişlik',minHeight:'En az yükseklik',height:'Yükseklik',borderRadius:'Köşe yuvarlaklığı',borderWidth:'Kenarlık kalınlığı',paddingX:'Yatay iç boşluk',paddingY:'Dikey iç boşluk',marginTop:'Üst dış boşluk',marginBottom:'Alt dış boşluk',gap:'Öğeler arası boşluk',fontSize:'Yazı boyutu',fontWeight:'Yazı kalınlığı',lineHeight:'Satır yüksekliği',letterSpacing:'Harf aralığı',iconSize:'Simge boyutu'};
const DEVICES={desktop:'Masaüstü',tablet:'Tablet',mobile:'Mobil'};
function NumericStyle({name,value,onChange}){const [draft,setDraft]=useState(value??''),[error,setError]=useState('');useEffect(()=>{setDraft(value??'');setError('');},[value]);const [min,max,unit]=STYLE_NUMBERS[name];function commit(){if(draft===''){onChange(undefined);setError('');return;}const number=Number(draft);if(!Number.isFinite(number)||number<min||number>max){setError(`${min}–${max} aralığında bir değer yaz.`);return;}setError('');onChange(number);}return <label className="ve-number"><span>{LABELS[name]}</span><div><input aria-label={LABELS[name]} type="number" min={min} max={max} step={name==='lineHeight'?.1:name==='letterSpacing'?.5:1} value={draft} placeholder="Devral" onChange={e=>{const raw=e.target.value;setDraft(raw);setError('');if(raw==='')onChange(undefined);else {const numeric=Number(raw);if(Number.isFinite(numeric)&&numeric>=min&&numeric<=max)onChange(numeric);}}} onBlur={commit} onKeyDown={e=>{if(e.key==='Enter'){commit();e.currentTarget.blur();}}}/><small>{unit}</small>{value!==undefined&&<button type="button" aria-label={`${LABELS[name]} ayarını kaldır`} onClick={()=>{setDraft('');onChange(undefined);}}><RotateCcw size={12}/></button>}</div>{error&&<small role="status">{error}</small>}</label>}
export default function ElementInspector({id,doc,channel,device,setDevice,update,block,updateBlock,onBack,notify,onSettings,selectElement,restrictedClassic=false}){
  const design=normalizeVisualDesign(doc.design),element=design.elements.find(item=>item.id===id),styles=element?.[device]||{},isBlock=id.startsWith('block:'),part=isBlock?id.split(':')[2]:'';
  const parsed=parseVisualElement(id),content=getVisualContent(design,id),contentKeys=visualContentKeys(id).filter(key=>!restrictedClassic||classicVisualContentKeys(id).includes(key)),[previewDefaults,setDefaults]=useState({});
  const defaults=id==='logoImage'?{...previewDefaults,imageUrl:'',alt:doc.chrome.header.logoText}:previewDefaults;
  const category=parsed?.kind==='category'?getDocumentCatalog(doc,channel).categories.find(item=>String(item.id)===parsed.key):null;
  useEffect(()=>{const read=()=>{const root=window.document.querySelector('.sp-canvas');setDefaults(root?readVisualDefaults(root,id,channel):{});};read();const frame=requestAnimationFrame(read);return()=>cancelAnimationFrame(frame);},[id,channel,doc]);
  const resetContent=()=>{const root=window.document.querySelector('.sp-canvas');setDefaults(id==='logoImage'?{}:root?readVisualDefaults(root,id,channel):{});update(next=>{next.design=normalizeVisualDesign(next.design);const row=next.design.elements.find(item=>item.id===id);if(row)delete row.content;});};
  const setContent=(key,value,target=id)=>update(next=>{next.design=setVisualContent(next.design,target,key,value);},{transactionId:`visual-content:${target}:${key}`,coalesce:true});
  const set=(key,value)=>update(next=>{next.design=setVisualStyle(next.design,id,device,key,value);},{transactionId:`visual:${id}:${device}:${key}`,coalesce:true});
  const field=(name)=><NumericStyle key={name} name={name} value={styles[name]} onChange={v=>set(name,v)}/>;
  const choose=(key,label,options)=><Select label={label} value={styles[key]||''} onChange={v=>set(key,v||undefined)} options={[{value:'',label:'Temadan / büyük ekrandan devral'},...options]}/>;
  const visibility={header:'header',footer:'footer',nav:'navigation'}[id];
  return <aside className="sp-inspector ve-inspector">
    <header className="sp-inspector-head"><span className="sp-icon-box"><MousePointer2 size={17}/></span><div><small>GÖRSEL DÜZENLEYİCİ</small><h2>{visualLabel(id)}</h2></div></header>
    <div className="ve-device-tabs" role="tablist" aria-label="Öğe ayarının cihazı">{Object.entries(DEVICES).map(([key,label])=><button key={key} role="tab" aria-selected={device===key} disabled={channel==='android'&&key!=='mobile'} onClick={()=>setDevice(key)}>{label}</button>)}</div>
    <div className="sp-inspector-scroll">{restrictedClassic&&<p className="sp-info-note">Gerçek ürün ve kategori metni, fiyat, yorum ve görselleri mağaza verisinden gelir. Burada görünüm, simgeler ve süsler düzenlenir; bölüm metinleri sabit bölüm ayarındadır.</p>}
      <p className="ve-scope">{parsed?.kind==='category'?`${category?.name||defaults.text||'Seçili kategori'} · bu kategorinin bütün sayfalardaki görünümü`:parsed?.kind==='item'?'Yalnız seçtiğin metin, görsel veya kutu':isBlock?'Yalnız seçili bölümün bu parçası':'Bu öğenin bütün sayfalardaki görünümü'}. {device==='desktop'?'Küçük ekranlar bu ayarları devralır.':'Boş alanlar büyük ekranın ayarını devralır.'}</p>
      {parsed?.kind==='category'&&selectElement&&<div className="ve-target-tabs" aria-label="Kategori parçası">{[['text','Yazı'],['image','Görsel'],['box','Kutu']].map(([key,label])=><button type="button" key={key} aria-pressed={parsed.part===key} onClick={()=>selectElement(`category:${parsed.key}:${key}`)}>{label}</button>)}</div>}
      {parsed?.kind==='item'&&parsed.part==='image'&&selectElement&&<button type="button" className="sp-text-button" onClick={()=>selectElement(`item:${parsed.key}:box`)}>Bu görselin kutusunu düzenle</button>}
      {!isBlock&&contentKeys.length>0&&<details open><summary>Seçili öğenin içeriği</summary>{contentKeys.includes('text')&&<Field label={parsed?.kind==='category'?'Kategori adı':'Görünen yazı'} value={content.text??category?.name??category?.label??defaults.text??''} multiline={parsed?.kind!=='category'} maxLength={2000} onChange={value=>setContent('text',value)} hint="İçerik bütün cihazlarda aynıdır; aşağıdaki görünüm ayarları cihaza özeldir."/>}{contentKeys.includes('imageUrl')&&<><ImageField label={id==='logoImage'?'Logo görseli':'Seçili görsel'} value={content.imageUrl||category?.imageUrl||category?.image||defaults.imageUrl||''} onChange={value=>setContent('imageUrl',value||undefined)} notify={notify}/><Field label="Görsel açıklaması" value={content.alt??category?.alt??defaults.alt??''} maxLength={300} onChange={value=>setContent('alt',value)}/></>}{Object.keys(content).length>0&&<button type="button" className="sp-text-button" onClick={resetContent}><RotateCcw size={13}/>Varsayılan içeriğe dön</button>}</details>}
      {visibility&&<Toggle label="Görünür" checked={design[visibility]} onChange={v=>update(next=>{next.design=normalizeVisualDesign(next.design);next.design[visibility]=v;})}/>}
      {['header','logo'].includes(id)&&<details open><summary>Marka ve içerik</summary><Field label="Logo metni" value={doc.chrome.header.logoText} maxLength={60} onChange={v=>update(next=>{next.chrome.header.logoText=v;},{coalesce:true,transactionId:'visual-logo'})}/>{!restrictedClassic&&<Field label="Marka sloganı" value={doc.chrome.header.tagline} maxLength={180} onChange={v=>update(next=>{next.chrome.header.tagline=v;},{coalesce:true,transactionId:'visual-tagline'})}/>}{id==='header'&&<Toggle label="Arama alanını göster" checked={doc.chrome.header.showSearch} onChange={v=>update(next=>{next.chrome.header.showSearch=v;})}/>}</details>}
      {['header','logo'].includes(id)&&<details><summary>Görsel logo kullan</summary><ImageField label="Logo görseli" value={getVisualContent(design,'logoImage').imageUrl||''} onChange={value=>setContent('imageUrl',value||undefined,'logoImage')} notify={notify}/><Field label="Logo görselinin açıklaması" value={getVisualContent(design,'logoImage').alt||doc.chrome.header.logoText} maxLength={300} onChange={value=>setContent('alt',value,'logoImage')}/>{selectElement&&<button type="button" className="sp-text-button" onClick={()=>selectElement('logoImage')}>Logo görselinin ölçülerini düzenle</button>}</details>}
      {id==='search'&&<Toggle label="Arama alanını göster" checked={doc.chrome.header.showSearch} onChange={v=>update(next=>{next.chrome.header.showSearch=v;})}/>}
      {isBlock&&block&&<details open><summary>Bölüm içeriği</summary>{['section','title'].includes(part)&&<Field label="Başlık" value={block.title} multiline maxLength={200} onChange={v=>updateBlock('title',v)}/ >}{['section','copy'].includes(part)&&<Field label="Açıklama" value={block.description} multiline maxLength={10000} onChange={v=>updateBlock('description',v)}/ >}{part==='button'&&(!restrictedClassic||(block.id==='classic-hero'&&(block.title||block.description||block.image)))&&<Field label="Düğme yazısı" value={block.buttonText} maxLength={100} onChange={v=>updateBlock('buttonText',v)}/ >}{part==='image'&&(!restrictedClassic||['classic-hero','classic-story'].includes(block.id))&&<ImageField label="Bölüm görseli" value={channel==='android'?block.mobileImage||block.image:block.image} onChange={v=>updateBlock(channel==='android'?'mobileImage':'image',v)} notify={notify}/>}<button className="sp-text-button" onClick={onBack}>{restrictedClassic?'Desteklenen bölüm ayarları':'Tüm içerik ve ürün ayarları'} <ArrowLeft size={13}/></button></details>}
      <VisualAssetControls allowReplacement={!restrictedClassic||classicVisualReplacementAllowed(id)} id={id} element={element} notify={notify} onChangeBatch={patch=>update(next=>{for(const [key,value]of Object.entries(patch))next.design=setVisualEnhancement(next.design,id,key,value);})} onChange={(key,value)=>update(next=>{next.design=setVisualEnhancement(next.design,id,key,value);})} onPreview={(elementId,placement)=>window.document.querySelector('.sp-canvas iframe')?.contentWindow?.postMessage({type:'novastore-studio-preview-motion',elementId,placement},location.origin)}/>
      <details open><summary>Ölçüler ve köşeler</summary><div className="ve-number-grid">{['width','widthPx','maxWidth','minHeight','height','borderRadius','borderWidth'].map(field)}</div></details>
      <details><summary>Boşluk ve yerleşim</summary><div className="ve-number-grid">{['paddingX','paddingY','marginTop','marginBottom','gap'].map(field)}</div>{choose('textAlign','Hizalama',[{value:'left',label:'Sol'},{value:'center',label:'Orta'},{value:'right',label:'Sağ'}])}{['header','nav','footer','canvas'].includes(id)||part==='section'?<>{choose('layout','Öğelerin akışı',[{value:'row',label:'Yatay'},{value:'column',label:'Dikey'}])}{choose('justify','Öğeleri yerleştir',[{value:'flex-start',label:'Başlangıç'},{value:'center',label:'Orta'},{value:'space-between',label:'İki yana'}])}</>:null}</details>
      <details><summary>Yazı ve simgeler</summary>{choose('fontFamily','Yazı ailesi',[{value:'Inter',label:'Inter'},{value:'Arial',label:'Arial'},{value:'Georgia',label:'Georgia · serif'},{value:'system',label:'Cihazın yazı tipi'}])}<div className="ve-number-grid">{['fontSize','fontWeight','lineHeight','letterSpacing','iconSize'].map(field)}</div></details>
      <details><summary>Renk ve gölge</summary>{[['background','Zemin'],['color','Metin'],['borderColor','Kenarlık']].map(([key,label])=><Color key={key} optional label={label} value={styles[key]||''} onChange={v=>set(key,v||undefined)}/>)}{choose('shadow','Gölge',[{value:'none',label:'Yok'},{value:'soft',label:'Hafif'},{value:'elevated',label:'Belirgin'}])}</details>
      {['productImage','productCard','logoImage'].includes(id)||['image','box'].includes(parsed?.part)?<details open><summary>Görsel sunumu</summary>{choose('imageFit','Görseli yerleştir',[{value:'contain',label:'Ürünün tamamını göster'},{value:'cover',label:'Alanı doldur'}])}{choose('imageRatio','Görsel oranı',[{value:'1 / 1',label:'Kare · 1:1'},{value:'3 / 4',label:'Dikey · 3:4'},{value:'4 / 3',label:'Yatay · 4:3'},{value:'16 / 9',label:'Geniş · 16:9'}])}</details>:null}
      {['footer','nav'].includes(id)&&!(restrictedClassic&&id==='nav')&&<button className="sp-button sp-button-outline sp-full" onClick={()=>onSettings(id==='footer'?'chrome':'menus')}>Bağlantıları ve içeriği düzenle</button>}
    </div>
    <footer className="sp-inspector-footer"><button onClick={onBack}><ArrowLeft size={14}/>Bölümlere dön</button><button onClick={()=>update(next=>{next.design=normalizeVisualDesign(next.design);const row=next.design.elements.find(item=>item.id===id);if(row)row[device]={};})}><RotateCcw size={14}/>{DEVICES[device]} ayarını sıfırla</button></footer>
  </aside>;
}
