import Capability from '../../studio-integration/Capability.jsx';
import {capabilityWritable,capabilityVisible} from '../../studio-integration/context.js';
import {toLocalInput,zonedLocalToISO} from '../campaignModel.js';
import React, {useEffect,useState} from 'react';
import {Copy, Eye, Image, LayoutTemplate, Plus, SlidersHorizontal, Trash2, Type} from 'lucide-react';
import {BLOCKS, Color, Field, ImageField, MoveButtons, Range, Select, Target, Toggle, uid} from './Controls.jsx';
import ProductSource from './ProductSource.jsx';
import CampaignCanvasEditor from './CampaignCanvasEditor.jsx';
import {normalizeCampaignCanvas} from '../campaignCanvas.js';

export default function Inspector({block,document,channel,updateBlock,remove,duplicate,notify,selectElement}){
  const [tab,setTab]=useState('content');
  const [canvasEditing,setCanvasEditing]=useState(null);
  useEffect(()=>setCanvasEditing(null),[block?.id,channel]);
  if(!block)return <aside className="sp-inspector"><div className="sp-inspector-empty"><LayoutTemplate size={32}/><h3>Bir bölüm seç</h3><p>Önizlemedeki bir bölüme ya da katman listesine tıklayarak düzenlemeye başla.</p></div></aside>;
  const openCanvas=()=>{if(!capabilityWritable('theme.campaign_canvas'))return;try{const canvas=normalizeCampaignCanvas(block.campaignCanvas);if(!canvas)return;setCanvasEditing({id:block.id,source:JSON.stringify(canvas),canvas});}catch(error){notify?.(error.message,true);}};
  const saveCanvas=canvas=>{try{if(canvasEditing?.id!==block.id||JSON.stringify(normalizeCampaignCanvas(block.campaignCanvas))!==canvasEditing.source)throw Error('Bu bölüm açıldıktan sonra değişti. Tuvali kapatıp güncel bölümden yeniden aç.');const next=normalizeCampaignCanvas(canvas);if(JSON.stringify(next)!==canvasEditing.source&&updateBlock('campaignCanvas',next)===false)return;setCanvasEditing(null);notify?.('Kampanya tuvali sayfadaki bölüme uygulandı.');}catch(error){notify?.(error.message,true);}};
  const style=block.style||{}, visibility=block.visibility||{};
  const patchStyle=(key,value)=>updateBlock('style',{...style,[key]:value});
  const localZone=Intl.DateTimeFormat().resolvedOptions().timeZone;
  const dateValue=value=>{try{return toLocalInput(value,localZone);}catch{return '';}};
  const updateDate=(key,value)=>{try{updateBlock(key,value?zonedLocalToISO(value,localZone):'');}catch(error){notify?.(error.message,true);}};
  const items=block.items||[];
  const imageType=['hero','editorial','banner'].includes(block.type);
  const showCopy=channel!=='android'||block.type!=='hero'||block.showCopy;
  const itemUpdate=(index,key,value)=>updateBlock('items',items.map((item,i)=>i===index?{...item,[key]:value}:item));
  return <aside className="sp-inspector">
    <header className="sp-inspector-head"><span className="sp-icon-box"><SlidersHorizontal size={17}/></span><div><small>BÖLÜM AYARLARI</small><h2>{BLOCKS[block.type]?.label||'Bölüm'}</h2></div></header>
    <div className="sp-inspector-tabs" role="tablist" aria-label="Bölüm ayarları sekmeleri">{[['content','İçerik',Type],['style','Tasarım',SlidersHorizontal],['visibility','Görünürlük',Eye]].map(([id,label,Icon])=><button key={id} role="tab" aria-selected={tab===id} onClick={()=>setTab(id)}><Icon size={14}/>{label}</button>)}</div>
    <div className="sp-inspector-scroll" key={`${block.id}-${tab}`}>
      {selectElement&&capabilityVisible('theme.advanced_blocks')&&<button disabled={!capabilityWritable('theme.advanced_blocks')} className="sp-button sp-button-outline sp-full" onClick={()=>selectElement(`block:${block.id}:section`,block.id)}><SlidersHorizontal size={14}/>Ölçüleri ve ayrıntıları düzenle</button>}
      {block.campaignCanvas&&capabilityVisible('theme.campaign_canvas')&&<><button type="button" className="sp-button sp-button-outline sp-full" disabled={!capabilityWritable('theme.campaign_canvas')} onClick={openCanvas}><LayoutTemplate size={16}/>Kampanya tuvalini düzenle</button><p className="sp-hint">Bu bölümün yazı, görsel ve dekor katmanlarını tuvalde düzenle. “Tuvali uygula” değişiklikleri tek adımda sayfaya kaydeder.</p></>}
      {tab==='content'&&<>
        {!['divider','spacer'].includes(block.type)&&<>
          {channel==='android'&&block.type==='hero'&&<Toggle label="Kampanya metnini göster" checked={block.showCopy} onChange={v=>updateBlock('showCopy',v)}/>}
          {channel==='android'&&block.type==='categories'&&<Toggle label="Bölüm başlığını göster" checked={block.showTitle} onChange={v=>updateBlock('showTitle',v)}/>}
          <Field label={showCopy?'Başlık':'Panelde görünen bölüm adı'} value={block.title} multiline maxLength={160} onChange={v=>updateBlock('title',v)}/>
          {showCopy&&<><Field label="Üst etiket" value={block.kicker} maxLength={60} onChange={v=>updateBlock('kicker',v)}/><Field label="Açıklama" value={block.description} multiline rows={4} maxLength={5000} onChange={v=>updateBlock('description',v)}/></>}
        </>}
        {imageType&&<><div className="sp-field-heading"><Image size={14}/> Görseller</div><ImageField label={channel==='android'?'Kampanya görseli':'Masaüstü görseli'} value={channel==='android'?(block.mobileImage||block.image):block.image} onChange={v=>updateBlock(channel==='android'?'mobileImage':'image',v)} notify={notify}/>{channel==='web'&&<ImageField label="Mobil görseli" value={block.mobileImage} onChange={v=>updateBlock('mobileImage',v)} notify={notify}/>}<Field label="Görsel açıklaması" value={block.alt} maxLength={200} onChange={v=>updateBlock('alt',v)} hint="Ekran okuyucular için görselin ne anlattığını yaz."/></>}
        {['features','faq','stats','testimonials'].includes(block.type)&&<div className="sp-item-editor"><div className="sp-field-heading">{block.type==='faq'?'Sorular':'İçerik kartları'}<span>{items.length}</span></div>{items.map((item,index)=><div className="sp-item-box" key={item.id}><header><b>{index+1}. {block.type==='faq'?'soru':'kart'}</b><MoveButtons label={`${index+1}. kart`} index={index} count={items.length} onMove={d=>{const next=[...items];[next[index],next[index+d]]=[next[index+d],next[index]];updateBlock('items',next);}} onDelete={()=>updateBlock('items',items.filter((_,i)=>i!==index))}/></header><Field label={block.type==='faq'?`${index+1}. soru`:`${index+1}. kart başlığı`} value={item.title} onChange={v=>itemUpdate(index,'title',v)} maxLength={140}/>{block.type==='stats'&&<Field label="Değer" value={item.value} onChange={v=>itemUpdate(index,'value',v)} maxLength={30}/>}<Field label={block.type==='faq'?'Yanıt':block.type==='testimonials'?'Yorum':'Kart açıklaması'} value={item.body} multiline onChange={v=>itemUpdate(index,'body',v)} maxLength={1200}/>{block.type==='features'&&<Select label="Simge" value={item.icon||'sparkles'} options={[{value:'sparkles',label:'Işıltı'},{value:'search',label:'Arama'},{value:'layers',label:'Katmanlar'},{value:'truck',label:'Teslimat'},{value:'shield',label:'Güvence'},{value:'heart',label:'Kalp'},{value:'headphones',label:'Destek'},{value:'package',label:'Paket'}]} onChange={v=>itemUpdate(index,'icon',v)}/>}</div>)}<button className="sp-button sp-button-outline sp-full" disabled={items.length>=12} onClick={()=>updateBlock('items',[...items,{id:uid(),title:block.type==='faq'?'Yeni soru':'Yeni başlık',body:'',value:'',icon:'sparkles'}])}><Plus size={14}/> {block.type==='faq'?'Soru ekle':'Kart ekle'}</button>{block.type==='testimonials'&&<p className="sp-hint">Yalnızca paylaşma izni olan, gerçek yorumları kullan.</p>}</div>}
        {block.type==='products'&&<><ProductSource key={block.id} block={block} document={document} channel={channel} updateBlock={updateBlock}/><Range label="Ürün sayısı" value={block.productLimit||8} min={1} max={24} step={1} onChange={v=>updateBlock('productLimit',v)}/></>}
        {!['divider','spacer','faq','stats','testimonials','features'].includes(block.type)&&<><div className="sp-field-heading">Yönlendirme</div>{showCopy&&<Field label="Düğme yazısı" value={block.buttonText} maxLength={60} onChange={v=>updateBlock('buttonText',v)}/>}<Target document={document} channel={channel} label="Bağlantı hedefi" value={block.target} onChange={v=>updateBlock('target',v)}/>{block.type==='products'&&(!block.productSource||block.productSource.mode==='all')&&<p className="sp-hint">Tüm ürünler seçiliyken raf, deneme kataloğundan beslenir. Bağlantı yalnız bölüm düğmesini yönlendirir.</p>}{block.type==='hero'&&channel==='web'&&<><Field label="İkinci düğme yazısı" value={block.secondaryText} maxLength={60} onChange={v=>updateBlock('secondaryText',v)}/><Target document={document} channel={channel} label="İkinci düğme hedefi" value={block.secondaryTarget} onChange={v=>updateBlock('secondaryTarget',v)}/></>}</>}
        {['spacer','divider'].includes(block.type)&&<p className="sp-hint">Bölümün yüksekliğini Tasarım sekmesinden ayarla.</p>}
      </>}
      {tab==='style'&&<><div className="sp-info-note">Bu ayarlar yalnızca seçili bölümü etkiler. Site genelini Tema bölümünden düzenleyebilirsin.</div><Color optional label="Bölüm arka planı" value={style.background} onChange={v=>patchStyle('background',v)}/><Color optional label="Bölüm yazı rengi" value={style.textColor} onChange={v=>patchStyle('textColor',v)}/><Select label="Metin hizası" value={style.align||'left'} options={[{value:'left',label:'Sola hizalı'},{value:'center',label:'Ortalanmış'},{value:'right',label:'Sağa hizalı'}]} onChange={v=>patchStyle('align',v)}/><Range label={block.type==='spacer'?'Boşluk yüksekliği':'Dikey iç boşluk'} min={0} max={160} step={4} unit=" px" value={style.padding??48} onChange={v=>patchStyle('padding',v)}/>{['editorial','banner'].includes(block.type)&&<Select label="Görsel yerleşimi" value={style.imagePosition||'right'} options={[{value:'right',label:'Görsel sağda'},{value:'left',label:'Görsel solda'}]} onChange={v=>patchStyle('imagePosition',v)}/>}<button className="sp-button sp-button-outline sp-full" onClick={()=>updateBlock('style',{background:'',textColor:'',padding:48,align:'left',imagePosition:'right'})}>Bölüm tasarımını sıfırla</button></>}
      {tab==='visibility'&&<><Toggle label="Bölüm yayında görünsün" checked={block.enabled!==false} onChange={v=>updateBlock('enabled',v)}/><div className="sp-field-heading">Cihaz görünürlüğü</div><Toggle label="Masaüstü ve tablet" checked={visibility.desktop!==false} onChange={v=>updateBlock('visibility',{...visibility,desktop:v})}/><Toggle label="Mobil ekranlar" checked={visibility.mobile!==false} onChange={v=>updateBlock('visibility',{...visibility,mobile:v})}/><Capability code="theme.scheduling"><div className="sp-field-heading">Gösterim takvimi</div><p className="sp-hint">Tarihleri boş bırakırsan bölüm sürekli gösterilir. Saatler bu cihazın saat dilimindedir.</p><Field label="Başlangıç tarihi" type="datetime-local" value={dateValue(block.startsAt)} onChange={v=>updateDate('startsAt',v)}/><Field label="Bitiş tarihi" type="datetime-local" value={dateValue(block.endsAt)} onChange={v=>updateDate('endsAt',v)}/>{(block.startsAt||block.endsAt)&&<button className="sp-button sp-button-outline" onClick={()=>{updateBlock('startsAt','');updateBlock('endsAt','');}}>Takvimi temizle</button>}</Capability></>}
    </div>
    <footer className="sp-inspector-footer"><button hidden={!capabilityVisible('theme.homepage_blocks')} disabled={!capabilityWritable('theme.homepage_blocks')} onClick={duplicate}><Copy size={14}/>Çoğalt</button><button hidden={!capabilityVisible('theme.homepage_blocks')} disabled={!capabilityWritable('theme.homepage_blocks')} className="sp-danger" onClick={remove}><Trash2 size={14}/>Bölümü sil</button></footer>
    {capabilityWritable('theme.campaign_canvas')&&canvasEditing?.id===block.id&&<CampaignCanvasEditor key={`${channel}-${block.id}`} value={canvasEditing.canvas} theme={document?.theme||{}} onClose={()=>setCanvasEditing(null)} onSave={saveCanvas}/>}
  </aside>
}
