import React,{useEffect,useState} from 'react';
import {CheckCircle2,FileDown,Plug,ShieldCheck} from 'lucide-react';
import {isStudioHost,getStudioHost,getStudioSession} from '../../studio-integration/context.js';
import {getDocumentHealth} from '../studioDocumentStore.js';
import {Section} from './Controls.jsx';

const PORTS=[['readDraft','Tasarım belgesini okuma'],['readCatalog','Mağazanın ürün ve kategorileri'],['saveDraft','Sürüm denetimiyle taslak kaydı'],['createPreview','Mağazaya özel önizleme'],['readReadiness','Sunucu yayın uygunluğu'],['requestPublication','Yetkili yayın isteği'],['openThemeWorkshop','Sektör tema atölyesi']];
export default function IntegrationReadiness({doc,channel}){
  const host=isStudioHost()?getStudioHost():null,health=getDocumentHealth(doc,channel);
  const [result,setResult]=useState(null),[error,setError]=useState(''),[pending,setPending]=useState(false);
  useEffect(()=>{setResult(null);setError('');},[doc,channel]);
  const inspect=async()=>{try{setPending(true);setError('');setResult(await getStudioSession().inspectReadiness(channel));}catch(e){setError(e.message);}finally{setPending(false);}};
  const exportReport=()=>{
    const report={format:'novastore-studio-readiness/1',at:new Date().toISOString(),channel,mode:host?'host':'isolated-demo',documentHealth:health,ports:PORTS.map(([id,label])=>({id,label,configured:typeof host?.ports[id]==='function'})),serverCheck:result,productionValidated:false,note:'Yerel yapı kontrolüdür. Sağlayıcı, gerçek cihaz, alan adı ve canlı ticaret kabulünün yerine geçmez.'};
    const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='novastore-entegrasyon-kontrolu.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);
  };
  return <div className="sp-settings-content"><Section title="Admin bağlantısına hazırlık" description="Tasarım kalitesi ile canlı mağaza bağlantısı ayrı kontrol edilir."><div className="sp-readiness-intro"><ShieldCheck size={30}/><div><h3>{host?'Admin modülü açık':'Bağımsız demo açık'}</h3><p>{host?'Düzenlemeler önce modül taslağında tutulur. Sunucuya kaydetme ve yayın isteği ayrı, yetkili işlemlerdir.':'Bu sunucu gerçek API çağrılarını kapatır. Tasarım, sepet ve hesap denemeleri canlı mağazaya yazmaz.'}</p></div></div><p>Belge sağlığı: <strong>{health.score}/100</strong>. Bu puan canlıya çıkış onayı değildir.</p><button className="sp-button sp-button-outline" onClick={exportReport}><FileDown size={16}/>Kontrol raporunu indir</button></Section>
    <Section title="Bağlantı envanteri" description="Bağlı bir işlevin görünmesi, onun gerçek backend ile kabul testinden geçtiği anlamına gelmez."><div className="sp-readiness-ports">{PORTS.map(([id,label])=><div key={id}><Plug size={17}/><span>{label}</span><strong>{typeof host?.ports[id]==='function'?'Bağlantı tanımlı':'Bağlantı bekliyor'}</strong></div>)}</div><button className="sp-button sp-button-dark" disabled={!host||host.capabilities.read!==true||typeof host.ports.readReadiness!=='function'||pending} onClick={inspect}>Sunucuda bu sürümü kontrol et</button>{result&&<p role="status"><CheckCircle2 size={15}/> {result.ready?'Sunucu bu kapsam ve sürüm için uygunluk bildirdi. Yayın işlemi yapılmadı.':result.unsaved?'Kaydedilmemiş düzenlemeler var; güncel sürüm için uygunluk alınamaz.':'Sunucu veya ticaret bağlantısı bu sürüm için hazır değil.'}</p>}{error&&<p role="alert">{error}</p>}</Section>
    <Section title="Canlıya geçişte tamamlanacaklar" description="Admin ekibinin kabul ortamında doğrulayacağı entegrasyonlar."><ul><li>Gerçek ürün, varyant, fiyat ve stok; müşteri oturumu, sepet, favoriler, sipariş ve NovaBot bağlantıları.</li><li>Mağaza ve satıcı kapsamı, yetkiler, eşzamanlı düzenleme çatışmaları ve kayıt geçmişi.</li><li>Önizleme, onay, yayın ve önceki sürüme dönüş için sunucu işlemleri.</li><li>Satıcı alan adı sahipliği, DNS/TLS, katalog ataması ve komisyon muhasebesi.</li><li>Android uygulamasının gerçek cihazda tema ve ticaret kabulü.</li></ul><p>Temayı seçmek bu bağlantıları kendiliğinden kurmaz. Demo kaynakları ayrı sayfada/iframe içinde çalışır; canlı mağazaya bağlandığında ortak stiller ve veri sözleşmeleri ayrıca doğrulanır.</p></Section></div>;
}
