import {isStudioHost,getStudioHost,getStudioSession} from '../../studio-integration/context.js';
import React,{useEffect,useState} from 'react';
import {CalendarDays,Clock3,ExternalLink,Pause,Play,ArrowUpRight} from 'lucide-react';
import {getPageBlocks} from '../store.js';
import {Field,Section} from './Controls.jsx';
import {previewURL} from './Canvas.jsx';

const status=(block,now)=>block.enabled===false?'paused':block.startsAt&&!Number.isFinite(Date.parse(block.startsAt))||block.endsAt&&!Number.isFinite(Date.parse(block.endsAt))||block.startsAt&&block.endsAt&&Date.parse(block.endsAt)<=Date.parse(block.startsAt)?'invalid':block.endsAt&&Date.parse(block.endsAt)<=now?'ended':block.startsAt&&Date.parse(block.startsAt)>now?'upcoming':'active';
const labels={active:'Gösterimde',upcoming:'Planlandı',ended:'Sona erdi',paused:'Duraklatıldı',invalid:'Tarih hatası'};
const date=value=>value?new Date(value).toLocaleString('tr-TR',{dateStyle:'medium',timeStyle:'short'}):'Sınır yok';
export default function Schedule({doc,channel,pages,update,editPage}) {
  const [previewError,setPreviewError]=useState(''),[pending,setPending]=useState(false),[hostPreview,setHostPreview]=useState(null);
  const [filter,setFilter]=useState('all'),[at,setAt]=useState(''),[now,setNow]=useState(Date.now());
  useEffect(()=>{const timer=setInterval(()=>setNow(Date.now()),15000);return()=>clearInterval(timer);},[]);
  const rows=pages.flatMap(page=>getPageBlocks(doc,page.id).filter(b=>b.startsAt||b.endsAt).map(block=>({page,block,state:status(block,now)}))).sort((a,b)=>(Date.parse(a.block.startsAt)||0)-(Date.parse(b.block.startsAt)||0));
  const [previewPage,setPreviewPage]=useState('home');
  const page=pages.find(p=>p.id===previewPage)||pages[0],url=isStudioHost()?null:new URL(previewURL(channel,page?.id||'home',page?.hash,{draft:true}));
  if(url&&at&&Number.isFinite(Date.parse(at)))url.searchParams.set('previewAt',new Date(at).toISOString());
  const validTime=Boolean(at&&Number.isFinite(Date.parse(at)));
  const canHostPreview=isStudioHost()&&getStudioHost().capabilities.scheduledPreview===true&&getStudioHost().capabilities.preview===true&&typeof getStudioHost().ports.createPreview==='function';
  useEffect(()=>{setHostPreview(null);setPreviewError('');},[at,previewPage,channel,doc]);
  const requestPreview=async()=>{try{setPreviewError('');setPending(true);const href=await getStudioSession().preview(channel,{pageKey:page?.id||'home',previewAt:new Date(at).toISOString()});setHostPreview(href);}catch(error){setPreviewError(error.message);}finally{setPending(false);}};
  return <div className="sp-settings-content"><div className="sp-schedule-stats">{['upcoming','active','ended','paused'].map(key=><button key={key} className={filter===key?'selected':''} onClick={()=>setFilter(filter===key?'all':key)}><span>{labels[key]}</span><strong>{rows.filter(row=>row.state===key).length}</strong><Clock3 size={18}/></button>)}</div>
    <Section title="Takvim önizlemesi" description="Bir tarih seç; o anda hangi bölümlerin görüneceğini taslağa dokunmadan incele. Saatler bu cihazın saat dilimindedir."><div className="sp-schedule-preview"><Field label="Önizleme tarihi ve saati" type="datetime-local" value={at} onChange={setAt}/><label className="sp-field"><span>Önizlenecek sayfa</span><select aria-label="Takvim önizleme sayfası" value={page?.id||'home'} onChange={e=>setPreviewPage(e.target.value)}>{pages.map(p=><option key={p.id} value={p.id}>{p.label}</option>)}</select></label>{isStudioHost()?<><button className="sp-button sp-button-dark" disabled={!validTime||!canHostPreview||pending} onClick={requestPreview}>Sunucuda tarihli önizleme hazırla</button>{hostPreview&&<a className="sp-button sp-button-outline" href={hostPreview} target="_blank" rel="noreferrer">Hazırlanan önizlemeyi aç</a>}{!canHostPreview&&<p className="sp-hint">Tarihli önizleme bağlantısı admin sunucusunda etkinleştirilmeli.</p>}{previewError&&<p role="alert">{previewError}</p>}</>:validTime?<a className="sp-button sp-button-dark" href={url.href} target="_blank" rel="noreferrer"><ExternalLink size={15}/>Bu tarihte önizle</a>:<button className="sp-button sp-button-dark" disabled><ExternalLink size={15}/>Önce bir tarih seç</button>}</div></Section>
    <Section title="Tarihli bölümler" description="Tüm sayfalardaki zamanlanmış içerikler. Takvim aralığı başlangıç anını içerir, bitiş anında gösterim kapanır."><div className="sp-schedule-filter">{['all','upcoming','active','ended','paused','invalid'].map(key=><button className={filter===key?'selected':''} key={key} onClick={()=>setFilter(key)}>{key==='all'?'Tümü':labels[key]}</button>)}</div><div className="sp-schedule-list">{rows.filter(row=>filter==='all'||row.state===filter).map(({page,block,state})=><article key={block.id}><span className={`sp-schedule-symbol ${state}`}><CalendarDays size={21}/></span><div><small>{page.label}</small><h3>{block.title||'İsimsiz bölüm'}</h3><p>{date(block.startsAt)} → {date(block.endsAt)}</p></div><span className={`sp-schedule-badge ${state}`}>{labels[state]}</span><button className="sp-icon-button" aria-label={`${block.title} ${block.enabled===false?'devam ettir':'duraklat'}`} onClick={()=>update(next=>{const item=getPageBlocks(next,page.id).find(b=>b.id===block.id);if(item)item.enabled=item.enabled===false;})}>{block.enabled===false?<Play size={16}/>:<Pause size={16}/>}</button><button className="sp-button sp-button-outline" onClick={()=>editPage(page.id,block.id)}>Düzenle<ArrowUpRight size={14}/></button></article>)}</div>{!rows.filter(row=>filter==='all'||row.state===filter).length&&<div className="sp-schedule-empty"><CalendarDays size={32}/><h3>{rows.length?'Bu durumda bölüm bulunmuyor.':'Takvimin yeni fikirlere hazır.'}</h3><p>Hazır dönem paketine veya bölümün Görünürlük ayarına başlangıç ve bitiş tarihi ekleyebilirsin.</p></div>}<p className="sp-hint">Bu ekran seçili kanalın taslağını gösterir. Düzenlemelerin müşteri önizlemesine geçmesi için denemede yayımla.</p></Section></div>;
}
