import Capability from '../../studio-integration/Capability.jsx';
import {isStudioHost,assetURL} from '../../studio-integration/context.js';
import React,{useEffect,useState} from 'react';
import {ArrowDown,ArrowUp,ArrowUpRight,Check,ChevronRight,Copy,Eye,FileText,Globe,LayoutTemplate,Plus,Search,Smartphone,Trash2} from 'lucide-react';
import {createPage,themePresets,mediaOptions,getPageBlocks} from '../store.js';
import {Color,Field,ImageField,MoveButtons,Range,Section,Select,TABS,Target,Toggle,uid} from './Controls.jsx';
import SortableList from './SortableList.jsx';

function PageSlugField({value,onChange}){
  const [draft,setDraft]=useState(value||''),[invalid,setInvalid]=useState(false);
  useEffect(()=>{setDraft(value||'');setInvalid(false);},[value]);
  const commit=()=>{const slug=draft.trim();if(!/^[a-z0-9]+(?:-[a-z0-9]+)*$/.test(slug)){setInvalid(true);return;}setInvalid(false);setDraft(slug);if(slug!==value)onChange(slug);};
  return <Field label="Sayfa adresi" value={draft} maxLength={100} aria-invalid={invalid} onChange={next=>{setDraft(next);setInvalid(false);}} onBlur={commit} onKeyDown={event=>{if(event.key==='Enter'){event.preventDefault();commit();}if(event.key==='Escape'){event.preventDefault();event.stopPropagation();setDraft(value||'');setInvalid(false);}}} hint={invalid?'Küçük harf, sayı ve kısa çizgi kullan; adres boş kalamaz.':'Kısa bir adres yaz: hakkimizda, yeni-koleksiyon… Enter ile veya alandan çıkınca kaydedilir.'}/>;
}

function applyThemeValues(document,values){
  const previousNavy=document.theme.navy;
  const nextNavy=values.navy??previousNavy;
  for(const area of (isStudioHost()?[]:['header','footer'])){
    if(document.chrome[area].background===previousNavy)document.chrome[area].background=nextNavy;
  }
  document.theme={...document.theme,...values};
}

export function ThemeSettings({doc,channel,update,notify}){
  const theme=doc.theme,commerce=doc.commerce||{};
  const change=(key,value)=>update(next=>{applyThemeValues(next,{[key]:value});},{transactionId:`theme-${key}`,coalesce:true});
  const card=(key,value)=>update(next=>{next.commerce[key]=value;});
  return <div className="sp-settings-content">
    <Section capability="theme.advanced_blocks" title="Bir görünümle başla. Her detayını değiştir." description="Bu kanalın tüm sayfaları aynı tasarım dilini kullanır. Hazır bir tema seçebilir veya kendi paletini oluşturabilirsin.">
      <div className="sp-theme-presets">{themePresets.filter(preset=>channel==='web'||preset.id!=='night').map(preset=><button key={preset.id} className={theme.accent===preset.theme.accent&&theme.navy===preset.theme.navy?'selected':''} onClick={()=>{if(update(next=>{applyThemeValues(next,preset.theme);}))notify(`${preset.name} teması taslağa uygulandı.`);}}><div className="sp-preset-swatches">{preset.colors.map((color,i)=><span key={i} style={{background:color}}/>)}</div><strong>{preset.name}</strong><small>{preset.description}</small>{theme.accent===preset.theme.accent&&theme.navy===preset.theme.navy&&<Check size={16}/>}</button>)}</div>
    </Section>
    <div className="sp-settings-columns">
      <Section capability="theme.colors" title="Renk sistemi" description="Marka, yüzey ve metin renkleri aynı yerden yönetilir."><div className="sp-color-grid">{[['accent','Vurgu rengi'],['navy','Ana marka rengi'],['background','Sayfa arka planı'],['surface','Kart ve panel yüzeyi'],['text','Ana yazı'],['muted','İkincil yazı'],['border','Çizgi ve kenarlık']].map(([key,label])=><Color key={key} label={label} value={theme[key]} onChange={v=>change(key,v)}/>)}</div></Section>
      <Section capability="theme.typography" title="Yazı ve ölçüler" description="Başlıkları, içerik genişliğini ve boşlukları birlikte ayarla."><Select label="Yazı ailesi" value={theme.fontFamily||'Inter'} options={[{value:'Inter',label:'Inter · modern ve sade'},{value:'system',label:channel==='android'?'Mevcut uygulama yazısı':'Sistem yazı ailesi'},{value:'Arial',label:'Arial · klasik'},{value:'Georgia',label:'Georgia · editoryal'}]} onChange={v=>change('fontFamily',v)}/><Range label="Genel yazı ölçeği" value={theme.fontScale} min={.75} max={1.5} step={.05} format={v=>`%${Math.round(v*100)}`} onChange={v=>change('fontScale',v)}/><Range label="Başlık ölçeği" value={theme.headingScale??1} min={.75} max={1.5} step={.05} format={v=>`%${Math.round(v*100)}`} onChange={v=>change('headingScale',v)}/>{channel==='web'&&<Capability code="theme.advanced_blocks"><Range label="İçerik genişliği" value={theme.contentWidth??1440} min={960} max={1920} step={40} unit=" px" onChange={v=>change('contentWidth',v)}/></Capability>}<Capability code="theme.advanced_blocks"><Range label="Bölüm aralıkları" value={theme.spacing??1} min={.5} max={2} step={.1} format={v=>`${v.toFixed(1)}×`} onChange={v=>change('spacing',v)}/></Capability></Section>
      <Section capability="theme.advanced_blocks" title="Biçim ve hareket" description="Düğmelerden kartlara kadar tutarlı ayrıntılar."><Range label="Köşe yumuşaklığı" value={theme.radius} min={0} max={40} step={2} unit=" px" onChange={v=>change('radius',v)}/><Select label="Düğme biçimi" value={theme.buttonStyle||'solid'} options={[{value:'solid',label:'Dolu'},{value:'outline',label:'Çerçeveli'},{value:'soft',label:'Yumuşak zemin'}]} onChange={v=>change('buttonStyle',v)}/><Select label="Gölgeler" value={theme.shadow||'soft'} options={[{value:'none',label:'Düz'},{value:'soft',label:'Hafif'},{value:'strong',label:'Belirgin'}]} onChange={v=>change('shadow',v)}/><Toggle label="Hafif animasyonlar" hint="Cihazın azaltılmış hareket tercihi ayrıca korunur." checked={theme.motion} onChange={v=>change('motion',v)}/><div className="sp-theme-live-sample" style={{background:theme.surface,color:theme.text,borderColor:theme.border,borderRadius:theme.radius}}><small style={{color:theme.accent}}>NOVASTORE SEÇKİSİ</small><h3 style={{fontFamily:theme.fontFamily==='system'?'inherit':theme.fontFamily,fontSize:`${24*(theme.headingScale||1)}px`}}>İyi seçimler, iyi hissettirir.</h3><p style={{color:theme.muted}}>Görünümün tüm sayfalarda aynı dili konuşsun.</p><span style={{background:theme.accent,borderRadius:theme.radius}}>Keşfet <ArrowUpRight size={16}/></span></div></Section>
      <Section capability="theme.product_grid" title="Ürün kartları" description={channel==='android'?'Mevcut uygulamanın ürün kartlarına uygulanır.':'Kategori, arama ve ürün raflarında ortak görünüm.'}>{channel==='web'&&<Range label="Masaüstü sütun sayısı" value={commerce.gridColumns??4} min={2} max={5} step={1} onChange={v=>card('gridColumns',v)}/>}<Select label="Ürün görseli oranı" value={commerce.imageRatio||'square'} options={[{value:'square',label:'Kare · 1:1'},{value:'portrait',label:'Dikey'},{value:'landscape',label:'Yatay · 4:3'}]} onChange={v=>card('imageRatio',v)}/>{[['showBrand','Marka / mağaza adı'],['showRating','Puan ve değerlendirme'],['showDiscount','İndirim etiketi'],['showQuickAdd','Hızlı sepete ekleme']].map(([key,label])=><Toggle key={key} label={label} checked={commerce[key]!==false} onChange={v=>card(key,v)}/>)}</Section>
    </div>
    {channel==='android'&&<Section capability="theme.mobile_editor" title="Uygulama düzeni" description="Mevcut V4.13 alt gezinmesi. Ana sayfa ilk sırada kalır."><Select label="İçerik yoğunluğu" value={doc.app.density} options={[{value:'comfortable',label:'Ferah'},{value:'compact',label:'Kompakt'}]} onChange={v=>update(next=>{next.app.density=v;})}/><div className="sp-app-nav-grid">{Object.keys(TABS).map(key=>{const index=doc.app.bottomTabs.indexOf(key),enabled=index>=0;return <div className="sp-app-nav-item" key={key}><Toggle label={TABS[key]} checked={enabled} disabled={key==='home'} onChange={v=>update(next=>{next.app.bottomTabs=v?[...next.app.bottomTabs,key]:next.app.bottomTabs.filter(t=>t!==key);})}/><span>{enabled?`${index+1}. sıra`:'Gizli'}</span><div className="sp-move-buttons"><button disabled={!enabled||index<=1} aria-label={`${TABS[key]} sekmesini yukarı taşı`} onClick={()=>update(next=>{[next.app.bottomTabs[index-1],next.app.bottomTabs[index]]=[next.app.bottomTabs[index],next.app.bottomTabs[index-1]];})}><ArrowUp size={14}/></button><button disabled={!enabled||index===doc.app.bottomTabs.length-1||key==='home'} aria-label={`${TABS[key]} sekmesini aşağı taşı`} onClick={()=>update(next=>{[next.app.bottomTabs[index+1],next.app.bottomTabs[index]]=[next.app.bottomTabs[index],next.app.bottomTabs[index+1]];})}><ArrowDown size={14}/></button></div></div>})}</div></Section>}
  </div>
}

export function ChromeSettings({doc,channel,update}){
  const header=doc.chrome.header,footer=doc.chrome.footer;
  const headerField=(key,value)=>update(next=>{next.chrome.header[key]=value;},{transactionId:`header-${key}`,coalesce:true});
  return <div className="sp-settings-content"><Section capability="theme.logo" title="Logo / marka"><Field label="Logo / marka yazısı" value={header.logoText} maxLength={40} onChange={v=>headerField('logoText',v)}/></Section><Section capability="theme.header" title={channel==='android'?'Uygulama duyurusu':'Üst bilgi ve marka'} description={channel==='android'?'Uygulamanın mevcut üst gezinmesi korunur. İsteğe bağlı duyuru tüm uygulama sayfalarında kullanılır.':'Markanın ilk karşılaşma noktası. Bu alan tüm web sayfalarında ortaktır.'}>
    <div className="sp-form-grid">{channel==='web'&&<><Field label="Marka açıklaması" value={header.tagline} maxLength={140} onChange={v=>headerField('tagline',v)}/></>}<Field label="Duyuru metni" value={header.announcement} maxLength={220} onChange={v=>headerField('announcement',v)} hint="Örn. Yeni koleksiyon şimdi NovaStore'da."/>{channel==='web'&&<><div><Color label="Üst bilgi arka planı" value={header.background||doc.theme.navy} onChange={v=>headerField('background',v)}/><button type="button" className="sp-text-button" aria-label="Üst bilgi arka planında tema rengini kullan" disabled={header.background===doc.theme.navy} onClick={()=>headerField('background',doc.theme.navy)}>Tema rengini kullan</button></div><Color label="Üst bilgi yazısı" value={header.textColor} onChange={v=>headerField('textColor',v)}/></>}</div><Toggle label="Duyuru şeridini göster" checked={header.showAnnouncement} onChange={v=>headerField('showAnnouncement',v)}/>{channel==='web'&&<><Toggle label="Arama alanını göster" checked={header.showSearch} onChange={v=>headerField('showSearch',v)}/><Toggle label="Üst bilgiyi sabitle" checked={header.sticky} onChange={v=>headerField('sticky',v)}/></>}
  </Section>{channel==='web'&&<Section capability="theme.footer" title="Alt bilgi" description="Marka metni, bağlantı sütunları ve alt satır her sayfada güncellenir."><div className="sp-form-grid"><Field label="Alt bilgi açıklaması" value={footer.description} multiline onChange={v=>update(next=>{next.chrome.footer.description=v;})} maxLength={500}/><Field label="Telif / alt satır" value={footer.copyright} onChange={v=>update(next=>{next.chrome.footer.copyright=v;})} maxLength={200}/><div><Color label="Alt bilgi arka planı" value={footer.background||doc.theme.navy} onChange={v=>update(next=>{next.chrome.footer.background=v;})}/><button type="button" className="sp-text-button" aria-label="Alt bilgi arka planında tema rengini kullan" disabled={footer.background===doc.theme.navy} onClick={()=>update(next=>{next.chrome.footer.background=next.theme.navy;})}>Tema rengini kullan</button></div><Color label="Alt bilgi yazısı" value={footer.textColor} onChange={v=>update(next=>{next.chrome.footer.textColor=v;})}/></div><div className="sp-footer-columns">{footer.columns.map((column,ci)=><div className="sp-footer-column" key={column.id}><header><Field label={`${ci+1}. sütun başlığı`} value={column.title} onChange={v=>update(next=>{next.chrome.footer.columns[ci].title=v;})} maxLength={60}/><button className="sp-icon-button sp-danger" aria-label={`${column.title} sütununu sil`} onClick={()=>update(next=>{next.chrome.footer.columns.splice(ci,1);})}><Trash2 size={15}/></button></header>{column.links.map((link,li)=><div className="sp-footer-link" key={link.id}><Field label={`${ci+1}.${li+1} bağlantı başlığı`} value={link.label} maxLength={80} onChange={v=>update(next=>{next.chrome.footer.columns[ci].links[li].label=v;})}/><Target document={doc} channel={channel} value={link.target} onChange={v=>update(next=>{next.chrome.footer.columns[ci].links[li].target=v;})}/><MoveButtons label={link.label} index={li} count={column.links.length} onMove={d=>update(next=>{const links=next.chrome.footer.columns[ci].links;[links[li+d],links[li]]=[links[li],links[li+d]];})} onDelete={()=>update(next=>{next.chrome.footer.columns[ci].links.splice(li,1);})}/></div>)}<button className="sp-button sp-button-outline" disabled={column.links.length>=12} onClick={()=>update(next=>{next.chrome.footer.columns[ci].links.push({id:uid(),label:'Yeni bağlantı',target:'home',enabled:true});})}><Plus size={14}/>Bağlantı ekle</button></div>)}</div><button className="sp-button sp-button-outline" disabled={footer.columns.length>=5} onClick={()=>update(next=>{next.chrome.footer.columns.push({id:uid(),title:'Yeni sütun',links:[]});})}><Plus size={15}/>Sütun ekle</button></Section>}</div>
}

export function MenusSettings({doc,channel,update}){
  return <div className="sp-settings-content"><Section capability="theme.navigation" title={channel==='android'?'Uygulama kategori menüsü':'Ana gezinme menüsü'} description="Tutma simgesinden sürükleyerek sırala. Her öğeyi bir kategoriye, ürüne veya oluşturduğun sayfaya bağla." actions={<button className="sp-button sp-button-dark" disabled={doc.menus.length>=40} onClick={()=>update(next=>{next.menus.push({id:uid(),label:'Yeni menü',target:'home',enabled:true});})}><Plus size={15}/>Menü ekle</button>}>
    <SortableList label="Gezinme sırası" items={doc.menus} getLabel={item=>item.label} onOrder={ids=>update(next=>{next.menus=ids.map(id=>next.menus.find(m=>m.id===id));})} renderItem={(menu,index)=><div className="sp-menu-fields"><span className="sp-number">{String(index+1).padStart(2,'0')}</span><Field label={`${index+1}. menü başlığı`} value={menu.label} maxLength={50} onChange={v=>update(next=>{next.menus.find(m=>m.id===menu.id).label=v;})}/><Target document={doc} channel={channel} value={menu.target} onChange={v=>update(next=>{next.menus.find(m=>m.id===menu.id).target=v;})}/><Toggle label="Görünür" checked={menu.enabled} onChange={v=>update(next=>{next.menus.find(m=>m.id===menu.id).enabled=v;})}/><button className="sp-icon-button sp-danger" aria-label={`${menu.label} menüsünü sil`} onClick={()=>update(next=>{next.menus=next.menus.filter(m=>m.id!==menu.id);})}><Trash2 size={15}/></button></div>}/>
  </Section></div>
}

export function PagesSettings({doc,channel,update,editPage,templates}){
  const [selected,setSelected]=useState(doc.pages[0]?.id),[query,setQuery]=useState('');
  const page=doc.pages.find(p=>p.id===selected)||doc.pages[0];
  const change=(key,value)=>update(next=>{next.pages.find(p=>p.id===page.id)[key]=value;},{transactionId:`page-${page?.id}-${key}`,coalesce:true});
  function add(){const item=createPage('Yeni sayfa');if(update(next=>{next.pages.push(item);}))setSelected(item.id);}
  return <div className="sp-settings-content"><Section capability="theme.advanced_blocks" title="Her sayfa için ayrı bir deneyim" description="Mağaza akışlarının çevresini düzenle; kendi içerik sayfalarını oluştur." actions={<button className="sp-button sp-button-dark" disabled={doc.pages.length>=40} onClick={add}><Plus size={15}/>Yeni sayfa</button>}><div className="sp-template-cards">{templates.filter(t=>t.id!=='home').map(t=><button key={t.id} onClick={()=>editPage(t.id)}><LayoutTemplate size={19}/><strong>{t.label}</strong><small>Sayfa şablonunu düzenle</small><ArrowUpRight size={16}/></button>)}</div></Section>
    <div className="sp-page-manager"><div className="sp-page-list"><label className="sp-search"><Search size={15}/><input aria-label="Sayfalarda ara" placeholder="Sayfa ara…" value={query} onChange={e=>setQuery(e.target.value)}/></label>{doc.pages.filter(p=>`${p.title} ${p.slug}`.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))).map(p=><button key={p.id} className={page?.id===p.id?'selected':''} onClick={()=>setSelected(p.id)}><FileText size={17}/><span><strong>{p.title||'İsimsiz sayfa'}</strong><small>/{p.slug||p.id}</small></span><i className={p.enabled===false?'is-hidden':''}/></button>)}</div>{page?<Section title={page.title||'Sayfa ayarları'} actions={<button className="sp-button sp-button-dark" onClick={()=>editPage(`page:${page.id}`)}><LayoutTemplate size={15}/>Bloklarla düzenle</button>}><div className="sp-form-grid"><Field label="Sayfa başlığı" value={page.title} maxLength={160} onChange={v=>change('title',v)}/><PageSlugField key={page.id} value={page.slug} onChange={v=>change('slug',v)}/></div><Field label="Sayfa metni" value={page.body} multiline rows={7} maxLength={10000} onChange={v=>change('body',v)} hint="Paragrafları boş satırla ayır. Görsel ve diğer bölümleri blok düzenleyicisinden ekle."/><Toggle label="Sayfa görünür" checked={page.enabled!==false} onChange={v=>change('enabled',v)}/><div className="sp-field-heading"><Globe size={15}/>Arama görünümü</div><Field label="SEO başlığı" value={page.seoTitle} maxLength={70} onChange={v=>change('seoTitle',v)}/><Field label="SEO açıklaması" value={page.seoDescription} multiline maxLength={180} onChange={v=>change('seoDescription',v)}/><div className="sp-search-preview"><small>NovaStore › {page.slug||page.id}</small><strong>{page.seoTitle||page.title}</strong><p>{page.seoDescription||'Arama sonuçları için kısa bir sayfa açıklaması ekle.'}</p></div>{!['about','help'].includes(page.id)&&<button className="sp-button sp-button-outline sp-danger" onClick={()=>{update(next=>{next.pages=next.pages.filter(p=>p.id!==page.id);});setSelected(doc.pages.find(p=>p.id!==page.id)?.id);}}><Trash2 size={14}/>Sayfayı sil</button>}</Section>:<Section title="İlk sayfanı oluştur"><button className="sp-button sp-button-dark" disabled={doc.pages.length>=40} onClick={add}>Sayfa ekle</button></Section>}</div>
  </div>
}

export function MediaSettings({doc,applyMedia,notify}){
  const [query,setQuery]=useState('');const allBlocks=[...doc.blocks,...doc.pages.flatMap(p=>p.blocks||[]),...Object.values(doc.templates||{}).flatMap(t=>t.blocks||[])];
  const existing=[...new Set(allBlocks.flatMap(b=>[b.image,b.mobileImage]).filter(Boolean))];const library=[...(isStudioHost()?[]:mediaOptions),...existing.filter(src=>!mediaOptions.some(m=>m.value===src)).map((src,i)=>({value:src,label:`Yüklenen görsel ${i+1}`}))];
  return <div className="sp-settings-content"><Section capability="theme.assets" title="Görsellerin tek bir yerde" description="Mevcut marka görsellerini keşfet. Uygula düğmesi, son seçili bölümün görselini değiştirir."><label className="sp-search sp-media-search"><Search size={15}/><input aria-label="Görsellerde ara" placeholder="Görsel ara…" value={query} onChange={e=>setQuery(e.target.value)}/></label><div className="sp-media-grid">{library.filter(m=>m.label.toLocaleLowerCase('tr').includes(query.toLocaleLowerCase('tr'))).map(m=><article key={m.value}><img src={assetURL(m.value)} alt={m.label} loading="lazy"/><div><strong>{m.label}</strong><small>{allBlocks.filter(b=>b.image===m.value||b.mobileImage===m.value).length} bölümde kullanılıyor</small><button className="sp-button sp-button-outline" onClick={()=>applyMedia(m.value)}>Seçili bölüme uygula<ArrowUpRight size={14}/></button></div></article>)}</div></Section><Section capability="theme.assets" title="Yeni bir görsel kullan" description="Görsel sunucuya yüklenir ve mağaza kapsamı doğrulandıktan sonra kullanılabilir."><div className="sp-upload-media"><ImageField label="Yeni görsel" value="" onChange={applyMedia} notify={notify}/></div></Section></div>
}
