import React,{useEffect,useRef,useState} from 'react';
import {GripVertical} from 'lucide-react';
import {moveOrder} from './previewOrder.js';

export default function SortableList({items,onOrder,onPreviewOrder,renderItem,disabled=false,disabledReason='Sıralama kapalı.',label='Bölümler',getLabel=item=>item.title||item.label||'Bölüm'}){
  const [drag,setDrag]=useState(null),[announcement,setAnnouncement]=useState('');
  const dragging=useRef(null),listRef=useRef(null);
  const callbacks=useRef({});callbacks.current={onPreviewOrder};
  const cancel=()=>{dragging.current=null;setDrag(null);callbacks.current.onPreviewOrder?.(null);};
  const itemKey=items.map(item=>item.id).join('|');
  useEffect(()=>{if(dragging.current)cancel();},[itemKey]);
  useEffect(()=>{if(disabled&&dragging.current)cancel();},[disabled]);
  useEffect(()=>{const escape=event=>{if(event.key==='Escape'&&dragging.current){event.preventDefault();event.stopPropagation();cancel();setAnnouncement('Sürükleme iptal edildi. Önceki sıra korundu.');}};document.addEventListener('keydown',escape,true);return()=>{document.removeEventListener('keydown',escape,true);callbacks.current.onPreviewOrder?.(null);};},[]);
  useEffect(()=>{if(drag?.moved)callbacks.current.onPreviewOrder?.({order:moveOrder(items,drag.id,drag.targetId,drag.after),draggedId:drag.id});},[drag?.moved,drag?.id,drag?.targetId,drag?.after,itemKey]);
  useEffect(()=>{if(!drag?.moved)return;let frame;function tick(){const current=dragging.current;if(current?.moved&&listRef.current){let scroller=listRef.current.parentElement;while(scroller&&!(scroller.scrollHeight>scroller.clientHeight+2&&/auto|scroll/.test(getComputedStyle(scroller).overflowY)))scroller=scroller.parentElement;scroller=scroller||document.scrollingElement;const rect=scroller===document.scrollingElement?{top:0,bottom:innerHeight}:scroller.getBoundingClientRect();const edge=36;const speed=current.y<rect.top+edge?-Math.ceil(12*(1-Math.max(0,current.y-rect.top)/edge)):current.y>rect.bottom-edge?Math.ceil(12*(1-Math.max(0,rect.bottom-current.y)/edge)):0;if(speed){scroller.scrollTop+=speed;const target=document.elementFromPoint(current.x,current.y)?.closest('[data-sort-id]');if(target&&listRef.current.contains(target)){const box=target.getBoundingClientRect();const next={...current,targetId:target.dataset.sortId,after:current.y>box.top+box.height/2};dragging.current=next;setDrag(next);}}}frame=requestAnimationFrame(tick);}frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[Boolean(drag?.moved)]);
  function down(event,item){if(disabled||event.button!==0)return;event.preventDefault();event.currentTarget.focus({preventScroll:true});event.currentTarget.setPointerCapture(event.pointerId);dragging.current={id:item.id,x:event.clientX,y:event.clientY,initialY:event.clientY,initialX:event.clientX,moved:false,targetId:item.id,after:false};}
  function move(event){if(disabled)return;const current=dragging.current;if(!current)return;const next={...current,x:event.clientX,y:event.clientY,moved:current.moved||Math.abs(event.clientY-current.initialY)+Math.abs(event.clientX-current.initialX)>5};const target=window.document.elementFromPoint(event.clientX,event.clientY)?.closest('[data-sort-id]');if(target&&target.closest('[data-sort-list]')===event.currentTarget.closest('[data-sort-list]')){const rect=target.getBoundingClientRect();next.targetId=target.dataset.sortId;next.after=event.clientY>rect.top+rect.height/2;}dragging.current=next;setDrag(next);}
  function up(event){const current=dragging.current;dragging.current=null;setDrag(null);if(event.currentTarget.hasPointerCapture(event.pointerId))event.currentTarget.releasePointerCapture(event.pointerId);if(!disabled&&current?.moved){const ids=moveOrder(items,current.id,current.targetId,current.after);if(ids.some((id,index)=>id!==items[index].id)){onOrder(ids);setAnnouncement(`${getLabel(items.find(item=>item.id===current.id))}, ${ids.indexOf(current.id)+1}. sıraya taşındı.`);}}onPreviewOrder?.(null);}
  function key(event,item,index){if(disabled)return;if(event.key==='Escape'){dragging.current=null;setDrag(null);return;}if(!['ArrowUp','ArrowDown','Home','End'].includes(event.key)||!event.altKey)return;event.preventDefault();const next=items.map(i=>i.id);const to=event.key==='Home'?0:event.key==='End'?next.length-1:index+(event.key==='ArrowUp'?-1:1);if(to<0||to>=next.length)return;next.splice(index,1);next.splice(to,0,item.id);onOrder(next);setAnnouncement(`${getLabel(item)}, ${to+1}. sıraya taşındı.`);}
  return <><div ref={listRef} className="sp-sort-list" role="list" aria-label={label} data-sort-list="true">{items.map((item,index)=><div role="listitem" key={item.id} data-sort-id={item.id} className={`sp-sort-row ${drag?.moved&&drag.id===item.id?'is-dragging':''} ${drag?.moved&&drag.targetId===item.id&&drag.id!==item.id?(drag.after?'drop-after':'drop-before'):''}`}>
    <button className="sp-drag-handle" disabled={disabled} title={disabled?disabledReason:undefined} aria-label={`${getLabel(item)} sürükle`} aria-description="Sürüklerken sırayı önizlemede gör. Bırakarak kaydet, Escape ile iptal et. Klavyede Alt ve yukarı/aşağı okları kullan." onPointerDown={e=>down(e,item)} onPointerMove={move} onPointerUp={up} onPointerCancel={cancel} onLostPointerCapture={()=>{if(dragging.current)cancel();}} onKeyDown={e=>key(e,item,index)}><GripVertical size={15}/></button>{renderItem(item,index)}
  </div>)}</div>{drag?.moved&&<div className="sp-drag-ghost" style={{left:drag.x+14,top:drag.y+12}}><GripVertical size={15}/>{getLabel(items.find(item=>item.id===drag.id))}</div>}<span className="sp-sr-only" role="status" aria-live="polite">{announcement}</span></>
}
