import React,{useCallback,useState} from 'react';
import {NumberField,MotionFields} from './VisualMotionFields.jsx';
import {visualAssets} from '../visual/visualAssets.js';
import {supportsVisualAsset} from '../visualDesign.js';
import './visual-assets.css';
import VisualIconLibrary from './VisualIconLibrary.jsx';

function AssetPicker({asset,animation,onChange,onLibraryChange,label}){
  const [markup,setMarkup]=useState(''),[message,setMessage]=useState(''),[library,setLibrary]=useState(false);const closeLibrary=useCallback(()=>setLibrary(false),[]);
  const apply=value=>{try{onChange(visualAssets.normalizeAsset(value));setMessage('Görsel uygulandı.');}catch(error){setMessage(error.message);}};
  async function upload(event){
    const file=event.target.files?.[0];event.target.value='';if(!file)return;
    if(!['image/png','image/jpeg','image/webp'].includes(file.type)||file.size>2000000){setMessage('PNG, JPG veya WebP görseli seç; dosya en fazla 2 MB olabilir.');return;}
    try{const src=await new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('Görsel okunamadı.'));reader.readAsDataURL(file);});const image=new Image();image.src=src;try{await image.decode();}catch{throw new Error('Dosya geçerli bir görsel olarak açılamadı.');}if(!image.naturalWidth||!image.naturalHeight||image.naturalWidth>8192||image.naturalHeight>8192||image.naturalWidth*image.naturalHeight>32000000)throw new Error('Görsel en fazla 8192 px kenar uzunluğu ve 32 milyon piksel olabilir.');apply({kind:'image',src,alt:file.name.slice(0,160)});}catch(error){setMessage(error.message);}
  }
  return <div className="va-picker">
    {asset&&<div className="va-current"><img src={visualAssets.assetDataURL(asset)} alt="Seçili görsel"/><span>{asset.kind==='svg'?'Vektör simge':'Yüklenen görsel'}</span></div>}
    <button type="button" className="va-library-open" aria-label={`${label} simge kütüphanesini aç`} onClick={()=>setLibrary(true)}><span>Simge kütüphanesini aç</span><small>{visualAssets.builtinIcons.length} simge · arama ve kategori</small></button>
    {library&&<VisualIconLibrary initialAsset={asset} initialAnimation={animation} onClose={closeLibrary} onSelect={(value,motion)=>{if(onLibraryChange)onLibraryChange(value,motion);else apply(value);setLibrary(false);}}/>}
    <label className="va-upload">Görsel yükle · PNG / JPG / WebP<input type="file" aria-label={`${label} görsel yükle`} accept="image/png,image/jpeg,image/webp" onChange={upload}/></label>
    <details className="va-svg"><summary>SVG kodu kullan</summary><label className="va-field"><span>{label} SVG kodu</span><textarea aria-label={`${label} SVG kodu`} value={markup} maxLength={65536} placeholder={'<svg viewBox="0 0 24 24">…</svg>'} onChange={event=>setMarkup(event.target.value)}/></label><button type="button" className="sp-button sp-button-outline" disabled={!markup.trim()} onClick={()=>{try{let removed;const next=visualAssets.sanitizeSvg(markup,{DOMParser:window.DOMParser,onSanitized:report=>{removed=report;}});apply(next);if(removed&&(removed.removedElements||removed.removedAttributes))setMessage('SVG uygulandı; desteklenmeyen öğeler veya özellikler çıkarıldı. Hareketi animasyon alanından seçebilirsin.');}catch(error){setMessage(error.message);}}}>SVG'yi uygula</button><small>Statik vektör şekilleri kullanılır. Betik, olay, dış bağlantı ve gömülü HTML kaydedilmez.</small></details>
    {message&&<p className="va-status" role="status">{message}</p>}
  </div>;
}
export default function VisualAssetControls({id,element,onChange,onChangeBatch,notify,onPreview,allowReplacement=true}){
  const decorations=element?.decorations||[];
  const retargetMotion=(motion,asset)=>{if(motion?.name!=='recommended')return motion;const iconId=visualAssets.iconIdForAsset(asset);return iconId?{...motion,iconId}:undefined;};
  const changeAsset=asset=>onChangeBatch({visual:{asset,size:element?.visual?.size||24},animation:retargetMotion(element?.animation,asset)});
  function commit(key,value){try{onChange(key,value);}catch(error){notify?.(error.message);}}
  function changeDecoration(index,patch){const next=decorations.map((item,i)=>i===index?{...item,...patch}:item);for(const item of next)if(item.animation===undefined)delete item.animation;commit('decorations',next);}
  return <div className="va-controls" key={id}>
    {allowReplacement&&supportsVisualAsset(id)&&<details open><summary>Simge veya görseli değiştir</summary><AssetPicker key={`asset:${id}`} label="Seçili öğe" asset={element?.visual?.asset} animation={element?.animation} onLibraryChange={(asset,animation)=>onChangeBatch({visual:{asset,size:element?.visual?.size||24},animation})} onChange={changeAsset}/>{element?.visual&&<><NumberField label="Görsel boyutu (px)" value={element.visual.size} min={8} max={256} onChange={size=>commit('visual',{...element.visual,size})}/><button type="button" className="sp-text-button" onClick={()=>onChangeBatch({visual:undefined,...(element?.animation?.name==='recommended'?{animation:undefined}:{})})}>Özgün simge veya görsele dön</button></>}</details>}
    <details><summary>Öğenin animasyonu</summary><MotionFields prefix="Öğe" iconId={element?.visual?.asset?visualAssets.iconIdForAsset(element.visual.asset):null} value={element?.animation} onChange={value=>commit('animation',value)} onPreview={()=>onPreview?.(id)}/><p className="va-hint">Hareketi azalt tercihi açık cihazlarda animasyon çalışmaz.</p></details>
    <details open><summary>Yanına küçük görsel ekle</summary><p className="va-hint">Logo, başlık, düğme veya bölümün iki yanına birer öğe ekleyebilirsin. Serbest simgeleri kutunun içinde istediğin noktaya yerleştirebilirsin. Bu öğeler alışveriş tıklamalarını engellemez.</p>
      {decorations.map((item,index)=>{const overlay=item.placement==='overlay',prefix=overlay?`Serbest simge ${index+1}`:item.placement==='before'?'Ön öğe':'Arka öğe',short=overlay?prefix:item.placement==='before'?'Ön':'Arka';return <div className="va-decoration" key={item.id||item.placement} data-decoration-editor={item.id||item.placement}><header><strong>{overlay?prefix:item.placement==='before'?'Önündeki öğe':'Arkasındaki öğe'}</strong><button type="button" className="sp-text-button" onClick={()=>commit('decorations',decorations.filter((_,i)=>i!==index))}>Öğeyi kaldır</button></header><AssetPicker label={prefix} asset={item.asset} animation={item.animation} onLibraryChange={(asset,animation)=>changeDecoration(index,{asset,animation})} onChange={asset=>changeDecoration(index,{asset,animation:retargetMotion(item.animation,asset)})}/><div className="va-grid"><NumberField label={`${short} öğe boyutu (px)`} value={item.size} min={8} max={128} onChange={size=>changeDecoration(index,{size})}/>{!overlay&&<NumberField label={`${short} öğe aralığı (px)`} value={item.gap} min={0} max={48} onChange={gap=>changeDecoration(index,{gap})}/ >}{overlay&&<><NumberField label={`${prefix} yatay yüzde`} value={item.x} min={0} max={100} step={.1} onChange={x=>changeDecoration(index,{x})}/><NumberField label={`${prefix} dikey yüzde`} value={item.y} min={0} max={100} step={.1} onChange={y=>changeDecoration(index,{y})}/></>}<NumberField label={`${short} yatay konum (px)`} value={item.offsetX} min={-96} max={96} onChange={offsetX=>changeDecoration(index,{offsetX})}/><NumberField label={`${short} dikey konum (px)`} value={item.offsetY} min={-96} max={96} onChange={offsetY=>changeDecoration(index,{offsetY})}/></div>{overlay&&<p className="va-hint">Önizlemede simgeyi sürükleyebilir veya konumunu yüzdeyle ayarlayabilirsin. Yerleşim seçili kutuya bağlıdır.</p>}<MotionFields prefix={prefix} iconId={visualAssets.iconIdForAsset(item.asset)} value={item.animation} onChange={animation=>changeDecoration(index,{animation})} onPreview={()=>onPreview?.(id,item.id||item.placement)}/></div>;})}
      <div className="va-actions">{[['before','Önüne ekle'],['after','Arkasına ekle']].map(([placement,label])=><button key={placement} type="button" className="sp-button sp-button-outline" disabled={decorations.length>=8||decorations.some(item=>item.placement===placement)} onClick={()=>commit('decorations',[...decorations,{asset:visualAssets.icon('spark'),placement,size:24,gap:6,offsetX:0,offsetY:0}])}>{label}</button>)}</div>
      <button type="button" className="sp-button sp-button-outline sp-full" disabled={decorations.length>=8} onClick={()=>commit('decorations',[...decorations,{id:crypto.randomUUID(),placement:'overlay',asset:visualAssets.icon('spark'),x:50,y:50,size:32,gap:0,offsetX:0,offsetY:0}])}>Bu kutuya serbest simge ekle</button>
    </details><p className="va-hint">Simge, ek öğe ve hareket seçimi bu kanalın bütün ekran boyutlarında kullanılır. Web ve Android tasarımları ayrı kaydedilir.</p>
  </div>;
}

