import React,{useEffect,useState} from 'react';
import {visualAssets} from '../visual/visualAssets.js';
const TRIGGERS=[['always','Sürekli veya sınırlı tekrar'],['click','Tıklandığında'],['hover','Üzerine gelindiğinde'],['page-load','Sayfa açıldığında'],['route-change','Sayfa geçişinde'],['product-enter','Ürün sayfasına girildiğinde'],['interval','Belirli aralıklarla']];
export function NumberField({label,value,min,max,step=1,onChange}){
  const [draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value]);
  return <label className="va-field"><span>{label}</span><input aria-label={label} type="number" value={draft} min={min} max={max} step={step} onChange={event=>{const raw=event.target.value;setDraft(raw);const number=Number(raw);if(raw!==''&&Number.isFinite(number)&&number>=min&&number<=max)onChange(number);}} onBlur={()=>setDraft(String(value))}/></label>;
}
export function MotionFields({value,onChange,prefix,onPreview,iconId}){
  const trigger=value?.trigger||'always',iterations=value?.iterations??'infinite';
  const recommendation=iconId?visualAssets.recommendationForIcon?.(iconId):null;
  const groups=new Map();for(const item of visualAssets.animationPresets.filter(item=>!['none','recommended'].includes(item.id))){const key=item.category||'Diğer hareketler';if(!groups.has(key))groups.set(key,[]);groups.get(key).push(item);}
  const update=patch=>{const next={...value,...patch};if(next.trigger!=='interval')delete next.interval;if(next.name!=='recommended')delete next.iconId;onChange(next);};
  return <><label className="va-field"><span>{prefix} animasyonu</span><select aria-label={`${prefix} animasyonu`} value={value?.name||'none'} onChange={event=>{if(event.target.value==='none'){onChange(undefined);return;}const next={...(value||{}),name:event.target.value,duration:value?.duration||recommendation?.duration||2};if(next.name==='recommended')next.iconId=iconId;else delete next.iconId;onChange(next);}}><option value="recommended" disabled={!recommendation}>Önerilen hareket</option><option value="none">Animasyonsuz</option>{[...groups].map(([category,items])=><optgroup key={category} label={visualAssets.animationGroups?.find(group=>group.id===category)?.label||category}>{items.map(item=><option key={item.id} value={item.id}>{item.label}</option>)}</optgroup>)}</select></label>{value?.name==='recommended'&&recommendation&&<p className="va-hint"><strong>{recommendation.label}</strong><br/>{recommendation.description}</p>}{!recommendation&&<p className="va-hint">Önerilen hareket için kütüphaneden bir simge seç.</p>}{value&&value.name!=='none'&&<>
    <label className="va-field"><span>Ne zaman başlasın?</span><select aria-label={`${prefix} başlama koşulu`} value={trigger} onChange={event=>update({trigger:event.target.value,iterations:event.target.value==='always'?iterations:(iterations==='infinite'?1:iterations),...(event.target.value==='interval'?{interval:5}:{})})}>{TRIGGERS.map(([name,label])=><option key={name} value={name}>{label}</option>)}</select></label>
    <div className="va-grid"><NumberField label={`${prefix} animasyon süresi (sn)`} value={value.duration} min={.2} max={60} step={.1} onChange={duration=>update({duration})}/><NumberField label={`${prefix} gecikme (sn)`} value={value.delay??0} min={0} max={60} step={.1} onChange={delay=>update({delay})}/></div>
    {trigger==='always'&&<label className="va-field"><span>Tekrarlama</span><select aria-label={`${prefix} tekrarlama biçimi`} value={iterations==='infinite'?'infinite':'finite'} onChange={event=>update({iterations:event.target.value==='infinite'?'infinite':1})}><option value="infinite">Sürekli</option><option value="finite">Belirli sayıda</option></select></label>}
    {iterations!=='infinite'&&<NumberField label={`${prefix} tekrar sayısı`} value={iterations} min={1} max={50} onChange={next=>update({iterations:next})}/>}
    {trigger==='interval'&&<NumberField label={`${prefix} oynatımlar arası bekleme (sn)`} value={value.interval||5} min={1} max={300} onChange={interval=>update({interval})}/>}
    <p className="va-hint">{iterations==='infinite'?'Seçili hareket sürekli oynar.':`Her başlangıçta ${iterations} tekrar · ${(value.duration*iterations).toLocaleString('tr-TR')} saniye hareket${value.delay?` + ${value.delay} saniye gecikme`:''}.`}{trigger==='interval'?' Önceki hareket bittikten sonra yeniden beklenir.':''}{trigger==='product-enter'?' Ürün detay sayfasına girildiğinde seçili öğede başlar.':''}</p>
    {onPreview&&<button type="button" className="sp-button sp-button-outline" onClick={onPreview}>Hareketi önizle</button>}
  </>}</>;
}
