/** 52 additional Nova Store campaigns. Existing identities and saved documents
 * are unchanged. These are presentation presets; real products, stock, prices,
 * eligibility and publishing still belong to their existing services. */
export const CAMPAIGN_EXPANSION = [
  {
    "id": "spring-organize",
    "name": "İlkbahar · Ferah bir düzen",
    "season": "spring",
    "sector": "home",
    "title": "Her şeye biraz yer aç.",
    "description": "Kutular, sepetler ve küçük çözümlerle günlük düzenini hafiflet.",
    "productsTitle": "Düzenin küçük yardımcıları.",
    "layout": "guide",
    "family": "notebook",
    "secondary": "window",
    "motif": "boxes",
    "note": "Düzenin küçük yardımcıları.",
    "index": 56
  },
  {
    "id": "balcony-break",
    "name": "Balkon · Küçük bir mola",
    "season": "spring",
    "sector": "home",
    "title": "Balkonda kendine yer ayır.",
    "description": "Bir sandalye, yumuşak bir minder ve güne eşlik eden küçük detaylar.",
    "productsTitle": "Balkon köşeni tamamla.",
    "layout": "editorial",
    "family": "window",
    "secondary": "botanical",
    "motif": "armchair",
    "note": "Balkon köşeni tamamla.",
    "index": 57
  },
  {
    "id": "city-cycling",
    "name": "Bisiklet · Şehrin yeni rotası",
    "season": "spring",
    "sector": "sports",
    "title": "Şehri kendi hızında keşfet.",
    "description": "Bisiklet aksesuarları ve günlük rotana eşlik edecek pratik parçalar.",
    "productsTitle": "Rotanın küçük yardımcıları.",
    "layout": "collection",
    "family": "trail",
    "secondary": "studio",
    "motif": "bike",
    "note": "Rotanın küçük yardımcıları.",
    "index": 58
  },
  {
    "id": "seed-to-green",
    "name": "Bahçe · Tohumdan yeşile",
    "season": "spring",
    "sector": "garden",
    "title": "Küçük bir tohumla başla.",
    "description": "Saksılar, el aletleri ve yeşeren fikirler için sade bir hazırlık.",
    "productsTitle": "Yetiştirmeye başla.",
    "layout": "guide",
    "family": "botanical",
    "secondary": "notebook",
    "motif": "sprout",
    "note": "Yetiştirmeye başla.",
    "index": 59
  },
  {
    "id": "summer-camping",
    "name": "Yaz · Kamp ateşi çevresinde",
    "season": "summer",
    "sector": "sports",
    "title": "Bir geceni yıldızlara ayır.",
    "description": "Kamp alanına, uzun akşamlara ve açık havada geçen zamana hazırlık.",
    "productsTitle": "Kamp çantana eşlik edenler.",
    "layout": "guide",
    "family": "trail",
    "secondary": "postcard",
    "motif": "tent",
    "note": "Kamp çantana eşlik edenler.",
    "index": 60
  },
  {
    "id": "grill-gathering",
    "name": "Mangal · Açık hava buluşması",
    "season": "summer",
    "sector": "grocery",
    "title": "Sofranın yerini değiştir.",
    "description": "Açık hava hazırlığına eşlik eden pişirme ve sunum araçlarını keşfet.",
    "productsTitle": "Dışarıda pişir, birlikte paylaş.",
    "layout": "editorial",
    "family": "table",
    "secondary": "coast",
    "motif": "utensils",
    "note": "Dışarıda pişir, birlikte paylaş.",
    "index": 61
  },
  {
    "id": "poolside-time",
    "name": "Havuz · Günün serin tarafı",
    "season": "summer",
    "sector": "sports",
    "title": "Suya yakın, güne hazır.",
    "description": "Havlu, yüzme aksesuarı ve gün boyunca yanında taşıyacakların.",
    "productsTitle": "Havuz çantanı hazırla.",
    "layout": "collection",
    "family": "coast",
    "secondary": "record",
    "motif": "sun",
    "note": "Havuz çantanı hazırla.",
    "index": 62
  },
  {
    "id": "road-companions",
    "name": "Yolculuk · Arabanın küçük yardımcıları",
    "season": "summer",
    "sector": "electronics",
    "title": "Yol boyunca yanında.",
    "description": "Şarj, düzen ve molalar için günlük yolculuğa uygun aksesuarlar.",
    "productsTitle": "Yolun pratik parçaları.",
    "layout": "guide",
    "family": "postcard",
    "secondary": "studio",
    "motif": "car",
    "note": "Yolun pratik parçaları.",
    "index": 63
  },
  {
    "id": "festival-ready",
    "name": "Festival · Müziğe hazırlan",
    "season": "summer",
    "sector": "fashion",
    "title": "Günün ritmine katıl.",
    "description": "Hafif katmanlar ve açık hava etkinliğine eşlik eden seçilmiş parçalar.",
    "productsTitle": "Ritmine yakışan seçimler.",
    "layout": "editorial",
    "family": "confetti",
    "secondary": "editorial",
    "motif": "music",
    "note": "Ritmine yakışan seçimler.",
    "index": 64
  },
  {
    "id": "fresh-sips",
    "name": "Yaz · Serin bir yudum",
    "season": "summer",
    "sector": "grocery",
    "title": "Molanı serinlet.",
    "description": "Sürahiler, bardaklar ve içecek hazırlığına eşlik eden küçük araçlar.",
    "productsTitle": "Serin sofranın detayları.",
    "layout": "collection",
    "family": "ritual",
    "secondary": "table",
    "motif": "glass-water",
    "note": "Serin sofranın detayları.",
    "index": 65
  },
  {
    "id": "autumn-baking",
    "name": "Sonbahar · Fırından yeni çıktı",
    "season": "autumn",
    "sector": "grocery",
    "title": "Güzel kokular mutfakta başlar.",
    "description": "Kek kalıpları, ölçü araçları ve birlikte hazırlanan küçük lezzetler.",
    "productsTitle": "Pişirmeye eşlik edenler.",
    "layout": "guide",
    "family": "table",
    "secondary": "notebook",
    "motif": "cake",
    "note": "Pişirmeye eşlik edenler.",
    "index": 66
  },
  {
    "id": "pantry-season",
    "name": "Sonbahar · Kiler hazırlığı",
    "season": "autumn",
    "sector": "grocery",
    "title": "Mevsimi rafına taşı.",
    "description": "Saklama, hazırlık ve mutfak düzeni için kullanışlı parçaları birleştir.",
    "productsTitle": "Kilerin yeni düzeni.",
    "layout": "guide",
    "family": "notebook",
    "secondary": "table",
    "motif": "package",
    "note": "Kilerin yeni düzeni.",
    "index": 67
  },
  {
    "id": "autumn-craft",
    "name": "Sonbahar · Renkli bir atölye",
    "season": "autumn",
    "sector": "books",
    "title": "Bir fikir, pek çok ihtimal.",
    "description": "Kâğıtlar, boyalar ve üretmek için açtığın masaya küçük dokunuşlar.",
    "productsTitle": "Atölyeni kur.",
    "layout": "editorial",
    "family": "notebook",
    "secondary": "editorial",
    "motif": "palette",
    "note": "Atölyeni kur.",
    "index": 68
  },
  {
    "id": "desk-reset",
    "name": "Sonbahar · Masanı yeniden kur",
    "season": "autumn",
    "sector": "home",
    "title": "Güne düzenli bir yerden başla.",
    "description": "Masa üstündeki küçük parçaları kendi çalışma ritmine göre seç.",
    "productsTitle": "Masana alan aç.",
    "layout": "guide",
    "family": "studio",
    "secondary": "notebook",
    "motif": "notebook",
    "note": "Masana alan aç.",
    "index": 69
  },
  {
    "id": "winter-knitting",
    "name": "Kış · İlmek ilmek",
    "season": "winter",
    "sector": "books",
    "title": "Sıcacık bir fikre başla.",
    "description": "İplikler ve örgü araçlarıyla kendi rengini, kendi dokunu seç.",
    "productsTitle": "İlk ilmeğin yardımcıları.",
    "layout": "guide",
    "family": "letter",
    "secondary": "notebook",
    "motif": "scissors",
    "note": "İlk ilmeğin yardımcıları.",
    "index": 70
  },
  {
    "id": "snow-route",
    "name": "Kış · Kar rotası",
    "season": "winter",
    "sector": "sports",
    "title": "Yeni bir iz bırak.",
    "description": "Karlı günlere eşlik edecek giyim ve ekipman seçkisini keşfet.",
    "productsTitle": "Kar yolunun parçaları.",
    "layout": "collection",
    "family": "trail",
    "secondary": "postcard",
    "motif": "mountain",
    "note": "Kar yolunun parçaları.",
    "index": 71
  },
  {
    "id": "movie-evening",
    "name": "Kış · Evde sinema akşamı",
    "season": "winter",
    "sector": "electronics",
    "title": "Bu akşamın planı belli.",
    "description": "Görüntü, ses ve rahat bir köşeyle sevdiğin hikâyeye yer aç.",
    "productsTitle": "Sinema köşeni tamamla.",
    "layout": "editorial",
    "family": "studio",
    "secondary": "record",
    "motif": "tv",
    "note": "Sinema köşeni tamamla.",
    "index": 72
  },
  {
    "id": "tea-ritual",
    "name": "Kış · Demli bir sohbet",
    "season": "winter",
    "sector": "grocery",
    "title": "Bir çay daha koyalım.",
    "description": "Demleme ve sunum için seçilmiş parçalarla molana kendi dokunu kat.",
    "productsTitle": "Çay saatine davetlisin.",
    "layout": "editorial",
    "family": "ritual",
    "secondary": "table",
    "motif": "coffee",
    "note": "Çay saatine davetlisin.",
    "index": 73
  },
  {
    "id": "school-lunch",
    "name": "Okul · Beslenme çantası",
    "season": "autumn",
    "sector": "kids",
    "title": "Küçük molalara hazırlan.",
    "description": "Beslenme kutuları, mataralar ve günlük okul düzeni için parçalar.",
    "productsTitle": "Molaya eşlik edenler.",
    "layout": "guide",
    "family": "parcel",
    "secondary": "notebook",
    "motif": "sandwich",
    "note": "Molaya eşlik edenler.",
    "index": 74
  },
  {
    "id": "school-art",
    "name": "Okul · Resim ve üretim",
    "season": "autumn",
    "sector": "kids",
    "title": "Hayalini kâğıda taşı.",
    "description": "Renkler, kâğıtlar ve üretmeye alan açan okul malzemeleri.",
    "productsTitle": "Renkli başlangıçlar.",
    "layout": "collection",
    "family": "notebook",
    "secondary": "confetti",
    "motif": "pencil",
    "note": "Renkli başlangıçlar.",
    "index": 75
  },
  {
    "id": "preschool-first",
    "name": "Okul · İlk küçük adımlar",
    "season": "autumn",
    "sector": "kids",
    "title": "Yeni bir dünyaya merhaba.",
    "description": "İlk okul günlerine uygun çanta, oyun ve düzen araçlarını keşfet.",
    "productsTitle": "İlk günün küçük hazırlıkları.",
    "layout": "guide",
    "family": "confetti",
    "secondary": "parcel",
    "motif": "backpack",
    "note": "İlk günün küçük hazırlıkları.",
    "index": 76
  },
  {
    "id": "exam-focus",
    "name": "Sınav dönemi · Kendi ritmini bul",
    "season": "spring",
    "sector": "books",
    "title": "Bir sayfa, bir adım.",
    "description": "Çalışma düzenine eşlik edecek masa araçları ve kırtasiye seçkisi.",
    "productsTitle": "Odaklandığın köşenin parçaları.",
    "layout": "guide",
    "family": "notebook",
    "secondary": "studio",
    "motif": "timer",
    "note": "Odaklandığın köşenin parçaları.",
    "index": 77
  },
  {
    "id": "ramadan-sharing",
    "name": "Ramazan · Paylaşmanın inceliği",
    "season": "special",
    "sector": "grocery",
    "title": "Birlikte güzel olan şeyler.",
    "description": "Özenli sunumlar ve düşünülmüş küçük ziyaret hediyeleriyle buluşmalara hazırlan.",
    "productsTitle": "Paylaşmaya eşlik edenler.",
    "layout": "gift",
    "family": "arch",
    "secondary": "parcel",
    "motif": "heart-handshake",
    "note": "Paylaşmaya eşlik edenler.",
    "index": 78
  },
  {
    "id": "ramadan-sahur",
    "name": "Ramazan · Sahur sofrası",
    "season": "special",
    "sector": "grocery",
    "title": "Sakin bir sofraya yer aç.",
    "description": "Küçük sunum kapları ve mutfak araçlarıyla kendi sofranı düzenle.",
    "productsTitle": "Sahur hazırlığının detayları.",
    "layout": "guide",
    "family": "table",
    "secondary": "arch",
    "motif": "moon",
    "note": "Sahur hazırlığının detayları.",
    "index": 79
  },
  {
    "id": "ramadan-coffee",
    "name": "Ramazan · İftar sonrası kahve",
    "season": "special",
    "sector": "grocery",
    "title": "Sohbete küçük bir mola.",
    "description": "Kahve hazırlığı ve sunumunda kullanacağın parçaları bir araya getir.",
    "productsTitle": "Kahve sohbetinin parçaları.",
    "layout": "editorial",
    "family": "record",
    "secondary": "arch",
    "motif": "coffee",
    "note": "Kahve sohbetinin parçaları.",
    "index": 80
  },
  {
    "id": "eid-visit",
    "name": "Bayram · Ziyaret çantası",
    "season": "special",
    "sector": "fashion",
    "title": "Güzel bir ziyarete hazırlan.",
    "description": "Günlük aksesuarlar ve küçük hediyelerle bayram buluşmalarına eşlik et.",
    "productsTitle": "Bayram yolunun detayları.",
    "layout": "gift",
    "family": "parcel",
    "secondary": "editorial",
    "motif": "handbag",
    "note": "Bayram yolunun detayları.",
    "index": 81
  },
  {
    "id": "eid-table-detail",
    "name": "Bayram · Sofranın zarafeti",
    "season": "special",
    "sector": "home",
    "title": "Buluşmanın güzel detayları.",
    "description": "Peçeteler, sunum tabakları ve sofrayı tamamlayan küçük dokunuşlar.",
    "productsTitle": "Bayram sofranı tamamla.",
    "layout": "editorial",
    "family": "table",
    "secondary": "letter",
    "motif": "utensils",
    "note": "Bayram sofranı tamamla.",
    "index": 82
  },
  {
    "id": "lighting-corners",
    "name": "Aydınlatma · Evin ışığını seç",
    "season": "all",
    "sector": "home",
    "title": "Her köşeye başka bir ışık.",
    "description": "Masa lambalarından küçük aydınlatmalara, yaşam alanına uygun parçalar.",
    "productsTitle": "Işığınla tamamla.",
    "layout": "editorial",
    "family": "window",
    "secondary": "studio",
    "motif": "lamp-desk",
    "note": "Işığınla tamamla.",
    "index": 83
  },
  {
    "id": "entryway-order",
    "name": "Antre · Eve ilk adım",
    "season": "all",
    "sector": "home",
    "title": "Eve girişin rahat hali.",
    "description": "Askılar, anahtarlıklar ve giriş alanını düzenleyen kullanışlı parçalar.",
    "productsTitle": "Antreyi birlikte düzenleyelim.",
    "layout": "guide",
    "family": "notebook",
    "secondary": "window",
    "motif": "door-open",
    "note": "Antreyi birlikte düzenleyelim.",
    "index": 84
  },
  {
    "id": "small-space",
    "name": "Küçük ev · Akıllı yerleşim",
    "season": "all",
    "sector": "home",
    "title": "Az alanda sana daha çok yer.",
    "description": "Katlanan, yer kazandıran ve birden fazla işe eşlik eden parçalar.",
    "productsTitle": "Alanına uygun seçimler.",
    "layout": "guide",
    "family": "window",
    "secondary": "editorial",
    "motif": "layout-grid",
    "note": "Alanına uygun seçimler.",
    "index": 85
  },
  {
    "id": "kitchen-order",
    "name": "Mutfak · Her şey elinin altında",
    "season": "all",
    "sector": "home",
    "title": "Mutfakta düzeni kendin kur.",
    "description": "Çekmeceler, raflar ve tezgâh için günlük işleri kolaylaştıran seçkiler.",
    "productsTitle": "Mutfak düzeninin parçaları.",
    "layout": "guide",
    "family": "notebook",
    "secondary": "table",
    "motif": "cooking-pot",
    "note": "Mutfak düzeninin parçaları.",
    "index": 86
  },
  {
    "id": "bedroom-textures",
    "name": "Yatak odası · Yumuşak bir geçiş",
    "season": "all",
    "sector": "home",
    "title": "Günün sonunda kendi köşen.",
    "description": "Nevresimler, örtüler ve yumuşak dokularla odanın havasını tamamla.",
    "productsTitle": "Yatak odanın yeni dokuları.",
    "layout": "editorial",
    "family": "window",
    "secondary": "letter",
    "motif": "bed-double",
    "note": "Yatak odanın yeni dokuları.",
    "index": 87
  },
  {
    "id": "bathroom-ritual",
    "name": "Banyo · Küçük düzenler",
    "season": "all",
    "sector": "home",
    "title": "Güne sade bir başlangıç.",
    "description": "Havlu, saklama ve banyo aksesuarlarını kendi ihtiyacına göre seç.",
    "productsTitle": "Banyonun sakin detayları.",
    "layout": "guide",
    "family": "ritual",
    "secondary": "window",
    "motif": "bath",
    "note": "Banyonun sakin detayları.",
    "index": 88
  },
  {
    "id": "home-training",
    "name": "Spor · Evde kendi alanın",
    "season": "all",
    "sector": "sports",
    "title": "Hareketine yer aç.",
    "description": "Evde kullanıma uygun ekipmanları alanına ve antrenmanına göre incele.",
    "productsTitle": "Kendi spor köşeni kur.",
    "layout": "guide",
    "family": "studio",
    "secondary": "trail",
    "motif": "dumbbell",
    "note": "Kendi spor köşeni kur.",
    "index": 89
  },
  {
    "id": "yoga-pause",
    "name": "Yoga · Kendine bir aralık",
    "season": "all",
    "sector": "sports",
    "title": "Günün içine küçük bir alan aç.",
    "description": "Matlar ve destek araçlarıyla kendi pratik alanını tamamla.",
    "productsTitle": "Pratiğine eşlik edenler.",
    "layout": "editorial",
    "family": "ritual",
    "secondary": "trail",
    "motif": "activity",
    "note": "Pratiğine eşlik edenler.",
    "index": 90
  },
  {
    "id": "running-morning",
    "name": "Koşu · Sabahın ilk rotası",
    "season": "spring",
    "sector": "sports",
    "title": "İlk adımı kendin için at.",
    "description": "Ayakkabı, çanta ve günlük koşuya eşlik eden parçaları keşfet.",
    "productsTitle": "Koşu rotanın yardımcıları.",
    "layout": "collection",
    "family": "trail",
    "secondary": "record",
    "motif": "footprints",
    "note": "Koşu rotanın yardımcıları.",
    "index": 91
  },
  {
    "id": "audio-world",
    "name": "Ses · Müziğin kendine ait hali",
    "season": "all",
    "sector": "electronics",
    "title": "Dinlediğin dünyaya yaklaş.",
    "description": "Kulaklıklar, hoparlörler ve ses deneyimine eşlik eden aksesuarlar.",
    "productsTitle": "Kendi ses alanını kur.",
    "layout": "collection",
    "family": "record",
    "secondary": "studio",
    "motif": "headphones",
    "note": "Kendi ses alanını kur.",
    "index": 92
  },
  {
    "id": "creator-desk",
    "name": "Üretici · Fikrini kayda al",
    "season": "all",
    "sector": "electronics",
    "title": "Aklındakini paylaşmaya başla.",
    "description": "Kayıt, ışık ve masa araçlarıyla kendi üretim alanını düzenle.",
    "productsTitle": "Üretim masanın parçaları.",
    "layout": "launch",
    "family": "studio",
    "secondary": "notebook",
    "motif": "mic",
    "note": "Üretim masanın parçaları.",
    "index": 93
  },
  {
    "id": "smart-home",
    "name": "Teknoloji · Evin küçük yardımcıları",
    "season": "all",
    "sector": "electronics",
    "title": "Günlük hayatına uyum sağlasın.",
    "description": "Bağlantılı cihazları özellikleri ve kullanım alanlarıyla birlikte incele.",
    "productsTitle": "Evin için teknoloji seçkisi.",
    "layout": "guide",
    "family": "studio",
    "secondary": "window",
    "motif": "house",
    "note": "Evin için teknoloji seçkisi.",
    "index": 94
  },
  {
    "id": "remote-work",
    "name": "Çalışma · Her yerde kendi masan",
    "season": "all",
    "sector": "electronics",
    "title": "Çalışma alanını yanında taşı.",
    "description": "Taşınabilir ve masa üstü aksesuarlarıyla günlük çalışma düzenini kur.",
    "productsTitle": "İş gününe eşlik edenler.",
    "layout": "guide",
    "family": "notebook",
    "secondary": "studio",
    "motif": "laptop",
    "note": "İş gününe eşlik edenler.",
    "index": 95
  },
  {
    "id": "skin-routine",
    "name": "Bakım · Kendi küçük rutinin",
    "season": "all",
    "sector": "beauty",
    "title": "Kendine ayırdığın birkaç dakika.",
    "description": "Bakım araçlarını ve günlük kullanıma uygun ürünleri yakından incele.",
    "productsTitle": "Rutinini kendin seç.",
    "layout": "guide",
    "family": "ritual",
    "secondary": "letter",
    "motif": "droplets",
    "note": "Rutinini kendin seç.",
    "index": 96
  },
  {
    "id": "beauty-travel-kit",
    "name": "Bakım · Çantaya sığan düzen",
    "season": "summer",
    "sector": "beauty",
    "title": "Küçük çantada kendi rutinin.",
    "description": "Taşınabilir kutular ve bakım aksesuarlarıyla yolculuk hazırlığını tamamla.",
    "productsTitle": "Bakım çantanı kur.",
    "layout": "collection",
    "family": "parcel",
    "secondary": "ritual",
    "motif": "gift",
    "note": "Bakım çantanı kur.",
    "index": 97
  },
  {
    "id": "cat-corner",
    "name": "Kediler · Onlara ait bir köşe",
    "season": "all",
    "sector": "pets",
    "title": "Küçük patilere büyük bir yer.",
    "description": "Oyun, dinlenme ve günlük bakım için kedine uygun parçaları keşfet.",
    "productsTitle": "Kedinin küçük dünyası.",
    "layout": "guide",
    "family": "window",
    "secondary": "botanical",
    "motif": "cat",
    "note": "Kedinin küçük dünyası.",
    "index": 98
  },
  {
    "id": "dog-walk",
    "name": "Köpekler · Birlikte dışarı",
    "season": "all",
    "sector": "pets",
    "title": "Gezintinin güzel hazırlıkları.",
    "description": "Tasma, taşıma ve oyun aksesuarlarıyla birlikte çıktığınız rotaya hazırlan.",
    "productsTitle": "Gezintiye eşlik edenler.",
    "layout": "guide",
    "family": "trail",
    "secondary": "parcel",
    "motif": "dog",
    "note": "Gezintiye eşlik edenler.",
    "index": 99
  },
  {
    "id": "build-play",
    "name": "Oyun · Parça parça hayal kur",
    "season": "all",
    "sector": "kids",
    "title": "Birleştir, boz, yeniden kur.",
    "description": "Yapı oyuncaklarını ve üretmeye açık oyunları birlikte keşfet.",
    "productsTitle": "Hayale yeni parçalar.",
    "layout": "collection",
    "family": "confetti",
    "secondary": "notebook",
    "motif": "blocks",
    "note": "Hayale yeni parçalar.",
    "index": 100
  },
  {
    "id": "garden-play",
    "name": "Oyun · Bahçeye taşın",
    "season": "summer",
    "sector": "kids",
    "title": "Oyunun yeri bu kez dışarısı.",
    "description": "Açık hava oyunlarını yaş ve kullanım bilgileriyle birlikte incele.",
    "productsTitle": "Dışarıda oyun zamanı.",
    "layout": "collection",
    "family": "coast",
    "secondary": "trail",
    "motif": "puzzle",
    "note": "Dışarıda oyun zamanı.",
    "index": 101
  },
  {
    "id": "artisan-shelf",
    "name": "Zanaat · Emekle biçimlenen",
    "season": "commerce",
    "sector": "home",
    "title": "Her parçanın bir hikâyesi var.",
    "description": "El emeği ürünleri, malzemeleri ve üretici ayrıntılarıyla yakından tanı.",
    "productsTitle": "Üreten ellerin seçkisi.",
    "layout": "editorial",
    "family": "editorial",
    "secondary": "letter",
    "motif": "paintbrush",
    "note": "Üreten ellerin seçkisi.",
    "index": 102
  },
  {
    "id": "neighborhood-picks",
    "name": "Yerel seçki · Yakından keşfet",
    "season": "commerce",
    "sector": "all",
    "title": "Güzel seçimler yakından başlar.",
    "description": "Mağazanın özenle bir araya getirdiği günlük yaşam parçalarını keşfet.",
    "productsTitle": "Yakındaki güzel fikirler.",
    "layout": "collection",
    "family": "ticket",
    "secondary": "postcard",
    "motif": "store",
    "note": "Yakındaki güzel fikirler.",
    "index": 103
  },
  {
    "id": "reading-notes",
    "name": "Kitap · Kenara bir not düş",
    "season": "all",
    "sector": "books",
    "title": "Okuduğun hikâyeye eşlik et.",
    "description": "Defterler, ayraçlar ve okuma düzenini tamamlayan küçük araçlar.",
    "productsTitle": "Bir sayfa daha için.",
    "layout": "guide",
    "family": "editorial",
    "secondary": "notebook",
    "motif": "book-marked",
    "note": "Bir sayfa daha için.",
    "index": 104
  },
  {
    "id": "ceramic-table",
    "name": "Seramik · Sofrada karakter",
    "season": "all",
    "sector": "home",
    "title": "Dokusu olan bir sofra kur.",
    "description": "Farklı formları ve günlük kullanıma eşlik eden seramik parçaları incele.",
    "productsTitle": "Sofranın seramik seçkisi.",
    "layout": "editorial",
    "family": "table",
    "secondary": "record",
    "motif": "cup-soda",
    "note": "Sofranın seramik seçkisi.",
    "index": 105
  },
  {
    "id": "jewelry-details",
    "name": "Takı · Küçük bir imza",
    "season": "all",
    "sector": "fashion",
    "title": "Stilinin ince detayları.",
    "description": "Küpe, kolye ve günlük aksesuarları kendi stiline göre bir araya getir.",
    "productsTitle": "Kendi imzanı seç.",
    "layout": "editorial",
    "family": "letter",
    "secondary": "parcel",
    "motif": "gem",
    "note": "Kendi imzanı seç.",
    "index": 106
  },
  {
    "id": "breakfast-weekend",
    "name": "Kahvaltı · Güne birlikte başla",
    "season": "all",
    "sector": "grocery",
    "title": "Sofrada biraz daha kalalım.",
    "description": "Kahvaltı hazırlığı ve sunumunda kullanacağın parçaları keşfet.",
    "productsTitle": "Sabah sofrasının detayları.",
    "layout": "editorial",
    "family": "table",
    "secondary": "postcard",
    "motif": "utensils",
    "note": "Sabah sofrasının detayları.",
    "index": 107
  }
];

const sectionTypes = {
  editorial: ['editorial', 'products', 'text'],
  guide: ['banner', 'products', 'faq'],
  collection: ['banner', 'products', 'categories'],
  gift: ['hero', 'products', 'text', 'faq'],
  launch: ['hero', 'text', 'products', 'faq'],
  event: ['announcement', 'banner', 'products', 'text'],
};
const sectorCategories = {
  electronics: 'electronics', fashion: 'fashion', home: 'home-living',
  beauty: 'beauty', sports: 'sports-outdoor', kids: 'kids-toys',
};
const familyLayouts = {
  arch:'poster', parcel:'collage', coast:'split', window:'showcase',
  notebook:'split', confetti:'poster', letter:'editorial', record:'showcase',
  editorial:'editorial', botanical:'collage', trail:'split', postcard:'collage',
  ritual:'showcase', table:'editorial', studio:'showcase', ticket:'ribbon',
};
const photoPath = id => `/media/campaigns-20260915/${id}.webp`;
const palette = {background:'#fffaf3', text:'#182b3a', accent:'#9d3b16', surface:'#ffe4cd'};

export const EXPANSION_CAMPAIGN_PACKS = CAMPAIGN_EXPANSION.map(record => ({
  id:record.id, name:record.name, occasion:record.name.split(' · ')[0],
  season:record.season, sector:record.sector, title:record.title,
  description:record.description, editorialText:record.description,
  productsTitle:record.productsTitle, layout:record.layout,
  rule:{kind:'manual', label:/^(ramadan|eid)/.test(record.id)
    ? 'Seçilen yılın dini takvimini doğrulayarak yayın aralığını belirle.'
    : /^(school|preschool|exam)/.test(record.id)
      ? 'Yerel eğitim takvimini doğrulayarak yayın aralığını belirle.'
      : 'Mağazanın seçkisine ve yerel sezona uygun yayın aralığını belirle.'},
  categoryId:sectorCategories[record.sector] || '', image:photoPath(record.id),
  colors:{background:palette.background,text:palette.text,accent:palette.accent},
  channels:['web','android'], types:[...sectionTypes[record.layout]],
  blockCount:sectionTypes[record.layout].length,
}));

export const EXPANSION_CAMPAIGN_COPY = Object.fromEntries(
  CAMPAIGN_EXPANSION.map(record => [record.id,[record.description,record.productsTitle]])
);

export function createExpansionArtDirections(families) {
  return Object.fromEntries(CAMPAIGN_EXPANSION.map(record => {
    const shift=(record.index%7)*.4, leftPhoto=record.index%2===1;
    return [record.id, {
      id:record.id, family:record.family,
      familyLabel:families.find(family=>family.id===record.family)?.label || 'Nova Store seçkisi',
      layout:familyLayouts[record.family], secondary:record.secondary,
      photo:leftPhoto?[7+shift,10,37-shift,78]:[55+shift,10,38-shift,78],
      copy:leftPhoto?[52,18,40,69]:[7,18,42,69], fontSize:48+(record.index%6),
      motif:record.motif, note:record.note,
      aspectRatio:2.08+(record.index%6)*.02,
      mobile:{photo:[10+shift,52,80-shift*2,40],copy:[10,9,80,37],aspectRatio:.79+(record.index%5)*.01},
      palette:{...palette}, index:record.index,
      image:photoPath(record.id), stageImage:photoPath(record.id),
    }];
  }));
}
