import {EXPANSION_CAMPAIGN_COPY} from './campaignExpansion.js';
// Customer-facing copy stays separate from planning instructions and commerce rules.
export const CAMPAIGN_COPY={
 ramadan:['Sıcak ışıklar, özenli sofralar ve birlikte geçen akşamlar.','Sofraya davetlisin.'],
 eid:['Bir ziyaret, küçük bir hediye, kocaman bir sevinç.','Bayrama eşlik edenler.'],
 summer:['Hafif bir çanta, uzun günler ve aklında yeni bir rota.','Yazı yanında taşı.'],
 winter:['Yumuşak dokular ve evde kalmayı sevdiren küçük detaylar.','Sıcak bir köşe kur.'],
 school:['Küçük hazırlıklarla yeni döneme kendi ritminde başla.','Yeni dönemin yol arkadaşları.'],
 'new-year':['Yeni başlangıçlara, paylaşılan anlara ve güzel dileklere.','Yeni yıla küçük bir armağan.'],
 'special-day':['Onu düşündüğünü anlatan, özenle seçilmiş küçük detaylar.','Bir gülümseme için.'],
 weekend:['Müziğini aç, kitabını al. Bu küçük mola senin.','Molaya eşlik edenler.'],
 'spring-refresh':['Perdeleri aç. Yeni mevsimi evinin her köşesine taşı.','Evin hafiflesin.'],
 'spring-garden':['Balkonda bir saksıyla başlar. Yeşile biraz daha yer aç.','Kendi bahçeni kur.'],
 'spring-walk':['Şehrin dışına, parkın içine, yeni bir patikaya.','Adımlarına eşlik edenler.'],
 'spring-wardrobe':['Hafif katmanlar ve gün boyu sana eşlik eden doğal tonlar.','Mevsimin yeni parçaları.'],
 'summer-travel':['Valizinde ihtiyacın olanlar, aklında keşfedilecek yerler.','Yolculuk çantan hazır mı?'],
 'summer-beach':['Kumun sıcağı, denizin sesi ve sahile yakışan hafif parçalar.','Sahil çantanın içindekiler.'],
 'summer-care':['Günlük bakımına, yazın ritmine uyan küçük dokunuşlar.','Kendi bakım rutinini kur.'],
 'summer-table':['Bir gölge bul, sofrayı kur. Yazın tadı birlikte güzel.','Sofranı açık havaya taşı.'],
 'autumn-home':['Mevsimin sıcak tonlarıyla yaşam alanına yeniden yerleş.','Dokusu güzel seçimler.'],
 'autumn-rain':['Yağmurlu sabahlara ve serinleyen günlere eşlik eden parçalar.','Sonbahara hazırlan.'],
 'autumn-reading':['Sakin bir köşe, sevdiğin bir fincan ve henüz bitmemiş bir hikâye.','Okuma köşenin parçaları.'],
 'autumn-coffee':['Sevdiğin fincanda, tam kendi ritminde bir kahve molası.','Demlemeye başla.'],
 'winter-prep':['Serin sabahları yumuşatan dokular, gününü ısıtan detaylar.','Kışın küçük ihtiyaçları.'],
 'winter-outdoor':['Soğuk havanın içinde yeni bir yol, yeni bir manzara.','Rotana hazırlan.'],
 'winter-gaming':['Oyuna, müziğe ve birlikte geçen uzun akşamlara yer aç.','Kendi oyun alanını kur.'],
 'winter-hobbies':['Bir ilmek, bir çizgi, yeni bir fikir. Kendi ellerinle başla.','Üretmenin küçük araçları.'],
 'school-bag':['Defterler, kalemler ve yeni hikâyelere hazır bir çanta.','Çantanı birlikte hazırlayalım.'],
 'school-desk':['Işığı, düzeni ve sana iyi gelen detayları bir araya getir.','Çalışma köşeni tamamla.'],
 'university-tech':['Dersten kütüphaneye, projelerinden günlük hayatına.','Kampüse eşlik eden teknoloji.'],
 'semester-break':['Biraz oyun, biraz merak, birlikte üretilecek yepyeni şeyler.','Tatile küçük fikirler.'],
 'ramadan-table':['Özenli bir sunum, tanıdık lezzetler ve aynı sofrada buluşanlar.','Sofranın güzel detayları.'],
 'ramadan-home':['Fenerlerin sıcak ışığında, sevdiklerine yer aç.','Misafirliğe hazır bir ev.'],
 'eid-gifts':['Özenle sarılmış küçük bir hediye, paylaşılan büyük bir mutluluk.','Hediye seçkisini keşfet.'],
 'eid-style':['Bayram sabahına yakışan zarif dokular ve hafif tonlar.','Kendi bayram kombinini bul.'],
 'sacrifice-feast':['Kapısı açık evler, tazelenen kahveler ve uzayan sohbetler.','Birlikte olmanın detayları.'],
 'mothers-day':['Sevdiği renkten, hobisinden, birlikte geçirdiğiniz bir andan ilham al.','Ona göre bir hediye.'],
 'fathers-day':['Birlikte paylaştığınız hobilerden, her gün sevdiği küçük şeylere.','Onun dünyasına bir armağan.'],
 valentines:['Küçük bir jest, birlikte içilen bir kahve, size ait bir an.','İkinize de iyi gelsin.'],
 'womens-day':['Fikre, ustalığa ve ellerin ortaya çıkardığı güzelliğe.','Üretimden ilham al.'],
 'childrens-day':['Renklerle oyna, yeni dünyalar kur. Bugün hayal etmenin günü.','Küçük keşiflere büyük alan.'],
 'youth-day':['Bir top, bir yol, yepyeni bir hedef. Hareketin ritmine katıl.','Yeni hedeflerine doğru.'],
 'teachers-day':['Bir düşünceyle başlayan, özenle seçilmiş bir teşekkür.','İlham verenlere bir armağan.'],
 'republic-day':['Umudu, emeği ve ortak yarınlarımızı birlikte kutluyoruz.','Cumhuriyet Bayramımız kutlu olsun.'],
 'family-time':['Masanın etrafına toplanın. Oyunun en güzel yanı birlikte olmak.','Herkese bir oyun var.'],
 'pet-care':['Onun oyununa, dinlenmesine ve evdeki küçük dünyasına.','Küçük dostuna göre seç.'],
 'new-home':['Bir anahtar, boş bir oda ve sana ait olacak yeni bir dünya.','İlk parçalarla başla.'],
 'wedding-season':['Birlikte kuracağınız evin, yıllarca paylaşacağınız küçük detayları.','Yeni hayatına eşlik etsin.'],
 'baby-arrival':['Yumuşacık dokular, küçük hazırlıklar ve heyecanlı bir bekleyiş.','İlk günlere hazırlan.'],
 'black-friday':['İhtiyacına uyan parçaları keşfet, kendi seçkini oluştur.','Kasım seçkisine yakından bak.'],
 'cyber-monday':['Günlük hayatına eşlik eden teknolojiyle kendi alanını yenile.','Dijital dünyanı tamamla.'],
 'november-eleven':['Aradığın parçaları bir araya getirmenin zamanı.','Sana uygun seçimi bul.'],
 'year-end':['Geride kalan güzel anılara, önümüzdeki yeni başlangıçlara.','Yıla küçük bir veda.'],
 'new-collection':['Yeni dokular, yeni çizgiler. Kendi stilinle yeniden tanış.','Koleksiyonun ilk parçaları.'],
 'product-launch':['Tasarımına, ayrıntılarına ve günlük hayatındaki yerine yakından bak.','Yeni bir keşfe hazır ol.'],
 'store-anniversary':['Birlikte büyüyen hikâyemizde, yeni bir sayfa açıyoruz.','İyi ki birlikteyiz.'],
 'weekend-discovery':['Sana iyi gelen bir rota ve yanına almak isteyeceğin küçük şeyler.','Hafta sonu seçkin.'],
 'last-chance':['Kendi stiline ve ihtiyacına uyan parçaları yeniden keşfet.','Seçkideki son dokunuşlar.'],
 'gift-guide':['Hobisine, sevdiği renge, küçük alışkanlıklarına göre düşün.','Onu anlatan hediyeyi bul.'],
 ...EXPANSION_CAMPAIGN_COPY
};
