import {useEffect,useState} from 'react';
import {ArrowRight,ArrowUpRight,Check,Compass,Leaf,Plus,Sparkles} from 'lucide-react';
import {targetHref} from './store.js';
import {SectorProductCardV6,v6Money,v6ProductGroup,v6ProductHref,v6ProductImage,v6Specs} from './SectorProductCardV6.jsx';

export const V6_FAMILIES=['beauty','sport','kids'];
const signature=products=>products.map(product=>product.id).join('|');
const categoryHref=category=>`#/kategori/${category.canonicalPath||category.path||category.slug}`;
const byCategory=(products,category)=>products.filter(product=>String(product.categoryId)===String(category.id)||product.categoryIds?.map(String).includes(String(category.id)));
function Copy({block,headingTag:Tag='h2'}){return <div className="v6-showcase-copy">{block.kicker&&<span className="v6-eyebrow">{block.kicker}</span>}{block.title&&<Tag>{String(block.title).split('\n').map((line,index)=><span key={index}>{index>0&&<br/>}{line}</span>)}</Tag>}{block.description&&<p>{block.description}</p>}</div>;}
function Actions({block,document}){if(!block.buttonText&&!block.secondaryText)return null;return <div className="v6-showcase-actions">{block.buttonText&&<a className="v6-action" href={targetHref(block.target,document)}>{block.buttonText}<ArrowUpRight size={19}/></a>}{block.secondaryText&&<a className="v6-secondary-action" href={targetHref(block.secondaryTarget,document)}>{block.secondaryText}<ArrowRight size={17}/></a>}</div>;}
function Cover({block,fallback,priority=false}){const source=block.image||fallback;return source?<picture><source media="(max-width:620px)" srcSet={block.mobileImage||source}/><img src={source} alt={block.alt||''} loading={priority?'eager':'lazy'} fetchPriority={priority?'high':'auto'}/></picture>:null;}
function ProductLink({product,family,number}){return <a className={`v6-linked-product v6-linked-product--${family}`} href={v6ProductHref(product)}>{number!==undefined&&<span className="v6-linked-number">{String(number+1).padStart(2,'0')}</span>}<img src={v6ProductImage(product)} alt="" loading="lazy"/><span><small>{v6ProductGroup(product,family)}</small><strong>{product.name}</strong><b>{v6Money(product.price)}</b></span><ArrowUpRight size={17}/></a>;}
function GroupTabs({family,products,selected,onSelect,label}){const groups=[...new Set(products.map(product=>v6ProductGroup(product,family)))];return groups.length>1?<div className={`v6-group-tabs v6-group-tabs--${family}`} role="group" aria-label={label||'Ürün seçkisini filtrele'}>{['all',...groups].map(group=><button type="button" key={group} aria-pressed={selected===group} onClick={()=>onSelect(group)}><span>{group==='all'?'Tümü':group}</span><small>{group==='all'?products.length:products.filter(product=>v6ProductGroup(product,family)===group).length}</small></button>)}</div>:null;}
function filteredProducts(products,family,group){return group==='all'?products:products.filter(product=>v6ProductGroup(product,family)===group);}

function BeautyRoutine({products,onAdd}){
  const items=products.filter(product=>Number(product.stock)>0&&!product.variants?.length).slice(0,4);
  const [selected,setSelected]=useState(()=>items.slice(0,2).map(product=>product.id));
  const [busy,setBusy]=useState(false),[notice,setNotice]=useState('');
  useEffect(()=>{setSelected(items.slice(0,2).map(product=>product.id));setNotice('');},[signature(items)]);
  const chosen=items.filter(product=>selected.includes(product.id));
  async function add(){if(busy||!chosen.length||typeof onAdd!=='function')return;setBusy(true);setNotice('');let added=0;try{for(const product of chosen){if(await onAdd(product.id,1)===false)break;added++;}setNotice(added===chosen.length?`${added} ürün sepete eklendi.`:`${added} ürün eklendi. Kalan ürünlerin stok durumunu kontrol et.`);}catch{setNotice(`${added} ürün eklendi. İşlem tamamlanamadı; sepetini kontrol et.`);}finally{setBusy(false);}}
  if(!items.length)return <p className="v6-empty">Bu seçkide henüz gösterilecek ürün yok.</p>;
  return <div className="v6-routine-builder"><div className="v6-routine-items">{items.map((product,index)=><div key={product.id} className={`v6-routine-item${selected.includes(product.id)?' is-selected':''}`}><label><input type="checkbox" checked={selected.includes(product.id)} disabled={busy} onChange={event=>{setSelected(ids=>event.target.checked?[...ids,product.id]:ids.filter(id=>id!==product.id));setNotice('');}}/><span className="v6-routine-check" aria-hidden="true">{selected.includes(product.id)?<Check size={14}/>:<Plus size={14}/>}</span><span className="v6-routine-number">SEÇKİ / {String(index+1).padStart(2,'0')}</span><img src={v6ProductImage(product)} alt="" loading="lazy"/><small>{v6ProductGroup(product,'beauty')}</small><strong>{product.name}</strong><b>{v6Money(product.price)}</b></label><a href={v6ProductHref(product)} aria-label={`${product.name} detayını incele`}><ArrowUpRight size={17}/></a></div>)}</div><div className="v6-routine-summary"><div><span>{chosen.length} seçili ürün</span><strong>{v6Money(chosen.reduce((sum,product)=>sum+Number(product.price||0),0))}</strong></div><p>İhtiyacın olan parçaları seç.<br/>Her ürünü ayrıca inceleyebilirsin.</p><button type="button" onClick={add} disabled={busy||!chosen.length||typeof onAdd!=='function'}>{busy?'Ekleniyor…':'Seçkimi sepete ekle'}<Plus size={18}/></button></div><p className="v6-operation-status" role="status">{notice}</p></div>;
}

export function V6Hero({family,block,document,products=[],headingTag='h1',priority=false}){
  const [group,setGroup]=useState('all');
  useEffect(()=>setGroup('all'),[family,block.id,signature(products)]);
  const selected=filteredProducts(products,family,group),first=products[0];
  const copy=<><Copy {...{block,headingTag}}/><Actions {...{block,document}}/></>;
  if(family==='beauty')return <div className="shell v6-showcase v6-showcase--beauty"><div className="v6-beauty-intro">{copy}<div className="v6-beauty-route-label"><span className="v6-line"/><Leaf size={17}/><span>Kendine ayırdığın zaman.</span></div></div><div className="v6-beauty-cover"><Cover block={block} fallback={v6ProductImage(first)} priority={priority}/>{products[1]&&<a className="v6-beauty-feature" href={v6ProductHref(products[1])}><img src={v6ProductImage(products[1])} alt=""/><span><small>SEÇKİDEN BİR PARÇA</small><strong>{products[1].name}</strong><b>{v6Money(products[1].price)}</b></span><ArrowUpRight size={19}/></a>}</div><div className="v6-beauty-steps">{products.slice(0,3).map((product,index)=><a href={v6ProductHref(product)} key={product.id}><span>{String(index+1).padStart(2,'0')}</span><div><small>{v6ProductGroup(product,family)}</small><strong>{product.name}</strong></div><ArrowRight size={19}/></a>)}</div></div>;
  if(family==='sport')return <div className="shell v6-showcase v6-showcase--sport"><div className="v6-sport-intro"><span className="v6-sport-compass"><Compass size={34} strokeWidth={1}/><span>AÇIK HAVA<br/>VE HAREKET</span></span>{copy}</div><div className="v6-sport-cover"><Cover block={block} fallback={v6ProductImage(first)} priority={priority}/><a href={targetHref(block.target,document)} className="v6-sport-cover-link"><span>{block.buttonText||'Seçkiyi keşfet'}</span><ArrowUpRight size={24}/></a></div><div className="v6-sport-activity"><div className="v6-sport-activity-heading"><h2>Bugün hangi rota?</h2><span>{selected.length} ürün</span></div><GroupTabs family={family} products={products} selected={group} onSelect={setGroup} label="Aktiviteye göre ürün keşfet"/><div className="v6-sport-activity-products">{selected.slice(0,2).map(product=><ProductLink key={product.id} {...{product,family}}/>)}</div></div></div>;
  return <div className="shell v6-showcase v6-showcase--kids"><div className="v6-kids-hero-photo"><Cover block={block} fallback={v6ProductImage(first)} priority={priority}/><span className="v6-kids-photo-mark" aria-hidden="true"><Sparkles size={26}/></span></div><div className="v6-kids-intro">{copy}<div className="v6-kids-age-finder"><span>Birlikte keşfetmeye başlayın.</span><GroupTabs family={family} products={products} selected={group} onSelect={setGroup} label="Yaş grubuna göre ürün keşfet"/></div></div><div className="v6-kids-featured"><div><span className="v6-eyebrow">{group==='all'?'KEŞİF SEÇKİSİ':group}</span><small>{selected.length} ürün</small></div>{selected.slice(0,2).map((product,index)=><ProductLink key={product.id} {...{product,family}} number={index}/>)}</div></div>;
}

export function V6Categories({family,block={},document,categories=[],products=[]}){
  const hasCopy=block.title||block.kicker||block.description||block.buttonText;
  return <div className={`shell v6-category-section v6-category-section--${family}`}>{hasCopy&&<div className="v6-section-heading"><Copy block={block}/><Actions {...{block,document}}/></div>}<div className={`v6-category-grid v6-category-grid--${family}`}>{categories.map((category,index)=>{const items=byCategory(products,category);const image=category.imageUrl||v6ProductImage(items[0]);const label=family==='kids'?[...new Set(items.map(product=>v6ProductGroup(product,family)))].join(' · '):`${items.length} ürün`;return <a data-visual-category-id={category.id} href={categoryHref(category)} key={category.id}><span className="v6-category-number">{String(index+1).padStart(2,'0')}</span>{image&&<img data-visual-category-part="image" src={image} alt="" loading="lazy"/>}<div><strong data-visual-category-part="text">{category.name}</strong><small>{label}</small></div><ArrowUpRight size={22}/></a>;})}</div></div>;
}

export function V6Collection({family,block,document,products=[],favorites=new Set(),onFavorite,onAdd}){
  const [group,setGroup]=useState('all');
  useEffect(()=>setGroup('all'),[family,block.id,signature(products)]);
  const visible=filteredProducts(products,family,group);
  return <div className={`shell v6-collection v6-collection--${family}`}><div className="v6-section-heading"><Copy block={block}/><Actions {...{block,document}}/></div><GroupTabs {...{family,products}} selected={group} onSelect={setGroup}/><div className={`v6-product-grid v6-product-grid--${family}`} data-product-count={visible.length}>{visible.map(product=><SectorProductCardV6 key={product.id} {...{product,family,onFavorite,onAdd}} favorite={favorites.has(product.id)}/>)}</div>{!visible.length&&<p className="v6-empty">Bu seçkide henüz gösterilecek ürün yok.</p>}</div>;
}

export function V6Story({family,block,document,products=[],onAdd}){
  if(family==='beauty')return <div className="shell v6-story v6-story--beauty"><div className="v6-section-heading"><Copy block={block}/><Actions {...{block,document}}/></div><BeautyRoutine {...{products,onAdd}}/></div>;
  if(family==='sport')return <div className="shell v6-story v6-story--sport"><div className="v6-sport-story-intro"><Copy block={block}/><Actions {...{block,document}}/></div><div className="v6-sport-specification-board">{products.slice(0,3).map((product,index)=><a href={v6ProductHref(product)} key={product.id}><span className="v6-specification-number">{String(index+1).padStart(2,'0')}<ArrowUpRight size={20}/></span><img src={v6ProductImage(product)} alt="" loading="lazy"/><h3>{product.name}</h3><dl>{v6Specs(product).slice(0,3).map(item=><div key={`${item.label}:${item.value}`}><dt>{item.label}</dt><dd>{item.value}</dd></div>)}</dl><strong>{v6Money(product.price)}</strong></a>)}</div></div>;
  return <div className="shell v6-story v6-story--kids"><div className="v6-kids-story-copy"><Sparkles size={30} strokeWidth={1.3}/><Copy block={block}/><Actions {...{block,document}}/></div><div className="v6-kids-learning-grid">{products.slice(0,3).map((product,index)=><a href={v6ProductHref(product)} key={product.id}><span className="v6-learning-number">{String(index+1).padStart(2,'0')}</span><img src={v6ProductImage(product)} alt="" loading="lazy"/><span><small>{product.learningArea||v6ProductGroup(product,'kids')}</small><strong>{product.name}</strong><p>{product.features?.[0]||''}</p></span><ArrowUpRight size={21}/></a>)}</div></div>;
}

export {V6Hero as SectorHeroV6,V6Categories as SectorCategoriesV6,V6Collection as SectorCollectionV6,V6Story as SectorStoryV6};
