import { getSectorCatalog } from './sectorCatalog.js';
// Each preset is a complete presentation contract, independent of customer state.
export const STORE_FAMILIES = ['nova-commerce', 'pocket', 'workspace', 'gallery', 'tech', 'living', 'fashion', 'market', 'beauty', 'sport', 'kids'];
const layouts = (header, category, card, home, product, account, cart, footer, motion) => ({ header, category, card, home, product, account, cart, footer, motion });
const preset = (id, name, family, sector, description, image, colors, theme, layout, categoryId, headline, subtitle) => ({ id, name, family, sector, description, image, colors, theme, layout, categoryId, headline, subtitle, tags: [sector, layout.card, layout.home], grid: family === 'workspace' || family === 'market' ? 2 : ['living','gallery','beauty'].includes(family) ? 3 : 4, ratio: ['fashion', 'gallery', 'beauty'].includes(family) ? 'portrait' : 'square' });
const light = { surface:'#ffffff', text:'#182336', muted:'#647084', border:'#e5e8ed', radius:14, fontFamily:'Inter', buttonStyle:'solid', shadow:'soft', spacing:1, headingScale:1 };
const STORE_DEMO_CATALOG = [
  preset('nova-pocket','Nova Pocket','pocket','Uygulama ile aynı dil','Uygulamanın beyaz yüzeyleri, kompakt ürün kartları ve üst gezinmedeki mavi seçim balonu; web için geniş kampanya ve düzenli kategori dizini.','/media/android-home-hero.png',{accent:'#d94b00',navy:'#061e45',background:'#f5f6f8'},{...light,fontFamily:'system',radius:18},layouts('Beyaz uygulama barı','Web kategori dizini','Kompakt uygulama kartı','Görsel önce, kısa kampanya','Odaklı ürün görünümü','Profil ve kısa yollar','Kartlar ve alt toplam','Uygulama bağlantıları','Dokunma geri bildirimi'),'home-living','Yaşam alanına ilham kat.','Gününü güzelleştiren iyi seçimler.'),
  preset('nova-commerce','Nova Commerce','nova-commerce','Web ile aynı dil','NovaStore’un kapsamlı arama ve mega menüsünü, ayrıntılı ürün kartlarını ve alışveriş akışını iki kanalda buluşturur.','/media/hero-editorial.webp',{accent:'#c45100',navy:'#04203b',background:'#ffffff'},{...light,surface:'#f5f7fa',radius:16},layouts('Arama ve mega menü','Ağaç ve görsel kategoriler','Ayrıntılı ticaret kartı','Geniş ana kampanya','Galeri ve satın alma paneli','Yan menülü hesap','Ürün satırları ve özet','Çok sütunlu mağaza','Kısa geçişler'),'electronics','İyi teknoloji, doğru seçimle başlar.','İhtiyacına uygun teknolojiyi birlikte bulalım.'),
  preset('tech-lab','Tech Lab','tech','Teknoloji','Cihazı öne çıkaran vitrin, teknik bilgi şeridi ve karşılaştırmaya odaklı kartlarla kolay karar verme.','/media/mega-electronics.webp',{accent:'#2455d6',navy:'#111b30',background:'#f4f6fa'},{...light,radius:8,shadow:'none'},layouts('Kompakt teknoloji barı','Kullanım alanı dizini','Teknik ürün kartı','Cihaz ve özellik panelleri','Sabit teknik özet','Sipariş odaklı panel','Kompakt ürün listesi','Teknik destek dizini','Kontrollü görsel yaklaşma'),'sector-tech-telefon','Bir sonraki seviyen.','Çalış, üret, dinle. Kendi teknolojini seç.'),
  preset('living-atelier','Living Atelier','living','Mobilya & yaşam','Yaşam alanlarından ilham alan büyük fotoğraflar, oda koleksiyonları ve geniş görselli ürünler.','/media/sectors/living/kavis-koltuk.png',{accent:'#8d563d',navy:'#37342f',background:'#faf8f3'},{...light,surface:'#eeeae1',text:'#37342f',muted:'#746e62',border:'#ded9ce',fontFamily:'Georgia',radius:2,headingScale:1.15,spacing:1.2,shadow:'none',buttonStyle:'outline'},layouts('Ortalanmış atölye başlığı','Oda koleksiyonları','Geniş görselli vitrin','Asimetrik oda hikâyesi','Büyük ürün galerisi','Yatay kişisel alan','Görsel alışveriş listesi','Dergi düzeninde alt bilgi','Yumuşak fotoğraf geçişi'),'sector-living-oturma','Evinin hikâyesini yaz.','İyi hissettiren mekânlar, zamansız detaylarla başlar.'),
  preset('fashion-studio','Fashion Studio','fashion','Moda','Koleksiyon kapağı, dikey ürün görselleri ve sade gezinmeyle ürünün stilini ön plana çıkaran mağaza.','/media/sectors/fashion/oversize-ceket.png',{accent:'#242424',navy:'#171717',background:'#ffffff'},{...light,text:'#242424',muted:'#6c6c6c',border:'#e6e6e6',radius:0,spacing:1.1,shadow:'none'},layouts('Minimal moda başlığı','Görsel koleksiyonlar','Portre ve hızlı işlem','Tam genişlik lookbook','Portre ürün incelemesi','Yatay profil menüsü','Varyant odaklı sepet','Minimal koleksiyon dizini','Görsel ve eylem geçişi'),'sector-fashion-ust-giyim','Kendi ritminde. Kendi stilinde.','Yeni sezonda sana ait parçaları keşfet.'),
  preset('daily-market','Daily Market','market','Günlük market','Kategori rayı, yoğun ürün listesi ve kolay sepet erişimiyle günlük ihtiyaçlara hızlı ulaş.','/media/sectors/market/yesil-elma.png',{accent:'#166b46',navy:'#153e2e',background:'#f6f8f4'},{...light,text:'#20382b',muted:'#617065',border:'#dfe7de',radius:10,spacing:.8,shadow:'none'},layouts('Önde arama alanı','Sabit kategori rayı','Yatay hızlı alışveriş','Kısa kampanya panoları','Hızlı ürün incelemesi','Alışveriş kısa yolları','Yoğun sepet ve sabit özet','Yardım ve hizmet alanı','Hızlı durum geçişi'),'sector-market-sut-kahvalti','Bugün ne eksik?','Kahvaltıdan akşam sofrasına, günlük ihtiyaçlarını tamamla.'),
  preset('stocky-purple','Desk Studio','workspace','Çalışma alanı','Masa düzeninden ergonomiye: uyumlu çalışma alanını parça parça kurabileceğin özgün stüdyo mağazası.','/media/sectors/workspace/ayarlanabilir-masa.png',{accent:'#663399',navy:'#35214b',background:'#f5f4f8'},{...light,text:'#30263b',muted:'#6b6075',border:'#e0dbe8',radius:8,spacing:.8,headingScale:.95,shadow:'none'},layouts('Mağaza araç çubuğu','Sıralı kategori dizini','Kompakt yatay kart','Modüler promosyon kutuları','Bilgi odaklı detay','Hesap konsolu','Tabloya yakın sepet','Düzenli bağlantı grupları','Kısa ve doğrudan'),'sector-workspace-mobilya','Daha iyi çalışmak için.','Ergonomi, düzen ve odak. Çalışma alanını birlikte kur.'),
  preset('editorial-gallery','Gallery Select','gallery','Tasarım objeleri','Numaralı seçkiler, büyük ürün fotoğrafları ve geniş boşluklarla her ürüne kendi sahnesini verir.','/media/sectors/gallery/seramik-vazo.png',{accent:'#934b37',navy:'#322a25',background:'#fffdf9'},{...light,surface:'#f4efe7',text:'#322a25',muted:'#746458',border:'#e5dcd0',fontFamily:'Georgia',radius:4,spacing:1.2,headingScale:1.15,shadow:'none',buttonStyle:'outline'},layouts('Editoryal masthead','Numaralı seçkiler','Büyük görselli editoryal','Koleksiyon hikâyeleri','Sakin ürün galerisi','Minimal kişisel alan','İki sütun görsel sepet','Tipografik alt bilgi','Hafif giriş hareketi'),'sector-gallery-seramik','Az, öz ve sana göre.','Günlük hayata değer katan tasarımlardan bir seçki.'),
  preset('ritual-beauty','Ritual Beauty','beauty','Bakım & kozmetik','Temizleme, bakım ve küçük rutinleri adım adım keşfettiren; doku ve ambalaj bilgisini öne çıkaran sakin bir bakım mağazası.','/media/sectors/beauty/nazik-temizleyici.png',{accent:'#a74465',navy:'#4d2937',background:'#fff9f7'},{...light,text:'#493840',muted:'#796873',border:'#eedde2',surface:'#fffdfc',fontFamily:'Georgia',radius:24,spacing:1.15,headingScale:1.1,shadow:'none'},layouts('Ritüel menüsü','Bakım adımlarına göre keşif','Rutin ve doku kartı','Adım adım bakım vitrini','Doku ve kullanım özeti','Kişisel bakım alanı','Rutin ürünleri sepeti','Bakım rehberi dizini','Sakin kart geçişleri'),'sector-beauty-temizleme','Kendine ayırdığın küçük anlar.','Temizle, bakımını tamamla ve sana ait bir rutin oluştur.'),
  preset('trail-outdoor','Trail Outdoor','sport','Spor & açık hava','Aktiviteye göre ekipman, ölçüleri görünen ürünler ve birlikte hazırlanabilen seçkilerle açık havaya davet eden mağaza.','/media/sectors/sport/sirt-cantasi.png',{accent:'#b44c18',navy:'#20372b',background:'#f3f5ee'},{...light,text:'#243328',muted:'#687363',border:'#d9e2d5',radius:10,spacing:1.05,shadow:'none'},layouts('Rota araç çubuğu','Aktivite koleksiyonları','Ölçü ve ekipman kartı','Macera ve ekipman vitrini','Ekipman özellik paneli','Aktif yaşam hesabı','Hazırlık listesi sepeti','Rota ve hizmet dizini','Kısa keşif hareketleri'),'sector-sport-yuruyus','Dışarıda seni bekleyen bir dünya var.','Kısa bir yürüyüşten kamp molasına, kendi rotana hazırlan.'),
  preset('little-wonder','Little Wonder','kids','Çocuk & oyun','Yaş grubu, oyun biçimi ve gündelik ihtiyaçları ayrı koleksiyonlarda buluşturan sıcak bir keşif dünyası.','/media/sectors/kids/pelus-ayi.png',{accent:'#b64c21',navy:'#24395b',background:'#fffbf2'},{...light,text:'#253856',muted:'#697080',border:'#e6e0d3',radius:24,spacing:1.1,shadow:'soft'},layouts('Oyun dünyası başlığı','Yaş ve ilgi alanları','Renkli keşif kartı','Hikâyeli oyun vitrini','Parça ve oyun bilgisi','Aile alışveriş alanı','Keşif çantası sepeti','Aile yardım dizini','Yumuşak oyun hareketleri'),'sector-kids-oyun','Küçük keşifler. Kocaman hikâyeler.','Oyna, üret ve her gün yeni bir şey hayal et.'),
];
// Tech Lab remains readable for saved drafts, but is no longer offered as a new demo.
export const STORE_DEMOS = STORE_DEMO_CATALOG.filter(preset => preset.id !== 'tech-lab');
export const DEMO_IDS = STORE_DEMO_CATALOG.map(preset => preset.id);
export function getStoreDemo(id) { return STORE_DEMO_CATALOG.find(preset => preset.id === id); }

export function createDemoBlocks(preset, channel) {
  const sector = getSectorCatalog(preset.family);
  const base = (type, suffix, values = {}) => ({ id:`demo-${preset.id}-${suffix}`,type,enabled:true,startsAt:'',endsAt:'',showCopy:true,showTitle:true,title:'',kicker:'',description:'',image:'',mobileImage:'',alt:'',buttonText:'',target:'home',secondaryText:'',secondaryTarget:'home',visibility:{desktop:true,mobile:true},style:{background:'',textColor:'',padding:channel === 'android' ? 0 : 40,align:'left',imagePosition:'right'},items:[],productLimit:8,productSource:{mode:'all',categoryId:'',productIds:[]},...values });
  const categoryId = sector?.categories[0].id || preset.categoryId;
  const hero = base('hero','hero',{title:preset.headline,kicker:preset.family === 'pocket' ? 'EV & YAŞAM' : preset.family === 'nova-commerce' ? 'NOVA SEÇKİSİ' : preset.sector.toLocaleUpperCase('tr-TR'),description:preset.subtitle,image:preset.image,mobileImage:preset.image,alt:preset.headline,buttonText:'Seçkiyi keşfet',target:`category:${categoryId}`,secondaryText:preset.family === 'pocket' ? '' : 'Tüm ürünler',secondaryTarget:'categories',showCopy:preset.family !== 'pocket' || channel !== 'android'});
  const categories = base('categories','categories',{title:({pocket:'Neye ihtiyacın var?',living:'Yaşam alanlarını keşfet',fashion:'Yeni sezona bir bakış',market:'İhtiyacın olan bölüm',tech:'Teknolojini keşfet',gallery:'Koleksiyonlar',beauty:'Rutinini adım adım kur',sport:'Bir aktivite seç',kids:'Keşfetmenin bir yolunu bul'}[preset.family] || 'Kategorileri keşfet'),buttonText:'Tüm kategoriler',target:'categories',showTitle:preset.family !== 'pocket' || channel !== 'android'});
  const products = base('products','products',{title:({pocket:'Bugünün Seçimleri',tech:'Güçlü bir başlangıç',living:'Evin için seçildi',fashion:'Stiline eşlik edenler',market:'Günlük seçkimiz',gallery:'Seçki / 01',beauty:'Ritüeline eşlik edenler',sport:'Rotana uygun ekipman',kids:'Yeni oyun arkadaşları'}[preset.family] || 'Öne çıkan ürünler'),kicker:'NOVASTORE SEÇKİSİ',buttonText:'Tümünü keşfet',target:`category:${categoryId}`,productLimit:preset.family === 'gallery' ? 4 : 8,productSource:{mode:'category',categoryId,productIds:[]}});
  if (preset.family === 'pocket') {
    products.productSource = { mode:'all', categoryId:'', productIds:[] };
    products.target = 'categories';
    products.kicker = '';
  }
  const story = base('editorial','story',{title:({living:'Küçük detaylar. Büyük bir değişim.',fashion:'Her güne kendi yorumunu kat.',tech:'Gün boyu, senin ritminde.',market:'Evde iyi hissettiren seçimler.',gallery:'İyi tasarımın gündelik hâli.',pocket:'Küçük bir mola, iyi bir seçim.'}[preset.family] || 'Yaşam alanını yeniden keşfet.'),description:'İhtiyacına ve yaşam tarzına uygun seçenekleri yakından incele.',image:['tech','gallery'].includes(preset.family)?'/media/product-watch.webp':'/media/category-home.webp',mobileImage:'',alt:'NovaStore yaşam seçkisi',buttonText:'Koleksiyona göz at',target:'category:home-living'});
  const second = base('products','more',{title:preset.family === 'fashion' ? 'Günlük stilin tamamlayıcıları' : 'Keşfetmeye devam et',productLimit:8,buttonText:'Bütün kategoriler',target:'categories'});
  if (sector) {
    const focus = sector.products[3];
    const storyCopy = {
      tech:['Üretmek için daha fazla alan.','Çalışma akışına uygun bilgisayarı özellikleriyle incele.'],
      living:['Işığı değiştir. Hissi değiştir.','Sıcak bir köşe için ölçüsü ve malzemesi düşünülmüş aydınlatma.'],
      fashion:['Sana ait bir siluet.','Kumaş, kesim ve beden seçeneklerini yakından incele.'],
      market:['Sofranın renkli tarafı.','Günlük tariflerine eşlik edecek meyve ve sebzeler.'],
      workspace:['Odaklanacak bir alan aç.','Çalışma masanın ışığını ve düzenini kendi ihtiyacına göre tamamla.'],
      gallery:['Malzemeden bir hikâye.','Doğal dokuları ve yalın formları yakından keşfet.'],
      beauty:['Küçük bir dokunuşla tamamla.','Günlük bakımına eşlik edecek doku ve ambalaj seçeneklerini incele.'],
      sport:['Çantanda küçük, gününde işe yarar.','Aktivitene eşlik edecek malzeme ve ölçüleri karşılaştır.'],
      kids:['Her güne küçük bir keşif.','Gündelik eşyalarını kendi hikâyesinin bir parçası yap.'],
    }[preset.family];
    products.productSource = {mode:'all',categoryId:'',productIds:[]};
    products.productLimit = 6;
    products.target = 'categories';
    products.kicker = sector.name.toLocaleUpperCase('tr-TR');
    Object.assign(story,{title:storyCopy[0],description:storyCopy[1],image:focus.imageUrl,mobileImage:focus.imageUrl,alt:focus.name,target:`${channel === 'android' ? 'android-product' : 'product'}:${focus.id}`,buttonText:'Ürünü yakından incele'});
    second.productSource = {mode:'selected',categoryId:'',productIds:sector.products.slice(3).map(product=>String(product.id))};
    second.productLimit = 3;
  }
  const features = base('features','features',{title:'Alışverişine eşlik ediyoruz.',items:[{id:'discover',title:'Kolay keşif',body:'Kategorilerden ihtiyacına uygun ürüne ulaş.',icon:'search'},{id:'favorite',title:'Kendi seçkin',body:'Beğendiklerini favorilerinde bir araya getir.',icon:'heart'},{id:'support',title:'Nova desteği',body:'Soruların için yardım merkezini ziyaret et.',icon:'headphones'}],buttonText:'Yardım merkezi',target:'support'});
  const announcement = base('announcement','announcement',{title:'İyi seçimler burada başlar.',description:'Kendi favorilerini bul, bir sonraki alışverişin için kaydet.',buttonText:'Favorilerime git',target:'favorites'});
  const orders = {pocket:[hero,categories,products,story,second], 'nova-commerce':[hero,categories,products,story,second,features],tech:[hero,features,products,categories,story,second],living:[hero,story,categories,products,features],fashion:[hero,categories,products,story,second],market:[categories,hero,products,story,second,features],workspace:[categories,hero,products,second,features],gallery:[hero,products,story,categories,second,announcement],beauty:[hero,categories,products,story,second],sport:[hero,categories,products,features,story,second],kids:[hero,categories,products,story,features,second]};
  return orders[preset.family];
}
