import React,{useState} from 'react';
import StudioFrame from './StudioFrame.jsx';
import {Thumbnail,ThemeGallery,Decisions,errorMessage} from './ThemeTools.jsx';
import {formSnapshot} from './studioFormGuard.js';
import {useFormGuard} from './useFormGuard.js';
import {isReadyTheme,unverifiedThemeMessage} from './themePresentation.js';
import DeliveryStatus from './DeliveryStatus.jsx';

const steps=['Mağaza','Tema','Görsel önizleme','Deneyim profili','Özellikler','Satıcı gibi gör','İncele','Teslime hazırla'];
export default function OfferComposer({client,stores,themes,profiles,catalog,initialStoreId='',initialThemeId='',initialChannel='',existingOffer=null,onClose,onDone,onDenied,onFormState}) {
  const [step,setStep]=useState(existingOffer?5:0),[storeId,setStoreId]=useState(String(existingOffer?.store_id||initialStoreId)),[themeId,setThemeId]=useState(existingOffer?.theme_version_id||initialThemeId),[channel,setChannel]=useState(existingOffer?.channel||initialChannel||(themes.find(item=>item.id===initialThemeId)?.supportedChannels.includes('web')===false?'app':'web')),[commerceMode,setCommerceMode]=useState(existingOffer?.commerce_mode||'SINGLE_STORE'),[profileCode,setProfileCode]=useState(existingOffer?.profile_code||'BASIC'),[overrides,setOverrides]=useState(existingOffer?.overrides||{}),[reason,setReason]=useState(''),[offer,setOffer]=useState(existingOffer),[visual,setVisual]=useState(null),[previewReady,setPreviewReady]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false),[denied,setDenied]=useState(false);
  const store=stores.find(item=>String(item.id)===storeId),theme=themes.find(item=>item.id===themeId),prepared=offer?.status==='PREPARED_FOR_DELIVERY';
  const presentationReady=isReadyTheme(theme,channel),legacyRecord=existingOffer&&!presentationReady&&!prepared;
  const snapshot=formSnapshot({storeId,themeId,channel,commerceMode,profileCode,overrides,reason});
  const [savedSnapshot,setSavedSnapshot]=useState(snapshot);
  useFormGuard(onFormState,{dirty:!prepared&&snapshot!==savedSnapshot,pending:busy});
  async function saveCandidate(purpose){if(!store?.service_id||!theme)throw Error('Etkin mağaza ve tema seçin.');if(!presentationReady)throw Error(unverifiedThemeMessage);const experience=await client.get(`/services/${store.service_id}/experience`);return (await client.write(`/services/${store.service_id}/offers`,{themeVersionId:themeId,channel,commerceMode,profileCode,overrides,expectedRevision:experience.policyRevision,reason:purpose})).result;}
  function fail(e){setError(errorMessage(e));if(e.status===403){setDenied(true);onDenied?.();}}
  function invalidate(){setVisual(null);setPreviewReady(false);setError('');}
  async function showVisual(){setBusy(true);setError('');setPreviewReady(false);try{setVisual(await saveCandidate('Tema seçiminin gerçek mağaza önizlemesi'));}catch(e){fail(e);}finally{setBusy(false);}}
  async function next(){setError('');setBusy(true);try{
    if(step===0&&(!store?.service_id||store.service_status!=='ACTIVE'))throw Error('Etkin tema hizmeti olan bir mağaza seçin.');
    if(step>=1&&!presentationReady)throw Error('Özgün tasarım kimliği doğrulanmış bir tema sürümü seçin.');
    if(step===2&&!previewReady)throw Error('Gerçek önizlemeyi açıp yüklenmesini bekleyin.');
    if(step===4){if(!reason.trim())throw Error('İşlem gerekçesi gerekli.');setOffer(await saveCandidate(reason));setSavedSnapshot(snapshot);setPreviewReady(false);}
    if(step===5&&!previewReady)throw Error('Satıcı görünümü yüklenmeden devam edilemez.');
    if(step===7){if(!reason.trim())throw Error('Teslime hazırlama gerekçesi gerekli.');const response=await client.write(`/offers/${offer.id}/prepare`,{expectedRevision:Number(offer.revision),reason});setOffer(response.result);await onDone();return;}
    setStep(step+1);
  }catch(e){fail(e);}finally{setBusy(false);}}
  function back(){setError('');if(step===5){setStep(4);setPreviewReady(false);}else setStep(step-1);}
  return <section className="tp-composer" aria-label="Tema sunumu hazırlama"><div className="tp-heading"><div><small>MAĞAZAYA ÖZEL TEMA</small><h2>Bir deneyim hazırla</h2><p>Seçimi inceleyin, satıcı yetkilerini belirleyin ve teslim için hazırlayın.</p></div><button onClick={onClose}>Kapat</button></div><ol className="tp-steps">{steps.map((label,index)=><li key={label} aria-current={step===index?'step':undefined}><b>{index+1}</b>{label}</li>)}</ol>{error&&<p role="alert" className="tp-error">{error}</p>}
    {legacyRecord?<div className="tp-notice"><h3>Sunum kaydı</h3><p>{unverifiedThemeMessage}</p><p>Bu kayıt salt okunur olarak korunur; özgün tema görünümü veya canlı yayın olarak sunulmaz.</p><dl><dt>Tema</dt><dd>{theme?.name||existingOffer.theme_version_id}</dd><dt>Sürüm</dt><dd>{theme?.version||'Katalog dışında'}</dd><dt>Durum</dt><dd>{existingOffer.status}</dd></dl><code>{existingOffer.id}</code></div>:prepared?<div className="tp-success"><h3>Teslim için hazırlandı</h3><p>Tema ve çalışma taslağı mağazaya atandı. Gerçek teslim durumu aşağıdaki sunucu kaydından okunur.</p><code>{offer.id}</code><DeliveryStatus client={client} offerId={offer.id}/><p>İşleme mağazanın Tema sekmesinden yeniden ulaşabilirsiniz.</p></div>:<>
      {step===0&&<label>Mağaza<select value={storeId} onChange={e=>{setStoreId(e.target.value);invalidate();}}><option value="">Mağaza seçin</option>{stores.map(item=><option key={item.id} value={item.id} disabled={!item.service_id||item.service_status!=='ACTIVE'}>{item.name} · {item.seller}{!item.service_id?' · hizmet açılmalı':''}</option>)}</select></label>}
      {step===1&&<ThemeGallery {...{client,themes}} selectedId={themeId} onSelect={item=>{setThemeId(item.id);setChannel(item.supportedChannels.includes('web')?'web':'app');invalidate();}}/>}
      {step===2&&theme&&<><div className="tp-preview-choice"><Thumbnail {...{client,theme,channel}}/><div><h3>{theme.name}</h3><p>Bu adım gerçek mağaza ürünleriyle bir aday önizleme kaydeder. Mağazaya tema atamaz.</p><label>Kanal<select value={channel} onChange={e=>{setChannel(e.target.value);invalidate();}}>{theme.supportedChannels.map(value=><option key={value} value={value} disabled={!isReadyTheme(theme,value)}>{value==='app'?'Uygulama önizlemesi':'Web'}</option>)}</select></label><label>Ticaret görünümü<select value={commerceMode} onChange={e=>{setCommerceMode(e.target.value);invalidate();}}><option value="SINGLE_STORE">Tek mağaza</option><option value="MARKETPLACE">Pazaryeri</option></select></label><button disabled={busy||denied} onClick={showVisual}>Gerçek mağaza önizlemesini aç</button></div></div>{visual&&<StudioFrame client={client} path={`/offers/${visual.id}/seller-preview`} renderOnly onReady={()=>setPreviewReady(true)} onFailure={()=>setPreviewReady(false)}/>}</>}
      {step===3&&<div className="tp-profile-grid">{profiles.map(profile=><button className={profileCode===profile.code?'selected':''} key={profile.code} onClick={()=>setProfileCode(profile.code)}><h3>{profile.name}</h3><p>{profile.code} · sürüm {profile.revision}</p><small>Abonelik ve sunucu rolünden bağımsız deneyim profili.</small></button>)}</div>}
      {step===4&&<><p>Profilin üzerine mağazaya özel kararlar ekleyebilirsiniz. Açık ret, diğer izinlerin önüne geçer.</p><Decisions catalog={catalog} values={overrides} onChange={setOverrides}/><label>İşlem gerekçesi<textarea maxLength={240} value={reason} onChange={e=>setReason(e.target.value)} placeholder="Bu mağaza için hazırlanan deneyimi açıklayın"/></label></>}
      {step===5&&offer&&<><p className="tp-notice">Sunucunun gerçek satıcı oturumu ve aday politikasıyla hesapladığı görünüm. Önizlemede kaydetme, yükleme ve yayın işlemleri kapalıdır.</p><StudioFrame client={client} path={`/offers/${offer.id}/seller-preview`} onReady={()=>setPreviewReady(true)} onFailure={()=>setPreviewReady(false)}/></>}
      {step===6&&<div className="tp-review"><h3>{store?.name} · {theme?.name}</h3><dl><dt>Sürüm</dt><dd>{theme?.version}</dd><dt>Kanal</dt><dd>{channel==='web'?'Web':'Uygulama'}</dd><dt>Ticaret</dt><dd>{commerceMode==='SINGLE_STORE'?'Tek mağaza':'Pazaryeri'}</dd><dt>Profil</dt><dd>{profileCode}</dd><dt>Özel karar</dt><dd>{Object.keys(overrides).length}</dd></dl><p>{reason}</p><p>Fiyat, stok, komisyon veya hukuki metin bu tema teklifinde tanımlanmaz.</p></div>}
      {step===7&&<div className="tp-review"><h3>Mağazaya ata ve teslim için hazırla</h3><p>Seçili sürüm ve politika birlikte atanır. Bu işlem sunucu teslim kuyruğuna kayıt oluşturur. Etkin teslim bağlantısı olduğunda Stocky alındısı ayrıca izlenir; mağazayı canlıya yayınlamaz ve DNS/TLS değiştirmez. Aynı kanalda mevcut atama varsa üzerine yazılmaz.</p><p>Teklif: {offer?.id}</p><label>Teslime hazırlama gerekçesi<textarea maxLength={240} value={reason} onChange={e=>setReason(e.target.value)}/></label></div>}
      <footer className="tp-actions"><button disabled={step===0||busy} onClick={back}>Geri</button><button className="tp-primary" disabled={busy||denied||([2,5].includes(step)&&!previewReady)} onClick={next}>{busy?'İşleniyor…':step===7?'Ata ve teslime hazırla':step===4?'Adayı kaydet ve satıcı görünümünü aç':'Devam et'}</button></footer>
    </>}
  </section>;
}
