import React, {useEffect, useState} from 'react';
import {formSnapshot} from './studioFormGuard.js';
import {useFormGuard} from './useFormGuard.js';
import {isReadyTheme,themeReadinessMessage} from './themePresentation.js';

export const stateLabels={HIDDEN:'Gizli',READ_ONLY:'Salt okunur',EDITABLE:'Düzenlenebilir',MANAGE:'Yönetebilir',PUBLISH:'Yayın isteği'};
export const errorMessage=e=>e?.code==='THEME_PRESENTATION_NOT_READY'?'Tema, seçili kanalda yeni atama için gerekli kontrolleri henüz tamamlamadı.':e?.status===403?'Bu işlem için yetkiniz bulunmuyor. Mağaza ve tema yönetimi izinleri sunucuda doğrulanır.':e?.status===409?'İşlem mevcut kayıt durumuyla uyuşmuyor. Verileri yenileyerek yeniden inceleyin.':e?.message||'Bağlantı kurulamadı.';
const validStates=item=>!item.supported?['HIDDEN']:item.code==='theme.publish'?['HIDDEN','READ_ONLY','PUBLISH']:item.code==='theme.version_history'?['HIDDEN','READ_ONLY']:['HIDDEN','READ_ONLY','EDITABLE','MANAGE'];

export function Thumbnail({client,theme,channel='web'}) {
  const [url,setURL]=useState(''),[failure,setFailure]=useState(''),[retry,setRetry]=useState(0);
  const thumbnail=theme.thumbnails?.find(item=>item.channel===channel)||theme.thumbnails?.[0];
  const assetKey=thumbnail?.assetKey||thumbnail?.key;
  useEffect(()=>{let cancelled=false,objectURL;const controller=new AbortController();setURL('');setFailure('');
    (async()=>{try{if(!assetKey)return;const blob=await client.blob(`/versions/${theme.id}/assets/${encodeURIComponent(assetKey)}`,{signal:controller.signal});if(cancelled)return;objectURL=URL.createObjectURL(blob);setURL(objectURL);}catch(e){if(!cancelled){setURL('');setFailure(errorMessage(e));}}})();
    return()=>{cancelled=true;controller.abort();if(objectURL)URL.revokeObjectURL(objectURL);};
  },[client,theme.id,assetKey,retry]);
  const current=thumbnail&&!thumbnail.stale&&thumbnail.documentDigest===theme.digest;
  return <div className="tp-thumbnail">{url?<img src={url} alt={`${theme.name} referans görünümü`} onError={()=>{setURL('');setFailure('Görsel tarayıcıda açılamadı. Küçük resmi tekrar yükleyin.');}}/>:<div className="tp-thumbnail-empty"><small>NOVA STORE</small><strong>{theme.name}</strong>{failure?<><span role="alert">{failure}</span><button type="button" onClick={()=>setRetry(value=>value+1)}>Küçük resmi tekrar yükle</button></>:<span>{assetKey?'Referans görsel yükleniyor…':'Bu pakette küçük resim yok. Canlı önizlemeyi açarak inceleyin.'}</span>}</div>}<span>{current?'Doğrulanmış sürüm görseli':'Referans görsel · güncel önizleme değil'}</span></div>;
}

export function ThemeGallery({client,themes,selectedId,onSelect,actionLabel='Bu temayı seç',disabled=false}) {
  const [search,setSearch]=useState(''),[channel,setChannel]=useState('all');
  const visible=themes.filter(theme=>(`${theme.name} ${theme.industry||''}`).toLocaleLowerCase('tr').includes(search.toLocaleLowerCase('tr'))&&(channel==='all'||theme.supportedChannels?.includes(channel)));
  return <section aria-label="Tema kütüphanesi"><div className="tp-filter-row"><label>Tema ara<input type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Ad veya sektör"/></label><label>Kanal<select value={channel} onChange={e=>setChannel(e.target.value)}><option value="all">Tüm kanallar</option><option value="web">Web</option><option value="app">Uygulama</option></select></label><span role="status">{visible.length} paket · {visible.filter(theme=>isReadyTheme(theme,channel==='all'?undefined:channel)).length} kullanıma hazır</span></div><div className="tp-theme-grid">{visible.map(theme=><article className={`tp-theme-card ${selectedId===theme.id?'selected':''}`} key={theme.id}><Thumbnail {...{client,theme}} channel={channel==='app'?'app':'web'}/><div className="tp-card-copy"><h3>{theme.name}</h3><p>{theme.industry||'Mağaza koleksiyonu'} · {theme.version}</p><small>{(theme.supportedChannels||[]).map(value=>value==='web'?'Web':'Uygulama').join(' / ')} · {theme.rendererVersion}</small><p className={isReadyTheme(theme,channel==='all'?undefined:channel)?'tp-metadata':'tp-notice'}>{themeReadinessMessage(theme)}</p><button disabled={disabled||!isReadyTheme(theme,channel==='all'?undefined:channel)} aria-pressed={selectedId===theme.id} onClick={()=>{if(isReadyTheme(theme,channel==='all'?undefined:channel))onSelect(theme);}}>{!isReadyTheme(theme,channel==='all'?undefined:channel)?'Sunuma kapalı':selectedId===theme.id?'Seçili tema':actionLabel}</button></div></article>)}</div>{!visible.length&&<p className="tp-empty">Bu filtrelere uygun doğrulanmış tasarım bulunamadı.</p>}</section>;
}

export function Decisions({catalog,values,onChange,effective,disabled=false}) {
  return <div className="tp-decisions">{catalog.map(item=><label key={item.code}><span><strong>{item.label}</strong><small>{!item.supported?'Bu sürümde desteklenmiyor':effective?.[item.code]?`Etkin: ${stateLabels[effective[item.code].state]} · ${effective[item.code].reason}`:'Profil varsayılanını kullanır'}</small></span><select aria-label={`${item.label} yeteneği`} disabled={disabled||!item.supported} value={values[item.code]?.effect==='DENY'?'DENY':values[item.code]?.state||''} onChange={e=>{const copy={...values};if(!e.target.value)delete copy[item.code];else copy[item.code]=e.target.value==='DENY'?{effect:'DENY'}:{effect:'ALLOW',state:e.target.value};onChange(copy);}}><option value="">Profil varsayılanı</option><option value="DENY">Açıkça reddet</option>{validStates(item).map(state=><option key={state} value={state}>{stateLabels[state]}</option>)}</select></label>)}</div>;
}

export function ProfileManager({client,profiles,catalog,onDone,onFormState,allowLeave=()=>true}) {
  const [code,setCode]=useState(''),[name,setName]=useState(''),[values,setValues]=useState({}),[revision,setRevision]=useState(0),[reason,setReason]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[denied,setDenied]=useState(false);
  const snapshot=formSnapshot({code,name,values,reason}),[savedSnapshot,setSavedSnapshot]=useState(snapshot);
  useFormGuard(onFormState,{dirty:snapshot!==savedSnapshot,pending:busy});
  function choose(profile){if(!allowLeave())return;const next={code:profile?.code||'',name:profile?.name||'',values:profile?.capabilities||Object.fromEntries(catalog.map(item=>[item.code,'HIDDEN'])),reason:''};setCode(next.code);setName(next.name);setValues(next.values);setSavedSnapshot(formSnapshot(next));setRevision(Number(profile?.revision||0));setReason('');setError('');setNotice('');}
  async function save(){setBusy(true);setError('');try{const response=await client.write('/experience/profiles',{code,name,capabilities:values,expectedRevision:revision,reason},'PUT');setRevision(Number(response.result.revision));setSavedSnapshot(snapshot);setNotice('Profil sunucuya kaydedildi. Bu profili kullanan mağazaların politikası yeniden hesaplanır.');await onDone();}catch(e){setError(errorMessage(e));if(e.status===403)setDenied(true);}finally{setBusy(false);}}
  return <section className="tp-panel"><div className="tp-section-heading"><div><h2>Deneyim profilleri</h2><p>Bir mağaza grubuna sunulacak düzenleme alanlarını belirleyin.</p></div><button onClick={()=>choose(null)}>Yeni profil</button></div><div className="tp-profile-grid">{profiles.map(profile=><button key={profile.code} className={profile.code===code?'selected':''} onClick={()=>choose(profile)}><strong>{profile.name}</strong><small>{profile.code} · sürüm {profile.revision}</small></button>)}</div><p className="tp-notice">Mevcut bir profilin değişmesi onu kullanan mağazaları etkiler. Abonelik, rol ve açık ret kararları yine sunucu tarafından uygulanır.</p>{error&&<p className="tp-error" role="alert">{error}</p>}{notice&&<p className="tp-success" role="status">{notice}</p>}<div className="tp-form-grid"><label>Profil kodu<input value={code} disabled={revision>0} maxLength={64} placeholder="ORN. TASARIM_EKIBI" onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z0-9_]/g,''))}/></label><label>Profil adı<input value={name} maxLength={120} onChange={e=>setName(e.target.value)}/></label></div><div className="tp-decisions">{catalog.map(item=><label key={item.code}><span><strong>{item.label}</strong><small>{item.supported?'Profilin izin verebildiği seviye':'Bu sürümde desteklenmiyor'}</small></span><select aria-label={`${item.label} profil durumu`} disabled={!item.supported||denied} value={values[item.code]||'HIDDEN'} onChange={e=>setValues({...values,[item.code]:e.target.value})}>{validStates(item).map(state=><option key={state} value={state}>{stateLabels[state]}</option>)}</select></label>)}</div><label>Değişiklik gerekçesi<textarea maxLength={240} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="tp-primary" disabled={busy||denied||!code||!name.trim()||!reason.trim()} onClick={save}>{busy?'Kaydediliyor…':'Profili kaydet'}</button></section>;
}
