import React,{useCallback,useEffect,useMemo,useRef,useState} from 'react';
import {createAdminThemeClient} from './adminThemeClient.js';
import OfferComposer from './OfferComposer.jsx';
import {ThemeGallery,Decisions,ProfileManager,errorMessage} from './ThemeTools.jsx';
import StudioFrame from './StudioFrame.jsx';
import StoreContent from './StoreContent.jsx';
import PublicationPanel from './PublicationPanel.jsx';
import StoreSupportInbox from './StoreSupportInbox.jsx';
import './theme-platform.css';
import {createFormGuardTracker,formSnapshot} from './studioFormGuard.js';
import {hasUnsavedStudioWork} from './studioNavigationGuard.js';
import {isReadyTheme,canPreviewTheme,resolveThemeIntent,unverifiedThemeMessage} from './themePresentation.js';

const labels={overview:'Genel bakış',theme:'Tema',features:'Editör özellikleri',permissions:'Yetkiler',versions:'Sürümler',deployments:'Dağıtımlar',support:'Destek',activity:'Etkinlik',audit:'Denetim',settings:'Ayarlar'};
const statuses={HIDDEN:'Gizli',READ_ONLY:'Salt okunur',EDITABLE:'Düzenlenebilir',MANAGE:'Yönetebilir',PUBLISH:'Yayın isteği',ACTIVE:'Etkin',SUSPENDED:'Askıda',REVOKED:'İptal',CONFIGURED:'Aday kaydedildi',PREPARED_FOR_DELIVERY:'Teslim için hazırlandı',ASSIGNED:'Atandı',ACCEPTED:'Kabul edildi',WITHDRAWN:'Geri çekildi',PENDING:'Bekliyor',COMPLETED:'Tamamlandı',BLOCKED:'Engellendi',FAILED:'Başarısız',VERIFIED:'Doğrulandı',SINGLE_STORE:'Tek mağaza',MARKETPLACE:'Pazaryeri',web:'Web',app:'Uygulama'};
const displayCell=(value,key)=>value===null||value===undefined?'—':typeof value==='object'?JSON.stringify(value):key.endsWith('_at')?new Date(value).toLocaleString('tr-TR'):statuses[value]||String(value);
const message=errorMessage;
function Rows({items,columns}){if(!items?.length)return <p className="tp-empty">Bu kapsamda kayıt bulunmuyor.</p>;return <div className="tp-table-wrap"><table><thead><tr>{columns.map(([key,label])=><th key={key}>{label}</th>)}</tr></thead><tbody>{items.map((item,index)=><tr key={item.id||index}>{columns.map(([key])=><td key={key}>{displayCell(item[key],key)}</td>)}</tr>)}</tbody></table></div>;}
export default function ThemePlatform({http,fetchImpl,embedded=false,onNavigationGuard,initialSourceThemeId='',initialChannel='web'}){
  const client=useMemo(()=>createAdminThemeClient(http,fetchImpl?{fetchImpl}:undefined),[http,fetchImpl]);
  const selectedService=useRef(''),loadSequence=useRef(0),frameLeaveGuard=useRef(null);
  const handledIntent=useRef('');
  const [catalogLoaded,setCatalogLoaded]=useState(false),[sourceIntent,setSourceIntent]=useState(initialSourceThemeId?{id:initialSourceThemeId,channel:initialChannel}:null);
  const [view,setView]=useState('services'),[plan,setPlan]=useState('basic'),[writeDenied,setWriteDenied]=useState(false);
  const [stores,setStores]=useState([]),[themes,setThemes]=useState([]),[profiles,setProfiles]=useState([]),[catalog,setCatalog]=useState([]),[serviceId,setServiceId]=useState(''),[tab,setTab]=useState('overview'),[details,setDetails]=useState(null),[audit,setAudit]=useState([]),[editor,setEditor]=useState(''),[composer,setComposer]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[overrides,setOverrides]=useState({}),[profileCode,setProfileCode]=useState('BASIC'),[reason,setReason]=useState('');
  const formGuard=useMemo(()=>createFormGuardTracker({confirm:text=>window.confirm(text),notify:setError}),[]);
  const composerState=useCallback(value=>formGuard.update('composer',value),[formGuard]);
  const profileState=useCallback(value=>formGuard.update('profile',value),[formGuard]);
  const contentState=useCallback(value=>formGuard.update('store-content',value),[formGuard]);
  const supportState=useCallback(value=>formGuard.update('store-support',value),[formGuard]);
  const publicationState=useCallback(value=>formGuard.update('publication',value),[formGuard]);
  const policyVisible=view==='services'&&!composer&&!editor&&!!details;
  const policyDirty=policyVisible&&formSnapshot({profileCode,overrides,reason})!==formSnapshot({profileCode:details.experience.profileCode,overrides:details.experience.overrides||{},reason:''});
  formGuard.update('policy',{dirty:!!policyDirty,pending:busy});
  const allowLeave=()=>formGuard.leave()&&(frameLeaveGuard.current?frameLeaveGuard.current():true);
  useEffect(()=>{onNavigationGuard?.(allowLeave);return()=>onNavigationGuard?.(null);},[onNavigationGuard]);
  useEffect(()=>{const beforeUnload=event=>{if(hasUnsavedStudioWork(formGuard.state())){event.preventDefault();event.returnValue='';}};window.addEventListener('beforeunload',beforeUnload);return()=>window.removeEventListener('beforeunload',beforeUnload);},[formGuard]);
  async function refresh(){setError('');try{const [a,b,c]=await Promise.all([client.get('/experience/stores'),client.get('/experience/catalog'),client.get('/experience/profiles')]);setStores(a);setThemes(b);setProfiles(c.items);setCatalog(c.catalog);setCatalogLoaded(true);setServiceId(current=>current||a.find(item=>item.service_status==='ACTIVE')?.service_id||'');}catch(e){setError(message(e));}}
  async function load(){if(!serviceId)return;const sequence=++loadSequence.current;const requested=serviceId;setError('');try{const result=await client.get(`/services/${requested}/experience-details`);if(selectedService.current!==requested||sequence!==loadSequence.current)return;setDetails(result);setOverrides(result.experience.overrides||{});setProfileCode(result.experience.profileCode);}catch(e){if(selectedService.current===requested&&sequence===loadSequence.current){setDetails(null);setError(message(e));}}}
  selectedService.current=serviceId;
  useEffect(()=>{refresh();},[client]);useEffect(()=>{setEditor('');setDetails(null);setAudit([]);setReason('');load();return()=>{loadSequence.current+=1;};},[serviceId,client]);
  useEffect(()=>{if(!catalogLoaded||!sourceIntent)return;const key=`${sourceIntent.id}:${sourceIntent.channel}`;if(handledIntent.current===key)return;handledIntent.current=key;const intent=resolveThemeIntent(themes,sourceIntent.id,sourceIntent.channel);setView('library');if(intent.status==='ready')setComposer({instanceId:crypto.randomUUID(),initialThemeId:intent.themeId,initialChannel:intent.channel});else setNotice(intent.message);},[catalogLoaded,themes,sourceIntent]);
  useEffect(()=>{let active=true;if(tab==='audit'&&serviceId)client.get(`/services/${serviceId}/audit`).then(result=>{if(active)setAudit(Array.isArray(result)?result:result.items||[]);}).catch(e=>{if(active)setError(message(e));});return()=>{active=false;};},[tab,serviceId,client]);
  async function savePolicy(){setBusy(true);setError('');try{await client.write(`/services/${serviceId}/experience`,{expectedRevision:details.experience.policyRevision,profileCode,overrides,reason},'PUT');await load();setReason('');setNotice('Deneyim politikası güncellendi. Açık editörler güncel politikayı yeniden alır.');}catch(e){setError(message(e));if(e.status===403)setWriteDenied(true);}finally{setBusy(false);}}
  async function importPackage(event){const file=event.target.files?.[0];event.target.value='';if(!file)return;setBusy(true);setError('');try{if(file.size>16*1024*1024)throw Error('Paket 16 MB sınırını aşıyor.');const value=JSON.parse(await file.text());await client.write('/experience/packages',{package:value,reason:'Admin tema paketini içe aktardı'});await refresh();setNotice('Paket ve görsel baytları doğrulanarak yeni sürüm oluşturuldu.');}catch(e){setError(message(e));if(e.status===403)setWriteDenied(true);}finally{setBusy(false);}}
  async function provision(store){setBusy(true);setError('');try{await client.write('/services',{storeId:Number(store.id),plan,status:'ACTIVE',startsAt:new Date().toISOString(),expiresAt:null,reason:'Admin tema hizmetini hazırladı'});await refresh();}catch(e){setError(message(e));if(e.status===403)setWriteDenied(true);}finally{setBusy(false);}}
  function changeView(next){if(!allowLeave())return;setEditor('');setComposer(false);setView(next);}
  const intent=sourceIntent?resolveThemeIntent(themes,sourceIntent.id,sourceIntent.channel):null;
  const selectableThemes=sourceIntent?intent.themes:themes;
  const readyThemes=selectableThemes.filter(theme=>isReadyTheme(theme));
  const acceptedAssignments=details?.assignments?.filter(item=>item.status==='ACCEPTED')||[];
  const assignedPresentationReady=acceptedAssignments.length>0&&acceptedAssignments.every(item=>canPreviewTheme(themes.find(theme=>theme.id===item.theme_version_id),item.channel));
  const Container=embedded?'section':'main';
  return <Container className={`theme-platform${embedded?' is-embedded':''}`} aria-label="Sunucuya bağlı satıcı tema yönetimi">
    <header className="tp-heading">{!embedded&&<div><small>NOVA STORE / SATICI DENEYİMİ</small><h1>Satıcıya tema sun</h1><p>Mağazaya özel tema, düzenleme yetkileri ve teslim hazırlığı.</p></div>}<div className="tp-actions"><label className="tp-upload">Paket içe aktar<input type="file" accept="application/json,.json" disabled={busy||writeDenied} onChange={importPackage}/></label><button className="tp-primary" onClick={()=>{if(allowLeave()){setEditor('');setComposer({instanceId:crypto.randomUUID(),...(intent?.status==='ready'?{initialThemeId:intent.themeId,initialChannel:intent.channel}:{})});}}} disabled={!readyThemes.length||writeDenied}>Yeni tema sunumu</button></div></header>
    <nav className="tp-main-tabs" aria-label="Satıcı tema yönetimi"><button aria-current={!composer&&view==='services'?'page':undefined} onClick={()=>changeView('services')}>Mağaza çalışma alanları</button><button aria-current={!composer&&view==='library'?'page':undefined} onClick={()=>changeView('library')}>Tema paketleri</button><button aria-current={!composer&&view==='profiles'?'page':undefined} onClick={()=>changeView('profiles')}>Deneyim profilleri</button></nav>
    {!composer&&view==='services'&&<p className="tp-notice">Bu bölüm sunucuya bağlı mağaza atamalarını, yetkileri ve sunum kayıtlarını yönetir. Studio'nun diğer tasarım araçlarındaki yerel taslaklar bu kayıtlardan ayrıdır. Teslime hazırlamak canlı yayın veya Stocky teslim alındısı oluşturmaz.</p>}

    {sourceIntent&&<div className="tp-notice"><strong>Galeriden seçilen tasarım: {sourceIntent.id} · {sourceIntent.channel==='android'?'Uygulama':'Web'}</strong><p>{intent.status==='ready'?'Sunucu paketinin özgün tasarım kimliği eşleşti. Yalnız bu tasarımın sürümleri gösteriliyor.':intent.message}</p><button onClick={()=>{if(allowLeave()){setSourceIntent(null);setComposer(false);setNotice('');setView('library');}}}>Tüm tema paketlerine dön</button></div>}
    {error&&<p className="tp-error" role="alert">{error}</p>}{notice&&!sourceIntent&&<p className="tp-success" role="status">{notice}</p>}
    {composer?<OfferComposer key={composer.instanceId} {...{client,stores,profiles,catalog}} themes={composer.existingOffer?themes:selectableThemes} {...composer} initialStoreId={stores.find(item=>item.service_id===serviceId)?.id||''} onFormState={composerState} onClose={()=>{if(allowLeave())setComposer(false);}} onDenied={()=>setWriteDenied(true)} onDone={async()=>{await refresh();await load();}}/>:<>
    {view==='library'?<ThemeGallery client={client} themes={selectableThemes} disabled={writeDenied} onSelect={theme=>{if(isReadyTheme(theme))setComposer({instanceId:crypto.randomUUID(),initialThemeId:theme.id,...(sourceIntent?{initialChannel:sourceIntent.channel==='android'?'app':sourceIntent.channel}:{})});}} actionLabel="Bu temayla sunum hazırla"/>:view==='profiles'?<ProfileManager {...{client,profiles,catalog,allowLeave}} onFormState={profileState} onDone={async()=>{await refresh();await load();}}/>:<>
    {<section className="tp-toolbar"><label>Mağaza hizmeti<select value={serviceId} onChange={e=>{if(allowLeave()){setReason('');setServiceId(e.target.value);}}}><option value="">Mağaza seçin</option>{stores.filter(store=>store.service_id).map(store=><option key={store.id} value={store.service_id}>{store.name} · {store.service_status}</option>)}</select></label><button onClick={()=>{if(allowLeave()){setReason('');refresh();load();}}}>Yenile</button><button onClick={()=>changeView('profiles')}>Deneyim profilleri</button>{serviceId&&<><button onClick={()=>{if(allowLeave())setEditor(`/services/${serviceId}/editor-context`);}} disabled={!assignedPresentationReady}>Admin Studio</button><button onClick={()=>{if(allowLeave())setEditor(`/services/${serviceId}/seller-preview`);}} disabled={!assignedPresentationReady}>Satıcı gibi gör</button></>}</section>}
    {details?.experience.sellerAccess?.status==='UNAVAILABLE'&&<p className="tp-notice" role="status">Mağazanın kayıtlı ayarları yüklendi. Doğrulanmış açık bir satıcı oturumu bulunmadığı için etkin satıcı erişimi henüz gösterilemiyor. Profil ayarlarını düzenleyebilirsin; satıcı önizlemesi için satıcının kendi hesabından giriş yapması gerekir.</p>}
    {acceptedAssignments.length>0&&!assignedPresentationReady&&<p className="tp-notice">Bu hizmette özgün tasarım kimliği doğrulanmamış eski bir atama var. Kayıtları aşağıda inceleyebilirsin; farklı bir görünüm gerçek tema diye açılmaz.</p>}
    {editor?<><button onClick={()=>{if(allowLeave())setEditor('');}}>Yönetime dön</button><StudioFrame client={client} path={editor} onLeaveGuard={guard=>{frameLeaveGuard.current=guard;}}/></>:details?<><nav className="tp-tabs" aria-label="Tema hizmeti bölümleri">{Object.entries(labels).map(([id,label])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>{if(allowLeave())setTab(id);}}>{label}</button>)}</nav>
    {tab==='overview'&&<div className="tp-summary"><article><small>Hizmet</small><h2>{details.service.status}</h2><p>{details.service.plan}</p></article><article><small>Satıcı deneyimi</small><h2>{details.experience.profileCode}</h2><p>Politika sürümü {details.experience.policyRevision}</p></article><article><small>Atanmış sürümler</small><h2>{details.assignments.length}</h2><p>Web ve uygulama ayrı kanallardır.</p></article><p className="tp-notice">Stocky teslimi ve canlı yayın bağımsız süreçlerdir. Bu ekran bir teslim alındısı üretmez.</p></div>}
    {tab==='theme'&&<>
      <h2>Atanmış temalar</h2>
      <Rows items={details.assignments.map(item=>({...item,presentation_label:canPreviewTheme(themes.find(theme=>theme.id===item.theme_version_id),item.channel)?'Özgün tasarım kimliği bağlı':'Eski şema örneği · tasarım eşleşmesi yok'}))} columns={[["name","Tema"],["version","Sürüm"],["channel","Kanal"],["commerce_mode","Ticaret"],["status","Durum"],["presentation_label","Tasarım bağlantısı"]]}/>
      <div className="tp-section-heading"><h2>Kayıtlı sunumlar</h2><button disabled={writeDenied||!readyThemes.length} onClick={()=>{if(allowLeave())setComposer({instanceId:crypto.randomUUID(),...(intent?.status==='ready'?{initialThemeId:intent.themeId,initialChannel:intent.channel}:{})});}}>Yeni sunum</button></div>
      <div className="tp-offers">{(details.offers||[]).map(offer=>{
        const offeredTheme=themes.find(theme=>theme.id===offer.theme_version_id),ready=isReadyTheme(offeredTheme,offer.channel);
        return <article key={offer.id}><div><strong>{offeredTheme?.name||'Tema sürümü'}</strong><p>{offer.channel==='web'?'Web':'Uygulama'} · {offer.profile_code} · {offer.status==='PREPARED_FOR_DELIVERY'?'Teslim için hazırlandı':'Aday kaydedildi'}</p>{!ready&&<p>{unverifiedThemeMessage}</p>}<small>{new Date(offer.created_at).toLocaleString('tr-TR')}</small></div><button onClick={()=>{if(allowLeave())setComposer({instanceId:crypto.randomUUID(),existingOffer:offer});}}>{!ready?'Eski kayıt bilgisini görüntüle':offer.status==='PREPARED_FOR_DELIVERY'?'Hazırlama kaydını görüntüle':'Düzenlemeye devam et'}</button></article>;
      })}</div>{!details.offers?.length&&<p className="tp-empty">Henüz kaydedilmiş sunum yok.</p>}
    </>}
    {tab==='features'&&<><label>Deneyim profili<select value={profileCode} onChange={e=>setProfileCode(e.target.value)}>{profiles.map(profile=><option key={profile.code} value={profile.code}>{profile.name}</option>)}</select></label>{details.experience.sellerAccess?.status==='UNAVAILABLE'&&<p>Kayıtlı profil ve özellik izinleri aşağıdadır. Bunlar doğrulanmış etkin satıcı erişimi değildir.</p>}<Decisions catalog={catalog} values={overrides} onChange={setOverrides} effective={details.experience.sellerAccess?.status==='UNAVAILABLE'?details.experience.configuredCapabilities:details.experience.capabilities}/><label>Değişiklik gerekçesi<textarea maxLength={240} value={reason} onChange={e=>setReason(e.target.value)}/></label><button className="tp-primary" disabled={busy||writeDenied||!reason.trim()} onClick={savePolicy}>Politikayı kaydet</button></>}
    {tab==='permissions'&&<><p>Bu değerler sunucunun canlı satıcı rolü, üyeliği, hizmeti ve özellik izinlerinden hesaplanır. İstemci rol ataması yapmaz.</p><Rows items={Object.entries(details.experience.capabilities).map(([code,value])=>({id:code,code,...value}))} columns={[["code","Yetenek"],["state","Etkin durum"],["reason","Karar kaynağı"]]}/></>}
    {tab==='versions'&&<Rows items={details.versions} columns={[["draft_id","Taslak"],["revision","Sürüm"],["digest","Özet"],["created_at","Oluşturuldu"]]}/>}
    {tab==='support'&&<StoreSupportInbox key={serviceId} client={client} serviceId={serviceId} kind="admin" onFormState={supportState}/>}
    {tab==='deployments'&&<><PublicationPanel key={serviceId} client={client} publications={details.publications} onDone={load} onFormState={publicationState}/><p>Hazırlama, yayın isteği, dağıtım ve teslim alındısı ayrı durumlardır.</p><Rows items={details.deployments} columns={[["id","Dağıtım"],["status","Durum"],["created_at","Oluşturuldu"]]}/></>}
    {tab==='activity'&&<Rows items={details.activity} columns={[["type","İşlem"],["status","Durum"],["failure_reason","Sonuç"],["created_at","Zaman"]]}/>}
    {tab==='audit'&&<Rows items={audit} columns={[["actor_id","Aktör"],["action","İşlem"],["reason","Gerekçe"],["created_at","Zaman"]]}/>}
    {tab==='settings'&&<><StoreContent key={serviceId} client={client} serviceId={serviceId} onFormState={contentState}/><h3>Alan adı bağları</h3><Rows items={details.domains} columns={[["hostname","Alan adı"],["status","Durum"],["commerce_mode","Görünüm"]]}/><p>Alan adı sahipliği ve mağaza bağı sunucu tarafından doğrulanır. Bu arayüz DNS veya TLS etkinleştirmez. Hukuki içerik işletmenin yetkili kayıtlarından gelir.</p></>}
    </>:<section className="tp-empty"><h2>Bir mağazanın tema hizmetini seçin</h2><p>Atamalar, Studio erişimi ve politika yalnız seçili mağaza kapsamında açılır.</p><label>Yeni hizmetin planı<select value={plan} onChange={e=>setPlan(e.target.value)}><option value="basic">Basic</option><option value="pro">Pro</option></select></label>{stores.filter(store=>!store.service_id).map(store=><p key={store.id}>{store.name} <button disabled={busy||writeDenied} onClick={()=>provision(store)}>Tema hizmetini hazırla</button></p>)}</section>}
    </>}
    </>}
  </Container>;
}
