import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import crypto from 'node:crypto';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {createCustomerCommerceRuntime,assertCustomerRuntimeContext,scopedCommerceStorage} from '../src/studio-integration/commerce-runtime.js';
import {commerceApiPath,createCommerceHttp} from '../src/studio-integration/commerce-http.js';
import {createCustomerEngineBridge} from '../src/studio-integration/commerce-engine-bridge.js';
import {customerRuntimeSource,customerProjectorSource} from '../src/studio-integration/commerce-runtime-source.mjs';
test('Classic header initial and refreshed totals use canonical variant prices, including missing-price lines',()=>{
 const original=fs.readFileSync(new URL('../workshop-public/theme-library/shared/core.js',import.meta.url),'utf8');
 const output=customerRuntimeSource(original,'nova-classic');
 const subtotal=output.slice(output.indexOf('  function classicCartSubtotal() {'),output.indexOf('  function classicHeader(',output.indexOf('  function classicCartSubtotal() {')));
 const counter=output.slice(output.indexOf('  function classicUpdateCounters()'),output.indexOf('  function classicSelectImage('));
 const totalsStart=output.indexOf('  function totals() {');
 const totalsEnd=output.indexOf('\n  function ',totalsStart+1);
 const values=[];
 const context={hostBridge:true,state:{cart:[{productId:'501',unitPrice:11100,qty:1},{productId:'501',unitPrice:22500,qty:1},{productId:'502',unitPrice:null,qty:2}]},products:new Map([['501',{price:11100}],['502',{price:4500}]]),classicCompareIds:()=>[],money:value=>value,document:{querySelectorAll:selector=>selector==='[data-classic-cart-subtotal]'?[{set textContent(value){values.push(value);}}]:[]}};
 vm.createContext(context);
 vm.runInContext(output.slice(totalsStart,totalsEnd)+subtotal+counter+';result=classicCartSubtotal();classicUpdateCounters();',context);
 assert.equal(context.result,33600);assert.deepEqual(values,[33600]);
});
import {renderCommercePage,createCommerceDOM,orderVariantText,createProductSelectionMemory,renderReviewEditor} from '../src/studio-integration/commerce-dom.js';
const require=createRequire(import.meta.url),registry=require('../../theme-platform/presentations.json');
const presentation=registry.presentations.find(row=>row.id==='nova-classic');
const descriptor={id:presentation.id,version:presentation.version,digest:presentation.digest};
const context={commerceMode:'SINGLE_STORE',customerRuntime:{enabled:true,contractVersion:2,storeId:9},presentation:descriptor};
const product={id:501,name:'Kanonik ürün',price:100,old_price:null,stock:30,image_url:'/image.png',average_rating:0,review_count:0,category_id:10,category_ids:[10],description:'Açıklama',media:[],variant_selection_required:true,variants:[901,902].map((id,i)=>({id,price:100+i*25,availableStock:30,purchasable:true,selections:[{group:'Renk',value:i?'Mavi':'Kırmızı'}]}))};
const storageOf=(entries={})=>{const values=new Map(Object.entries(entries));return{values,getItem:key=>values.get(key)||null,setItem:(key,value)=>values.set(key,String(value)),removeItem:key=>values.delete(key)};};
test('PDP choice survives canonical rerender but never guesses replacement variant or crosses product',()=>{const memory=createProductSelectionMemory();assert.deepEqual(memory.read(product),{variantId:'',quantity:'1'});memory.write(501,902,2);assert.deepEqual(memory.read(structuredClone(product)),{variantId:'902',quantity:'2'});assert.deepEqual(memory.read({...product,variants:product.variants.filter(v=>v.id!==902)}),{variantId:'',quantity:'2'});assert.deepEqual(memory.read({...product,id:502}),{variantId:'',quantity:'1'});memory.clear();assert.equal(memory.read(product).variantId,'');});
test('order detail displays stored canonical variant snapshot and explicit id when no snapshot exists',async()=>{const make=tag=>({tag,children:[],textContent:'',append(...items){this.children.push(...items);},replaceChildren(...items){this.children=items;}}),host=make('section');const root={createElement:make,querySelector:selector=>selector==='[data-commerce-load="orders"]'?host:null,addEventListener(){},removeEventListener(){}};const runtime={snapshot:()=>({session:{status:'authenticated'}}),orders:{detail:async()=>({id:88,payment_status:'PAID',status:'PROCESSING',total_amount:200,items:[{name:'Sandalye',variant_id:901,variant_selections:[{group:'Renk',value:'<Yeşil>'}],quantity:1},{name:'Sandalye',variant_id:902,quantity:1}]})}};const dom=createCommerceDOM({runtime,root});await dom.onRendered({name:'order',id:88});const text=host.children.flatMap(el=>el.children).map(el=>el.textContent).join('\n');assert.ok(text.includes('Renk: <Yeşil>'));assert.ok(text.includes('Ürün seçeneği #902'));assert.equal(orderVariantText({variant_id:null}),'');dom.dispose();});
const json=(body,status=200)=>new Response(status===204?null:JSON.stringify(body),{status,headers:{'Content-Type':'application/json'}});
test('review editor never offers a write when canonical eligibility is denied, missing, guest or contradictory',()=>{
 const denied={canReview:false,requiresAuth:false,code:'SELLER_REVIEW_HANDOFF_REQUIRED',message:'<Satıcı değerlendirmesi kapalı>'};
 for(const permission of [denied,undefined,{canReview:true},{canReview:true,requiresAuth:true,code:'ELIGIBLE'}])assert.ok(!renderReviewEditor(501,{authenticated:true,permission}).includes('data-commerce-form'));
 assert.ok(renderReviewEditor(501,{authenticated:true,permission:denied}).includes('&lt;Satıcı'));
 assert.ok(renderReviewEditor(501,{authenticated:false,permission:{canReview:true,requiresAuth:false,code:'ELIGIBLE'}}).includes('href="#/account"'));
 assert.ok(renderReviewEditor(501,{authenticated:true,permission:{canReview:true,requiresAuth:false,code:'ELIGIBLE'}}).includes('data-commerce-form="review"'));
});
for(const authenticated of [true,false])test(`review permission uses canonical scoped authenticated authority; guest=${!authenticated}`,async()=>{
 const permission={canReview:false,requiresAuth:false,code:'SELLER_REVIEW_HANDOFF_REQUIRED',message:'İş akışı henüz açık değil.'};
 const f=fixture({authenticated,custom:path=>path.endsWith('/reviews')?json({reviews:[],reviewPermission:permission}):path.endsWith('/questions')?json({questions:[]}):null});
 await f.runtime.initialize();const result=await f.runtime.reputation(501);
 assert.ok(f.calls.some(call=>call.path===(authenticated?'/api/theme-storefront/customer/products/501/reviews':'/api/theme-storefront/products/501/reviews')));
 assert.equal(result.reviewPermission.code,authenticated?'SELLER_REVIEW_HANDOFF_REQUIRED':'AUTH_REQUIRED');
 assert.equal(f.calls.filter(call=>call.method==='POST'&&call.path.endsWith('/reviews')).length,0);f.runtime.dispose();
});
function fixture({authenticated=true,custom}={}){
 const storage=storageOf(authenticated?{nova_user_token:'customer-a',nova_user_info:JSON.stringify({id:7,fullName:'Müşteri A'})}:{}),calls=[],root=new EventTarget();root.location={origin:'http://localhost'};
 let revision=0,items=[],checkoutRevision=0,checkoutItems=[];const response=()=>({key:'cart',exists:true,revision,payload:{cartSchemaVersion:2,items},migration:{status:'NONE',unresolvedItems:[]}});
 const fetchImpl=async(path,options={})=>{calls.push({path,...options,body:options.body?JSON.parse(options.body):undefined});const customResult=await custom?.(path,options);if(customResult)return customResult;
  if(path==='/api/theme-storefront/context')return json(context);
  if(path.startsWith('/api/theme-storefront/products?'))return json({products:[product],pagination:{total:1}});
  if(path==='/api/theme-storefront/products/501')return json(product);
  if(path==='/api/theme-storefront/categories')return json([{id:10,parent_id:null,name:'Giyim',slug:'giyim',image_url:'/image.png',product_count:1}]);
  if(path==='/api/theme-storefront/collections')return json([]);
  const base='/api/theme-storefront/customer';
  if(path===base+'/users/me')return json({id:7,fullName:'Müşteri A',role:'customer'});
  if(path===base+'/users/login')return json({token:'customer-a',user:{id:7,fullName:'Müşteri A'}});
  if(path===base+'/users/logout')return json(null,204);
  if(path===base+'/favorites')return json({productIds:[],favorites:[]});
  if(path===base+'/cart'){
   if(options.method==='PUT'){const body=JSON.parse(options.body);assert.equal(body.expectedRevision,revision);items=body.payload.items.map(item=>({...item,storeId:9,name:product.name,price:item.variantId===902?125:100,stock:30,imageUrl:'/image.png'}));revision++;}
   return json(response());
  }
  if(path===base+'/checkout'){
   if(options.method==='PUT'){const body=JSON.parse(options.body);assert.equal(body.expectedRevision,checkoutRevision);checkoutItems=body.payload.items.map(item=>({...item,storeId:9}));checkoutRevision++;}
   return json({...response(),key:'checkout',revision:checkoutRevision,payload:{cartSchemaVersion:2,items:checkoutItems}});
  }
  if(path==='/api/theme-storefront/quote')return json({totals:{currency:'TRY',subtotal:225,bundleDiscount:0,couponDiscount:0,shippingFee:25,total:250},items});
  throw Error('Unexpected request: '+path);
 };
 const navigate=[],runtime=createCustomerCommerceRuntime({fetchImpl,storage,root,navigate:hash=>navigate.push(hash)});
 return {runtime,storage,calls,root,navigate,setCart:(next)=>{items=next;revision++;},response};
}
test('B03 behavioral source provenance preserves exact bytes except declared import relocation',()=>{const provenance=require('../src/studio-integration/commerce-source-provenance.json');assert.equal(provenance.sourceCommit,'493164b26aee16ca25225e01aeb03d6e28f3f9aa');for(const row of provenance.entries){let source=fs.readFileSync(new URL('../../'+row.target,import.meta.url),'utf8');assert.equal(crypto.createHash('sha256').update(source).digest('hex'),row.targetSHA256);for(const [before,after]of Object.entries(row.importRelocations))source=source.replaceAll(after,before);assert.equal(crypto.createHash('sha256').update(source).digest('hex'),row.sourceSHA256);}});
test('fixed scoped routes reject arbitrary/provider/admin and traversal paths',()=>{for(const [before,after]of [['/api/users/me','/users/me'],['/api/shared-state/cart/finalize','/cart/finalize'],['/api/payments/agreements/preview','/agreements/preview']])assert.equal(commerceApiPath(before),'/api/theme-storefront/customer'+after);for(const path of ['/api/admin/me','/api/payments/initialize','https://evil/api/users/me','/api/users/../users/me','/api/%2e%2e/users/me'])assert.throws(()=>commerceApiPath(path),{code:'CUSTOMER_PATH_FORBIDDEN'});});
test('server activation and exact presentation identity are mandatory; scope cache leaves auth canonical',()=>{assert.equal(assertCustomerRuntimeContext(context),9);for(const value of [{...context,customerRuntime:{...context.customerRuntime,enabled:false}},{...context,presentation:{...descriptor,digest:'0'.repeat(64)}},{...context,commerceMode:'MARKETPLACE'}])assert.throws(()=>assertCustomerRuntimeContext(value));const raw=storageOf(),scoped=scopedCommerceStorage(raw,9);scoped.setItem('novastore_cart_v2_7','{}');scoped.setItem('nova_user_token','a');assert.ok(raw.values.has('theme-store:9:novastore_cart_v2_7'));assert.equal(raw.getItem('nova_user_token'),'a');});
test('guest catalog works without local demo cart and add redirects only through explicit account path',async()=>{const f=fixture({authenticated:false});await f.runtime.initialize();assert.equal(f.runtime.snapshot().session.status,'guest');assert.equal(f.calls.filter(c=>c.path.endsWith('/cart')).length,0);await assert.rejects(f.runtime.cart.add(501,901),{code:'CUSTOMER_SESSION_MISSING'});assert.equal(f.storage.values.size,0);await assert.rejects(f.runtime.checkout.initialize(),{code:'PAYMENT_PROVIDER_GATED'});f.runtime.dispose();});
test('two canonical variants survive CAS writes, store scope and removal; no client price authority',async()=>{const f=fixture();await f.runtime.initialize();await f.runtime.cart.add(501,901);await f.runtime.cart.add(501,902,2);assert.deepEqual(f.runtime.snapshot().cart.map(row=>[row.productId,row.variantId,row.quantity,row.price]),[[501,901,1,100],[501,902,2,125]]);await f.runtime.cart.setQuantity(501,901,0);assert.deepEqual(f.runtime.snapshot().cart.map(row=>row.variantId),[902]);for(const call of f.calls.filter(c=>c.path.endsWith('/cart')&&c.method==='PUT')){assert.equal(call.headers['X-Cart-Schema-Version'],'2');for(const row of call.body.payload.items)assert.deepEqual(Object.keys(row).sort(),['productId','quantity','storeId','variantId']);}f.runtime.dispose();});
test('foreign-store server cart is rejected rather than displayed, filtered or overwritten',async()=>{const f=fixture();f.setCart([{storeId:77,productId:501,variantId:901,quantity:1}]);await assert.rejects(f.runtime.initialize(),{code:'CART_STORE_IDENTITY_MISMATCH'});assert.deepEqual(f.runtime.snapshot().cart,[]);assert.equal(f.calls.filter(c=>c.method==='PUT').length,0);f.runtime.dispose();});
test('historical storage quantity can be reduced/removed without bypassing purchase limits',async()=>{const f=fixture();f.setCart([{storeId:9,productId:501,variantId:901,quantity:40,price:100,stock:0,unavailable:true}]);await f.runtime.initialize();await assert.rejects(f.runtime.checkout.quote(),{code:'CART_QUANTITY_INVALID'});await f.runtime.cart.setQuantity(501,901,35);assert.equal(f.runtime.snapshot().cart[0].quantity,35);await f.runtime.cart.setQuantity(501,901,0);assert.equal(f.runtime.snapshot().cart.length,0);f.runtime.dispose();});
test('account switch rejects in-flight product reply before any cart write and hides previous account',async()=>{let release;const gate=new Promise(resolve=>release=resolve);const f=fixture({custom:async(path)=>{if(path.endsWith('/products/501')){await gate;return json(product);}}});await f.runtime.initialize();const pending=f.runtime.cart.add(501,901);await new Promise(r=>setTimeout(r,0));f.storage.setItem('nova_user_token','customer-b');f.storage.setItem('nova_user_info',JSON.stringify({id:8}));f.root.dispatchEvent(new Event('novastore:auth-required'));release();await assert.rejects(pending,{code:'SHARED_STATE_PRINCIPAL_CHANGED'});assert.equal(f.runtime.snapshot().session.status,'guest');assert.deepEqual(f.runtime.snapshot().cart,[]);assert.equal(f.calls.filter(c=>c.method==='PUT').length,0);f.runtime.dispose();});
test('expired auth opens guest catalog without clearing scoped v2 authority or hiding login',async()=>{const f=fixture({custom:path=>path.endsWith('/users/me')?json({code:'TOKEN_EXPIRED'},401):null});f.storage.setItem('theme-store:9:novastore_cart_v2_7','persisted-authority');await f.runtime.initialize();assert.equal(f.runtime.snapshot().phase,'ready');assert.equal(f.runtime.snapshot().session.status,'guest');assert.equal(f.storage.getItem('theme-store:9:novastore_cart_v2_7'),'persisted-authority');assert.equal(f.storage.getItem('nova_user_token'),null);f.runtime.dispose();});
test('recoverable cart outage preserves catalog and normal account access but blocks writes until explicit retry',async()=>{let unavailable=true;const f=fixture({custom:path=>unavailable&&path.endsWith('/customer/cart')?json({code:'SERVICE_UNAVAILABLE'},503):null});await f.runtime.initialize();assert.equal(f.runtime.snapshot().phase,'ready');assert.equal(f.runtime.snapshot().catalog.products.length,1);assert.equal(f.runtime.snapshot().cartSync.phase,'blocked');await assert.rejects(f.runtime.cart.add(501,901),{code:'CART_SYNC_BLOCKED'});assert.equal(f.calls.filter(c=>c.method==='PUT').length,0);unavailable=false;await f.runtime.cart.retrySync();await f.runtime.cart.add(501,901);assert.equal(f.runtime.snapshot().cart.length,1);f.runtime.dispose();});
test('support read markers and pagination use canonical positive numeric message ids',async()=>{const id='11111111-2222-3333-4444-555555555555';const f=fixture({custom:path=>path.includes('/support/')?json({thread:{id},messages:[],nextAfter:null}):null});await f.runtime.initialize();await f.runtime.support.messages(id,100);await f.runtime.support.read(id,101);assert.ok(f.calls.some(c=>c.path.endsWith('?after=100')));assert.deepEqual(f.calls.find(c=>c.path.endsWith('/read')).body,{throughMessageId:101});assert.throws(()=>f.runtime.support.read(id,'101'),{code:'INVALID_REFERENCE'});f.runtime.dispose();});
test('engine bridge retains variant tuples, rejects ambiguous product-only quantity and emits server scope',async()=>{const f=fixture(),bridge=createCustomerEngineBridge(f.runtime,{projectCatalog:async catalog=>catalog,navigate:()=>{}});await bridge.initialize();await bridge.addToCart(501,901);await bridge.addToCart(501,902);assert.equal(bridge.snapshot().cart.length,2);assert.equal(bridge.snapshot().cart[1].unitPrice,12500);assert.equal(bridge.snapshot().scope.storeId,'9');await assert.rejects(bridge.setQuantity(501,0),{code:'VARIANT_IDENTITY_REQUIRED'});await bridge.setQuantity(501,0,901);assert.equal(bridge.snapshot().cart[0].variantId,902);bridge.dispose();});
test('derived renderers preserve originals but route cart, checkout, account and support to canonical tuple ports',()=>{const original=fs.readFileSync(new URL('../workshop-public/theme-library/shared/core.js',import.meta.url),'utf8');for(const id of ['nova-classic','nova-atelier']){const output=customerRuntimeSource(original,id);new vm.Script(output);assert.ok(output.includes("['product','cart','checkout','account','orders','order','success','support','contact','about','help','legal']"));assert.ok(output.includes('window.NovaThemeKitPorts.renderCustomerPage(name,route.id)'));assert.ok(output.includes('Number.isSafeInteger(line.unitPrice)'));}assert.throws(()=>customerRuntimeSource(original,'unknown'));});
test('pure catalog projection keeps canonical variant selection without a tenant or a legacy write owner',()=>{const source=fs.readFileSync(new URL('../workshop-public/theme-library/shared/theme-host-bridge.js',import.meta.url),'utf8'),sandbox={module:{exports:{}},Map,Set};vm.runInNewContext(customerProjectorSource(source),sandbox);const projected=sandbox.module.exports.projectCatalog({categories:[{id:'10',name:'Giyim',parentId:null}],products:[{...product,categoryId:'10',categoryIds:['10'],requiresVariantSelection:true,imageUrl:'/p.png'}]});assert.equal(projected.products[0].hostProductId,501);assert.equal(projected.products[0].purchaseRequiresHostSelection,true);assert.equal(projected.products[0].canOpenProduct,true);assert.equal(projected.products[0].price,10000);});
test('normal login/logout use scoped canonical session routes and preserve scoped persisted cart authority',async()=>{const f=fixture({authenticated:false});await f.runtime.initialize();await f.runtime.auth.login('customer@example.test','synthetic-password');assert.equal(f.runtime.snapshot().session.status,'authenticated');await f.runtime.cart.add(501,901);await f.runtime.auth.logout();assert.equal(f.runtime.snapshot().session.status,'guest');assert.equal(f.storage.getItem('nova_user_token'),null);assert.ok([...f.storage.values.keys()].some(key=>key.startsWith('theme-store:9:novastore_cart_v2_')));assert.ok(f.calls.some(c=>c.path.endsWith('/customer/users/logout')&&c.method==='POST'));f.runtime.dispose();});
test('checkout handoff keeps tuple identity and address agreement request sends identities only',async()=>{const totals={currency:'TRY',subtotal:100,bundleDiscount:0,couponDiscount:0,shippingFee:20,total:120};const f=fixture({custom:path=>path.endsWith('/agreements/preview')?json({schemaVersion:'checkout-agreements-v2',snapshotSha256:'a'.repeat(64),contextSha256:'b'.repeat(64),quote:{totals,items:[]},context:{totals},documents:[{slug:'terms',path:'/legal/terms',title:'Koşullar',version:'1',text:'Metin',sourceContentSha256:'c'.repeat(64),contentSha256:'d'.repeat(64)}]}):null});await f.runtime.initialize();await f.runtime.cart.add(501,901);await f.runtime.checkout.begin();assert.equal(f.navigate.at(-1),'#/checkout');const prepared=await f.runtime.checkout.prepare(42,'KOD');assert.equal(prepared.quote.totals.total,120);const sent=f.calls.find(c=>c.path.endsWith('/agreements/preview'));assert.deepEqual(sent.body,{addressId:42,cartItems:[{product_id:501,variant_id:901,quantity:1}],couponCode:'KOD'});assert.equal(f.calls.some(c=>c.path.includes('/payments/initialize')),false);f.runtime.dispose();});
test('finalization requires canonical paid proof then uses order receipt without client purchased quantities',async()=>{let paid=false;const f=fixture({custom:(path,options)=>{if(path.includes('/payments/status?'))return json({paymentRef:'paid-ref',orderId:88,providerFinalized:paid,commerceFinalized:paid,paymentStatus:paid?'PAID':'PENDING'});if(path.endsWith('/cart/finalize'))return json({...f.response(),revision:2,payload:{cartSchemaVersion:2,items:[]},finalizedOrderId:88,reused:false});}});await f.runtime.initialize();await f.runtime.cart.add(501,901);await assert.rejects(f.runtime.checkout.finalizePaid({paymentRef:'paid-ref',orderId:88}),{code:'PAYMENT_NOT_FINALIZED'});assert.equal(f.calls.some(c=>c.path.endsWith('/finalize')),false);paid=true;await f.runtime.checkout.finalizePaid({paymentRef:'paid-ref',orderId:88});const sent=f.calls.find(c=>c.path.endsWith('/finalize'));assert.deepEqual(sent.body,{expectedRevision:1,orderId:88});assert.equal(f.runtime.snapshot().cart.length,0);f.runtime.dispose();});
test('scoped support never accepts a client-selected recipient and uses finite UUID actions',async()=>{const threadId='11111111-2222-3333-4444-555555555555',messageId='77777777-2222-3333-4444-555555555555';const f=fixture({custom:path=>path.includes('/support/')?json(path.endsWith('/context')?{enabled:true,recipient:'SELLER',label:'Mağaza desteği'}:path.endsWith('/threads')?{threads:[]}:{thread:{id:threadId},messages:[]}):null});await f.runtime.initialize();await f.runtime.support.context();await f.runtime.support.threads();await f.runtime.support.messages(threadId);await f.runtime.support.send(threadId,{body:'Merhaba',clientMessageId:messageId});await assert.rejects(async()=>f.runtime.support.messages('../../admin'));assert.deepEqual(f.calls.find(c=>c.path.endsWith('/messages')).body,{body:'Merhaba',clientMessageId:messageId});f.runtime.dispose();});
test('customer cart markup escapes canonical labels and preserves separate remove targets',async()=>{const f=fixture();await f.runtime.initialize();f.setCart([901,902].map(id=>({storeId:9,productId:501,variantId:id,quantity:1,name:'<img src=x onerror=alert(1)>',variantLabel:'<script>',price:100,stock:30})));await f.runtime.cart.retrySync();const html=renderCommercePage(f.runtime,'cart');assert.ok(html.includes('&lt;img'));assert.ok(!html.includes('<script>'));assert.ok(html.includes('data-variant="901"'));assert.ok(html.includes('data-variant="902"'));assert.ok(html.includes('width="104"')===false);f.runtime.dispose();});
