import test from 'node:test';
import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {mountPlatformStudio,createPlatformClient,contextIdentity} from '../src/studio-integration/platform-bridge.js';
import {assetCacheKey} from '../src/studio-integration/asset-cache.js';
import {createLatestRequest} from '../src/studio-integration/latest-request.js';
import {createSessionBoundary} from '../../seller-theme-web/src/session-boundary.js';
const require=createRequire(import.meta.url),{createNativeExample}=require('../../services/themePlatformStudioDocument.js');
const deferred=()=>{let resolve,reject;const promise=new Promise((a,b)=>{resolve=a;reject=b;});return {promise,resolve,reject};};
test('failed save reaches host status and policy refresh cannot claim document persistence',async()=>fakeDOM(async env=>{
  const value=context(),errors=[],events=[];value.channels.web.base=structuredClone(value.channels.web.document);let writes=0;
  const denied=Object.assign(new Error('private-upstream'),{status:403,code:'THEME_PERMISSION_DENIED'});
  const mounted=await mountPlatformStudio(env.container,{context:value,contextPath:'/services/s1/editor-context',client:{get:async()=>value,write:async()=>{writes++;throw denied;}},onError:error=>errors.push(error),onContextUpdated:(_value,event)=>events.push(event)});
  try{
    await assert.rejects(env.configs[0].ports.saveDraft({channel:'web',expectedRevision:'1',document:value.channels.web.document.studio,idempotencyKey:'test'}),error=>error===denied);
    assert.deepEqual(errors,[denied]);assert.equal(writes,1);assert.deepEqual(events,[]);
    await mounted.refresh();assert.deepEqual(events,[{reason:'policy-refreshed'}]);assert.deepEqual(errors,[denied]);
  }finally{mounted.unmount();}
}));
const context=()=>({scope:{tenantId:'1',storeId:'2'},actor:{id:'seller:3'},serviceId:'s1',mode:'seller',readOnly:false,policyRevision:1,availableChannels:['web'],capabilities:{'theme.save_draft':{state:'EDITABLE'},'theme.preview':{state:'EDITABLE'}},channels:{web:{assignmentId:'a1',draftId:'d1',themeVersionId:'v1',revision:1,document:createNativeExample(),catalog:{products:[],categories:[]},commerce:{}}}});
async function fakeDOM(run,{mountError=false}={}){
  const saved={document:globalThis.document,window:globalThis.window,create:URL.createObjectURL,revoke:URL.revokeObjectURL};
  const created=[],revoked=[],configs=[],policies=[];let removed=0;
  globalThis.window=new EventTarget();
  globalThis.document={createElement:()=>({contentWindow:{NovaStoreStudio:{mount:async configuration=>{configs.push(configuration);if(mountError)throw Error('mount rejected');},updatePolicy:(...args)=>policies.push(args),unmount(){},navigate(){}}},remove(){removed++;}})};
  URL.createObjectURL=blob=>{const value='blob:test-'+created.length;created.push({value,blob});return value;};URL.revokeObjectURL=value=>revoked.push(value);
  const container={replaceChildren(frame){if(frame)queueMicrotask(()=>frame.onload?.());}};
  try{await run({container,created,revoked,configs,policies,removed:()=>removed});}finally{globalThis.document=saved.document;globalThis.window=saved.window;URL.createObjectURL=saved.create;URL.revokeObjectURL=saved.revoke;}
}
test('same packaged key has distinct URLs for two immutable versions',async()=>fakeDOM(async env=>{const value=context();value.availableChannels.push('app');value.channels.app={...structuredClone(value.channels.web),assignmentId:'a2',draftId:'d2',themeVersionId:'v2'};for(const channel of value.availableChannels)value.channels[channel].document.studio.blocks[0].image='package:theme-assets/shared/art.png';const fetched=[];const client={kind:'seller',blob:async path=>{fetched.push(path);return new Blob([path],{type:'image/png'});}};const mounted=await mountPlatformStudio(env.container,{client,context:value});assert.equal(fetched.length,2);const config=env.configs[0];assert.notEqual(config.assetURLs[assetCacheKey('package:theme-assets/shared/art.png','v1')],config.assetURLs[assetCacheKey('package:theme-assets/shared/art.png','v2')]);assert.deepEqual(config.themeVersions,{web:'v1',android:'v2'});mounted.unmount();assert.equal(env.revoked.length,2);}));
test('initial module mount failure revokes all created image URLs',async()=>fakeDOM(async env=>{const value=context();value.channels.web.document.studio.blocks[0].image='package:theme-assets/shared/art.png';await assert.rejects(mountPlatformStudio(env.container,{client:{kind:'seller',blob:async()=>new Blob(['x'],{type:'image/png'})},context:value}),/mount rejected/);assert.equal(env.created.length,1);assert.equal(env.revoked.length,1);assert.equal(env.removed(),1);},{mountError:true}));
test('later asset failure revokes earlier URLs and ignores late asset completion',async()=>fakeDOM(async env=>{const value=context(),late=deferred();value.channels.web.document.studio.blocks[0].image='package:theme-assets/shared/first.png';value.channels.web.document.studio.blocks[0].mobileImage='package:theme-assets/shared/late.png';value.channels.web.document.studio.blocks[1].image='package:theme-assets/shared/fail.png';const client={kind:'seller',blob:path=>path.includes('late.png')?late.promise:path.includes('fail.png')?Promise.reject(Error('asset failed')):Promise.resolve(new Blob(['x'],{type:'image/png'}))};await assert.rejects(mountPlatformStudio(env.container,{client,context:value}),/asset failed/);const count=env.created.length;assert.equal(env.revoked.length,count);late.resolve(new Blob(['late'],{type:'image/png'}));await new Promise(resolve=>setImmediate(resolve));assert.equal(env.created.length,count);assert.equal(env.configs.length,0);}));
test('abort during initial asset load cannot create URLs or mount old UI',async()=>fakeDOM(async env=>{const value=context(),late=deferred(),controller=new AbortController();value.channels.web.document.studio.blocks[0].image='package:theme-assets/shared/art.png';const promise=mountPlatformStudio(env.container,{client:{kind:'seller',blob:()=>late.promise},context:value,signal:controller.signal});controller.abort();late.resolve(new Blob(['x'],{type:'image/png'}));await assert.rejects(promise,/kapandı/);assert.equal(env.created.length,0);assert.equal(env.configs.length,0);}));
test('withdrawal during policy refresh closes access and all existing ports',async()=>fakeDOM(async env=>{const value=context(),fresh={...structuredClone(value),availableChannels:[],channels:{}};let writes=0,errors=0;const mounted=await mountPlatformStudio(env.container,{client:{get:async()=>fresh,write:async()=>{writes++;}},context:value,contextPath:'/services/s1/editor-context',onError:()=>errors++});await mounted.refresh();assert.equal(env.policies.at(-1)[0].read,false);await assert.rejects(env.configs[0].ports.readDraft({channel:'web'}),/kapandı/);await assert.rejects(env.configs[0].ports.uploadAsset('x'),/kapandı/);assert.equal(writes,0);assert.equal(errors,1);mounted.unmount();}));
test('authority identity changes for actor, assignment, version, tenant, or readonly projection',()=>{const value=context();for(const mutate of [x=>x.actor.id='other',x=>x.scope.tenantId='other',x=>x.channels.web.assignmentId='other',x=>x.channels.web.themeVersionId='other',x=>x.readOnly=true]){const other=structuredClone(value);mutate(other);assert.notEqual(contextIdentity(value),contextIdentity(other));}const next=structuredClone(value);next.channels.web.revision++;next.policyRevision++;assert.equal(contextIdentity(value),contextIdentity(next),'revision changes remain CAS rather than discarding unsaved edits');});
test('transport allows encoded package filenames but rejects traversal',async()=>{const prior=globalThis.fetch;const paths=[];globalThis.fetch=async path=>{paths.push(path);return {ok:true,blob:async()=>new Blob(['x'],{type:'image/png'})};};try{const client=createPlatformClient({kind:'admin',token:()=> 'memory-only'});await client.blob('/versions/v1/assets/theme-assets%2Fshared%2Fart.png');assert.equal(paths.length,1);await assert.rejects(client.blob('/versions/v1/assets/../art.png'));await assert.rejects(client.blob('/versions/v1/assets/%2e%2e%2fart.png'));assert.equal(paths.length,1);}finally{globalThis.fetch=prior;}});
test('old request 401 cannot expire a newly authenticated token',async()=>{const prior=globalThis.fetch,late=deferred();let token='old',expired=0;globalThis.fetch=()=>late.promise;try{const client=createPlatformClient({kind:'seller',token:()=>token,onUnauthorized:issued=>{if(issued===token)expired++;}});const old=client.get('/assignments');token='new';late.resolve({ok:false,status:401,json:async()=>({code:'EXPIRED'})});await assert.rejects(old);assert.equal(expired,0);}finally{globalThis.fetch=prior;}});
test('late refresh and history results cannot apply after logout or a new login',async()=>{const boundary=createSessionBoundary(),pending=deferred();let credentials=null,history=null;const old=boundary.advance(),refresh=pending.promise.then(value=>boundary.apply(old,()=>{credentials=value;history=['private-old-row'];}));boundary.advance();const current=boundary.advance();boundary.apply(current,()=>{credentials='new-session';history=[];});pending.resolve('old-refreshed-session');await refresh;assert.equal(credentials,'new-session');assert.deepEqual(history,[]);});
test('changed quote inputs reject a previous total even if a newer request is pending',async()=>{const gate=createLatestRequest(),old=deferred(),next=deferred();let visible=null;const first=gate.begin(),p1=old.promise.then(value=>{if(gate.current(first))visible=value;});gate.invalidate();const second=gate.begin(),p2=next.promise.then(value=>{if(gate.current(second))visible=value;});old.resolve('old quantity total');await p1;assert.equal(visible,null);next.resolve('new quantity total');await p2;assert.equal(visible,'new quantity total');gate.invalidate();assert.equal(gate.current(second),false);});
test('workspace policy closure invalidates late history even while the auth session is unchanged',async()=>{const boundary=createSessionBoundary(),history=createLatestRequest(),late=deferred(),authGeneration=boundary.capture(),request=history.begin();let visible=null;const pending=late.promise.then(value=>{if(boundary.current(authGeneration)&&history.current(request))visible=value;});history.invalidate();late.resolve(['private pre-revocation revision']);await pending;assert.equal(boundary.current(authGeneration),true);assert.equal(visible,null);});
