import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import vm from 'node:vm';
import {createRequire} from 'node:module';
import {atelierRuntimeSource} from '../src/studio-integration/atelier-runtime-source.mjs';
import {trustedThemeKit} from '../scripts/theme-kit-plugin.mjs';
import {trustedPresentation} from '../src/studio-integration/theme-kit-adapter.js';
import {applyAtelierDocument} from '../src/studio-integration/atelier-dom.js';
import {assertPresentationEditorChange,isPresentationEditorHost} from '../src/studio-integration/presentation-editor-policy.js';
import {channelCapabilities,channelPolicyConfig} from '../src/studio-integration/platform-bridge.js';
const require=createRequire(import.meta.url),atelier=require('../../theme-platform/packages/nova-atelier-studio-web-v1.json'),classic=require('../../theme-platform/packages/nova-classic-studio-web-v1_1.json');
const guard=require('../../services/themePlatformPresentationEditGuard');
const host={scope:{tenantId:'1',storeId:'2'},availableChannels:['web'],presentations:{web:atelier.renderer.presentation}};
test('Atelier exact source identity selects only web; unknown identities never obtain editor permissions',()=>{assert.equal(trustedPresentation(atelier.renderer.presentation).sourceThemeId,'02-atelier');assert.equal(trustedPresentation(atelier.renderer.presentation,'android'),null);assert.equal(isPresentationEditorHost(host),true);assert.equal(isPresentationEditorHost({...host,presentations:{web:{...atelier.renderer.presentation,digest:'0'.repeat(64)}}}),false);assert.equal(isPresentationEditorHost({...host,scope:null}),false);});
test('Atelier editor and server agree on supported fields and reject template/source substitution',()=>{const before=atelier.document.studio,next=structuredClone(before);next.blocks[0].title='BaÄŸÄ±msÄ±z koleksiyon';next.blocks[3].description='Yeni maÄŸaza Ã¶ykÃ¼sÃ¼';assert.equal(assertPresentationEditorChange(before,next,before,host,'web'),true);guard.validatePresentationDocument(atelier.renderer.presentation,atelier.document,{schemaVersion:2,studio:next});for(const change of [s=>s.blocks.reverse(),s=>{s.blocks[1].title='Gizli deÄŸiÅŸim';},s=>{s.blocks[3].image=s.blocks[0].image;},s=>{s.design.elements.push({id:'productTitle',content:{text:'YanlÄ±ÅŸ Ã¼rÃ¼n'}});},s=>{s.chrome.header.sticky=false;}]){const draft=structuredClone(before);change(draft);assert.throws(()=>assertPresentationEditorChange(before,draft,before,host,'web'),{code:'THEME_PRESENTATION_EDIT_UNSUPPORTED'});}assert.throws(()=>assertPresentationEditorChange(before,classic.document.studio,before,host,'web'),{code:'THEME_PRESENTATION_EDIT_UNSUPPORTED'});});
test('Atelier derived engine retains original editorial home/header/fashion cards/footer/PDP templates',()=>{const source=fs.readFileSync(new URL('../workshop-public/theme-library/shared/core.js',import.meta.url),'utf8');for(const input of [source.replace(/\r\n/g,'\n'),source.replace(/\r?\n/g,'\r\n')]){const output=atelierRuntimeSource(input);new vm.Script(output);for(const name of ['legacyClassicDetail','productCard','visualCategories','campaign','home','header']){const start=input.indexOf('  function '+name+'('),end=input.indexOf('\n  function ',start+1);assert.ok(start>=0,name);assert.ok(output.includes(input.slice(start,end)),name);}assert.ok(output.includes('return legacyClassicDetail(id);'));assert.ok(!output.includes('return legacyClassicHostedDetail(id);'));assert.ok(!output.includes("if(hostBridge)return hostedFooter();"));}assert.throws(()=>atelierRuntimeSource(source.replace('return legacyClassicHostedDetail(id);','return broken();')));});
test('Atelier build ships original fashion presentation and no demo catalog or foreign hero image',()=>{const assets=[];trustedThemeKit().generateBundle.call({emitFile:a=>assets.push(a)});const config=JSON.parse(assets.find(a=>a.fileName==='theme-kit/nova-atelier/presentation.json').source);assert.equal(config.style,'editorial');assert.equal(config.cardStyle,'fashion');assert.equal(config.id,'02-atelier');for(const key of ['products','cats','productAtlas','heroImage'])assert.equal(Object.hasOwn(config,key),false);assert.equal(assets.filter(a=>a.fileName==='theme-kit/core.css').length,1);assert.ok(assets.find(a=>a.fileName==='theme-kit/classic-runtime.js'));});
test('Atelier canonical data stays intact while authored hero/photo/CTA and visibility update in place',()=>{
 const style={setProperty(){}},heading={textContent:'Old'},paragraph={textContent:'Old'},image={src:'old',removeAttribute(key){delete this[key];}},link={href:'old',removeAttribute(key){delete this[key];}},kicker={textContent:'Old'};
 const hero={setAttribute(){},querySelector:s=>({'.campaign-copy h1':heading,'.campaign-copy p':paragraph,'.campaign-photo':image,'.hero-actions .button':link,'.eyebrow':kicker}[s]||null)};
 const root={documentElement:{style},body:{style},querySelectorAll:()=>[],querySelector:s=>s==='.campaign-editorial'?hero:null};const doc=structuredClone(atelier.document.studio);doc.blocks[0].title='Yeni koleksiyon';doc.blocks[0].target='category:12';
 applyAtelierDocument(root,doc,value=>value?'blob:owned-image':'',{products:[],categories:[{id:12,name:'Elbiseler'}]});assert.equal(heading.textContent,'Yeni koleksiyon');assert.equal(image.src,'blob:owned-image');assert.equal(link.href,'#/catalog?category=Elbiseler');assert.equal(hero.hidden,false);
 doc.blocks[0].target='category:99';doc.blocks[0].image='';doc.blocks[0].enabled=false;applyAtelierDocument(root,doc,()=>'',{products:[],categories:[]});assert.equal(link.href,undefined);assert.equal(image.src,undefined);assert.equal(image.hidden,true);assert.equal(hero.hidden,true);
});
test('channel policy uses exact renderer intersection, preserves explicit revocation and legacy minimum only as fallback',()=>{const top={'theme.save_draft':{state:'READ_ONLY'}},web={'theme.save_draft':{state:'EDITABLE'},'theme.preview':{state:'EDITABLE'}},value={availableChannels:['web','app'],capabilities:top,channels:{web:{effectivePolicy:{capabilities:web}},app:{effectivePolicy:{capabilities:{}}}}};assert.equal(channelCapabilities(value,'web'),web);assert.deepEqual(channelCapabilities(value,'android'),{});const config=channelPolicyConfig(value);assert.equal(config.web.capabilities.edit,true);assert.equal(config.android.capabilities.edit,false);assert.equal(channelCapabilities({...value,channels:{}},'web'),top);const denied=channelPolicyConfig({...value,readOnly:true});assert.equal(denied.web.capabilities.edit,false);assert.equal(denied.web.capabilities.preview,true);});
test('active channel changes and policy refresh cannot reuse a revoked channel grant',async()=>{const context=await import('../src/studio-integration/context.js?closure-policy');const calls=[];context.configureStudioHost({scope:{tenantId:'1',storeId:'2'},actor:{id:'seller'},ports:{},availableChannels:['web','android'],activeChannel:'web',capabilities:{read:true,edit:true},policy:{'theme.logo':{state:'EDITABLE'}},channelPolicies:{web:{capabilities:{read:true,edit:true},policy:{'theme.logo':{state:'EDITABLE'}}},android:{capabilities:{read:true,edit:false},policy:{'theme.logo':{state:'READ_ONLY'}}}}});context.attachStudioSession({updateCapabilities:(flags,policy)=>calls.push({flags,policy})});context.setStudioChannel('android');assert.equal(context.capabilityWritable('theme.logo'),false);context.setStudioChannel('web');assert.equal(context.capabilityWritable('theme.logo'),true);context.updateStudioPolicy({read:true,edit:false},{},{},{web:{capabilities:{read:true,edit:false},policy:{}},android:{capabilities:{read:true,edit:false},policy:{}}});assert.equal(context.capabilityVisible('theme.logo'),false);context.setStudioChannel('android');assert.equal(context.capabilityVisible('theme.logo'),false);context.updateStudioPolicy({read:false,edit:false},{},{},{});context.setStudioChannel('web');assert.equal(context.getStudioHost().capabilities.read,false);assert.ok(calls.length>=5);});

test('original Atelier PDP receives canonical feature details without invented demo specifications',()=>{const source=fs.readFileSync(new URL('../workshop-public/theme-library/shared/core.js',import.meta.url),'utf8'),output=atelierRuntimeSource(source),statement=output.split(/\r?\n/).find(line=>line.trim().startsWith('const products = new Map(T.products.map'));assert.ok(statement);const products=vm.runInNewContext(statement+';products',{T:{products:[{id:'1',features:['Pamuk']},{id:'2',features:[]}]},hostBridge:{},Map});assert.equal(JSON.stringify(products.get('1').details),JSON.stringify([['Özellik 1','Pamuk']]));assert.equal(products.get('2').details.length,0);});
