import React,{useEffect,useRef,useState} from 'react';
import {getStudioHost} from './context.js';
import {createLatestRequest} from './latest-request.js';
const money=value=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(value);
const totalLabels={subtotal:'Ürünler toplamı',bundleDiscount:'Kampanya indirimi',couponDiscount:'Kupon indirimi',shippingFee:'Teslimat ücreti',total:'Ödenecek tutar'};
export default function CanonicalProduct({id,onClose,onProduct}){
  const host=getStudioHost(),[data,setData]=useState(null),[error,setError]=useState(''),[variantId,setVariantId]=useState(''),[quantity,setQuantity]=useState(1),[coupon,setCoupon]=useState(''),[quote,setQuote]=useState(null),[busy,setBusy]=useState(false),generation=useRef(0);
  const quotes=useRef(createLatestRequest()).current;
  function invalidateQuote(){quotes.invalidate();setQuote(null);setBusy(false);}
  useEffect(()=>{const version=++generation.current;setData(null);setError('');setVariantId('');setQuantity(1);setCoupon('');invalidateQuote();host.ports.loadProduct({channel:host.availableChannels[0],productId:id}).then(result=>{if(version===generation.current)setData(result);}).catch(e=>{if(version===generation.current)setError(e.message);});return()=>{generation.current++;quotes.invalidate();};},[id]);
  const product=data?.product,variant=product?.variants?.find(item=>String(item.id)===variantId),price=variant?.price??product?.price,stock=variant?.availableStock??product?.stock,maxQuantity=Math.min(20,Math.max(0,Math.floor(Number(stock)||0))),validQuantity=Number.isSafeInteger(quantity)&&quantity>=1&&quantity<=maxQuantity;
  async function calculate(){const version=generation.current,request=quotes.begin();const active=()=>version===generation.current&&quotes.current(request);setBusy(true);setError('');try{const result=await host.ports.quote({channel:host.availableChannels[0],body:{items:[{productId:product.id,...(variant?{variantId:variant.id}:{}),quantity}],...(coupon.trim()?{couponCode:coupon.trim()}:{})}});if(active())setQuote(result);}catch(e){if(active()){setQuote(null);setError(e.message);}}finally{if(active())setBusy(false);}}
  return <section className="theme-pdp shell" aria-label="Ürün detayı"><button onClick={onClose}>Mağazaya dön</button>{error&&<p role="alert">{error}</p>}{!product?<p>{error?'Ürün bilgisi şu anda gösterilemiyor. Mağazaya dönüp yeniden deneyebilirsiniz.':'Ürün bilgisi yükleniyor…'}</p>:<><div className="theme-pdp-main"><div className="theme-pdp-gallery">{product.image_url?<img src={product.image_url} alt={product.name}/>:<div className="theme-product-placeholder">Ürün görseli bulunmuyor</div>}{(product.media||[]).filter(item=>item.media_url!==product.image_url).map(item=><img key={item.id} src={item.media_url} alt={product.name}/>)}</div><div><small>{host.commerce?.store?.name}</small><h1>{product.name}</h1><p className="theme-price">{money(price)}</p>{product.old_price>price&&<del>{money(product.old_price)}</del>}<p>{product.average_rating} / 5 · {product.review_count} değerlendirme</p><p>{stock>0?`${stock} adet stokta`:'Stokta yok'}</p><p>{product.description}</p>{product.variant_selection_required&&<label>Ürün seçeneği<select value={variantId} onChange={e=>{setVariantId(e.target.value);invalidateQuote();}}><option value="">Seçenek seçin</option>{product.variants.map(item=><option key={item.id} value={item.id} disabled={!item.purchasable}>{item.selections.map(option=>`${option.group}: ${option.value}`).join(' · ')} · {money(item.price)} · {item.availableStock} adet</option>)}</select></label>}<label>Adet<input aria-label="Ürün adedi" type="number" min="1" max={maxQuantity||1} step="1" value={quantity} onChange={e=>{setQuantity(Number(e.target.value));invalidateQuote();}}/></label><label>Kupon<input aria-label="Kupon kodu" maxLength={80} value={coupon} onChange={e=>{setCoupon(e.target.value);invalidateQuote();}}/></label><button disabled={busy||!validQuantity||(product.variant_selection_required&&!variant)} onClick={calculate}>Sepet tutarını hesapla</button><button disabled>Sipariş verme kullanıma açık değil</button></div></div>
    <section><h2>Teslimat ve iade</h2><p>{host.commerce?.store?.shipping_summary||'Bu mağazanın teslimat özeti henüz tanımlanmamış.'}</p><p>{host.commerce?.store?.return_summary||'Bu mağazanın iade özeti henüz tanımlanmamış.'}</p></section>
    {quote&&<section className="theme-cart-preview"><h2>Sunucudan hesaplanan sepet</h2>{quote.items.map(item=><p key={`${item.productId}-${item.variantId}`}>{item.name} × {item.quantity} · {money(item.line_total)}</p>)}<dl>{Object.entries(totalLabels).filter(([key])=>Object.hasOwn(quote.totals,key)).map(([key,label])=><React.Fragment key={key}><dt>{label}</dt><dd>{money(quote.totals[key])}</dd></React.Fragment>)}</dl><p>Kupon: {quote.coupon.applied?'Uygulandı':'Uygulanmadı'}</p><p>Stok ayrılmadı. Sipariş veya ödeme oluşturulmadı.</p></section>}
    <section><h2>Müşteri değerlendirmeleri</h2>{(data.reviews||[]).length?(data.reviews||[]).map(review=><article key={review.id}><strong>{review.full_name} · {review.rating} / 5</strong><p>{review.comment}</p></article>):<p>Yayımlanmış değerlendirme bulunmuyor.</p>}</section>
    <section><h2>Soru ve cevap</h2>{(data.questions||[]).length?data.questions.map(question=><article key={question.id}><strong>{question.user_name}</strong><p>{question.question}</p><p>{question.answer}</p></article>):<p>Yanıtlanmış soru bulunmuyor.</p>}</section>
    <section><h2>Bu mağazadan diğer ürünler</h2><div className="theme-related">{data.recommendations.map(item=><button key={item.id} onClick={()=>onProduct(item.id)}>{item.name}<strong>{money(item.price)}</strong></button>)}</div></section>
    {host.commerce?.store?.legal_refs?.map(ref=><section key={`${ref.type}-${ref.version}`}><h2>{ref.public_trade_name||ref.public_legal_name}</h2><p>{ref.disclosure}</p></section>)}
    </>}</section>;
}
