import {assertProductVariant,normalizeVariantId} from './commerce-variant-contract.js';
import {renderProductGallery} from './commerce-layout.js';
export const escapeCommerceText=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const esc=escapeCommerceText;
const money=value=>typeof value==='number'&&Number.isFinite(value)?new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(value):'Fiyat doğrulanamadı';
const image=value=>{if(typeof value!=='string')return '';if(/^\/(?!\/)/.test(value)&&!/[\\\u0000-\u0020]/.test(value))return value;try{const url=new URL(value);return url.protocol==='https:'&&!url.username&&!url.password?url.href:'';}catch{return '';}};
const action=(name,label,attributes='',style='button secondary')=>`<button type="button" class="${style}" data-commerce-action="${name}" ${attributes}>${esc(label)}</button>`;
const status='<p data-commerce-status role="status" aria-live="polite"></p>';
const shell=(title,body)=>`<div class="container page commerce-page"><div class="breadcrumbs"><a href="#/home">Ana sayfa</a> / ${esc(title)}</div><h1>${esc(title)}</h1>${status}${body}</div>`;
const login=()=>`<form data-commerce-form="login" class="profile-card commerce-login"><label class="field">E-posta<input name="email" type="email" autocomplete="username" required maxlength="254"></label><label class="field">Şifre<input name="password" type="password" autocomplete="current-password" required maxlength="1024"></label><button class="button" type="submit">Giriş yap</button></form>`;
const labels={PENDING:'Bekliyor',PAID:'Ödendi',FAILED:'Başarısız',CANCELLED:'İptal edildi',PROCESSING:'Hazırlanıyor',SHIPPED:'Kargoda',DELIVERED:'Teslim edildi'};
const statusText=value=>labels[value]||String(value||'Bilgi bekleniyor');
export function renderReviewEditor(productId,{authenticated,permission}={}){
 if(!authenticated)return '<p class="commerce-review-permission">Değerlendirme yapabilmek için <a href="#/account">giriş yap</a>.</p>';
 if(permission?.canReview!==true||permission.requiresAuth!==false||permission.code!=='ELIGIBLE')return `<p class="commerce-review-permission">${esc(typeof permission?.message==='string'&&permission.message?permission.message:'Değerlendirme yetkisi doğrulanamadı. Daha sonra yeniden deneyebilirsin.')}</p>`;
 return `<form data-commerce-form="review" data-product="${esc(productId)}"><label class="field">Puan<select name="rating">${[5,4,3,2,1].map(value=>`<option value="${value}">${value}</option>`).join('')}</select></label><label class="field">Değerlendirmen<textarea name="comment" maxlength="4000" required></textarea></label><button class="button secondary">Değerlendirme gönder</button></form>`;
}
export function orderVariantText(line){
 const selections=Array.isArray(line.variant_selections)?line.variant_selections.filter(value=>value&&typeof value.group==='string'&&typeof value.value==='string').map(value=>`${value.group}: ${value.value}`).join(' · '):'';
 if(selections)return selections;
 if(typeof line.variant_label==='string'&&line.variant_label.trim())return line.variant_label;
 const id=normalizeVariantId(line.variant_id);return id?`Ürün seçeneği #${id}`:'';
}
export function createProductSelectionMemory(){
 let selection=null;
 return {write(productId,variantId,quantity){selection={productId:Number(productId),variantId:normalizeVariantId(variantId),quantity:String(quantity)};},clear(){selection=null;},read(product){if(!selection||selection.productId!==Number(product.id))return{variantId:'',quantity:'1'};const variant=product.variants?.find(row=>Number(row.id)===selection.variantId&&row.purchasable&&row.availableStock>0);return{variantId:variant?String(variant.id):'',quantity:selection.quantity};}};
}
export function renderCommercePage(runtime,name,id){
 const s=runtime.snapshot(),authenticated=s.session.status==='authenticated';
 if(name==='product')return shell('Ürün bilgileri','<section data-commerce-product-pending aria-busy="true"><p role="status">Ürün bilgileri doğrulanıyor…</p></section>');
 if(['help','contact','about','legal'].includes(name)){const store=s.context.store;if(name==='legal')return shell('Mağaza koşulları',`<section data-commerce-load="legal" data-type="${esc(id||'')}">İçerik yükleniyor…</section>`);return shell(name==='contact'?'İletişim':name==='about'?'Mağazamız':'Yardım merkezi',`<section class="profile-card"><h2>${esc(store.name)}</h2><p>${esc(store.description)}</p>${Object.entries(store.contact||{}).filter(([,value])=>typeof value==='string'&&value).map(([,value])=>`<p>${esc(value)}</p>`).join('')}<h3>Teslimat</h3><p>${esc(store.shipping_summary)}</p><h3>İade</h3><p>${esc(store.return_summary)}</p><a class="button secondary" href="#/support">Destek mesajları</a><nav class="commerce-actions">${(store.legal_documents||[]).map(doc=>`<a href="#/legal/${esc(doc.type)}">${esc(({privacy:'Gizlilik',terms:'Kullanım koşulları','distance-sales':'Mesafeli satış',returns:'İade',shipping:'Teslimat',kvkk:'KVKK',cookie:'Çerez politikası',contact:'İletişim','business-information':'İşletme bilgileri'})[doc.type]||doc.type)}</a>`).join('')}</nav></section>`);}
 if(name==='account')return shell('Hesabım',authenticated?`<section class="profile-card"><h2>${esc(s.session.user.fullName)}</h2><p>${esc(s.session.user.email)}</p><nav class="commerce-actions"><a class="button secondary" href="#/orders">Siparişlerim</a><a class="button secondary" href="#/favorites">Favorilerim</a><a class="button secondary" href="#/support">Destek mesajları</a>${action('logout','Çıkış yap')}</nav><h3>Adreslerim</h3><div data-commerce-load="addresses">Adresler yükleniyor…</div></section>`:login());
 if(!authenticated)return shell(({cart:'Sepetim',checkout:'Teslimat ve ödeme',orders:'Siparişlerim',order:'Sipariş detayı',success:'Sipariş sonucu',support:'Destek mesajları'})[name]||'Hesabım',`<p>Bu bilgileri görmek için hesabına giriş yap.</p>${login()}`);
 if(name==='cart'){
  const rows=s.cart.map(item=>{const key=`data-product="${item.productId}" data-variant="${item.variantId??''}"`,url=image(item.imageUrl);return `<article class="cart-item commerce-cart-row">${url?`<img src="${esc(url)}" alt="${esc(item.name||'Ürün')}" width="104" height="104">`:''}<div><a href="#/product/${item.productId}"><h3>${esc(item.name||'Ürün #'+item.productId)}</h3></a><p>${esc(item.variantLabel||'')}</p><strong>${esc(money(item.price))}</strong>${item.unavailable?'<p class="error">Bu seçenek şu anda satın alınamıyor. Sepetten kaldırabilir veya miktarını azaltabilirsin.</p>':''}<div class="commerce-quantity">${action('quantity','−',`${key} data-quantity="${Math.max(0,item.quantity-1)}" aria-label="Adedi azalt"`)}<output aria-label="Adet">${item.quantity}</output>${action('quantity','+',`${key} data-quantity="${item.quantity+1}" aria-label="Adedi artır" ${item.unavailable?'disabled':''}`)}${action('quantity','Kaldır',`${key} data-quantity="0"`)}</div></div></article>`;}).join('');
  const pending=[...s.migration.unresolvedItems.map(row=>({...row,local:false})),...s.migration.localItems.map(row=>({...row,local:true}))];
  const review=pending.length?`<section class="profile-card" role="alert"><h2>Önceki sepetini gözden geçir</h2><p>Bu ürünlere otomatik seçenek atanmadı. Ürünü açıp yeniden seçebilir veya eski kaydı kaldırabilirsin.</p>${pending.map(row=>`<p>Ürün #${esc(row.productId)} · ${esc(row.quantity)} adet <a href="#/product/${esc(row.productId)}">Ürünü aç</a> ${action('resolve-legacy','Eski kaydı kaldır',`data-product="${esc(row.productId)}" data-variant="${esc(row.variantId??'')}" data-local="${row.local}"`)}</p>`).join('')}</section>`:'';
  return shell('Sepetim',`${review}${s.cartSync.phase!=='ready'?`<section class="profile-card" role="alert"><p>Sepet eşitlemesi tamamlanmadı. Kayıtların korunuyor.</p>${action('sync','Yeniden eşitle')}</section>`:''}<div class="cart-layout"><section>${rows||'<p>Sepetin şu anda boş.</p><a href="#/catalog" class="button">Ürünleri keşfet</a>'}</section><aside class="summary-card"><h2>Sepet özeti</h2><p>${s.cart.reduce((sum,item)=>sum+item.quantity,0)} ürün</p><p>Güncel toplam ve teslimat bedeli sunucudan hesaplanır.</p>${action('checkout','Teslimat ve ödeme',s.cart.length&&s.cartSync.phase==='ready'&&!pending.length?'':'disabled','button full')}</aside></div>`);
 }
 if(name==='checkout')return shell('Teslimat ve ödeme',`<div class="cart-layout"><section><form data-commerce-form="prepare" class="profile-card"><label class="field">Teslimat adresi<select name="addressId" data-commerce-addresses required><option value="">Adresler yükleniyor…</option></select></label><label class="field">Kupon kodu<input name="coupon" maxlength="80" autocomplete="off"></label><button type="submit" class="button">Güncel tutarı ve sözleşmeleri göster</button></form><section data-commerce-agreements></section></section><aside class="summary-card"><h2>Ödeme durumu</h2><p data-commerce-capability>Ödeme yeteneği kontrol ediliyor…</p><p>Bu sürüm gerçek ödeme başlatmaz.</p><a href="#/cart" class="button secondary">Sepete dön</a></aside></div>`);
 if(name==='orders'||name==='order'||name==='success')return shell(name==='orders'?'Siparişlerim':'Sipariş detayı',`<section data-commerce-load="orders" data-order="${normalizeVariantId(id)||''}">Siparişler yükleniyor…</section>`);
 if(name==='support')return shell('Destek mesajları','<section class="profile-card" data-commerce-load="support">Destek bağlantısı kontrol ediliyor…</section>');
 throw Object.assign(Error('Müşteri sayfası desteklenmiyor.'),{code:'CUSTOMER_ROUTE_UNSUPPORTED'});
}
export function createCommerceDOM({runtime,root=document,navigate=hash=>location.assign(hash),refresh=()=>{},onImages=()=>{},productTemplate=()=>'',onProductMounted=()=>{}}){
 let generation=0,disposed=false,currentRoute=null,pendingNotice=null;const selection=createProductSelectionMemory();
 const active=ticket=>!disposed&&ticket===generation;
 const node=(tag,text,className)=>{const result=root.createElement(tag);if(text!==undefined)result.textContent=String(text);if(className)result.className=className;return result;};
 let toastTimer,operationSequence=0;
 const message=text=>{const target=root.querySelector('[data-commerce-status]')||root.querySelector('[data-commerce-product-status]');if(target)target.textContent=text;const toast=root.querySelector('#toast');if(toast){clearTimeout(toastTimer);toast.textContent=text;toast.classList.add('visible');toastTimer=setTimeout(()=>toast.classList.remove('visible'),3500);}};
 async function perform(button,fn){const ticket=generation,operation=++operationSequence;if(button)button.disabled=true;message('İşlem tamamlanıyor…');try{const completed=await fn(ticket);if(active(ticket))message(typeof completed==='string'?completed:'İşlem tamamlandı.');}catch(error){if(active(ticket)){message(error.message||'İşlem tamamlanamadı.');if(['CUSTOMER_SESSION_MISSING','SHARED_STATE_PRINCIPAL_CHANGED'].includes(error.code))navigate('#/account');}}finally{if(button?.isConnected)button.disabled=false;if(!disposed&&operation===operationSequence)for(const selector of ['[data-commerce-status]','[data-commerce-product-status]','#toast']){const target=root.querySelector(selector);if(target?.textContent==='İşlem tamamlanıyor…'){target.textContent='';if(selector==='#toast'){clearTimeout(toastTimer);target.classList.remove('visible');}}}}}
 async function loadAddresses(ticket,select){const values=await runtime.addresses.load();if(!active(ticket))return;const addresses=Array.isArray(values)?values:values.addresses;if(!Array.isArray(addresses))throw Error('Adres yanıtı doğrulanamadı.');const host=select||root.querySelector('[data-commerce-load="addresses"]');if(!host)return;host.replaceChildren();if(select){const empty=node('option',addresses.length?'Adres seçin':'Kayıtlı adres bulunmuyor');empty.value='';select.append(empty);}for(const a of addresses){const label=[a.title,a.full_name||a.fullName,a.addressLine||a.address||a.address_line,a.district,a.city].filter(Boolean).join(' · ');if(select){const option=node('option',label);option.value=String(a.id);select.append(option);}else host.append(node('p',label));}if(!addresses.length&&!select)host.append(node('p','Kayıtlı adres bulunmuyor.'));}
 async function loadOrders(ticket,id){const result=id?await runtime.orders.detail(id):await runtime.orders.list();if(!active(ticket))return;const orders=id?[result]:result;if(!Array.isArray(orders))throw Error('Sipariş yanıtı doğrulanamadı.');const host=root.querySelector('[data-commerce-load="orders"]');if(!host)return;host.replaceChildren();for(const o of orders){const article=node('article',undefined,'profile-card'),link=node('a',`Sipariş #${o.id}`);link.href=`#/order/${o.id}`;article.append(link,node('p',`Sipariş: ${statusText(o.status)} · Ödeme: ${statusText(o.payment_status)}`),node('strong',money(Number(o.total_amount??o.total))));if(id){for(const line of o.items||[]){const variant=orderVariantText(line),row=node('p',`${line.name||line.product_name||'Ürün'}${variant?' · '+variant:''} · ${line.quantity} adet`);article.append(row);}}host.append(article);}if(!orders.length)host.append(node('p','Bu mağazada henüz siparişin bulunmuyor.'));}
 async function loadSupport(ticket){const value=await runtime.support.context();if(!active(ticket))return;const host=root.querySelector('[data-commerce-load="support"]');if(!host)return;host.replaceChildren();if(value.enabled!==true){host.append(node('p','Bu mağazanın destek mesajı bağlantısı henüz etkinleştirilmedi.'));return;}if(!['SELLER','PLATFORM'].includes(value.recipient))throw Error('Destek alıcısı sunucu tarafından doğrulanmadı.');host.append(node('h2',value.label||'Mağaza desteği'));const data=await runtime.support.threads();if(!active(ticket))return;if(!Array.isArray(data.threads))throw Error('Destek geçmişi doğrulanamadı.');for(const thread of data.threads){const button=node('button',`${thread.subject} · ${thread.status==='CLOSED'?'Kapalı':'Açık'}${thread.unreadCount?' · '+thread.unreadCount+' okunmamış':''}`,'button secondary');button.type='button';button.dataset.commerceAction='support-thread';button.dataset.thread=thread.id;host.append(button);}host.insertAdjacentHTML('beforeend','<div data-commerce-thread></div><h3>Yeni destek görüşmesi</h3><form data-commerce-form="support-create"><label class="field">Konu<input name="subject" maxlength="160" required></label><label class="field">Mesajın<textarea name="body" maxlength="4000" required></textarea></label><button class="button">Görüşme başlat</button></form>');}
 async function openThread(ticket,id,after){const data=await runtime.support.messages(id,after);if(!active(ticket))return;const host=root.querySelector('[data-commerce-thread]');if(!host)return;if(!data.thread||!Array.isArray(data.messages))throw Error('Destek görüşmesi doğrulanamadı.');if(!after)host.replaceChildren(node('h3',data.thread.subject));host.querySelectorAll('[data-commerce-form],[data-commerce-action]').forEach(el=>el.remove());for(const item of data.messages){const p=node('p');p.append(node('strong',item.senderKind==='CUSTOMER'?'Sen: ':'Destek: '),node('span',item.body));host.append(p);}if(data.thread.status!=='CLOSED')host.insertAdjacentHTML('beforeend',`<form data-commerce-form="support-send" data-thread="${esc(id)}"><label class="field">Yanıtın<textarea name="body" maxlength="4000" required></textarea></label><button class="button">Gönder</button></form>`);if(data.nextAfter){const more=node('button','Sonraki mesajlar','button secondary');more.type='button';more.dataset.commerceAction='support-thread';more.dataset.thread=id;more.dataset.after=String(data.nextAfter);host.append(more);}const last=data.messages.at(-1);if(last&&active(ticket))await runtime.support.read(id,last.id);}
 async function productPage(ticket,id){const {product:p}=await runtime.loadProduct(id);if(!active(ticket))return;const pending=root.querySelector('[data-commerce-product-pending]');if(!pending)return;
  // Canonicalize the original layout while detached: no demo purchase form or
  // unverified stock/shipping label ever enters the live customer document.
  const scope=node('div');scope.innerHTML=productTemplate(String(id));const info=scope.querySelector('.detail-info'),old=scope.querySelector('#product-form');if(!info||!old)throw Error('Ürün sunumu doğrulanamadı.');
  const title=info.querySelector('h1'),description=info.querySelector('.detail-desc');if(title)title.textContent=p.name;if(description)description.textContent=p.description||'';
  const rating=info.querySelector('.detail-rating');if(rating)rating.textContent=`${p.average_rating} / 5 · ${p.review_count} değerlendirme`;
  const store=runtime.snapshot().context.store;for(const line of info.querySelectorAll(':scope > .stock-line'))line.textContent=store.shipping_summary||'';
  const details=info.querySelector('.details-list');if(details){details.replaceChildren(node('h2','Ürün bilgileri'),node('p',p.description||''),node('h3','Teslimat ve iade'),node('p',store.shipping_summary||''),node('p',store.return_summary||''));}
  const form=node('form');form.id='commerce-product-form';form.dataset.commerceForm='product';form.dataset.product=String(p.id);form.className=old.className;
  const variantLabel=node('label','Ürün seçeneği','field'),select=node('select');select.name='variantId';select.setAttribute('aria-label','Ürün seçeneği');const empty=node('option','Seçenek seçin');empty.value='';select.append(empty);
  for(const v of p.variants||[]){const option=node('option',`${v.selections.map(s=>`${s.group}: ${s.value}`).join(' · ')} · ${money(v.price)}`);option.value=String(v.id);option.disabled=!v.purchasable||v.availableStock<=0;select.append(option);}variantLabel.append(select);if(p.variant_selection_required)form.append(variantLabel);
  const quantityLabel=node('label','Adet','field'),quantity=node('input');quantity.type='number';quantity.name='quantity';quantity.value='1';quantity.min='1';quantity.max='20';quantity.step='1';quantity.required=true;quantityLabel.append(quantity);
  const remembered=selection.read(p);select.value=remembered.variantId;quantity.value=remembered.quantity;
  const remember=()=>selection.write(p.id,select.value||null,quantity.value);
  select.addEventListener('change',remember);quantity.addEventListener('input',remember);
  const buy=node('button','Sepete ekle','button');buy.type='submit';const stock=node('p',undefined,'classic-stock'),output=node('p');output.dataset.commerceProductStatus='';output.setAttribute('role','status');output.setAttribute('aria-live','polite');form.append(quantityLabel,buy,stock,output);old.replaceWith(form);
  const update=()=>{let variant=null,valid=true;try{variant=assertProductVariant(p,select.value?Number(select.value):null);}catch{valid=false;}const amount=variant?.price??p.price,available=valid?(variant?.availableStock??p.stock):0;for(const price of scope.querySelectorAll('.detail-info .price-stack .price,.detail-info .detail-price .price,.classic-sticky-buy .price-stack .price'))price.textContent=money(amount);for(const oldPrice of scope.querySelectorAll('.detail-info .old-price,.classic-sticky-buy .old-price'))oldPrice.hidden=p.variant_selection_required===true||!p.old_price;for(const badge of info.querySelectorAll('.detail-price .pill'))badge.remove();stock.textContent=valid?`${available} adet stokta`:'Fiyat ve stok için ürün seçeneğini seçin.';quantity.max=String(Math.min(20,available));buy.disabled=!valid||available<=0||Number(quantity.value)>available;};select.onchange=update;quantity.oninput=update;update();
  const images=[p.image_url,...(p.media||[]).map(m=>m.media_url)].filter((url,i,list)=>image(url)&&list.indexOf(url)===i);onImages(p.id,images);const main=scope.querySelector('.classic-detail-image img,.detail-image img'),thumbnails=scope.querySelector('.classic-thumbnails,.gallery-tabs');renderProductGallery({root,main,thumbnails,urls:images,name:p.name,isCurrent:()=>active(ticket)});
  const data=await runtime.reputation(p.id);if(!active(ticket))return;const community=node('section',undefined,'details-list commerce-community');community.append(node('h2','Değerlendirmeler'));for(const r of data.reviews||[])community.append(node('p',`${r.full_name||''} · ${r.rating} / 5 · ${r.comment||''}`));if(!data.reviews?.length)community.append(node('p','Henüz yayımlanmış değerlendirme yok.'));community.append(node('h2','Soru ve cevap'));for(const q of data.questions||[])community.append(node('p',`${q.question}${q.answer?' · '+q.answer:''}`));
  community.insertAdjacentHTML('beforeend',renderReviewEditor(p.id,{authenticated:runtime.snapshot().session.status==='authenticated',permission:data.reviewPermission})+`<form data-commerce-form="question" data-product="${p.id}"><label class="field">Ürünle ilgili sorun<textarea name="question" maxlength="2000" required></textarea></label><button class="button secondary">Soru gönder</button></form>`);const reviewPanel=scope.querySelector('#classic-panel-reviews');if(reviewPanel)reviewPanel.replaceChildren(community);else info.append(community);
  if(!active(ticket))return;const host=root.querySelector("#main-content");if(!host||root.querySelector("[data-commerce-product-pending]")!==pending)return;host.replaceChildren(scope);onProductMounted();
 }
 async function onRendered(route){if(route.name!=='product'||currentRoute?.name!=='product'||String(route.id)!==String(currentRoute.id)){selection.clear();pendingNotice=null;}currentRoute=route;const ticket=++generation;try{if(route.name==='product'){await productPage(ticket,route.id);if(active(ticket)&&pendingNotice?.productId===Number(route.id))message(pendingNotice.text);return;}if(route.name==='legal'){const value=await runtime.legal(route.id);if(active(ticket)){const host=root.querySelector('[data-commerce-load="legal"]');host.replaceChildren(node('h2','Mağaza koşulları'),node('p',value.content,'commerce-legal-text'));}return;}if(runtime.snapshot().session.status!=='authenticated')return;if(route.name==='account')await loadAddresses(ticket);if(route.name==='checkout'){await loadAddresses(ticket,root.querySelector('[data-commerce-addresses]'));const result=await runtime.checkout.capability();if(active(ticket)){const target=root.querySelector('[data-commerce-capability]');if(target)target.textContent=result.message||'Bu mağazada ödeme başlatma henüz etkin değil.';}}if(['orders','order','success'].includes(route.name))await loadOrders(ticket,normalizeVariantId(route.id));if(route.name==='support')await loadSupport(ticket);}catch(error){if(active(ticket)){message(error.message||'Bilgi yüklenemedi.');if(route.name==='product'){const pending=root.querySelector('[data-commerce-product-pending]');if(pending){const retry=node('button','Yeniden dene','button secondary');retry.type='button';retry.dataset.commerceAction='product-retry';pending.setAttribute('aria-busy','false');pending.replaceChildren(node('p','Ürün bilgileri yüklenemedi.'),retry);}}}}}
 function click(event){const button=event.target.closest?.('[data-commerce-action]');if(!button||button.disabled)return;event.preventDefault();const name=button.dataset.commerceAction,id=Number(button.dataset.product),variant=button.dataset.variant?Number(button.dataset.variant):null;if(name==='product-retry'){refresh();return;}perform(button,async()=>{if(name==='support-thread')return openThread(generation,button.dataset.thread,button.dataset.after?Number(button.dataset.after):undefined);if(name==='logout'){await runtime.auth.logout();navigate('#/account');}else if(name==='quantity')await runtime.cart.setQuantity(id,variant,Number(button.dataset.quantity));else if(name==='checkout')await runtime.checkout.begin();else if(name==='sync')await runtime.cart.retrySync();else if(name==='resolve-legacy')await runtime.cart.resolveLegacy(id,button.dataset.local==='true',variant);refresh();});}
 function submit(event){const form=event.target.closest?.('[data-commerce-form]');if(!form)return;event.preventDefault();const data=new FormData(form),kind=form.dataset.commerceForm,id=Number(form.dataset.product),button=form.querySelector('button[type="submit"],button');perform(button,async(ticket)=>{
  if(kind==='login'){await runtime.auth.login(String(data.get('email')),String(data.get('password')));navigate('#/account');refresh();}
  else if(kind==='product'){const variantId=data.get('variantId')?Number(data.get('variantId')):null,quantity=Number(data.get('quantity'));selection.write(id,variantId,quantity);pendingNotice=null;await runtime.cart.add(id,variantId,quantity);if(!disposed&&currentRoute?.name==='product'&&Number(currentRoute.id)===id){pendingNotice={productId:id,text:`${quantity} adet ürün sepetine eklendi.`};message(pendingNotice.text);return pendingNotice.text;}}
  else if(kind==='prepare'){const value=await runtime.checkout.prepare(Number(data.get('addressId')),String(data.get('coupon')||''));if(!active(ticket))return;const target=root.querySelector('[data-commerce-agreements]');if(!target)return;target.replaceChildren(node('h2','Güncel sipariş özeti'));for(const [key,label]of Object.entries({subtotal:'Ürünler',bundleDiscount:'Kampanya indirimi',couponDiscount:'Kupon indirimi',shippingFee:'Teslimat',total:'Toplam'}))target.append(node('p',`${label}: ${money(value.quote.totals[key])}`));for(const doc of value.documents){const details=node('details');details.append(node('summary',doc.title),node('p',doc.text,'commerce-legal-text'));target.append(details);}target.append(node('p','Sözleşme özeti hazırlandı. Ödeme başlatılmadı.'));}
  else if(kind==='review'){await runtime.community.review({productId:id,rating:Number(data.get('rating')),comment:String(data.get('comment'))});message('Değerlendirme isteği alındı.');}
  else if(kind==='question'){await runtime.community.question({product_id:id,question:String(data.get('question'))});message('Sorun mağazaya iletildi.');}
  else if(kind==='support-create'||kind==='support-send'){const body=String(data.get('body')),subject=String(data.get('subject')||''),fingerprint=JSON.stringify([kind,subject,body]);if(form.dataset.requestFingerprint!==fingerprint){form.dataset.requestFingerprint=fingerprint;form.dataset.requestId=crypto.randomUUID();}const clientMessageId=form.dataset.requestId;if(kind==='support-create'){await runtime.support.create({subject,body,clientMessageId});refresh();}else{await runtime.support.send(form.dataset.thread,{body,clientMessageId});await openThread(generation,form.dataset.thread);}}
 });}
 root.addEventListener('click',click);root.addEventListener('submit',submit);
 return {renderPage:(name,id)=>renderCommercePage(runtime,name,id),onRendered,dispose(){disposed=true;generation++;clearTimeout(toastTimer);root.removeEventListener('click',click);root.removeEventListener('submit',submit);},currentRoute:()=>currentRoute};
}
