import React,{useState} from 'react';
import {getStudioHost,getStudioSession,capabilityVisible} from './context.js';
import {DESIGN_PRESETS,applyDesign} from '../sandbox/designLibrary.js';
import registry from '../sandbox/sectorThemeRegistry.json';
import './module.css';

export function HostActions({channel,state}) {
  const session=getStudioSession(),host=getStudioHost(),[note,setNote]=useState(''),[result,setResult]=useState(''),[localError,setLocalError]=useState('');
  const status=state.host,busy=Boolean(status.pending[channel]);
  async function run(operation,message){setLocalError('');setResult('');try{await operation();setResult(message);}catch(error){setLocalError(error.code==='FORBIDDEN'?'Bu işlem için yetkin yok.':error.code==='DIRTY'?'Önce taslağı sunucuya kaydet.':'İşlem tamamlanamadı. Bağlantı durumunu kontrol et.');}}
  return <div className="nsi-actions"><span className={`nsi-status ${status.dirty[channel]?'pending':''}`} role="status">{busy?'Sunucu yanıtı bekleniyor':status.dirty[channel]?'Kaydedilmemiş değişiklikler':'Sunucu taslağı güncel'}</span><button hidden={!capabilityVisible('theme.preview')} className="sp-button sp-button-outline" disabled={busy||host.capabilities.preview!==true||typeof host.ports.createPreview!=='function'} onClick={()=>run(()=>session.preview(channel),'Önizleme hazır. Sayfa düzenleyicide açabilirsin.')}>Önizleme hazırla</button><button hidden={!capabilityVisible('theme.save_draft')} className="sp-button sp-button-dark" disabled={busy||!status.dirty[channel]||host.capabilities.edit!==true||typeof host.ports.saveDraft!=='function'} onClick={()=>run(()=>session.save(channel),'Taslak sunucuya kaydedildi.')}>Taslağı kaydet</button><details hidden={!capabilityVisible('theme.publish')} className="nsi-publication"><summary>Yayın isteği</summary><label>Yayın notu<input aria-label="Admin yayın notu" maxLength={300} value={note} onChange={event=>setNote(event.target.value)}/></label><p>Bu işlem yetkili admin iş akışına istek gönderir. Kendiliğinden yayın yapmaz.</p><button className="sp-button sp-button-dark" disabled={busy||status.dirty[channel]||host.capabilities.publish!==true||typeof host.ports.requestPublication!=='function'||typeof host.ports.readReadiness!=='function'} onClick={()=>run(()=>session.requestPublication(channel,note),'Yayın isteği admin onay akışına gönderildi. Henüz yayımlanmadı.')}>Admin onayına gönder</button></details>{(status.error||localError)&&<p className="nsi-error" role="alert">{status.error||localError}</p>}{result&&<p className="nsi-success" role="status">{result}</p>}</div>;
}

export function HostDesignGallery({doc,channel,update,notify,onOffer}) {
  const host=getStudioHost();
  async function openWorkshop(theme){try{const result=await host.ports.openThemeWorkshop({contractVersion:'novastore-gallery-host/1',scope:{...host.scope},actor:{id:host.actor.id},themeId:theme.id,channel:channel==='android'?'app':'web'});if(result?.status!=='ready'||result?.scope?.tenantId!==host.scope.tenantId||result?.scope?.storeId!==host.scope.storeId)throw Error('Atölye bağlamı doğrulanmadı.');notify('Mağazaya özel tema atölyesi açıldı.');}catch{notify('Admin tema atölyesi açılamadı. Bağlantı ve mağaza kapsamını kontrol et.',true);}}
  return <section className="sp-settings-content nsi-gallery"><h2>Nova Store · {DESIGN_PRESETS.length + registry.themes.length} hazır tasarım</h2><p>Mevcut içerik taslakta korunur. Yeni sektör koleksiyonunun yayın ve düzenleme bağlantıları ayrıca admin tarafından yapılandırılır.</p><div className="sd-demo-grid">{DESIGN_PRESETS.map(theme=><article className="sd-demo-card" key={theme.id} data-host-theme={theme.id}><div className="sd-demo-copy"><small>{theme.sector}</small><h3>{theme.name}</h3><p>{theme.description}</p>{onOffer&&<button className="sp-button sp-button-outline" onClick={()=>onOffer(theme.id)}>Satıcıya sun</button>}<button className="sp-button sp-button-dark" disabled={host.capabilities.edit!==true||typeof host.ports.saveDraft!=='function'} onClick={()=>{if(update(next=>Object.assign(next,applyDesign(next,theme.id,channel))))notify(`${theme.name} çalışma taslağına alındı. Sunucuya kaydet ve önizle.`);}}>Tasarımı taslağa uygula</button></div></article>)}{registry.themes.map(theme=><article className="sd-demo-card" key={theme.id} data-host-theme={theme.id}><div className="sd-demo-copy"><small>{theme.sector} · Sektör koleksiyonu</small><h3>{theme.name}</h3><p>{theme.description}</p>{onOffer&&<button className="sp-button sp-button-outline" onClick={()=>onOffer(theme.id)}>Satıcıya sun</button>}{typeof host.ports.openThemeWorkshop==='function'?<button className="sp-button sp-button-outline" onClick={()=>openWorkshop(theme)}>Koleksiyon atölyesinde düzenle</button>:<button className="sp-button sp-button-outline" disabled>Atölye bağlantısı bekleniyor</button>}<p className="sp-hint">Yayın adayı · Bu ayrı tasarım motorunun admin belge adaptörü doğrulanmadan canlıya uygulanmaz.</p></div></article>)}</div></section>;
}
