import {themeTokens,classicTargetURL} from './theme-kit-adapter.js';
import {selectedProductFacts,canQuoteProduct} from './theme-kit-product.js';
const authoredValues=new WeakMap();
function authored(node,key,value,enabled){
 if(!node)return;let values=authoredValues.get(node);if(!values){values={};authoredValues.set(node,values);}
 const snapshot=()=>({base:node[key],last:node[key],children:key==='textContent'&&node.childNodes?[...node.childNodes].map(child=>child.cloneNode(true)):null});
 let entry=values[key];if(!entry||node[key]!==entry.last)entry=values[key]=snapshot();
 const next=enabled?value:entry.base;
 if(node[key]!==next){
  if(!enabled&&entry.children)node.replaceChildren(...entry.children.map(child=>child.cloneNode(true)));
  else if(!(key==='textContent'&&String(node[key]).replace(/\s/g,'')===String(next).replace(/\s/g,'')))node[key]=next;
 }
 entry.last=node[key];
}
export function applyClassicDocument(root,document,assetURL,catalog={products:[],categories:[]}){
 root.body.style.background=document.theme.background;
 const vars=themeTokens(document);for(const [key,value]of Object.entries(vars)){root.documentElement.style.setProperty(key,value);root.body.style.setProperty(key,value);}for(const [key,value]of Object.entries({'--classic-green':document.theme.accent,'--classic-ink':document.theme.text,'--classic-muted':document.theme.muted,'--classic-line':document.theme.border,'--classic-soft':document.theme.surface.toLowerCase()==='#ffffff'?'#f7f7f7':document.theme.surface}))root.body.style.setProperty(key,value);
 const mark=(selector,id)=>root.querySelectorAll(selector).forEach(node=>node.setAttribute('data-visual-element',id));
 // Canonical business records may be styled through fixed visual targets, but
 // may never become free text/image overrides discovered from the DOM.
 for(const node of root.querySelectorAll('.classic-detail .detail-info,.classic-detail-tabs,.classic-sticky-buy,.classic-gallery,.classic-hero-price,.classic-hero-image,.classic-hero-thumbs,.classic-spotlight'))node.setAttribute('data-canonical-content','true');
 for(const [selector,id]of [['.classic-header','header'],['.classic-brand','logo'],['.classic-search','search'],['.classic-search button','searchButton'],['.classic-navigation','nav'],['.classic-browse','allCategories'],['.classic-footer','footer'],['.classic-card','productCard'],['.classic-card .product-visual','productImage'],['.classic-card h3','productTitle'],['.classic-card .price','productPrice'],['.classic-card .add-button','addButton'],['.classic-gallery','productGallery'],['.classic-detail .detail-info','productInfo'],['#classic-panel-reviews','communityScore'],['#classic-panel-questions','communityQuestions']])mark(selector,id);
 const header=root.querySelector('.classic-header'),footer=root.querySelector('.classic-footer'),navigation=root.querySelector('.classic-navigation');if(header){header.hidden=!document.design.header;header.style.background=document.chrome.header.background;header.style.color=document.chrome.header.textColor;}if(footer){footer.hidden=!document.design.footer;footer.style.background=document.chrome.footer.background;footer.style.color=document.chrome.footer.textColor;}if(navigation)navigation.hidden=!document.design.navigation;
 const brand=root.querySelector('.classic-brand');if(brand){brand.textContent=document.chrome.header.logoText;const logoContent=document.design.elements.find(item=>item.id==='logoImage')?.content,logo=logoContent?.imageUrl;if(logo){const image=root.createElement('img');image.src=assetURL(logo);image.alt=logoContent.alt??document.chrome.header.logoText;image.setAttribute('data-visual-element','logoImage');image.style.maxWidth='180px';image.style.maxHeight='64px';brand.prepend(image);}}
 const search=root.querySelector('.classic-search');if(search)search.hidden=!document.chrome.header.showSearch;
 for(const [id,selector,title,copy,image]of [
  ['classic-hero','.classic-hero','[data-classic-hero-title]','[data-classic-hero-description]','.classic-hero-image img'],
  ['classic-categories','.classic-category-section','h2','.classic-section-heading p',null],
  ['classic-products','.classic-featured','h2','.classic-section-heading p',null],
  ['classic-story','.classic-story','h2','.classic-story-copy p','.classic-story-image img'],
 ]){const node=root.querySelector(selector),block=document.blocks.find(b=>b.id===id);if(!node)continue;node.setAttribute('data-module-id',id);node.hidden=!block||block.enabled===false;if(!block)continue;authored(node.querySelector(title),'textContent',block.title,id!=='classic-hero'||!!block.title);authored(node.querySelector(copy),'textContent',block.description,id!=='classic-hero'||!!block.description);if(image){const target=node.querySelector(image);authored(target,'src',block.image?assetURL(block.image):'',!!block.image);authored(target,'alt',block.alt||'',!!block.image);}}
 const hero=root.querySelector('.classic-hero'),block=document.blocks.find(item=>item.id==='classic-hero');if(hero&&block){const custom=!!(block.title||block.description||block.image),target=classicTargetURL(block.target,catalog);hero.dataset&&(hero.dataset.authoredCampaign=String(custom));for(const node of root.querySelectorAll('.classic-hero-price .price-stack,.classic-hero-thumbs,.classic-hero-dots,.classic-hero-arrow'))node.hidden=custom;for(const link of root.querySelectorAll('[data-classic-hero-link],[data-classic-hero-visual]')){authored(link,'href',target?new URL(target,root.baseURI).href:'',custom);authored(link,'ariaLabel',block.buttonText||'Koleksiyonu keşfet',custom);if(custom&&!target)link.removeAttribute('href');}const label=hero.querySelector('.classic-hero-price>span');authored(label,'textContent',block.buttonText||'Koleksiyonu keşfet',custom);}
 for(const heading of root.querySelectorAll('.classic-hero h1,.classic-section h2,.classic-detail h1')){heading.style.fontFamily=document.theme.fontFamily==='Arial'?'':themeTokens(document)['--display-font'];heading.style.color=document.theme.text.toLowerCase()==='#242424'?'':document.theme.text;}
 for(const card of root.querySelectorAll('.classic-card,.classic-product-visual,.classic-button,.classic-detail .button,.classic-card .add-button'))card.style.borderRadius=document.theme.radius?`${document.theme.radius}px`:'';
}

export function createClassicProductBinder({root,host,channel,onError=()=>{},onImages=()=>{}}){
 let generation=0,disposeCurrent=()=>{};
 const element=(tag,text,className)=>{const node=root.createElement(tag);if(text!==undefined)node.textContent=String(text);if(className)node.className=className;return node;};
 const money=value=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(value);
 return {dispose(){generation++;disposeCurrent();},async render(productId){const request=++generation;disposeCurrent();let closed=false,quoteSequence=0;disposeCurrent=()=>{closed=true;quoteSequence++;};const active=()=>!closed&&request===generation;
 try{const data=await host.ports.loadProduct({channel,productId});if(!active())return;const product=data.product,form=root.querySelector('#product-form'),info=root.querySelector('.classic-detail .detail-info');if(!form||!info||String(product.id)!==String(productId))return;
  const title=info.querySelector('h1');if(title)title.textContent=product.name;const stickyName=root.querySelector('.classic-sticky-buy>strong');if(stickyName)stickyName.textContent=product.name;
  const description=info.querySelector('.detail-desc');if(description)description.textContent=product.description||'';const fullDescription=root.querySelector('#classic-panel-description .classic-description p');if(fullDescription)fullDescription.textContent=product.description||'';
  const score=element('p',`${product.average_rating} / 5 · ${product.review_count} değerlendirme`,'classic-canonical-score');info.querySelector('h1')?.after(score);
  const reviews=root.querySelector('#classic-panel-reviews');if(reviews){reviews.replaceChildren(element('h2','Müşteri değerlendirmeleri'));for(const review of data.reviews||[]){const article=element('article',undefined,'profile-card');article.append(element('strong',`${review.full_name} · ${review.rating} / 5`),element('p',review.comment));reviews.append(article);}if(!(data.reviews||[]).length)reviews.append(element('p','Yayımlanmış değerlendirme bulunmuyor.'));}
  const tabs=root.querySelector('.classic-detail-tabs'),tablist=tabs?.querySelector('[role=tablist]');if(tabs&&tablist){const button=element('button','Soru ve cevap');button.type='button';button.id='classic-tab-questions';button.role='tab';button.setAttribute('aria-controls','classic-panel-questions');button.setAttribute('aria-selected','false');button.dataset.action='classic-detail-tab';button.dataset.tab='questions';tablist.append(button);const panel=element('div');panel.id='classic-panel-questions';panel.role='tabpanel';panel.hidden=true;panel.setAttribute('aria-labelledby',button.id);panel.setAttribute('data-visual-element','communityQuestions');panel.append(element('h2','Soru ve cevap'));for(const q of data.questions||[]){const article=element('article',undefined,'profile-card');article.append(element('strong',q.user_name),element('p',q.question),element('p',q.answer));panel.append(article);}if(!(data.questions||[]).length)panel.append(element('p','Yanıtlanmış soru bulunmuyor.'));tabs.append(panel);}
  const delivery=root.querySelector('#classic-panel-delivery');if(delivery)delivery.replaceChildren(element('h2','Teslimat ve iade'),element('p',host.commerce?.store?.shipping_summary||'Teslimat özeti henüz tanımlanmamış.'),element('p',host.commerce?.store?.return_summary||'İade özeti henüz tanımlanmamış.'));
  const brand=root.querySelector('#classic-panel-brand');if(brand){brand.replaceChildren(element('h2',host.commerce?.store?.name||'Mağaza'));for(const legal of host.commerce?.store?.legal_refs||[])brand.append(element('p',legal.disclosure));}
  const imageURLs=[product.image_url,...(product.media||[]).map(item=>item.media_url)].filter((url,index,list)=>url&&list.indexOf(url)===index),thumbs=root.querySelector('.classic-thumbnails'),mainImage=root.querySelector('.classic-detail-image img');onImages(product.id,imageURLs);if(mainImage&&imageURLs[0]){mainImage.src=imageURLs[0];mainImage.alt=product.name;mainImage.closest('.classic-detail-image').dataset.index='0';}if(thumbs&&mainImage){thumbs.replaceChildren();for(const [index,url]of imageURLs.entries()){const button=element('button'),image=element('img');button.type='button';button.setAttribute('aria-label',`${index+1}. ürün görseli`);button.setAttribute('aria-pressed',String(index===0));image.src=url;image.alt=product.name;button.append(image);button.onclick=()=>{if(active()){mainImage.src=url;mainImage.closest('.classic-detail-image').dataset.index=String(index);for(const node of thumbs.children)node.setAttribute('aria-pressed',String(node===button));}};thumbs.append(button);}}
  const variantLabel=element('label','Ürün seçeneği','field'),select=element('select');select.setAttribute('aria-label','Ürün seçeneği');select.append(new Option('Seçenek seçin',''));for(const variant of product.variants||[]){const option=new Option(`${variant.selections.map(s=>`${s.group}: ${s.value}`).join(' · ')} · ${money(variant.price)} · ${variant.availableStock} adet`,String(variant.id));option.disabled=!variant.purchasable;select.append(option);}variantLabel.append(select);if(product.variant_selection_required)form.prepend(variantLabel);
  const quantity=form.querySelector('[name=quantity]'),couponLabel=element('label','Kupon','field'),coupon=element('input');coupon.maxLength=80;coupon.setAttribute('aria-label','Kupon kodu');couponLabel.append(coupon);const calculate=element('button','Sepet tutarını hesapla','button'),output=element('section',undefined,'summary-card');calculate.type='button';output.setAttribute('aria-live','polite');form.append(couponLabel,calculate,element('p','Sipariş veya ödeme oluşturulmaz. Yalnız sunucu fiyat hesabı gösterilir.','muted'),output);
  let pending=false;const variant=()=>selectedProductFacts(product,select.value).variant,valid=()=>canQuoteProduct(product,select.value,Number(quantity?.value));
  const invalidate=()=>{quoteSequence++;pending=false;output.replaceChildren();calculate.disabled=!valid();const facts=selectedProductFacts(product,select.value);for(const stack of root.querySelectorAll('.classic-detail .detail-info>.price-stack,.classic-sticky-buy>.price-stack')){const price=stack.querySelector('.price');if(price)price.textContent=money(facts.price);let old=stack.querySelector('.old-price');if(facts.oldPrice!==null){if(!old){old=element('span',undefined,'old-price');stack.append(old);}old.hidden=false;old.textContent=money(facts.oldPrice);}else if(old)old.hidden=true;}const stockNode=form.querySelector('.classic-stock');if(stockNode)stockNode.textContent=facts.requiresSelection?'Fiyat ve stok için ürün seçeneğini seçin.':facts.stock>0?`${facts.stock} adet stokta`:'Stokta yok';if(quantity)quantity.max=String(facts.maxQuantity);};
  select.onchange=invalidate;coupon.oninput=invalidate;if(quantity)quantity.addEventListener('input',invalidate);form.addEventListener('click',event=>{if(event.target.closest('[data-action="classic-quantity"]'))queueMicrotask(invalidate);});invalidate();
  calculate.onclick=async()=>{if(!active()||pending||!valid())return;const sequence=++quoteSequence,v=variant();pending=true;calculate.disabled=true;output.replaceChildren(element('p','Sunucu hesabı hazırlanıyor…'));try{const quote=await host.ports.quote({channel,body:{items:[{productId:product.id,...(v?{variantId:v.id}:{}),quantity:Number(quantity.value)}],...(coupon.value.trim()?{couponCode:coupon.value.trim()}:{})}});if(!active()||sequence!==quoteSequence)return;output.replaceChildren(element('h3','Sunucudan hesaplanan sepet'));for(const [key,label]of Object.entries({subtotal:'Ürünler toplamı',bundleDiscount:'Kampanya indirimi',couponDiscount:'Kupon indirimi',shippingFee:'Teslimat ücreti',total:'Ödenecek tutar'}))if(Object.hasOwn(quote.totals,key))output.append(element('p',`${label}: ${money(quote.totals[key])}`));output.append(element('p','Stok ayrılmadı. Sipariş oluşturulmadı.'));}catch(error){if(active()&&sequence===quoteSequence)output.replaceChildren(element('p',error.message));}finally{if(active()&&sequence===quoteSequence){pending=false;calculate.disabled=!valid();}}};
 }catch(error){if(active())onError(error.message);}
 }};
}
